### ISSUE TITLE
strange Find behaviour when search terms contain uppercase characters

### ISSUE THREAD

**Issue by xavi** [LightTable/LightTable#1022]
This is in LT 0.6.0. Create a new file with just these lines...

    light
    LIGHT

Invoke the Find command (Cmd+f) and type `light` as the search term. Both lines are displayed as matches, as expected. Now replace the search term `light` with `LIGHT` and only the second line is displayed as a match. I would expect that Find displayed both lines as matches in this latter case too.

**Comment by kenny-evitt** [comment]
We can reopen this if anyone is interested in submitting a PR to add a configuration setting for this.

I created a separate issue for the search match lighting bug – #1999

**Comment by Mouvedia** [comment]
I didn't realize it by then but #1870 is a duplicate.
