### ISSUE TITLE
Provide for starting instarepl sessions with live mode disabled

### ISSUE THREAD

**Issue by mmower** [LightTable/LightTable#1039]
At the moment it is not possible for LT to default to starting Instarepl's with Live mode turned off.

There was a suggestion that LT needed a new behaviour to execute a command when something is opened.

Please see:

https://groups.google.com/forum/#!topic/light-table-discussion/uezb1183s7k

for discussion.

**Comment by Knotschi** [comment]
I think it is still relevant (or I just could not find out how to do that)
I would love to have that option

**Comment by kenny-evitt** [comment]
@Knotschi This isn't currently possible.

**Comment by cldwalker** [comment]
This issue has moved to https://github.com/LightTable/ClojureInstarepl/issues/12 as the instarepl is now its own plugin
