### ISSUE TITLE
Font settings for a type of editor apply to all editors

### ISSUE THREAD

**Issue by puterleat** [LightTable/LightTable#1045]
I have this in my user behaviours file:

    {:+ {
         ;; The editor tag is applied to all editors
         :editor [:lt.objs.editor/no-wrap
                  (:lt.objs.style/set-theme "default")
                  (:lt.objs.style/font-settings "" "12" "")]

         :editor.python  [(:lt.objs.style/set-theme "neat")
                          (:lt.objs.style/font-settings "" "16" "")]

         }}

But unfortunately all fonts end up 16pt (everywhere). Am I missing something?

**Comment by cldwalker** [comment]
Closing as this is the same as and better explained in #1460
