### ISSUE TITLE
pick up file type from #! as well as file extension?

### ISSUE THREAD

**Issue by puterleat** [LightTable/LightTable#1079]
At present, a python command line utility with no file extension isn't recognised as python within LightTable. However the file does start with 

   #!python

Which should perhaps be enough of a hint?

**Comment by kenny-evitt** [comment]
I added this to [the feature wishlist](https://github.com/LightTable/LightTable/wiki/Feature-wishlist). We can re-open if anyone is interested in submitting a PR for this, tho this could also be implemented as a plugin.
