### ISSUE TITLE
Window is sometimes not redrawn with tiling window manager on Linux

### ISSUE THREAD

**Issue by sstewartgallus** [LightTable/LightTable#1080]
I use a tiling window manager such as XMonad on Linux and LightTable sometimes does not redraw the window. Attached is an image of the problem (scaled down for convenience).
![screenshot from 2014-01-12 14 53 04](https://f.cloud.github.com/assets/4070335/1897367/a2597b7c-7bdd-11e3-8f7f-53e5453541bd.png)

**Comment by kenny-evitt** [comment]
Anyone – comment whether this is still unresolved, particularly with a build of the latest source (on the *master* branch), and we can reopen it.

**Comment by sstewartgallus** [comment]
This is fixed.

**Comment by kenny-evitt** [comment]
@sstewartgallus Excellent
