### ISSUE TITLE
Ctrl/Cmd + Up/Down Should scroll screen

### ISSUE THREAD

**Issue by charlie-harvey** [LightTable/LightTable#1111]
In most editors (text or IDE), pressing Ctrl+Down Arrow scrolls the active window down without moving the cursor. Pressing Ctrl+Down in LightTable for some reason puts the cursor at the end of the file. Ctrl+Up puts it at the top.

Confusing for many users. Maybe some editors that I have not used has the same behavior as LightTable and my opinion is off base. Thought I would put it out there anyway.

Thanks for making such a great tool.

**Comment by BenjaminVanRyseghem** [comment]
any progress here? :smile:

**Comment by BenjaminVanRyseghem** [comment]
According to CodeMirror [doc](https://codemirror.net/doc/manual.html#commands),
there are

```
goPageUpPageUp, Shift-Ctrl-V (Mac)
Move the cursor up one screen, and scroll up by the same distance.

goPageDownPageDown, Ctrl-V (Mac)
Move the cursor down one screen, and scroll down by the same distance.
```

**Comment by cldwalker** [comment]
@BenjaminVanRyseghem PageUp moves the cursor while he's looking to scroll while keeping the cursor in place.
Closing as ctrl/cmd up/down aren't standard keys for this behavior on osx editors. LT needs to choose keybindings that work well across three OSes. On osx 10.10, ctrl-up and ctrl-down are global keys for window motions. Cmd-up and Cmd-down have no effect on terminal editors (as expected) and in Atom scrolls to the top and to the bottom as described.
