### ISSUE TITLE
Making light table play nicely with clojure.test

### ISSUE THREAD

**Issue by olivergeorge** [LightTable/LightTable#114]
Hi

I'm trying to write code using light table and use tests but I'm only getting a terse summary report from (run-tests).  Looks like I'm not getting the stdout reporting, only the result of calling (run-tests).

I can fix this by rebinding _test-out_ to _out_.

``` clojure
(binding [*test-out* *out*]
  (run-tests))
```

Is is possible that *out* is bound to something odd when clojure.test loads?

cheers, Oliver

PS. Just an idle related thought.  I'd like to have a set of tests run (instarepl style) as I'm coding in Table mode.  If a test fails I want to see what values where passing through functions (instarepl style).

**Comment by nethopper** [comment]
For anyone trying this with the new flat format, the `(:eval.custom "code" {:result-type :statusbar})` should not be in an array. The above key binding entry would therefore look like this:

     [:editor.clj "pmeta-r" (:eval-custom
                             "(clojure.test/run-all-tests
                                (re-pattern
                                  (str \"^\" *ns* \".*\")))"
                             {:result-type :statusbar})]
