### ISSUE TITLE
Menus should have access keys; Exit missing from File menu

### ISSUE THREAD

**Issue by jdnier** [LightTable/LightTable#1143]
Now that LightTable has menus, I'd like to suggest that for Linux and Windows, it feels very non-standard for menus not to have Alt access keys (e.g., Alt-f for File, Alt-e for Edit, etc.).

It's also odd that the File menu is missing Exit or Quit item to shutdown LightTable. More than once I've selected "Close file" at the bottom of the File menu expecting the application to quit (because it's the last item in the File menu, which in virtually any application will be Quit/Exit).

**Comment by cldwalker** [comment]
Looking through old issues and found this. Agree alt-keys are reasonable and there should be an Exit/Quit for linux and windows. Fix coming shortly

**Comment by jdnier** [comment]
Thanks for this!
