### ISSUE TITLE
Toggle connect bar instead of show/hide connect bar

### ISSUE THREAD

**Issue by Morgawr** [LightTable/LightTable#1167]
Most of LightTable's 'toggleable' features (like console, workspace, etc etc) work with a single behavior of toggle in the search bar, yet for the connect bar there are two distinct triggers, show/hide connect bar. 

I think those should be merged into a single "toggle connect bar"

**Comment by cldwalker** [comment]
Looking through old issues. Agree a that description change is enough. Fix coming shortly
