### ISSUE TITLE
user.keymap has no effect

### ISSUE THREAD

**Issue by doxxx** [LightTable/LightTable#1180]
Using latest 0.6.2 but seen since 0.6.0, the key bindings in my user.keymap have no effect.

I opened the user keymap file in LightTable using the "Settings: User keymap" command from the command bar, added some keybindings and then saved the file. Light Table said "keys loaded" in the status bar at the bottom, but the new keybindings were not working.

Since it had been a while since I had Light Table last installed, I thought maybe it was picking up an old file, so I moved my current user.keymap and user.settings files out of the settings folder and restarted LightTable so that it would recreate the default contents. Then I re-opened the file in LightTable, made the same changes again, saved again, but still no effect.

**Comment by madkinder** [comment]
Since Light Table 0.7.2 the syntax has changed:

```clojure
[:editor "-pmeta-shift-s"]
```

You don't need the action for unbinding, just prepend the dash to the key specification to unbind it.
