### ISSUE TITLE
File not saving

### ISSUE THREAD

**Issue by dubiousdavid** [LightTable/LightTable#1196]
I'm experiencing fairly regularly an issue where changes are made to a file, but Cmd-S is not actually saving the changes.  The file continues to indicate that there are unsaved changes (asterisk next to file tab), so it's not reporting something erroneous.

**Comment by BenjaminVanRyseghem** [comment]
Can someone reproduce this in the `atom-shell` branch?

**Comment by kenny-evitt** [comment]
*atom-shell* has been merged into *master*, so use that if you're going to test the latest code.

**Comment by Verneri** [comment]
I'm having this as well with OS X 10.10.4 and LT 0.7.2. To add also clicking save on the menu does not work when it happens. only copying everything, closing the file, reopening it, pasting everything and then saving helps.

**Comment by kenny-evitt** [comment]
@Verneri Would you try to reproduce this with a build of the latest source version?

**Comment by kenny-evitt** [comment]
@rundis Are you still observing this with the latest source version?

**Comment by rundis** [comment]
@kenny-evitt Haven't experienced this on atom/electron as far as I can remember.

**Comment by cldwalker** [comment]
This should be fixed with 0.8.0-alpha - https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss
