### ISSUE TITLE
Multiline comments in Python doesn't compile

### ISSUE THREAD

**Issue by sterfield** [LightTable/LightTable#1200]
OS : Debian testing
Lighttable version : 0.6.2 (64 bit) (binary version 0.8.4)
Python version : 2.7.6

How to reproduce : 
- create a new file "test.py" and open it in LighTable
- create a multiline comment

```
'''  
This  
is a  
multiline  
comment  
'''
```
- execute the file (CTRL + SHIFT + ENTER)

Current results : Stacktrace saying "SyntaxError: EOF while scanning triple-quoted string literal"

Expected results : normal compilation.

Note on Python comments:
- The "standard" comment used in Python is the '#' character (http://docs.python.org/2/reference/lexical_analysis.html?highlight=comment#comments)
- However, multiline comments using triple quotes works in a Python interpreter. Moreover, this usage is validated by Guido van Rossum in a tweet. (https://twitter.com/gvanrossum/status/112670605505077248)

Thanks !

EDIT : 
Change the code block to correctly displayed the line break.
Change the shortcut to execute the file to CTRL + SHIFT + ENTER

**Comment by ufechner7** [comment]
Could some add the label "Python"? This would make it more visible.

**Comment by kenny-evitt** [comment]
I created LightTable/Python#40 to replace this.
