### ISSUE TITLE
Make LightTable a "Journaled Editor"

### ISSUE THREAD

**Issue by brandondrew** [LightTable/LightTable#1222]
LightTable is blowing away other IDEs and editors in so many ways, but there's one killer feature that it lacks, which keeps me using SublimeText for now: when the OS or editor crashes, I lose ***absolutely nothing***, whether I've saved it or not.  Everything is saved automatically in temporary files somewhere (I don't have to worry about where, or configure anything to make it work this way).  I don't know what else to call this feature, so I'll borrow terminology from file systems and databases, and refer to it as journalling, and to an app that has this feature as being journaled. 

In fact, even if I close Sublime Text without saving, it doesn't bother prompting me to save each file (and I could have dozens of them open at once!).  It just closes, and when it reopens everything is just as I left it.

This is how more and more apps are working: Safari and Chrome and Firefox are all reasonably good at restoring their pre-crash state when you reopen them.  (Yes they have flaws, but they're getting there.)  To me this is a killer feature that is essential, because Windows has always been pretty crash-happy, and even OS X has gotten pretty bad with Mavericks (at least for me, with the software I've got installed on it).  I would ***love*** to see LightTable get this feature.

**Comment by Joshfindit** [comment]
If this is an unhelpful observation, feel free to delete or dismiss:

Sublime is hooking in a feature of OSX 10.7+, which manages the "Saved Application State" folder.
The functionality can not be hooked by Light Table as it relies on the OS, but it can be replicated (and seemingly has been with Reminisce / Recall)

**Comment by cldwalker** [comment]
We'll be tracking handling unsaved state for cases like crashes in #1700. Restoring LT from restart is handled by the Reminisce plugin
