### ISSUE TITLE
Instarepl watches history build up

### ISSUE THREAD

**Issue by johnjelinek** [LightTable/LightTable#1230]
![light_table](https://f.cloud.github.com/assets/873610/2060652/2f660ed2-8c27-11e3-9eb4-0ea0be568a44.png)

As you can see, my instarepl history is building up in 0.6.2. I don't think this is intended.

**Comment by kemenaran** [comment]
I also have the same issue.

**Comment by joshuafcole** [comment]
Pull the latest and you should be good to go!

**Comment by kemenaran** [comment]
Indeed, I just build the latest version and it works like a charm. Thanks for the fix!
