### ISSUE TITLE
Problem deploying LT on xubuntu 13.04

### ISSUE THREAD

**Issue by bonega** [LightTable/LightTable#1237]
```
git clone https://github.com/LightTable/LightTable.git
cd LightTable
bash linux_deps.sh
./deploy/LightTable
```

The LightTable logo shows with gray background and nothing else happens.
I get this in the console: `~/git/LightTable$ [5143:0203/195959:ERROR:browser_main_loop.cc(226)] Gdk: gdk_window_set_icon_list: icons too large`

And the prompt returns (the LT windows is still there, but unresponsive)

**Comment by nwork** [comment]
Received this error today
[4188:0416/171703:ERROR:browser_main_loop.cc(226)] Gdk: gdk_window_set_icon_list: icons too large
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[4224:0416/171706:ERROR:sandbox_linux.cc(142)] InitializeSandbox() called with multiple threads in process gpu-process
I downloaded LightTable a couple days ago, looked at it for a little bit and then closed it. Today it won't load, I haven't made any changes so I am stumped.

**Comment by rickedanielson** [comment]
Reinstallation of ubuntu 14.04 on a new disk gave some similar errors:

[8230:0423/131333:INFO:gpu_info_collector_x11.cc(80)] NVCtrl extension does not exist.
[8230:0423/131333:ERROR:browser_main_loop.cc(226)] Gdk: gdk_window_set_icon_list: icons too large

This doesn't stop one from running from the command line (and one would think that the (icon) launcher would also start by adding ">&/dev/null" at the end of the Exec line in ltbin.desktop, but I have yet to see that).  Anyway, it didn't seem to remove the messages to try this "cd LightTable/deploy ; mv libffmpegsumo.so libffmpegsumo.sold ; cp /opt/google/chrome/libffmpegsumo.so . ; chmod +x libffmpegsumo.so"
