### ISSUE TITLE
Disable Intro screen

### ISSUE THREAD

**Issue by johnjelinek** [LightTable/LightTable#1258]
I saw `(:lt.objs.intro/show-intro)` when looking in user.behaviors, I want to hide the intro, I tried to put it here:

```
:- {
     :app [(:lt.objs.intro/show-intro)]

     :editor []}
```

This did not disable the welcome screen. Any thoughts?

**Comment by sbauer322** [comment]
For anyone looking to disable the intro screen in later versions of Light Table, you simply need to add the following snippet to your `user.behaviors` file:

```
[:app :-lt.objs.intro/show-intro]
```

**Comment by MarcelHekkert** [comment]
Works, although i'd suggest at some point they rename that to:

`
lt.objs.intro/hide-intro
`

**Comment by denis631** [comment]
@MarcelHekkert we can just create an alias for that, right? 
```
(def -lt.objs.intro/show-intro lt.objs.intro/hide-intro)
```
