### ISSUE TITLE
Github flavored markdown syntax highlighting doesn't work

### ISSUE THREAD

**Issue by bilderbuchi** [LightTable/LightTable#1262]
Github flavored markdown is not correctly highlighted. Failing elements are fenced code blocks (i.e. surrounded with three backticks) or `underscores_between_words` (where "between" is highlighted as recursive, when it should not be.
I have switched this on with 
```
     :files [(:lt.objs.files/file-types [{:name "Github Markdown"
                                         :exts [:md :markdown]
                                         :mime "gfm" :tags [:editor.markdown]}])]
```

in user.behaviours as per [a google group thread](https://groups.google.com/d/msg/light-table-discussion/rxVQEw-wwYQ/ylMjnve-yCYJ), and Codemirror [can do this](http://codemirror.net/mode/gfm/index.html) and it is [in LT](https://github.com/LightTable/LightTable/blob/master/deploy/core/node_modules/codemirror/modes/gfm.js) so I don't see why this doesn't work.

**Comment by ohAitch** [comment]
Seems to still be the case. Additionally, if the _current editor syntax_ is set to Github Flavored Markdown, the file loses all highlighting entirely until switched back.

**Comment by kenny-evitt** [comment]
@ohAitch You're setting the current editor syntax thru the command bar, right? Would you build and run the *atom-shell* branch version and confirm if this is still an issue with that version?

**Comment by Joshfindit** [comment]
Adding the relevant examples from #1922 :

In Github Flavoured Markdown, the following are valid:

```js
    ```javascript
    var firstName = "Gregg";
    ```
```

```clojure
    ``` clojure
    user=> (type #'user/my-number)
    clojure.lang.Var
    user=> ;
    ```
```

and

```js
    <script>
      var firstName = "Gregg";
      // This is less "valid", but works in Markdown compilers like Jekyll
    </script>
```

**Comment by cldwalker** [comment]
Closing as I've verified latest 0.8.0 does have syntax highlighting for gfm
