### ISSUE TITLE
Fuzzy matching or substring search for plugins

### ISSUE THREAD

**Issue by zubko** [LightTable/LightTable#1268]
I wanted to find 'Scrubber' plugin.
In 'Plugin manager' I entered 'scr' into the 'Search available plugins' field.
I didn't get any result despite that the 'Scrubber' is in the list.
When I entered 'scrubber' I got the result.

We use fuzzy matching for command list and open file pane. 
It would be nice to have it for plugins too.

**Comment by cldwalker** [comment]
This specific case has been fixed since 0.7.2 when we moved the search into the plugin. [Relevant search code](https://github.com/LightTable/LightTable/blob/f4d680e28cc00e520ce18a292d3ca1b87c3736f5/src/lt/objs/plugins.cljs#L261-L267)
