### ISSUE TITLE
LT shouldn't allow actions from keys that aren't mapped to a command.

### ISSUE THREAD

**Issue by Frozenlock** [LightTable/LightTable#1299]
It seems that some actions are sent directly to the editor and doesn't call any command.

For example, in vanilla LT, pressing the right arrow key will move the cursor right, without calling any LT commands.

The problem is described here:
(https://github.com/Frozenlock/describe-key/issues/1)

While this isn't such a big issue for this plugin, I fear this will cause many headaches to anyone trying to do anything with the keys/commands.

Furthermore, it seems that these command-less actions differ depending on your OS, making it that much difficult to develop for many OS.

**Comment by cldwalker** [comment]
Looking through old issues. Closing as this is a fair amount of work for questionable gain. Can reopen if interested in discussing this more
