### ISSUE TITLE
Commands go to the wrong tab

### ISSUE THREAD

**Issue by berdario** [LightTable/LightTable#1319]
I showed the issue in this 22 sec video:

http://www.youtube.com/watch?v=4LkhUYik2BA
(I used screenkey for the overlay, it doesn't show `shift` keypresses)

it just happens after I change one of the keybindings... if I go back to the .keymap file and do some other kind of change, then when I later switch to another tab, the keyboard commands will actually go where intended

**Comment by cldwalker** [comment]
Looking through old issues and it's not clear what the issue is. `[:editor "pmeta-shift-left" :paredit.grow.left]` works for me as a keybinding on osx. If you're still interested, please try on latest LT and provide reproducible steps. Otherwise I'll close in a few days

**Comment by berdario** [comment]
I cannot test the latest version, since LT fails to upgrade. I see this in the console:

    Error: incorrect header check
        at Zlib._binding.onerror (zlib.js:295:17)

Is this a known (transient?) error?

I'll try again later on.

Can you please try to reproduce it on Linux?

**Comment by cldwalker** [comment]
> Is this a known (transient?) error?

Unless you are behind a proxy, there shouldn't be an issue with downloading a new version of LT 

> Can you please try to reproduce it on Linux?

I'll need reproducible steps e.g:

1. Go to file X
2. Type `abc`
3. See Y

It's not clear in the video what to look for

**Comment by berdario** [comment]
> Unless you are behind a proxy, there shouldn't be an issue with downloading a new version of LT 

Nope, I was on the train so I thought it might be my tethered internet, but I tried again now when at home, and LT is not sending any packets whatsoever.

The LT upgrade is apparently borked. I presume that LT fetched a corrupted zip in the past (how could it be? surely LT should use a checksum before trusting what it downloaded) and now it won't redownload it again, even if it sees it's corrupted?

I could report it as a new bug

> It's not clear in the video what to look for

The video is pretty clear, maybe to properly see the problem you'd need to play it back at its native (1080p) resolution?

Anyhow, you can compare it between seconds 0.04 and 0.18: there's a `{` before `"backspace"` that gets shifted all the way before `:editor`, that happens due to the `:paredit-grow-left` command, which is incorrectly executed when another tab is in the foreground... that's due to the editor pool not properly being updated

**Comment by kenny-evitt** [comment]
@berdario What version of LT are you running now? You might need to download a release package because older versions look for new versions at an endpoint that the open source team doesn't control or have access to. Going forward, LT looks for new releases on GitHub.

**Comment by berdario** [comment]
The about page says

Light Table version
0.8.0
Binary version
0.8.4

But when opening up LT, it says

>Would you like us to download and install version 0.8.0?

If this is known issue due to the change in the releases, I'll just redownload LT separately and ignore this

**Comment by kenny-evitt** [comment]
@berdario That's weird. Your binary version really says "0.8.4"? It should be "0.34.5". I'm actually pretty curious how that happened.

I think you're going to need to just re-download LT.

**Comment by berdario** [comment]
Yup, weird indeed...

Anyhow, now that I got a new release package I tried to reproduce again this bug, but it's been quite a while and it doesn't happen right away, I'd need more time using LT to find it out... and since I'm not using LT day-to-day anymore, I think I'll just close this issue for now and reopen it if needed
