### ISSUE TITLE
LightTable for Windows and NodeJS

### ISSUE THREAD

**Issue by reinier-gonzalez** [LightTable/LightTable#1322]
Hi,

I'm trying to use LightTable on windows7 with a node-webkit application i'm building, when i add the nodejs connection and link to my file "main.js" (my app's starting point) i'm getting this:

The node process exited.

The node process you were connected to suddenly quit. Check the console for more information.

node[stderr]:
connect error:Error: connect ENOENT
at errnoException (net.js:901:11)
at Object.afterConnect as oncomplete

What i'm I doing wrong? how to fix it? Any help will be highly appreciated. Thanks!

**Comment by cldwalker** [comment]
Closing as this fairly old and doesn't have a reproducible project. If you're still interested in the issue please provide a project and open it on the [JavaScript plugin](https://github.com/LightTable/Javascript/issues)
