### ISSUE TITLE
Much faster way to open an HTML file in a browser tab

### ISSUE THREAD

**Issue by ackalker** [LightTable/LightTable#1326]
The Getting Started docs within Light Table on evaluating HTML suggest to open a browser tab from the `commands` menu item, then manually specify the URL to the .html file to view in the browser address bar.

By accident (using Light Table built from Git), I found that pressing Shift-Ctrl-Enter while editing an .html file, without a browser tab open yet, does all this in one step: it opens a browser tab and opens the currently edited file in it. Nice touch, as this follows the pattern for eval'ing a ClojureScript file.

Please update the documentation to include this shortcut, this will also make the steps a bit more similar to the steps for eval'ing a .js file which follow immediately below in the same section.

Thanks in advance.

**Comment by BayyinahAwesome** [comment]
Bro/sis acKalker, I opened a github account just so I could thank you for this thing!!!!!!!!!!!
