### ISSUE TITLE
Getting black screen on launch

### ISSUE THREAD

**Issue by prestonviewer** [LightTable/LightTable#1339]
Windows 7 64bit
2GB
AMD E-350

Screenshot:
http://screencloud.net/v/uY4e

Trying 0.6.0 and 0.6.4 versions. Same thing.

**Comment by kenny-evitt** [comment]
@prestonviewer @remco138 @tkelman are you still experiencing this issue with the latest version of Light Table?

**Comment by tkelman** [comment]
With "Light Table version 0.7.2, Binary version 0.8.6," I still see the same problem.

**Comment by prestonviewer** [comment]
Ya, same thing.

**Comment by kenny-evitt** [comment]
@tkelman @prestonviewer thanks. Unfortunately, it doesn't seem like upgrading node-webkit is feasible. There's work being done now to port Light Table to Atom Shell. I don't know when that will be released, but you could try building Light Table from that branch. [Here's a thread](https://groups.google.com/d/msg/light-table-discussion/PfQ6kCKrj84/hMNG7flMoZkJ) in the Light Table Discussion Google Groups group with more info about others doing that.

**Comment by Varanas** [comment]
Or you could just try @one-more-minute 's [Juno-Binaries](http://julialang.org/downloads/) - those are built with Atom Shell too.

**Comment by kenny-evitt** [comment]
@prestonviewer @remco138 @tkelman @shamanx Mind building the latest source and trying to reproduce this? The port to Atom Shell (now "Electron") was completed a little while ago.

**Comment by cldwalker** [comment]
We've release 0.8.0-alpha which is based on Electron - https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss. Closing as this should be resolved. Ping us if it is still an issue
