### ISSUE TITLE
"clojure.core.reducers" is not available when connected to Light Table UI

### ISSUE THREAD

**Issue by sroccaserra** [LightTable/LightTable#1363]
Hi,

If I create a new file, set its syntax to ClojureScript, and connect it to Light Table UI, then the ClojureScript reducers namespace is not available.

```
(ns foo
  (:require [clojure.string :as s]
            [clojure.core.reducers :as r]))

(s/reverse "abc") ;; => "cba"

(r/reduce + [1 2 3]) ;; => "TypeError: Cannot read property 'reducers' of undefined"
```

Note : I'm using a Windows version downloaded from http://www.lighttable.com/ (Light Table version 0.6.4, Binary version 0.8.4).

Note : in the "LightTableWin.zip" file used to build Light Table for Windows, ClojureScript "0.0-2138" is bundled in core/node_modules/lighttable/ but is missing some files. In particular, the directory "core/node_modules/lighttable/cljs/clojure/core" does not exist (it's where the file "reducers.cljs" should be in ClojureScript r2138).

Note : the file "core/node_modules/lighttable/cljs/clojure/zip.cljs" is missing too, and trying to use "clojure.zip" when connected to Light Table UI results in the same error as trying to use "clojure.core.reducers".

Is this intended, or can it be fixed ?

Cheers!
Sébastien.

**Comment by rundis** [comment]
will this be fixed in version 0.8 ?

**Comment by cldwalker** [comment]
Unlikely. Upgrading clojurescript breaks key functionality and requires more investigation - see 8e73f59891c45f73a1b985fed69795d1061a8ecf

**Comment by rundis** [comment]
Weirdness:
- When I required clojure.zip in a namespace in a plugin, it wouldn't evaluate usage of it through LT-ui (but looking at the compiled js it contained the functions for clojure zip )
- I saved my namespace
- Restarted LT
- Then managed to evaluate clojure.zip methods !
