### ISSUE TITLE
Impossible to select something from the autocompletion menu on editor!

### ISSUE THREAD

**Issue by mogarick** [LightTable/LightTable#1392]
Code something and summon autocomplete on editor.
Use arrow keys move through autocomplete menu suggestions.
Hit enter to select the one you want to use
Bam! No selection and just a simple enter occurs in editor!

The only annoying workaround is to select option using the pointer arrow from pointer device (mouse, trackpad, etc).

I'm using MacOSX 10.9.2 and the last version of Light Table (0.6.5)

![image](https://f.cloud.github.com/assets/4414145/2512190/e054492e-b423-11e3-95ea-7bd8fc96bedf.png)

![image](https://f.cloud.github.com/assets/4414145/2512200/f664d0f8-b423-11e3-8f0d-f7d2f4a9fedb.png)

**Comment by anandtrex** [comment]
Just a quick note for people trying to subtract out the enter keybinding. In Julia 0.3.9, I had to add the `[:editor.keys.hinting.active "-enter" :passthrough]` line in user.keymap instead of user.behaviors to get it to work.
