### ISSUE TITLE
"Wrong number of args (4) passed to: core$make-array" error in Clojure InstaREPL

### ISSUE THREAD

**Issue by asemt** [LightTable/LightTable#1402]
In a Clojure Instarepl the following valid code produces the error message "Wrong number of args (4) passed to: core$make-array":

```clojure
;; Anything you type in here will be executed
;; immediately with the results shown on the
;; right.
(make-array Double/TYPE 3) 
```
Affected version:
* Light Table version 0.6.5
* Binary version 0.8.4  

_LightTable is such an awesome piece of software - please keep going!_

**Comment by wbridewell** [comment]
This bug is still visible in Light Table 0.8.0 running on Mac OS X. You see the same error message for

(clojure.core/make-array Double/TYPE 3)

for any type and for any dimensions.

**Comment by cldwalker** [comment]
This issue has moved to https://github.com/LightTable/ClojureInstarepl/issues/5 as the instarepl is now its own plugin
