### ISSUE TITLE
Light skin not working

### ISSUE THREAD

**Issue by cayennes** [LightTable/LightTable#1403]
The light skin seems to be set to new-dark instead:

https://github.com/LightTable/LightTable/blob/abf22ea21e161ca09b5b54e8d677de5706765823/deploy/settings/default/default.behaviors#L66

But even when I changed that line, the light skin is largely dark.

**Comment by cldwalker** [comment]
Since no one has shown interest in a light skin for sometime, light skin has been removed and added [to the wishlist](https://github.com/LightTable/LightTable/wiki/Feature-wishlist#general)

**Comment by jbenet** [comment]
> Since no one has shown interest in a light skin for sometime

i think it is a mistake to assume that lack of voices on github == lack of interest. obviously you have dev priorities and so on, nobody will be unhappy with you doing what you think is best. But people do exist that care about these things, so bear that in mind even if "people haven't shown interest".

FWIW, the reason i care about it a lot is that i use Nocturne/Tranquility, and the dark skin looks awful inverted.

**Comment by cldwalker** [comment]
We have higher priorities. Happy to take a light skin contribution from users who care about this
