### ISSUE TITLE
Python dot autocomplete reads strings

### ISSUE THREAD

**Issue by 4of92000** [LightTable/LightTable#1404]
When I am using a Python module or a class, I'll obviously, if you know Python, use dot notation, like `this.that`. LightTable (helpfully) offers to help me by presenting a range of options as soon as I press the period button.

There are two problems with it at the moment. 

One, the thing reads anything, even things in strings, so often, when I have a `this.that`, and I put `this.` and there is a string like "The quick brown fox jumps over the lazy dog", I will often get "lazy," or "fox," or "quick."

The other problem is basically the first problem in reverse. Whenever I put a period in a string, it will give me a range of options, even though it's in a string.

Thank you.

**Comment by kenny-evitt** [comment]
I'm closing this just 'cause it's old. Add a comment if this is still unresolved and I'll re-open.
