### ISSUE TITLE
Plugin manager search box should get focus when opened

### ISSUE THREAD

**Issue by imdark** [LightTable/LightTable#1422]
It is something I am very much used to from sublime text and it streamlines the whole "Getting new plugins" experience.
Il will try to learn some clojure and make it my first project.

**Comment by Mouvedia** [comment]
+1 (atom version)

@one-more-minute this is still relevant, please reopen.

**Comment by one-more-minute** [comment]
Will do, thanks

**Comment by cldwalker** [comment]
This is something I've wanted as well.
@LightTable/committers I'll add this later today unless there's an objection
