### ISSUE TITLE
:open-path command doesn't open path in existing tab

### ISSUE THREAD

**Issue by rschroll** [LightTable/LightTable#1427]
The `:open-path` command should switch to the tab with a file if it is already open.  But it doesn't normalize the paths it receives, so if given multiple paths to the same location, multiple tabs will be opened.  For example,
```Clojure
(cmd/exec! :open-path "/home/rschroll/path.cljs")
(cmd/exec! :open-path "/home/rschroll/./path.cljs")
(cmd/exec! :open-path "/home/rschroll/Pictures/../path.cljs")
```
results in three tabs with the same file.

This was the problem behind rschroll/litex#11, and there we could fix it by running the path through `files/resolve`.  I suspect that could be dropped in here to fix the problem for everyone.

**Comment by cldwalker** [comment]
Looking through old issues... LT uses :open-path internally in places where it makes sense to always open another file e.g. searcher. However we could use such a command for the jump stack where it would make sense to stay in the same file. I'm inclined to make a separate command :open-or-move-to-existing-path. I could also make this an option e.g. `:open-path "FILE" {:existing-path-in-same-tab true}`. @rundis @rschroll  Any thoughts? I'll try a separate command tomorrow unless there are concerns

**Comment by cldwalker** [comment]
Disregard previous comment. Agree with @rschroll fix - just files/resolve the file for this command
