### ISSUE TITLE
Wrap words on press some char like ( ' ) 

### ISSUE THREAD

**Issue by malukenho** [LightTable/LightTable#1444]
Currently if I select a text and press `'` the current text selected is replaced by `'` char.
I want press `'` and wrapper the text selected by this char, like `<` , `[`, `(`, `"`

**Comment by Mouvedia** [comment]
This one is worth reopening.

**Comment by sbauer322** [comment]
Could you point out where this convention comes from? I've never encountered (or at least noticed) it in the wild.

**Comment by Mouvedia** [comment]
![webstorm surround](https://cloud.githubusercontent.com/assets/208817/18576102/933be9d2-7bde-11e6-8a26-f3c426a7086b.png)

**Comment by rundis** [comment]
Hm this seems to work as expected when I use it. Ie write `hello` select hello then press `'` and the text becomes `'hello'`.

**Comment by sbauer322** [comment]
Seems to work for me as well in all cases except `<`. Might be something trivial to add if the others currently work.

**Comment by Mouvedia** [comment]
@rundis it's not working for me.

version 0.8.1

**Comment by rundis** [comment]
Have you turned on the autoclose brackets plugin (https://codemirror.net/demo/closebrackets.html)

ie do you have the following in your user.behaviors ?
```
[:editor :lt.objs.editor/autoclose-brackets]
```

**Comment by Mouvedia** [comment]
@rundis I have it but commented. Thanks for the reminder!
