### ISSUE TITLE
Is there a .deb or PPA for LightTable?

### ISSUE THREAD

**Issue by jameshfisher** [LightTable/LightTable#1457]
I see I can download .tar.gz files from the website, but that's somewhat inconvenient. I can also build from source, but that's still a little more inconvenient.

For us Debian/Ubuntu users, it would be great if there were .deb files, or better, a PPA. Does either exist?

**Comment by theblacklion** [comment]
+1

**Comment by martin-svk** [comment]
+1

**Comment by herbert-mutterwhooze** [comment]
+1

**Comment by kservik** [comment]
+1

**Comment by SwaginWagon101** [comment]
+1

**Comment by AdamSimpson** [comment]
+1

**Comment by DavidJFelix** [comment]
+1

**Comment by bdsatish** [comment]
Me too

**Comment by BlueT** [comment]
+1

**Comment by drakulavich** [comment]
Hi there!

I have not enough experience with packaging. But I have created deb package like sublime-text-installer by Alin Andrei from webupd8. Internal scripts download tarball, extract it to /opt/LightTable, create .desktop file and /usr/bin/ltable symlink.

I would appreciate any feedback and advice.

[https://dl.dropboxusercontent.com/u/734560/lighttable_0.7.2_all.deb](https://dl.dropboxusercontent.com/u/734560/lighttable_0.7.2_all.deb)

**Comment by cldwalker** [comment]
@drakulavich Thanks for the package! I've added it to our [wiki package list](https://github.com/LightTable/LightTable/wiki#os-distributions-package). Closing as this is done
Anyone else feel free to add other links to the above wiki page

**Comment by DavidJFelix** [comment]
Awesome!

**Comment by edwinksl** [comment]
Excellent, thanks!

**Comment by drakulavich** [comment]
Just [updated PPA](https://launchpad.net/~dr-akulavich/+archive/ubuntu/lighttable) to the 0.8.0 release.
Now only amd64 package, cause it download official binaries from lighttable.com.

**Comment by byaka** [comment]
what about 0.8.1?
