### ISSUE TITLE
Support fonts with ligatures

### ISSUE THREAD

**Issue by Reilithion** [LightTable/LightTable#1459]
I wanted to use a font to make Haskell code prettier. It uses ligatures to, e.g. make -> into something that looks more like an arrow, among other things. I can switch to the font in my user behaviors (it looks like it's using the new one, since the appearance of the font changes when I save), but the ligatures don't show up. -> still looks like -> rather than the pretty arrow I see in gedit.

The font I'm trying to use is called Hasklig, and is available here: https://github.com/i-tu/Hasklig

Hope this is something that LightTable can support!

**Comment by Mouvedia** [comment]
For the ones on the Electron version the file is `LightTable.app/Contents/Resources/app/core/css/structure.css`.
