### ISSUE TITLE
Support different fonts for different languages

### ISSUE THREAD

**Issue by Reilithion** [LightTable/LightTable#1460]
I tried to change my user behaviors so that most files show up in the normal Monospace font, but files of a particular language show up in a different font, like so:

    {:+ {:editor [(:lt.objs.style/font-settings "Monospace" "" "")]
         :editor.haskell [(:lt.objs.style/font-settings "Hasklig" "" "")]}

Unfortunately, this seems to have the effect of changing the font everywhere (in all tabs) to the second font, regardless of the language. This happens as soon as a file of that language is opened (I tried it with clojure, too, and it waited until I opened or saved a file with the .clj extension before it applied the new font). Perhaps I am just doing this wrong? But it seems like a bug to me. With this in my user behaviors, I expect Haskell files to use the Hasklig font and all other files to appear in the Monospace font.

**Comment by cldwalker** [comment]
Closing as no one has shown interest in adding this feature. I've added it to [the wishlist](https://github.com/LightTable/LightTable/wiki/Feature-wishlist#general). In the meantime, I'm updating the description from "Editor" to "App" to make it clear it's a global behavior
