### ISSUE TITLE
Background selection/highlight doesn't line up with text when using Consolas font

### ISSUE THREAD

**Issue by mjane** [LightTable/LightTable#1492]
On 64 bit Linux, with Consolas font:

![consolas](https://cloud.githubusercontent.com/assets/1270834/3153943/fea01002-eaa1-11e3-8a5f-51d766a48259.png)

The correct behavior, here DejaVu Sans Mono as an example:

![dejavusansmono](https://cloud.githubusercontent.com/assets/1270834/3153944/fea3391c-eaa1-11e3-828a-eb8c6ed002d6.png)

**Comment by cldwalker** [comment]
Closing as I don't see this behavior when using ` [:app :lt.objs.style/font-settings "Consolas" 12]` on latest LT. I can reopen if you're interested digging more into your issue on the latest LT. Here's a screenshot of what I saw:

<img width="1440" alt="screen shot 2016-01-12 at 2 20 05 am" src="https://cloud.githubusercontent.com/assets/11994/12257297/3fdadf6a-b8d3-11e5-827a-9b5cad8d172e.png">
