### ISSUE TITLE
Linux (Fedora 20): Please install leiningen before running this script.

### ISSUE THREAD

**Issue by mwcz** [LightTable/LightTable#1495]
I just tried to give LightTable a test run in Linux (Fedora 20), but the
linux_deps.sh script seems to not detect leiningen correctly after
installing it with yum.

    $ git clone https://github.com/LightTable/LightTable.git
    $ cd LightTable
    $ bash linux_deps.sh
    Please install leiningen before running this script.
    $ sudo yum install leiningen
    # yum completes the install
    $ bash linux_deps.sh
    Please install leiningen before running this script.

**Comment by cldwalker** [comment]
Closing as this is pretty old and refers to a build script that no longer exists. In general you don't need to run the build script unless you're developing or running on the bleeding edge
