### ISSUE TITLE
Expand block comments

### ISSUE THREAD

**Issue by seemikehack** [LightTable/LightTable#1499]
When I type `/*` or `/**` and hit enter, I'd like to see:
```
/**
 * >
 */
```
with my cursor at the `>`. If I hit enter again, I'd like for another `*` to be inserted:
```
/**
 *
 * >
 */
```

**Comment by cldwalker** [comment]
Closing as this is old and there hasn't been much interest. LT did recently get a [block comment command] which you can bind to any keybinding. Feel free to also add this to [the wishlist](https://github.com/LightTable/LightTable/wiki/QA-Checklist)
