### ISSUE TITLE
We couldn't connect [Errno 22]

### ISSUE THREAD

**Issue by prathamesh96** [LightTable/LightTable#1502]
Whenever I try to evaluate a line by pressing Ctrl+Enter (I'm using python btw), I get the error message 

We couldn't connect.

Looks like there was an issue trying to connect to the project. Here's what we got:
python: can't open file '"C:\Users\Prathamesh\LightTable\plugins\python\py-src\ltmain.py"': [Errno 22] Invalid argument

Please help (I'm using WIndows 8, 64-bit. I have python 2.7 installed)

**Comment by kenny-evitt** [comment]
@joshuafcole this is another issue that warrants the windows label.

**Comment by kenny-evitt** [comment]
@prathamesh96 @bhadra @Pansell @ipstone would you add a comment with specific example code you're trying to run? And please upgrade to the latest version of Light Table first, so we can rule out anything that might have already been fixed.

**Comment by kenny-evitt** [comment]
@prathamesh96 @bhadra @Pansell @ipstone any update on this after upgrading to the latest version of Light Table?

**Comment by cldwalker** [comment]
Closing as no one has responded to this and there isn't information to reproduce the connection bug here. If you are having connection issues please provide reproducible steps and open an issue [on the plugin](https://github.com/LightTable/Python/issues)
