### ISSUE TITLE
single apostrophe ( ' ) not working..

### ISSUE THREAD

**Issue by DeRaNGeR** [LightTable/LightTable#1538]
when i press " ' " it prints " [ ". how can i fix this? i've an IT keyboard layout

**Comment by awage** [comment]
On version 0.8.1 on linux 64 bit this problem remains. I have a spanish keyboard. 

I put this line user.behavior: 
[:editor :lt.objs.editor/autoclose-brackets  ] 
but doesn't change anything.

**Comment by carocad** [comment]
@awage that's weird. I also have a spanish keyboard with a Ubuntu 14.04 on a v0.8.1 Lighttable and the apostrophe works without any problem. Did you change something in your LT?

**Comment by awage** [comment]
Nop. I work on Debian Jessie and I execute the program directly from the downloaded folder. I discovered a workaround: "Windows key + apostrophe" display the apostrophe. So it is not a big issue.
