### ISSUE TITLE
Feature request: Open file at location

### ISSUE THREAD

**Issue by rschroll** [LightTable/LightTable#1549]
Many text editors include the option to open a file at a give line and column number.  This is useful with SyncTeX-aware PDF viewer, for example -- the viewer can open the source TeX file at the location corresponding to a given place in the PDF file.  Light Table should have a command line option to specify the line and column number, and either open the file at that location or move to that location in the already-open file.

**Comment by cldwalker** [comment]
Opening files to a line is available with 0.8.0-alpha - https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss. Happy to take a PR for columns e.g. FILE:LINE:COL
