### ISSUE TITLE
Doesn't open file when started trough "open with"

### ISSUE THREAD

**Issue by V1ncam** [LightTable/LightTable#1555]
When started from the terminal like this: "/path/LightTable <FileNamePath>" it works fine. 

But when it is registered as an launcher with this: "Exec=/path/LightTable %f" and a file is opened trough the right-click context menu it just loads up LightTable. It doesn't load the file.

**Comment by cldwalker** [comment]
All this functionality has been reworked with the move to electron. Closing but feel free to ping us if this is still an issue with the latest
