### ISSUE TITLE
Ability to choose color of parentheses in themes

### ISSUE THREAD

**Issue by Cottin** [LightTable/LightTable#1558]
I've modified the paradiso-light.css theme too make a light an high-contrast theme for outside coding in the bright sun.

However, the parans often get light colors like light-blue and green which are hard to see towards the white background.

It would be nice if you could control the color of the parans in a theme file.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/4736419/3601192/370faeaa-0cff-11e4-9bbe-530be8465c44.png)

**Comment by cldwalker** [comment]
Closing as this seems done
