### ISSUE TITLE
Windows Save (Ctrl + S) Scrolls To Top of Document

### ISSUE THREAD

**Issue by godlikemouse** [LightTable/LightTable#1561]
On windows when editing a file, a few seconds after hitting Ctrl + S (Save) the cursor goes to the very top of the document and scrolls the view away from where you were when you saved.  Then you have to scroll back down and find out where you left off.  This issue happens without any further user input or action after the Ctrl + S is hit.

**Comment by kenny-evitt** [comment]
@godlikemouse I can't reproduce this after following the steps you described. I tried a Clojure file, a Markdown file, a Javascript file, and a CSS file.

What kind of file are you editing?

Do you have any non-standard plugins installed?

**Comment by godlikemouse** [comment]
Any type of file that is long enough to have scrollbars on it.  For instance a zend application.ini configuration file.  When I scroll down to the bottom of the page, make change, click Ctrl S (for save), then move the cursor again I'm magically at the top of the page.  Sometimes however I notice there is a delay before it moves the cursor to the top of the screen.  I've also noticed this seems to only happen when editing non-local files.  For instance if I modify a file on the local machine, everything is fine.  If I modify a file over SSH (using sshfs or something), then the move to top happens.

I don't think I have any non-standard plugins installed.  Installed plugins are:

Clojure 0.1.0
CSS 0.0.6
HTML 0.0.2
Javascript 0.0.6
Paredit 0.0.4
Python 0.0.5
Rainbow 0.0.8
User 0.0.1

This only happens under windows, I don't see this happening on Mac.

**Comment by kenny-evitt** [comment]
@godlikemouse I suspect the "non-local" aspect is probably the key!

What are you using for SSHFS on Windows? I'll see if i can reproduce it myself.

**Comment by godlikemouse** [comment]
I'm using win-sshfs (https://code.google.com/p/win-sshfs/).  Thank you.

**Comment by joshuafcole** [comment]
I believe Kenny is right. If your sshfs program is in some way touching the
file such that LT marks it dirty, it'll reopen the file (consequently
scrolling you to the top). Perhaps investigate why it's modifying the file
after your saves?

On Tue, Jan 20, 2015 at 3:06 PM, Jason Graves <notifications@github.com>
wrote:

> I'm using win-sshfs (https://code.google.com/p/win-sshfs/). Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LightTable/LightTable/issues/1561#issuecomment-70753416>
> .
>



-- 
Screw the environment. Please print this email immediately. And then burn
it.

**Comment by godlikemouse** [comment]
Verified.  I switched to Dokan SSHFS and the problem does not occur.  Thank you and sorry for the bother.  I should have tried that first before reporting.
