### ISSUE TITLE
Do checksum on tarball on install.

### ISSUE THREAD

**Issue by dkinzer** [LightTable/LightTable#1579]
The current install script does not do a checksum on the dependency download.  This security hole is compounded by the fact that the files are also downloaded via HTTP vs HTTPS (see #1578).

See: http://blog.ontoillogical.com/blog/2014/07/28/how-to-take-over-any-java-developer/ , for more details on the security concerns regarding this issue.

**Comment by cldwalker** [comment]
Closing as [our releases now](https://github.com/LightTable/LightTable/releases/tag/0.8.0) include a checksums section at the bottom
