### ISSUE TITLE
Error messages cover/obscure input line in InstaRepl

### ISSUE THREAD

**Issue by ccg** [LightTable/LightTable#1586]
New user here, so I'm sorry if this has already been covered somewhere, but I'm using LT to learn Clojure, and I noticed that when I'm using the InstaRepl, error messages regarding the line of text I'm currently editing are displayed at the bottom of the InstaRepl window. The problem is that when I get to the bottom of the window, the error message covers the line of text I'm trying to edit, making it impossible to see what I'm typing. I'm attaching a screenshot in which you can see an error message for line 61 while only lines 22-59 are visible in the window.
![screen shot 2014-08-03 at 8 51 49 am](https://cloud.githubusercontent.com/assets/59996/3802047/a1fd162a-1c0a-11e4-96b7-cda9d8fba862.png)

**Comment by cldwalker** [comment]
This issue has moved to https://github.com/LightTable/ClojureInstarepl/issues/9 as the instarepl is now its own plugin
