### ISSUE TITLE
Layout redesign game plan

### ISSUE THREAD

**Issue by joshuafcole** [LightTable/LightTable#1609]
### Layout Redesign
- [ ] Phase 1 - Rename #1610
  Tackle the low hanging fruit -- standardize naming conventions and dom structure.
- [ ] Phase 2 - Refactor #1611
  Refactor the source to be more cohesive. Group things on the basis of being a container, being a UI element, or being a widget (functionality embeddable in containers).
- [ ] Phase 3 - Restructure #1612
  Restructure the entire interface of LT to use the flexbox paradigm.

**Comment by rundis** [comment]
@joshuafcole Is there any chance of progressing this work after the atom-shell release. If you don't have any capacity to carry on with this, would it be possible to create some kind of summary to make it possible for us to put this on the roadmap for others to pick up at some point ?

**Comment by cldwalker** [comment]
Closing as interest in this has stalled. Happy to reopen if someone wants to pick it up
