### ISSUE TITLE
Sabayon/Gentoo: libudev.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jotbe** [LightTable/LightTable#161]
After downloading the 64bit Version of Light Table (see #158) it still did not start:

```
$ ./LightTable 
./LightTable: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
```

I was able to workaround this issue by creating a symlink:

```
$ sudo ln -s /usr/lib/libudev.so.1.1.0 /usr/lib/libudev.so.0
```

Maybe recompiling Light Table using the latest systemd libs might help. Not sure though.

**Comment by ThomasChilinski** [comment]
The Binary distribution of Juno. ships with it's own statically linked libudev.so. It's "basically" Light Table with the Juno plugin installed.
