### ISSUE TITLE
Layout redesign phase 2 - refactor

### ISSUE THREAD

**Issue by joshuafcole** [LightTable/LightTable#1611]
Phase 2 of #1609 **INCOMPLETE**
## Phase 2 - Refactor
* [ ] Group containers -> containers/
* [ ] Refactor sidebar/left-bar -> containers/left-bar
* [ ] Refactor sidebar/right-bar -> containers/right-bar
* [ ] Pull sidebar content -> widgets/
  - e.g. widgets/command
* [ ] Pull filter-list / selector -> ui/selector
* [ ] Pull loader out of status
* [ ] Merge status into bottom bar

**Comment by cldwalker** [comment]
Closing as interest in this has stalled. Happy to reopen if someone wants to pick it up
