### ISSUE TITLE
Layout redesign phase 3 - restructure

### ISSUE THREAD

**Issue by joshuafcole** [LightTable/LightTable#1612]
Phase 3 of #1609 **INCOMPLETE**
# Phase 3 - Restructure
... Rebuild the layout system using the flexbox model, per whatever we land on at:
https://github.com/joshuafcole/lt-layout-example/tree/develop

**Comment by cldwalker** [comment]
Closing as interest in this has stalled. Happy to reopen and discuss if someone wants to pick it up
