### ISSUE TITLE
Multiple browser-repls/connections per editor

### ISSUE THREAD

**Issue by Cottin** [LightTable/LightTable#1621]
From javascript development I'm used to having a watch deamon and a livereload server reacting every time I save a file and also having at least 3 browsers viewing the site under development (e.g. Chrome, Firefox and Mobile Safari). Like this I can directly make sure the app looks fine cross different browsers every time I hit `cmd+s`.

How could I get the same workflow with ClojureScript in LightTable?

Now, I'm using the External Browser repl (with script tag) and it reloads directly when I press `cmd+shift+enter` (which is nice!) but if I point another browser to the `index.html` file that new browser becomes the new repl and the old one stops reacting when I evaluate.

Is there a way I can have multiple browser repls open at the same time?
Or are people using some other workflow in Light Table?

**Comment by cldwalker** [comment]
Closing as no one else has shown interest in this and this potentially requires a fair amount of work
