### ISSUE TITLE
instarepl results displaying on wrong line

### ISSUE THREAD

**Issue by crimsonalucard** [LightTable/LightTable#1622]
My cursor starts initially at the end of a line of code. The code will have no new lines after it as well. I evaluate the line with command + enter and the results appear to the right of the line of code.

Then I press enter a few times to create some new lines and the evaluated results actually follow my cursor and stays appended to any piece of of code I write. ANy additional code I evaluate gets appended to the end of the line.

![light_table](https://cloud.githubusercontent.com/assets/1806857/4178794/8b491430-36a7-11e4-80cd-25368ac42bbf.png)

**Comment by cldwalker** [comment]
Closing as we weren't able to reproduce this. If interested, please trying the latest LightTable and install the ClojureInstarepl plugin
