### ISSUE TITLE
Instarepl throws ClassNotFoundException on :or with a java object

### ISSUE THREAD

**Issue by sindux** [LightTable/LightTable#1626]
Lighttable: 0.6.7
```clojure
(defn test
  [& {:keys [date] :or {date (java.util.Date.)}}]
  (str date))
```
InstaRepl could not evaluate above code and threw this exception:
`clojure.lang.Compiler$CompilerException: java.lang.ClassNotFoundException: java.util.Date., compiling:(null:4:1)`

**Comment by cldwalker** [comment]
This issue has moved to https://github.com/LightTable/ClojureInstarepl/issues/8 as the instarepl is now its own plugin
