### ISSUE TITLE
Smart-indent not outdenting correctly with Python

### ISSUE THREAD

**Issue by Voxelot** [LightTable/LightTable#1627]
I'm running into a roadblock using Light Table with python because the smart-indent feature isn't out-denting when it should after functions or classes.

Ex. before smart-indent:

    class Dog:
        kind = 'canine'
        def __init__(self, name):
            self.name = name
    
    class Cat:
        kind = 'feline'
        def __init__(self, name):
            self.name = name

After smart-indent:
    
    class Dog:
      kind = 'canine'
      def __init__(self, name):
        self.name = name
    
        class Cat:
          kind = 'feline'
          def __init__(self, name):
            self.name = name

Not only did it reduce the tabs down to 2 spaces, it also didn't pickup on when to outdent causing the sibling classes to become nested.

This is a major blocker for polyglot Light Table users who use python.

LightTable 0.6.7

**Comment by kenny-evitt** [comment]
I created LightTable/Python#41 to move this to the Python plugin repo.
