### ISSUE TITLE
Pre and post conditions are not respected in the instarepl

### ISSUE THREAD

**Issue by fogus** [LightTable/LightTable#163]
As has been mentioned in #107 and #127 the InstaREPL "ignores" pre and post conditions.  I suspect that what's really happening is that IR uses CLJS as its evaluation chain.  In this case it makes sense because a pre/post map is just a map in the body of a function def to CLJS.  It would be nice to allow the user to select the eval engine (CLJ vs CLJS) for use in the InstaREPL.

**Comment by cldwalker** [comment]
This issue has moved to https://github.com/LightTable/ClojureInstarepl/issues/1 as the instarepl is its own plugin
