### ISSUE TITLE
Autocomplete is slow and may even hang editor up if there's huge string literal

### ISSUE THREAD

**Issue by corristo** [LightTable/LightTable#1635]
I added an image in base64 for prototyping purposes (as a map value, if it matters), it seems that every time I type something in editor, autocomplete tries to match it against this huge string literal.

Haven't tried with other languages, though.

**Comment by kenny-evitt** [comment]
@corristo FYI, there's [an open PR that implements a behavior to limit the completions](https://github.com/LightTable/LightTable/pull/2019).

**Comment by kenny-evitt** [comment]
@Mosho1 There's an open PR that fixes this if you want to test it. Confirmation of whether it resolves this would be appreciated.

**Comment by izarov** [comment]
PR #2019 fixes it for me.

**Comment by kenny-evitt** [comment]
@izarov Thanks. Did the default limit value work for you too? I was still able to reproduce the issue with a limit of 1,000 characters on my Windows 7 box.

**Comment by izarov** [comment]
Yes, seems to work fine with the default, just tried with 998 character strings. 
This is on quite a beefy laptop running El Capitan.

**Comment by cldwalker** [comment]
Fix available with 0.8.0 release
