### ISSUE TITLE
Evaluating Python not working consistantly - Please help

### ISSUE THREAD

**Issue by veryluckyxyz** [LightTable/LightTable#1641]
Hi there,
Evaluating python [on mac osx] has erratic (on my machine at least). It works sometimes  (http://pastebin.com/Yzd2xFvy) while it does not work many other times (blocks at the left hand corner just keep rotating) (http://pastebin.com/5Su6dhg3)
I will be very thankful to you for your help in resolving this.

**Comment by kenny-evitt** [comment]
I created LightTable/Python#42 to migrate this to the Python plugin repo.
