### ISSUE TITLE
Wrong placement of r-click context menu when window is split

### ISSUE THREAD

**Issue by voltcode** [LightTable/LightTable#1642]
steps to reproduce (Windows version):
left panel - editor with html
right panel - browser
r-click on the browser

expected: context menu shows at mouse position
actual: context menu shows somewhere inside the left panel (see screenshot)

![image](https://cloud.githubusercontent.com/assets/5236618/4430622/1d40f0f0-463a-11e4-839f-cf7e3e63e7a8.png)

**Comment by cldwalker** [comment]
@kenny-evitt Could see if this is still an issue on latest LT with windows? I can't reproduce on osx

**Comment by kenny-evitt** [comment]
@cldwalker @voltcode I couldn't reproduce this just now, tho I'm running a build of the latest source. But I don't think we've made any changes since the latest release (0.8.0) that would have fixed this.

**Comment by cldwalker** [comment]
@kenny-evitt Wasn't this last looked into when we were on node-webkit? If it's been a year since we saw this and can't reproduce I'm inclined to close

**Comment by kenny-evitt** [comment]
@cldwalker I think you're right that this was a node-webkit bug.

@voltcode Comment if this is still unresolved for you with the latest version and we'll re-open.
