### ISSUE TITLE
Visual aid: workspace and files in use

### ISSUE THREAD

**Issue by Trapets** [LightTable/LightTable#1661]
Hei!

I experienced that editing with LightTable many files at the same time it would be good to have some visual aids, which file corresponds to its location in the system directory. E.g. if i have many data files with the same name in different project directories.
Maybe plugin?

Some ideas.
Coloring the workspace tree. Users can change the color values with css.
![workspace_tree_visual_aid_1](https://cloud.githubusercontent.com/assets/5584236/4575138/8f79f870-4fa3-11e4-8de2-71ab862bfd0e.png)

If this gets too cluttered and becomes troublesome..
![workspace_tree_visual_aid_2](https://cloud.githubusercontent.com/assets/5584236/4575140/8f869e54-4fa3-11e4-81e1-647b70a7a7b1.png)

A good solution would be if user can toggle workspace coloring for the current file or for all the opened files.
![workspace_tree_visual_aid_1a](https://cloud.githubusercontent.com/assets/5584236/4575139/8f832f80-4fa3-11e4-8ff7-5d964aa3491e.png)

Trapets

**Comment by kenny-evitt** [comment]
This seems to be covered by the plugin [Link with editor](https://github.com/obarbeau/lt-link-with-editor).
