### ISSUE TITLE
Syntax highlighting of map for Clojure

### ISSUE THREAD

**Issue by boxed** [LightTable/LightTable#1664]
The syntax highlighting for map could

1. Display some kind of error indication if you have an odd number of items. Example: {:foo :bar :baz} is not a valid map
2. Display keys different from values. Maybe through a background color, underlined, etc.

**Comment by cldwalker** [comment]
Closing as no one has shown interest in this. Feel free to add to https://github.com/LightTable/LightTable/wiki/Feature-wishlist. Note that the functionality discussed here could be implemented as commands or linter by anyone as a plugin
