### ISSUE TITLE
Sets don't display an inline evaluation

### ISSUE THREAD

**Issue by Misophistful** [LightTable/LightTable#1665]
LT: 0.6.7
OS: OS X (10.9.4)

Lists, vectors and maps evaluate to themselves, but sets don't produce any inline evaluation at all. This can be reproduced by evaluating the following in an Instarepl or a Clojure project:

```clojure
'(1 4.3 1/2 100N)

[\a true "string"]

{:a 1, :b 2}

#{1 2 3 4}
```

**Comment by cldwalker** [comment]
This issue has moved to https://github.com/LightTable/ClojureInstarepl/issues/7 as the instarepl is now its own plugin
