### ISSUE TITLE
Avoid downloading binary tarball in the install shell scripts

### ISSUE THREAD

**Issue by AaronM04** [LightTable/LightTable#1666]
This issue was reported previously in #1494 , but as far as I can tell, is still present (see, for example, https://github.com/LightTable/LightTable/blob/master/linux_deps.sh#L19 ).

I appreciate all the work that's gone into this excellent piece of software, and I can't wait to see it build straight from the source! :-)

**Comment by cldwalker** [comment]
Closing as we've been able to build from source for awhile. See https://github.com/LightTable/LightTable/blob/master/doc/developer-install.md for details
