### ISSUE TITLE
Connection stacking

### ISSUE THREAD

**Issue by clojens** [LightTable/LightTable#1671]
Correct me if I'm wrong, but I don't think each and every evaluation (I pressed Ctrl-Enter a few times) should result in a new connection - at most - it should ask but might even assume the starting up one to be the one we desire and not spawn new attempts until that is finished:

[screeeeen](https://cloud.githubusercontent.com/assets/3727933/4604630/0139c69c-51ad-11e4-9ca1-b6b55dbd2f79.png)

edit: and although this is probably due to an error on my behalf, might still be desirable to prevent this type of behavior, hence posting it here to show this can happen.

**Comment by clojens** [comment]
Ok so this hasn't really happened at all anymore, and I've been using LT quite intensively lately. Since no one else confirmed this symptom and since I no longer experience it either, I'm going to close this.

**Comment by kenny-evitt** [comment]
@clojens Thanks!
