### ISSUE TITLE
python suggestions about LightTable

### ISSUE THREAD

**Issue by bbsdkjdx** [LightTable/LightTable#1673]
It's no doubt that LightTable is a powerful tool for users,but as a pythoner,I have several suggestions for it.
1.it's often execute all codes even if I press"ctrl+enter" at the first line.
2.it's not continous between two executions.especially when I execute win32 COM operation,it will show me that "CoInitialize"haven't called,though I have called it in last execution.
3.the theme for python is less colourful.

**Comment by kenny-evitt** [comment]
I created LightTable/Python#43 for issue [1].

**Comment by kenny-evitt** [comment]
I created LightTable/Python#44 for issue [2].

**Comment by kenny-evitt** [comment]
@bbsdkjdx I'm not sure what [3] is referring to exactly as there's no Python theme (included in the core Light Table package). I'm pretty sure syntax highlighting is provided by CodeMirror but whatever Light Table theme you're using is providing the specific colors that you're seeing. What theme are you using/ The default theme?

**Comment by kenny-evitt** [comment]
I'm closing this as all of the Python-specific issues have been moved to [the Python plugin repo](https://github.com/LightTable/Python).
