### ISSUE TITLE
IPython connects but never evals *in existing files*

### ISSUE THREAD

**Issue by choct155** [LightTable/LightTable#1682]
The issue I am having is almost identical to this issue:  https://github.com/LightTable/LightTable/issues/576

The difference is that, as long as I am writing a new file in this LightTable instance *that did not previously exist in my workspace*, I actually can eval.  Thus, my rather clunky workaround is just to copy my old script into a new unused file, and just overwrite the old one.  This happens on two separate systems:

System 1
-LT v 0.6.7
-Binary v 0.8.4
-Python v 2.7.6
-IPython v 1.1.0
-Windows 7 x64

System 2
-LT v 0.6.7
-Binary v 0.8.4
-Python v 2.7.6
-IPython v 1.0.0
-Ubuntu 14.04 LTS

**Comment by jzthree** [comment]
I am having the problem exactly as described here. Light Table 0.7.2.  Python 2.7.5 . IPython 1.1.0. Windows Server 2012.

**Comment by choct155** [comment]
I am also, to confirm, still having this issue.

On Tue, Mar 31, 2015 at 3:12 AM, Jian Zhou <notifications@github.com> wrote:

> I am having the problem exactly as described here. Light Table 0.7.2.
> Python 2.7.5 . IPython 1.1.0. Windows Server 2012.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LightTable/LightTable/issues/1682#issuecomment-87970065>
> .
>



-- 
Marvin Ward Jr.
Associate Analyst
Tax Analysis Division
*Congressional Budget Office <http://www.cbo.gov>*
Email:  Marvin.Ward@cbo.gov <Marvin.Ward@dc.gov>
Phone:  (202) 226-2688

**Comment by kenny-evitt** [comment]
@choct155 are you also running on Windows?

**Comment by cldwalker** [comment]
Closing as we'll be tracking this in https://github.com/LightTable/Python/issues/35
