### ISSUE TITLE
LT very slow on Yosemite

### ISSUE THREAD

**Issue by avstudio** [LightTable/LightTable#1685]
Hi,
After Yosemite  installation LT become very slow. It's freezes very often on autocomplete. In one word it becomes useless. On Maverics everything was perfect.

Any idea why?

LT 0.6.7
Macbook Pro 2011

**Comment by priyatam** [comment]
@cldwalker I still cannot install atom-shell on a brand new mac and none of my co-workers can get it working either. Further, the latest branch of atom-shell doesn't have 'osx_deps.sh'. Given that there are close [1500 views](https://groups.google.com/forum/#!searchin/light-table-discussion/atom$20shell$20yosemite) on this issue, would you be open to building a binary that _works_ for 0.80?

**Comment by one-more-minute** [comment]
I think it probably goes without saying that we'll want to release a binary that works.

While the atom-shell branch is far from complete, there does seem to be a lot of interest and we could perhaps release some betas. I may have time to give this a go in the next week.

**Comment by priyatam** [comment]
Thanks, @one-more-minute. A weekly beta (binary) off `atom-shell` would be great.

**Comment by alilee** [comment]
I've had a showstopper build issue on OS X (Yosemite) for a long while now, but trying again today it builds and instarepl seems to be working well.

**Comment by kenny-evitt** [comment]
@alilee You may have run into the name-change of Atom shell to Electron. That was fixed just a couple of weeks ago. Thanks for trying it out again! Issues and pull requests welcome!

@avstudio @vbauer @simax @priyatam Building the *atom-shell* branch is pretty straightforward – or should be at least. We're working on the next release now, but it'd be great if you all could try out the latest code.

**Comment by kenny-evitt** [comment]
I'm guessing this is no longer an unresolved issue. If it is, please build the latest source off the *master* branch and comment on this issue if you're still having this problem.

**Comment by alilee** [comment]
No issues now - thanks.

**Comment by izarov** [comment]
I upgraded from Mavericks to El Capitan and I am now having this problem even after building off the latest source. In particular autocomplete often freezes for several seconds.

I can see the following LightTable process suggesting it is using Electron underneath:
*lighttable-0.8.0-alpha-mac/LightTable.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper*

Is there something else I can try? I'm using a late 2013 Macbook Pro with Intel and NVIDIA GPUs.

**Comment by kenny-evitt** [comment]
@izarov If you're only experiencing slowness with auto-completion, you may be running into #1635. If you're experiencing slowness generally, please open a new issue as you're using a newer version of OS X than covered by this issue.

**Comment by izarov** [comment]
Thanks @kenny-evitt, it's indeed #1635. 
I deleted some long string literals that I had in the code and it is much better now.
