### ISSUE TITLE
Middle-mouse click on tab disables hotkeys and mouse click 

### ISSUE THREAD

**Issue by AlstonA** [LightTable/LightTable#1686]
Out of habit, I normally try to close the tabs with the middle- mouse button. This causes the scroll direction arrow to appear and when I try to click away, I am denied the option to do so. I don't know what's going on, but I've managed to replicate this error.  I've provided a video url (YouTube)
video displaying the issue:

https://www.youtube.com/watch?v=0wbNxCa_B4s&feature=youtu.be

**Comment by cldwalker** [comment]
Closing as we never get more info to reproduce and fix this
