### ISSUE TITLE
non-integer line height is not working in the live refresh of User behaviors

### ISSUE THREAD

**Issue by pierre-haessig** [LightTable/LightTable#1696]
This is a follow-up of the question I asked on Stackoverflow http://stackoverflow.com/questions/26485798/

I noticed that when setting a **non-integer line height** in the User  behaviors like:

```Clojure
:editor [:lt.objs.editor/no-wrap
         (:lt.objs.style/set-theme "default")
         (:lt.objs.style/font-settings "Ubuntu" 12 **1.5**)
    ]
```
the live refresh of the User Interface is working erratically (like sometimes it sticks at an integer value, or some other value).

However, notice that the setting is correctly applied  *after restarting* Lighttable entirely.

This issue is by itself minor, but I'm reporting it because it is maybe a symptom of some other problem in the live refresh process.

best,
Pierre

**Comment by db47h** [comment]
The issue does not seem to occur anymore with latest master (d79adff7855).

A workaround that worked for me with LT 0.7.2 was to put the numbers between double quotes:

    [:editor :lt.objs.style/font-settings "Ubuntu Mono" "13" "1.05"]

**Comment by kenny-evitt** [comment]
@pierre-haessig Comment to re-open if you can reproduce this in the newest version.
