### ISSUE TITLE
Plugin naming convention

### ISSUE THREAD

**Issue by one-more-minute** [LightTable/LightTable#1702]
At the moment the language plugins are simply called `Python`, `Clojure` etc.. That's fine under `LightTable/Clojure` but potentially causes conflicts and confusion for people who work on both the language and the plugin. So I suggest having an LT plugin naming convention, something like `Python-LT`, `Emacs-LT` etc. (which is what I've been using for Juno/Julia).

It wouldn't be that necessary for non-language plugins with distinctive names, but might still be good for googleability and consistency.

**Comment by cldwalker** [comment]
Closing as this hasn't been an issue for the core team or any plugin authors
