### ISSUE TITLE
Modal dialogs overlap each other

### ISSUE THREAD

**Issue by can3p** [LightTable/LightTable#1720]
This report summarize a bunch of tasks connected with prompt dialogs behavior, e.g. #709, #1061, #937 that are closed, but the issue still exists. The main thing is that there is nothing prevents LT from opening new popups over and over again on top of each other, that leads to some ui and logic issues.

Example cases:
1) Open a file in LT and modify it slightly.
2) Open the same file in other editor, then modify and save it multiple times.

On each save LT will produce another dialog about file changes on top of previous one.

Expected behavior: only one prompt dialog at the end

Another case: do the same actions and delete file at the end. LT will show another prompt window above all other that ask about file reload. If you press "ok", this dialog will close, but you will still see
prompts about file changes and if you click "Reload from disk" on any of them, LT will produce JS exception, and buffer will get empty.

Moreover dialogs only look like modal ones, in reality user can do anything with keyboard (e.g. ctrl - space, or even edit the buffer)

**Comment by cldwalker** [comment]
Closing as master no longer has these dialogs for modified or deleted files
