### ISSUE TITLE
Strange behaviour loading error: Invalid behaviors file

### ISSUE THREAD

**Issue by one-more-minute** [LightTable/LightTable#1727]
```
Invalid behaviors file: /Users/mike/LightTable/deploy. Behaviors must be either a vector or a map.
```

I see this, and variants that seem to be looking for `appnw`, when installing plugins.

**Comment by rljohnsn** [comment]
Answering https://github.com/LightTable/LightTable/issues/1801#issuecomment-68614256 Yes the pluggins do appear in plugin manager even though they are not on disk.

**Comment by sherpc** [comment]
0.7.2 Windows 8 fresh install error persists. Maybe exists some workaround?

**Comment by ghassanpl** [comment]
Oh wow, this problem is still there? Huh.

**Comment by olivervejen** [comment]
Anyone got some new info on this?

**Comment by OryxGazella** [comment]
Is there a workaround for this?

**Comment by kenny-evitt** [comment]
@OryxGazella @olivervejen I saw this erro while installing plugins on a build of the latest source but I didn't actually have any problems with any of the plugins. What problems are you having beyond seeing this error? What plugins are you installing?

**Comment by OryxGazella** [comment]
@kenny-evitt Oh, I didn't actually check whether the plugins were installed or not. Just assumed it meant it wasn't installed. Silly me.

**Comment by olivervejen** [comment]
@kenny-evitt the plugins work well enough, but it annoys me to have an error for every plugin i've installed in the console every time i start light table, but i guess it will be fixed eventually :)

**Comment by kenny-evitt** [comment]
@OryxGazella @olivervejen thanks for checking. And always remember – pull requests welcome!

**Comment by kenny-evitt** [comment]
@olivervejen Magnus didn't spend the time to fully investigate *why* this was happening, but hopefully it at least won't be annoying you any more. You'll need to run a build of the latest source version (which is actually remarkably easy to build) until we release 0.8.0.

**Comment by IGitSylvia** [comment]
Bump,

It is happening to me as well... when trying to install a plugin...

```text
Invalid behaviors file: P:\PortableApps\LightTable-TextEditor+Portable. Behaviors must be either a vector or a map.
Invalid behaviors file: P:\PortableApps\LightTable-TextEditor+Portable. Behaviors must be either a vector or a map.
Invalid behaviors file: P:\PortableApps\LightTable-TextEditor+Portable. Behaviors must be either a vector or a map.
```

**Comment by rundis** [comment]
@IGitSylvia Did you try building from master before reporting this ?
