### ISSUE TITLE
Issues with HiDPI Scaling on Windows 8.1

### ISSUE THREAD

**Issue by Mocuto** [LightTable/LightTable#1729]
Right now Light Tables does not support HiDPI scaling. If you look at the screenshot, you can see how the text looks blurry compared to Sublime Text 3: 
![image](https://cloud.githubusercontent.com/assets/5456121/5117573/3bc02a64-7024-11e4-9f13-89c83a8b02f1.png)

**Comment by kenny-evitt** [comment]
@Mocuto Can you try building and running the *atom-shell* branch? I'm curious if this is still an issue with Atom/Electron (which replaces node-webkit/NW.js).

**Comment by Mocuto** [comment]
Will do, will edit this comment with update in 2 days.

**Comment by cldwalker** [comment]
We've release 0.8.0-alpha which is based on Electron - https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss. Closing as this should be resolved. Ping us if it is still an issue

**Comment by crquan** [comment]
this is still an issue on HiDPI monitor on Linux when I am trying lighttable-0.8.0-alpha today, the window / font size are 1/2 size of a regular window

```
-rw-r--r-- 1 mint users 53M Oct 22 21:29 lighttable-0.8.0-alpha-linux.tar.gz
```

**Comment by kenny-evitt** [comment]
@crquan Would you try the Atom editor too? There seem to have been some fixes for graphics issues in versions of Electron, which both LT and Atom use, that are more recent than what LT is running.

**Comment by crquan** [comment]
yes I did, atom editor doesn't have this issue.

**Comment by kenny-evitt** [comment]
@crquan That's probably good news actually; it means that upgrading to a newer version of Electron should fix this. You can build the source with the changes in PR #2052 and test it yourself now – that would be *really* helpful.

**Comment by raoulmillais** [comment]
I've just built #2052 on Linux 

```bash
$ uname -a
4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
```
This build of Lighttable looks great on my HiDPI monitor.

![screenshot from 2015-12-07 16-37-17](https://cloud.githubusercontent.com/assets/302663/11633039/60c9fc6c-9d01-11e5-9101-f82162f8fa5f.png)

**Comment by kenny-evitt** [comment]
@raoulmillais Thanks for the update!

@crquan I suspect this should be fixed for you in the latest source version. We're going to be releasing 0.8.0 (sans alpha designation) soon and it will include the changes in the current source version.

**Comment by crquan** [comment]
great! will have a test; while is 0.8.0-alpha already release? I'd usually download a `-linux.tar.gz` version
https://github.com/LightTable/LightTable/releases

**Comment by kenny-evitt** [comment]
@crquan The 0.8.0-alpha release doesn't have the new changes I'd like you to test.

Clone the repo onto your computer and run *script/build.sh*. Then run *builds/lighttable-0.8.0-linux/lighttable*.

**Comment by cldwalker** [comment]
Closing as we haven't heard back and @raoulmillais has had success. Can reopen if this is still reproducible with LT 0.8.0 and more info is given on the environment
