### ISSUE TITLE
Refresh tab when trailing whitespaces are removed

### ISSUE THREAD

**Issue by integricho** [LightTable/LightTable#1733]
The behavior `:lt.objs.editor.file/remove-trailing-whitespace` does not refresh the tab where it was executed on save. So even though it removed the trailing whitespaces, the file has to be closed/reopened in order to see that those changes actually happened. Actually, the same goes for `:lt.objs.editor.file/last-char-newline` as well.

**Comment by cldwalker** [comment]
Sorry for the delay. Agree this is a bug. Fix coming shortly
