### ISSUE TITLE
Overriding LTs built in file types

### ISSUE THREAD

**Issue by one-more-minute** [LightTable/LightTable#1737]
It seems like the order of behaviours has been changed somewhere, because now [this definition](https://github.com/LightTable/LightTable/blob/db2d804e5de1d763d481f9fbd5d6c7f4c13ef874/deploy/settings/default/default.behaviors#L287) is overriding the one in my plugin.

Is there some way to either negate that definition or make sure it's overridden properly? If not I'd settle for removing it from `default.behaviors` completely, so long as we can get a patch release out reasonably soon.

Side note: If you wanted to negate that behaviour, how would it work? Would you have to copy/paste the whole thing and add a minus sign?

**Comment by cldwalker** [comment]
Closing as this has been fixed
