### ISSUE TITLE
Problems with cursor placing on coffeescript and javascript files

### ISSUE THREAD

**Issue by alun** [LightTable/LightTable#1738]
```coffeescript
#I write this code and go new line in .coffee file:
app.factory "userApi", ['$resource', (resource) ->
                        #cursor gets here
  #but I expecting it here
]
```

The worse thing is that when I put the second line in right place by hand, third line going back to the incorrect place under opening square bracket.

It does appear to work as expected in plane CM demo:

http://codemirror.net/demo/changemode.html
```javascript
app.factory("userApi", ['$resource', function (resource) {
  console.log('hi');
}]);
```

**Comment by cldwalker** [comment]
I'm not seeing this issue with the current CM on LightTable 0.8.0-alpha. Fwiw, CM has a more accurate mode demo for coffeescript [here](http://codemirror.net/mode/coffeescript/index.html)
