### ISSUE TITLE
Pressing enter while navigating filter-list just makes a new line

### ISSUE THREAD

**Issue by thomasgauthier** [LightTable/LightTable#1745]
It's impossible to select an element in the filter list with enter.
The keymap seems to be good:       [:filter-list.input "enter" :filter-list.input.select!].

I'm having this issue since I updated to 0.7.

**Comment by muhuk** [comment]
It took me a while to figure this out myself so I'm adding this:

**You can use TAB to select an item from the autocomplete list, ENTER will make a new line by default**.
