### ISSUE TITLE
Energy Impact is too big on OS X

### ISSUE THREAD

**Issue by wondernet** [LightTable/LightTable#1750]
I have a django project opened in LightTable and I observed a big impact on Energy: in few days Average Energy Impact for LightTable is 59.25% and Safari has an impact of 7.27%.

**Comment by kenny-evitt** [comment]
@wondernet Have you tried building and running the *atom-shell* branch? I'm curious whether this is resolved with that version.

**Comment by wondernet** [comment]
@kenny-evitt  I didn't tried that.

**Comment by kenny-evitt** [comment]
@wondernet If you didn't try that, please do. If you did, please confirm that this issue still applies.

**Comment by petermolnarnomicom** [comment]
The energy issue still exists. The problem is that LT keeps the background Julia process busy...at about 20% when I'm not typing...
I'm running LIghtTable version 0.7.2 (binary version 0.21.2) from the atom-shell branch on GitHub, OS X 10.10.5, and Julia 0.3.11.
I keep other Julia REPLs running, and they are fine when idle.
I would greatly appreciate any suggestions. 
Thanks

**Comment by kenny-evitt** [comment]
@petermolnarnomicom Try building the latest *master* branch and running that. But I suspect this may be an issue with [the Julia plugin](https://github.com/one-more-minute/Julia-LT).

**Comment by petermolnarnomicom** [comment]
Has the atom-shell part been merged to the master?
I’ll try it out.
Thanks
-p

Peter Molnar
Senior Data Scientist
NOMi®
O +1.678.367.2943 | M +1.404.271.2872
twitter @getnomi <https://twitter.com/getnomi> | LinkedIn petermolnar <https://www.linkedin.com/in/petermolnar>

**Comment by kenny-evitt** [comment]
@petermolnarnomicom Yeah, [*atom-shell* was merged almost three months ago](https://github.com/LightTable/LightTable/pull/1756) (!). We're definitely getting *closer* to the next release.

**Comment by cldwalker** [comment]
We've release 0.8.0-alpha which is based on Electron - https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss. If this is still an issue, please [provide reproducible steps](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md#bugs)

@petermolnarnomicom If this still issue exists and it's specific to a Julia process, please open an issue with [the appropriate plugin](https://github.com/one-more-minute/Julia-LT/issues)

**Comment by cldwalker** [comment]
Closing as we haven't heard back on reproducible steps to address this. 0.8.0-alpha release may have resolved. Feel free to ping us if it's still an issue
