### ISSUE TITLE
Opening brackets, parens, curly braces not triggering closing brackets, parens, curly braces

### ISSUE THREAD

**Issue by peterk87** [LightTable/LightTable#1754]
After updating from LT 0.6.0 to LT 0.7.2, opening brackets/parens/curly braces is not triggering closing brackets/ parens/curly braces. It seems like this behaviour has been removed from the `default.keymap` file.

In order to return this behaviour, I needed to add the following to the `user.keymap` file:

```
 [:editor.keys.normal "(" (:editor.open-pair "(")]
 [:editor.keys.normal "{" (:editor.open-pair "{")]
 [:editor.keys.normal "[" (:editor.open-pair "[")]

 [:editor.keys.normal ")" (:editor.close-pair ")")]
 [:editor.keys.normal "}" (:editor.close-pair "}")]
 [:editor.keys.normal "]" (:editor.close-pair "]")]

 [:editor.keys.normal "\"" (:editor.repeat-pair "\"")]
```

It's quite frustrating to have this kind of functionality suddenly removed after an update.

**Comment by rundis** [comment]
Not sure if its this issue or a new repeat issue of a previous classic. But for international keyboards (norwegian, german etc). The 0.7.0 "fix" hasn't solved anything when you actually want matching (:
