### ISSUE TITLE
Openning IPython Notebook with Light Table

### ISSUE THREAD

**Issue by cjermain** [LightTable/LightTable#1761]
I'm really excited to see that I can open the IPython Notebook (version 2.3) in Light Table by using a Browser in Connections. However, I've noticed that when clicking on a link to the actual notebook, it opens up the notebook in a different window instead of as a tab. What is more peculiar is that if I type in the address for the notebook, which has displayed fine in the seperate window, the page no longer loads. Here is the error from the console.

```
Uncaught Error: Mismatched anonymous define() module: [object Object] http://requirejs.org/docs/errors.html#mismatch
require.js?v=07d7db4d3fd6519996822665e4239282 [166]	makeError
require.js?v=07d7db4d3fd6519996822665e4239282 [1221]	intakeDefines
require.js?v=07d7db4d3fd6519996822665e4239282 [1408]	anonymous
```

Is this a Light Table issue, or an IPython issue?

I would be great to be able to work in the editor and with IPython notebooks in the same program!
![lighttableipythonnotebook](https://cloud.githubusercontent.com/assets/4521567/5257098/e9179258-79a0-11e4-9af8-076349aa96a4.png)

**Comment by cldwalker** [comment]
Closing as iPython no longer works for more recent versions and support is being tracked in https://github.com/LightTable/Python/issues/35
