### ISSUE TITLE
Cannot open files from desktop on gnome

### ISSUE THREAD

**Issue by Lucas-C** [LightTable/LightTable#1762]
Spotted in http://stackoverflow.com/questions/26161805/open-plain-text-files-with-lighttable-by-default-when-double-clicking-them-in-u

There are 2 issues here:
- currently the deployed Bash script doesn't pass any arguments to LightTable if it's not invoked from a terminal, but this is needed e.g. to make a gnome desktop shortcut and make LightTable the default text editor. This issue can also be reproduced by using the ALT+F2 launcher under Ubuntu.
- independently LightTable cannot currently open files whose names contain ' ' characters.

**Comment by matt-della** [comment]
I can confirm that the bug is also affecting me on the latest version for Linux. Dragging the file into LT works, adding the file as a command line argument works, but double-clicking the file does not. Adjusting the lighttable.desktop did enable me to show the program in my "open with..." menu, but I am still persented with a welcom screen instead of the file I wanted to open.

**Comment by QM-Hacker** [comment]
I just managed to fix this problem in Arch with a KDE desktop. After changing my lighttable.desktop file to

```
[Desktop Entry]
Name=Light Table
Comment=Light Table IDE
Type=Application
Icon=lighttable
Exec=/opt/LightTable/ltbin
Categories=Utility;TextEditor;Development
Terminal=false
MimeType=text/plain;
```
from
```
[Desktop Entry]
Name=Light Table
Comment=Light Table IDE
Type=Application
Icon=lighttable
Exec=lighttable
Categories=Utility;TextEditor;Development
Terminal=false
MimeType=text/plain;
```
I can open text files in LightTable from the desktop.

Hope this helps

**Comment by matt-della** [comment]
This did partially solve the issue for me. I also made one additional change for my system:

    [Desktop Entry]
    Name=Light Table
    Comment=Light Table IDE
    Type=Application
    Icon=lighttable
    Exec=/opt/LightTable/ltbin %U
    Categories=Utility;TextEditor;Development
    Terminal=false
    MimeType=text/plain;

Adding the %U made LightTable available in the "open with..." menu in GNOME. Now it just needs to properly handle spaces in filenames and we'll be golden.

**Comment by cldwalker** [comment]
Closing as the second issue has been resolved for some time and the first issue is a wontfix. LightTable is agnostic to installation paths and thus can't generate desktop files that work out of the box. Feel free to share desktop scripts [in this wiki section](https://github.com/LightTable/LightTable/wiki#miscellaneous-scripts)
