### ISSUE TITLE
Python connection without output values (rehash)

### ISSUE THREAD

**Issue by rickedanielson** [LightTable/LightTable#1773]
This issue follows directly from #495, so I will update some version numbers here and add the juno is installed and working (just not python): I'm running LightTable 0.7.2 on Ubuntu Kernel 3.13.0-40-generic (12.04) 64-bit. I have python 2.7.3, IPython 1.0.0, and python-zmq installed.

When I try to start a python connection, the spinning boxes start up and the status line reads "Connecting" before quickly switching to "Connected to $HOME". However, the spinning boxes never go away, and no result is returned at the python expression. (I'm trying '2+2' to start.) There are no messages in the console or on the terminal from which LightTable was launched (though there were some unrelated (?) startup errors there).

I don't think any python is actually being evaluated.  The clojure connection seems to work and so does julia (via juno).

This problem was also previously discussed in #495 and #469.  Following #495, I uninstalled ipython but the problem remained.

**Comment by cldwalker** [comment]
Closing as I believe this issue is covered by https://github.com/LightTable/Python/issues/35. If I'm incorrect, feel free to try the latest LT and python plugin and reopen an issue on https://github.com/LightTable/Python/issues with the python project that is hanging
