### ISSUE TITLE
file.encoding

### ISSUE THREAD

**Issue by danjohansson** [LightTable/LightTable#1774]
When I start a clojure project in lighttable with file.encoding=UTF-8 set in leiningen project.clj file on windows and check the jvm arguments of the process via visualvm it has two file.encoding arguments one is UTF-8 but the other is cp1252 and 
cp1252 is being used as default.

When starting the same project using leiningen repl it still has two file.encoding arguments but both are UTF-8 and UTF-8 is used as the default.

**Comment by kenny-evitt** [comment]
@danjohansson  I'm unclear whether you were able to reproduce your issue yourself in the empty project. Here's what I did:

I created a new Leiningen project via `lein new light-table-issue-1774`.

I added the following to *project.clj*:

```
:jvm-opts ["-Dfile.encoding=UTF-8"]
:main light-table-issue-1774.core
```

I changed *core.clj* to the following:

```
(ns light-table-issue-1774.core)

(defn -main
  "I don't do a whole lot."
  []
  (loop [x 100000]
    (when (> x 0)
      (println "Hello, World!")
      (recur (- x 1)))))
```

When I run the project via `lein run` and check the process command line setting in Process Explorer I see this:

```
... -Dfile.encoding=UTF-8 -Dclojure.compile.path=C:\@code\light-table-issue-1774\target\classes -Dlight-table-issue-1774.version=0.1.0-SNAPSHOT -Dfile.encoding=Cp1252 ...
```

When I run the *core.clj* file in Light table the command line setting for the relevant process is this:

```
... -Dfile.encoding=UTF-8 -Dclojure.compile.path=C:\@code\light-table-issue-1774\target\classes -Dlight-table-issue-1774.version=0.1.0-SNAPSHOT -Dfile.encoding=Cp1252 ...
```

**Comment by danjohansson** [comment]
When I run in the lighttable repl and the lein repl I get the following:
Lighttable:
process explorer:
```
java ... -Dfile.encoding=UTF-8 -Dfile.encoding=Cp1252 -Dclojure.debug=false clojure.main -i C:\Users\mdajo.MILLTECH0\AppData\Local\Temp\form-init7053980434270346778.clj
```
repl:
```
(System/getProperty "file.encoding")  ->  "Cp1252"
```

lein
process explorer:
```
java ... -Dfile.encoding=Cp1252 -Dfile.encoding=UTF-8 -Dclojure.compile.path=C:\Users\mdajo.MILLTECH0\kod\testprj\target\classes -Dtestprj.version=0.1.0-SNAPSHOT -Dclojure.debug=false clojure.main -i C:\Users\mdajo.MILLTECH0\AppData\Local\Temp\form-init6289668231174882651.clj
```
repl:
```
(System/getProperty "file.encoding")  ->  "UTF-8"
```

This information differs from what I wrote in the original issue description. That is because I ran lein in minGW and forgot about that.

Seems to me this issue has to do with the order of the file.encoding definitions.

**Comment by kenny-evitt** [comment]
@danjohansson what's the desired behavior?

**Comment by danjohansson** [comment]
It is desired that the encoding specified in the project.clj file is used.
The behaviour of leiningen in the example above is correct.

The last definition of file.encoding on the commandline has precedence so fixing this issue is a matter of making sure that the file.encoding from the project.clj file is specified after the other. 
Though Im not sure where the other comes from.

**Comment by kenny-evitt** [comment]
@danjohansson sorry for taking so long to follow-up. I tried to find any obvious culprits in the Light Table source code, but I'm almost completely unfamiliar with it.

@cldwalker would you point me in the direction of the relevant Light Table source code so I can try to first understand where Light Table is picking up the encoding options?

**Comment by kenny-evitt** [comment]
@danjohansson I'm stilling looking into this.

**Comment by danjohansson** [comment]
@kenny-evitt Thanks for looking at this. I noticed that the clojure plugin depends on an old version of leiningen so tried to upgrade it to 2.5.1 and the problem is gone!

**Comment by kenny-evitt** [comment]
@danjohansson you updated the version of Leiningen referenced by the Clojure plugin?

**Comment by danjohansson** [comment]
Yes
Den 26 feb 2015 15:11 skrev "kenny-evitt" <notifications@github.com>:

**Comment by kenny-evitt** [comment]
@danjohansson would you submit a PR to the Clojure plugin repo for this?

**Comment by kenny-evitt** [comment]
[This commit](https://github.com/LightTable/Clojure/commit/819ae4ef791e2dc51e068e703556ebe62006af16) bumped the Leiningen version to 2.5.2 so this should be fixed in the latest version of the Clojure plugin, which is the default version of the latest (alpha) release of LT itself.

**Comment by kenny-evitt** [comment]
@danjohansson Comment if this is still an issue and I'll re-open.
