### ISSUE TITLE
Horizontally scroll tab bar with middle wheel vertical scroll

### ISSUE THREAD

**Issue by Morgawr** [LightTable/LightTable#1776]
If I open too many tabs (especially in a split tabset) the extra tabs go "under" the other tabset (or past the screen) and disappear, I can't use them until I close some previous tabs or enlarge the window/tabset. There should be horizontal scrolling or a fold to contain the extra tabs, in my opinion, or at least give me a way to retrieve the lost tabs.

**Comment by cldwalker** [comment]
Closing as this has been open for more than a year and no one who's interested in this has contributed. Happy to reopen if someone will work on this
