### ISSUE TITLE
Indentation changes for Clojure code

### ISSUE THREAD

**Issue by bbatsov** [LightTable/LightTable#1782]
I've noticed that Clojure code gets indented in LT the same way it's indented (or was) by Emacs's clojure-mode. Unfortunately some of the indentation stuff you copied were actually bugs in clojure-mode (that were recently fixed in version 4.0) - like the indentation of `cond` (which should use 2 spaces) and threading forms, which should be indented like:

```
(-> a
  b
  c)
```

instead of:

```
(-> a
    b
    c)
```

**Comment by cldwalker** [comment]
Moved to https://github.com/LightTable/Clojure/issues/67
