### ISSUE TITLE
Mac and Meta-Keys

### ISSUE THREAD

**Issue by benjyz** [LightTable/LightTable#1783]
I've run into this issue with Mac and haven't been able to fix it myself (Mac OS 10.8, German keyboard). Alt is not interpreted as a meta-key. For emacs I can set the preference "use option as meta key" for a terminal - not sure how to do this globally for Lighttable.

**Comment by joshuafcole** [comment]
While you can't swap keycodes -> keysyms in LT, you can rebind hotkeys in your keymaps. LT Does have global preferences in the form of your user plugin, which has a user.keymap (for keybinding alterations) and user.behaviors (for other preferences and wiring). I know it can be frustrating to remap hotkeys manually though. I'm unsure about OSX, but I know that KDE in Ubuntu has a rich system for remapping control keys. Perhaps look for that in your preferences and/or for an app with that capability?

Hope that helps!
Josh

**Comment by cldwalker** [comment]
Closing as this is fairly old and there isn't enough info to reproduce a specific bug. On osx, I can use "alt-" to map an alt/option keybinding and "cmd-" to map an apple/command keybinding. For more about our keybindings and how mousetrap defines meta [see here](https://github.com/LightTable/LightTable/blob/master/doc/behavior-and-keymap-configuration.md#keys). Can reopen if there's a specific reproducible keybinding that's still an issue with latest LT
