### ISSUE TITLE
Minor aesthetic and slightly pedantic perhaps ... a drag icon

### ISSUE THREAD

**Issue by clojens** [LightTable/LightTable#1787]
But persistent enough to keep bugging me and my hack attempts of the styles involved in LT given CSS were unable to resolve this issue:

When I **drag a panel** (e.g. console, tabset), in Linux, I get this godawful **new-document kind of icon** instead of a "proper hand icon of some sort".

Now I know I'm a minority using Linux but I guess not if you are frequent user of LT I'd assume, I was wondering if anyone else has this problem and how to (preferably from within LT of course, if it is everywhere) fix this. Because it is killing some of the appeal of the slick-modern editor.

It's not a major turn-off but difficult enough to not have a clue where to look on either internet searches or elsewhere so I figured I'd start here.

Note that I use ArchLinux with a basic Xcfe setup (which has the basic Gtk accessories like basic theme etc set up).

Input or solutions please advice

edit: since a picture says more than a thousand words ... 
[screenshot](https://cloud.githubusercontent.com/assets/3727933/5528876/8fd390b6-8a0d-11e4-9f42-e8af2fbaf10c.png)

**Comment by joshuafcole** [comment]
Just to add to this, I was unable to reproduce the issue on Ubuntu + KDE, so I think this may be GTK specific.

**Comment by clojens** [comment]
cldwalker: yea I would say so too... next time I'm hacking the CSS I'll take another round at it, most of it wanted to see if anyone else had this or if it was mostly me/limited. 

joshuafcole: ok, thanks for the feedback. I'll refine my searches aimed more towards that, as I'm fairly sure I should be able to override this on platform and not in webkit/css.

Cheers.
