### ISSUE TITLE
Editor tab setting dose not work

### ISSUE THREAD

**Issue by mengzyou** [LightTable/LightTable#1799]
I set below in the *user.behaviors*:   
> [:editor :lt.objs.editor/tab-settings false 2 2]   
   
But it dose not work for me, in editing, the tab is still 4 spaces.
And when I use "Smart indent line(s)", it use 4 spaces as indent length.

The version is __0.7.2__.

**Comment by joshuafcole** [comment]
Hey mengzyou, what is the syntax of the file you're editing? LT has overrides for various behaviors, including tab-settings, on a language-by-language basis. LT uses the most specific behavior possible in the event of a collision. E.g. if you're having an issue with html, try:

```
[:editor.html :lt.objs.editor/tab-settings false 2 2] 
```

Cheers

**Comment by BenjaminVanRyseghem** [comment]
@mengzyou any news here?

**Comment by mengzyou** [comment]
@BenjaminVanRyseghem Yes, it works when use `[:editor.html :lt.objs.editor/tab-settings false 2 2]`.
