### ISSUE TITLE
Multiple lighttable instances run on ./deploy/light

### ISSUE THREAD

**Issue by justintaft** [LightTable/LightTable#1800]
The "open -a LightTable" in deploy/light is causing the issue i think...

https://github.com/LightTable/LightTable/blame/b50bacadbe969bf13b07b7795a3e06f5da459284/platform/mac/light#L35

I have a development copy and a stable copy installed on osx 10.8

Running ./deploy/light in my development folder then both copies are launched. (I have the LT_HOME env. var set too).

If I run /home/justin/programming/LightTableMain/deploy/LightTable.app/Contents/MacOS/node-webkit
then only my development instance runs.

**Comment by cldwalker** [comment]
I've seen this behavior as well on the atom-shell branch and it is fixed on that branch. For now, I'd recommend commenting out that line locally. I'll close this once atom-shell lands on master

**Comment by BenjaminVanRyseghem** [comment]
I think it's done now :smile:

@cldwalker I think you can close this one ;)
