### ISSUE TITLE
shortcut for duplicate line don't work in html files

### ISSUE THREAD

**Issue by dcz-switcher** [LightTable/LightTable#1805]
In my user.keymap, I set this line to shortcut "duplicate line" :
[:editor "shift-pmeta-d" :editor.sublime.duplicateLine]

it works great for JS files, but not in html files ?!?
instead the shortcup select all lines

note : I use macbook pro laptop (french keyboard)

**Comment by cldwalker** [comment]
It's working fine for me in .html files. Could you drop in your user.keymaps, user.behaviors and list of plugins you've installed? Perhaps this is specific to french keyboards. Can you change your keyboard to U.S. and see if the issue persists?

**Comment by dcz-switcher** [comment]
thanks to reply so fast, here is my settings
keymap
'[
    [:editor "alt-shift-w" :editor.watch.unwatch]
    [:editor "alt-w" :editor.watch.watch-selection]
 ;; emmet est appelé par pmeta-e et ne bloque plus le tab natif de LT
    [:editor.keys.normal.emmet "-tab" :editor.codemirror.command "emmet.expand_abbreviation_with_tab"]

 ;; comment - uncomment selection
    [:editor "pmeta-shift-/" :toggle-comment-selection]
 ;; duplicate line
    [:editor "shift-pmeta-d" :editor.sublime.duplicateLine]
 ;; move current line up or down
    [:editor "ctrl-pmeta-up" :editor.sublime.swapLineUp]
    [:editor "ctrl-pmeta-down" :editor.sublime.swapLineDown]
]'

behaviors
'[
    [:app :lt.objs.style/set-skin "dark"]

    [:editor :lt.objs.editor/no-wrap]
    [:editor :lt.objs.style/set-theme "default"]

    [:editor.clojure :lt.objs.langs.clj/print-length 1000]

    [:editor :lt.objs.style/set-theme "monokai"]

    [:editor :lt.objs.style/font-settings "Menlo"  11  1.4]
    ;; auto close parenthesis (only...)
    [:app :lt.objs.settings/pair-keymap-diffs]

    [:editor :lt.objs.editor/tab-settings  false  4  4]
]'

plugins
I just show in folder /Library/Application support/Light Table/plugins/
Emmet-master
HTML_Live
Javascript
Palette
TernJS

I'll try after uninstall HTML_Live then change my keyboard to US and edit this post ...

**Comment by cldwalker** [comment]
Looking through old issues and found this. Turns out the issue was Emmet was overriding the keybinding - https://github.com/LightTable/Emmet/blob/a51837768b5bcd3785351f52e72cb45a83451293/emmet.keymap#L4
