### ISSUE TITLE
autocomplete pair keybindings for international keyboards

### ISSUE THREAD

**Issue by dcz-switcher** [LightTable/LightTable#1807]
I know the autocomplete option was disabled by default to prevent issues but, if light table really want to be the future IDE, I don't think this function can't work

I use many others IDE like Brackets, Atom, Sublime ... and all of them autocomplete parenthesis, brackets on my laptop mac with french keyboard so it's possible.

Actually, if I activate this option, only parenthesis are self closed
[:app :lt.objs.settings/pair-keymap-diffs]

I really think LT can be the first class IDE and if my skills allow me to do this modification myself, be sure I'll try.

thanks for your awesome work

**Comment by cldwalker** [comment]
Having pair keybindings work on international keyboards (including french) would be great. Pull requests would be appreciated since none of the core team uses (or is too familiar with) international keyboards.

**Comment by cldwalker** [comment]
Are you using a French Azerty keyboard? If so, can you confirm if [this solution](https://groups.google.com/d/msg/light-table-discussion/xv81Mn7Z7j4/1KJQYmEy_lwJ) works for you in your user.keymap:

```cljs
 [:editor "(" (:editor.open-pair "(")]
 [:editor ")" (:editor.close-pair ")")]
 [:editor "ctrl-alt-4" (:editor.open-pair "{")]
 [:editor "ctrl-alt-5" (:editor.open-pair "[")]
 [:editor "ctrl-alt-=" (:editor.close-pair "}")]
 [:editor "ctrl-alt-[" (:editor.close-pair "]")]
```

**Comment by noaxtogrind** [comment]
That solution worked fined in my qwerty Portuguese (PT) keyboard. The keybindings I added to my user.keymap were this:

 [:editor "(" (:editor.open-pair "(")]
 [:editor ")" (:editor.close-pair ")")]
 [:editor "ctrl-alt-7" (:editor.open-pair "{")]
 [:editor "ctrl-alt-8" (:editor.open-pair "[")]
 [:editor "ctrl-alt-0" (:editor.close-pair "}")]
 [:editor "ctrl-alt-9" (:editor.close-pair "]")]

**Comment by noaxtogrind** [comment]
Beautiful editor, by the way! Thanks for the great work!

**Comment by dcz-switcher** [comment]
Great day for me, I finally be able to have auto close everythings : (, [, {

here is how I do it on MacBook Pro with French keyboard
//user.keymap
[:editor "(" (:editor.open-pair "(")]
[:editor ")" (:editor.close-pair ")")]
[:editor "alt-[" (:editor.open-pair "{")]
[:editor "alt-]" (:editor.close-pair "}")]
[:editor "alt-shift-[" (:editor.open-pair "[")]
[:editor "alt-shift-]" (:editor.close-pair "]")]

I disabled "pair-keymap-diffs" too

**Comment by kenny-evitt** [comment]
Another solution that someone confirmed worked for them with a French keyboard from [this comment](https://github.com/LightTable/LightTable/issues/2003#issuecomment-166308023):

> Hi everyone. This problem can be solved by using codemirror addon, that allready exist in lighttable package, just add this to user.behaviors to apply this addon:

>      ;; Normal brackets autoclose
>      [:app :lt.objs.editor/load-addon ["edit/closebrackets.js"]]
>      [:editor :lt.objs.editor/set-codemirror-flags {:autoCloseBrackets true}]

> And you may disable lighttable autoclose plugin (if it enabled):

>      [:editor :-lt.objs.settings/pair-keymap-diffs]

> This addon also close single quotes(') and add extra new line when you press return inside empty breackets.
