### ISSUE TITLE
add command : toggle word wrap

### ISSUE THREAD

**Issue by dcz-switcher** [LightTable/LightTable#1810]
I use LT in production for web dev (front end) and it's great, I think there is not much to add to have the next editor for devs

A feature which may be cool is the ability to toggle word wrap from the command panel

**Comment by joshuafcole** [comment]
This seems reasonable to me. I'll tag it as a beginner issue so anyone who wants to contribute can tackle it. It should be as simple as dynamically adding/removing the `:lt.objs.editor/wrap` behavior from the active editor.

**Comment by mjgpy3** [comment]
Unless I'm misunderstanding something, it looks like this already exists here:
https://github.com/LightTable/LightTable/blob/master/src/lt/objs/editor/pool.cljs#L579-L585

**Comment by joshuafcole** [comment]
So it does! Thanks for pointing that out mjgpy3, I'll mark this issue closed.

**Comment by snufkon** [comment]
I didn't know `:editor.force.wrap` command to read this issue. After I read this issue, I tried to use this command and I find following unexpected behavior.

- When I open command pane, line wrapping state change to "Wrapping on".

I think this is a bug and if so, I will send a pull request.
