### ISSUE TITLE
LightTable does not seem to remember fullscreen

### ISSUE THREAD

**Issue by mydoghasworms** [LightTable/LightTable#1814]
When starting LightTable, the window is always restored. It does not remember whether it was previously maximized of full screen.
Not sure if this is a bug or feature request.

**Comment by cldwalker** [comment]
I noticed this bug and fixed it in the atom-shell branch with b4af0dcbf1b184c2dc49684359c97a97c33b7f7b. I'll mark this as fixed-on-master since that branch will go out with the next release.

**Comment by cldwalker** [comment]
Fixed and available with 0.8.0-alpha - https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss
