### ISSUE TITLE
Closing Tab via middle-click on XServer pastes clipboard

### ISSUE THREAD

**Issue by peacememories** [LightTable/LightTable#1816]
On the X windowing system, the middle mouse button defaults to a paste function for the X clipboard. If i close a tab in LightTable with the middle mouse button, the tab gets closed correctly but then the contents of my clipboard get inserted into the next tab.

**Comment by kolya-ay** [comment]
Confirm [the same](https://github.com/LightTable/LightTable/issues/1554#issuecomment-64996304) on my Linux box. In browser codemirror instance seem not have this issue. Something with stopPropagation chain?

**Comment by cldwalker** [comment]
Confirmed this is an issue on latest LT with ubuntu. Fix coming
