### ISSUE TITLE
Splash Screen displays incorrectly

### ISSUE THREAD

**Issue by MrDetonia** [LightTable/LightTable#1817]
On application startup, the LightTable splash image appears in the upper left corner of the window. The rest of the frame is white and empty.

Image:
![lighttable startup](https://cloud.githubusercontent.com/assets/9915250/5720609/68337860-9b1e-11e4-8e19-d787277ac048.png)

LightTable Version: 0.72

Operating System: Debian Linux
Output of uname -a: 'Linux Zac-Linux-PC 3.2.0-4-686-pae #1 SMP Debian 3.2.65-1 i686 GNU/Linux'

Desktop Environment: XFCE
GPU: Radeon HD 6570 (using open Radeon drivers)

**Comment by MrDetonia** [comment]
Should note: I have other problems with this GPU + driver, so this may be the cause of the problem.
I'm switching to an NVidea card in a few weeks, so I'll see if the problem is the same with that setup.

**Comment by Trapets** [comment]
Also in Win7.

**Comment by wzhishen** [comment]
Win7 seems working fine for me.

LightTable Version: 0.72
OS: Windows 7 Enterprise (Build 7601: Service Pack 1)

**Comment by kenny-evitt** [comment]
@MrDetonia @Trapets Try building the latest source version and comment whether you can reproduce this.

**Comment by cldwalker** [comment]
Closing as we haven't heard back and this hasn't been an issue with the latest LT. Can reopen if it is and reproducible steps are given
