### ISSUE TITLE
Unable to map pmeta-up / pmeta-down

### ISSUE THREAD

**Issue by TeffenEllis** [LightTable/LightTable#1818]
Hello,

I'm migrating from Sublime Text and want to map `:editor.sublime.swapLineUp` and `:editor.sublime.swapLineDown` to `command+up` and `command+down`.

The following does not work:

```clojure
 [:editor "pmeta-up" :editor.sublime.swapLineUp]
 [:editor "pmeta-down" :editor.sublime.swapLineDown]
```
https://gist.github.com/TeffenEllis/6288990ba6cf7c23e3ca#file-user-keymap-L40-L41

I'm using OSX 10.10.1 and LightTable 0.7.2.

Thank you.

**Comment by cldwalker** [comment]
Those work for me on osx 10.9.4. Does "pmeta-something-else" or "shift-up" work? Does "cmd-up" or trying the above on a new file work? You shouldn't need to do the last question in order for it to work but perhaps this is a strange edge case. If none of those work, check the keymaps of your plugins for potential conflicts e.g. [vim's keymap](https://github.com/LightTable/Vim/blob/master/vim.keymap)

**Comment by TeffenEllis** [comment]
I'm able to map "pmeta" and an letter to activate the command. Strangely, I'm able to make the mapping with "alt-down" and "alt-up". The limitation seems to be limited to the command key and an arrow..

I've reinstalled LightTable with the default plugins and the issue persists.

Thank you for your support. 

![screen shot 2015-01-13 at 8 12 30 pm](https://cloud.githubusercontent.com/assets/592134/5733952/887ee11c-9b60-11e4-88d7-70f27b8a0962.png)

**Comment by joshuafcole** [comment]
Is it possible that you have apps running with global shortcuts such as
moom or spectacle that might be stealing the keypress? Any global hotkey
will get snatched before LT sees it.

On Tue, Jan 13, 2015 at 8:13 PM, Teffen Ellis (Eric) <
notifications@github.com> wrote:

> I'm able to map "pmeta" and an letter to activate the command. Strangely,
> I'm able to make the mapping with "alt-down" and "alt-up". The limitation
> seems to be limited to the command key and an arrow..
>
> I've reinstalled LightTable with the default plugins and the issue
> persists.
>
> Thank you for your support.
>
> [image: screen shot 2015-01-13 at 8 12 30 pm]
> <https://cloud.githubusercontent.com/assets/592134/5733952/887ee11c-9b60-11e4-88d7-70f27b8a0962.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LightTable/LightTable/issues/1818#issuecomment-69866764>
> .
>



-- 
Screw the environment. Please print this email immediately. And then burn
it.

**Comment by cldwalker** [comment]
I've tried the keybindings on a fresh install on the same osx version and am not seeing a mapping issue. Like Josh mentioned, there is most likely some global keybindings that are interfering. Closing soon unless there is more information to make this reproducible.

**Comment by TeffenEllis** [comment]
I apologize for any confusion. I had Karabiner remapping command+arrow to alt+arrow.

Thank you for your assistance.
