### ISSUE TITLE
Vim Normal mode cursor not shown when broken html tags are highlighted

### ISSUE THREAD

**Issue by RatanRSur** [LightTable/LightTable#1821]
The cursor is underneath the pink highlight right now but it can't be seen.

![screen shot 2015-01-15 at 4 16 06 pm](https://cloud.githubusercontent.com/assets/4733314/5766745/e034b284-9cd1-11e4-9164-1fcfce568c8d.png)

**Comment by cldwalker** [comment]
Looking through old issues and found this. There isn't enough info to reproduce this e.g. what theme and os is used. Will close in a few days unless this is tried on latest LT and there are reproducible steps

**Comment by RatanRSur** [comment]
I don't use LT anymore so no worries if you close it.

**Comment by cldwalker** [comment]
Ok. Can't fix without reproducible steps
