### ISSUE TITLE
Installing lighttable-atom-shell gives Fatal error: certificate not trusted

### ISSUE THREAD

**Issue by rogergl** [LightTable/LightTable#1822]
Just downloaded the latest  zip from github. Now I get the following error message when I run build.sh:
npm WARN package.json download-atom-shell@0.1.0 No description
npm WARN package.json download-atom-shell@0.1.0 No repository field.
npm WARN package.json download-atom-shell@0.1.0 No README data
Running "download-atom-shell" task
Fatal error: certificate not trusted
I'm on MAc OS X 10.10

**Comment by cldwalker** [comment]
I can't reproduce this, especially since build.sh has changed a fair amount. Can you use the latest atom-shell branch and provide the exact console output again?

**Comment by rogergl** [comment]
It works now. BTW: the problem may have been caused by io.js. But I’m not sure if i removed io.js before or after I tried to recompile LightTable.

**Comment by cldwalker** [comment]
Cool
