### ISSUE TITLE
Java interop 'new' issue in instarepl

### ISSUE THREAD

**Issue by naikus** [LightTable/LightTable#1823]
Java's new keyword or its equivalent reader syntax the '.' operator is not working.  Whereas the same is working in the on clojure's repl (lein repl). I'm using clojure 1.6.0 for lein repl
Light Table version
0.7.2
Binary version
0.8.4
Clojure Plugin 0.1.1 (Kodowa)

Below is the screenshot

![image](https://cloud.githubusercontent.com/assets/422158/5791302/1d6e6222-9ef2-11e4-835a-74e440e65a4c.png)

![image](https://cloud.githubusercontent.com/assets/422158/5791309/c68645e6-9ef2-11e4-9d0d-fbd47c7bf858.png)

**Comment by sashton** [comment]
Confirmed defect on atom-shell branch. 

From my experimentation, it appears to be an issue when destructuring in the function arguments, but it works fine in a let destructuring:
```clojure
(defn bad-destructuring 
  [{:keys [date] :or {date (java.util.Date.)}}]
  (println "bad:" date))


(defn good-destructuring 
  [input]
  (let [{:keys [date] :or {date (java.util.Date.)}} input]
    (println "good:" date)))

```

**Comment by kenny-evitt** [comment]
@sashton Thanks for isolating this.

I was also able to reproduce this in *atom-shell* on Windows 7.

**Comment by sashton** [comment]
I think I've tracked it down to lein-light-nrepl.

With the following form evaluated in Instarepl:
```
(defn bad-destructuring   [{:keys [date] :or {date (new java.util.Date)}}]  
   (println "bad:" date))
```
The `lighttable.nrepl.sonar/defn++`  macro generates the following:
```
(clojure.core/defn bad-destructuring [{:keys [date], :or {date (new java.util.Date)}}]
  (clojure.core/swap! lighttable.nrepl.sonar/*caps* clojure.core/merge (lighttable.nrepl.sonar/restructure (quote [date date new java.util.Date]) [date date new java.util.Date])) 
  nil 
  (println bad: date))
```
I'm guessing the call to `(restructure '[date date new java.util.Date] [date date new java.util.Date])` is the source of the problem. It doesn't look like it handles destructuring correctly.

I'm not sure what the fix is yet. I'm still trying to understand what `*caps*` is and what `defn++` is doing.

**Comment by kenny-evitt** [comment]
@sashton Thanks for looking into this.

**Comment by cldwalker** [comment]
This issue has moved to https://github.com/LightTable/ClojureInstarepl/issues/13 as the instarepl is now its own plugin
