### ISSUE TITLE
OSX Yosemite: File > Open Folder: Button in finder browser says "Upload"

### ISSUE THREAD

**Issue by JohnPostlethwait** [LightTable/LightTable#1825]
I realize this relates to "workspaces" but it doesn't make a lot of contextual (contextual to the menu action) sense:
![screen shot 2015-01-20 at 11 24 43 pm](https://cloud.githubusercontent.com/assets/39127/5832523/8ab7e712-a0fb-11e4-8b54-0dfd359fc0dd.png)

And then you get:
![screen shot 2015-01-20 at 9 35 12 pm](https://cloud.githubusercontent.com/assets/39127/5831703/75251546-a0ec-11e4-829f-cfa6920fd1bc.png)

And after you select something, it seemingly adds it to your workspace. That should be a separate and distinct action than opening a folder. There should be a menu-item for opening in this current workspace, and one for opening in a new workspace.

Even if this is, under the hood, technically an upload, it still sounds/seems weird.

**Comment by cldwalker** [comment]
Marking as fixed on master since once we merge atom-shell this button says "Open"

**Comment by cldwalker** [comment]
Fixed and available with 0.8.0-alpha - https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss
