### ISSUE TITLE
OSX Yosemite: "Open folder" opens workspace tree before dialog instead of after dialog

### ISSUE THREAD

**Issue by JohnPostlethwait** [LightTable/LightTable#1827]
* Have a workspace open in LightTable that is a single directory
* Quit LightTable
* Open LightTable again from the Applications folder - you will see the Welcome screen
* command-w to close the welcome screen, LightTable is now totally empty
* Go to File > Open folder

When I do this, it auto-opens my last folder I had into my current workspace, for no apparent reason, I have not selected a folder in Finder yet, nor have I clicked "Upload"

It should either auto-open my last workspace/folder right when I launch the application, or it should not auto-open anything, especially after it has been sitting there empty for a while.

Nothing should open in LightTable when I am in the Open folder Finder menu, that should only happen after I make a selection and click Upload.

**Comment by cldwalker** [comment]
Thanks for the reproducible steps. This boils down to if we prefer opening the workspace tree before or after selecting a folder. I don't have a strong opinion. @LightTable/committers Thoughts on if this behavior should be changed?

**Comment by cldwalker** [comment]
Closing as this has been open awhile, no other users have reported this preference and would require a nontrivial amount of shuffling code around
