### ISSUE TITLE
Redefining most clojure.core fns e.g. defn or defmacro doesn't work in Instarepl

### ISSUE THREAD

**Issue by matevarga** [LightTable/LightTable#1828]
This ```(defmacro defn [name & body] `(clojure.core/defn ~name ~@body))```
works fine in the Clojure repl, but results in ```clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Can't create defs outside of current ns, compiling:(null:6:1)``` in LightTable Instarepl.

**Comment by cldwalker** [comment]
This seems to be an issue with redefining most clojure.core fns. If I point the defmacro to a non-reserved name, I don't see the issue e.g. `(defmacro defn [name & body] `(clojure.core/defn ~name ~@body))`. While I'm open to a fix for this, I wouldn't encourage users to do this

**Comment by matevarga** [comment]
Sure, this is not something that's appropriate in most situations and I am not sure that it's really crucial to fix. I was essentially trying to wrap built in-functions to do some tricks with the REPL -- I just wanted to leave some trace here in case somebody runs into it.

**Comment by cldwalker** [comment]
This issue has moved to https://github.com/LightTable/ClojureInstarepl/issues/6 as the instarepl is now its own plugin
