### ISSUE TITLE
OSX Yosemite: shell script doesn't work on directories

### ISSUE THREAD

**Issue by JohnPostlethwait** [LightTable/LightTable#1830]
This happens regardless of if it is a single file, or a directory.
```
01:04:35AM (Johns-MacBook-Air) ~/Documents/workspace
» light lighthouse/README.rst
01:04:47AM (Johns-MacBook-Air) ~/Documents/workspace
» 2015-01-23 01:04:47.889 node-webkit[15056:1767624] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
[15056:0123/010447:ERROR:breakpad_mac.mm(234)] Breakpad initializaiton failed
```

With directories, it opens the Light Table app, but never opens the directory, with files, the file is seemingly opened fine, but still has those messages.

**Comment by cldwalker** [comment]
Opening a directory on osx 10.9 correctly adds the directory to my workspace. What do you see in your workspace sidebar? Have you tried opening different directories? The node-webkit error messages are irrelevant, especially since we'll be switching to atom-shell soon. Can't reproduce this as described.

**Comment by JohnPostlethwait** [comment]
It happens with any directory:

```
01:06:52AM (Johns-MacBook-Air) ~/Documents/workspace
» light .
```
![screen shot 2015-01-23 at 10 59 51 am](https://cloud.githubusercontent.com/assets/39127/5880659/12cf9f24-a2ef-11e4-8839-14b0c2035f51.png)

Is there any way I can get a log/trace for you?

**Comment by JohnPostlethwait** [comment]
Another detail: I already have Ligth Table opened, this seems to open a whole new (blank) window.

**Comment by ibdknox** [comment]
If you open the workspace tree is your folder in it?

**Comment by JohnPostlethwait** [comment]
HA! Yes... I didn't notice it was closed...

I DO think it should open the workspace when opening a dir?

**Comment by ibdknox** [comment]
Yep, but that's a different issue :)

**Comment by JohnPostlethwait** [comment]
Sure, but it is the heart of this ticket. Is thee another ticket open already to make that happen?

**Comment by cldwalker** [comment]
Agreed we should open workspace tree and added on the atom-shell branch. This will go out on the next release
