### ISSUE TITLE
build.sh shows syntax error on OS X

### ISSUE THREAD

**Issue by seancorfield** [LightTable/LightTable#1838]
This code in `build.sh` fails on OS X (Yosemite):

    if [ "$(expr substr $(uname -s) 1 9)" == "CYGWIN_NT" ]; then                    
      sed -i 's/:source-map/;;:source-map/' project.clj                             
    fi                                                                              

This yield: `expr: syntax error` although the script continues to run just fine.

**Comment by cldwalker** [comment]
Didn't have an effect but thanks for noticing
