### ISSUE TITLE
The Light Table mades same connection when i evaluate the code on Instarepl.

### ISSUE THREAD

**Issue by hjbaek** [LightTable/LightTable#1839]
I builded latest version of Light table to run and to explore and i got this.

<img src="http://dl.dropbox.com/u/11372945/Screen%20Shot%202015-01-29%20at%202.54.45%20PM.png"/>

I don't know why.. Plz help me.

* Environment
ProductName:	Mac OS X
ProductVersion:	10.10.1
BuildVersion:	14B23

* Lein Version and Java Version
Leiningen 2.5.0 on Java 1.6.0_65 Java HotSpot(TM) 64-Bit Server VM

* The following thing is What i did.
$ git clone https://github.com/LightTable/LightTable.git
$ cd LightTable
$ sh osx_deps.sh
$ export LT_HOME=$(pwd)/deploy
$ ./deploy/light

* I got the below things.

2015-01-29 14:49:04.400 node-webkit[9720:312538] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
[9720:0129/144904:ERROR:breakpad_mac.mm(234)] Breakpad initializaiton failed
[MacBook-Air] LightTable $ 2015-01-29 14:49:04.688 node-webkit Helper[9724:312623] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
2015-01-29 14:49:04.968 node-webkit Helper[9725:312652] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650

How to solve this problem. 

Thank you for read this.

**Comment by cldwalker** [comment]
Hi. Does this behavior also happen when you use the latest binary from lighttable.com? That might indicate if this is a build issue or a connection issue. If you're getting errors from the latest binary, run the command `Toggle console` and please paste  any errors you see. Without more information, this is not yet reproducible.

**Comment by hjbaek** [comment]
Okay, i'll try again.

**Comment by cldwalker** [comment]
Closing as I haven't heard back on the above questions. Feel free to provide reproducible steps and we can reopen
