### ISSUE TITLE
Undo history wiped on split-view edit

### ISSUE THREAD

**Issue by ohAitch** [LightTable/LightTable#1841]
- Codemirror behavior: unified undo history between two linked views
- LT behavior: editing a split view clobbers undo history on the other split side

@joshuafcole

**Comment by cldwalker** [comment]
If you want shared history between tabs, add to your user.behaviors:

  [:document :lt.objs.document/set-linked-doc-options {:shared-history true}]

When history is not shared, I only see undo history get clobbered if the linked tab edits in a line adjacent to the recent edits in the first tab, which I believe is CM's behavior. If you're seeing undo getting clobbered for cases that only happen in LT, please provide the CM script you're using to verify this. Keep in mind to use the same CM version when verifying the behaviorial difference.

**Comment by cldwalker** [comment]
Closing as I haven't heard back. Feel free to provide reproducible steps and we can dig in more

**Comment by ohAitch** [comment]
Sorry, I did turn on shared history and that is providing expected
behavior, thank you.
