### ISSUE TITLE
Can't run on CentOS 6.5

### ISSUE THREAD

**Issue by ionuthulub** [LightTable/LightTable#1842]
LightHouse won't run:

/lib64/libc.so.6: version `GLIBC_2.15' not found
/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found

**Comment by bitmonk** [comment]
I have a similar problem, even when I try a developer build it seems to be downloading ELF binaries.  The instructions suggest this has to do with avoiding building node-webkit from source, but it would be nice if LT had instructions for performing a full build.

Obviously, i could run a newer Linux, but this workstation matches our production environment.  I've really enjoyed using LT on Mac and would love to on this machine.

**Comment by kenny-evitt** [comment]
@bitmonk there may never be published instructions for a full build that includes node-webkit. We're still working on migrating to Atom (Electron). Try building from that branch (*atom-shell*). You will probably need to manually merge PR #1892 and #1899 to account for Atom being renamed to Electron.

@ionuthulub please feel free to re-open this if you're still having trouble running Light Table. If you are still having this issue, please confirm whether you tried installing the versions of *libc* that are supposedly missing.

**Comment by bitmonk** [comment]
!kenny-evitt FWIW, I think we're both trying to build the source, so while I'm happy to explore further experimental builds, the versions of libc that are supposedly missing are not available.  A source build shouldn't depend on a specific version of libc.

**Comment by kenny-evitt** [comment]
Atom/Electron requires the specific version of libc. And it just doesn't seem to work on CentOS versions prior to 7; one issue among several:

 - [atom-shell not available on CentOS? · Issue #1172 · atom/electron](https://github.com/atom/electron/issues/1172)

There seem to be lots of people struggling to build it on CentOS 6.*x*, to no obvious avail.

I don't think I, or anyone else, will be able to help you. Light Table is nearly moribund as-is. Migrating from node-webkit to Atom was a significant project aimed to address major issues for a large number of users. Migrating to another alternative is just not realistic anytime soon – unless you are willing to spearhead that effort yourself.

**Comment by bitmonk** [comment]
Thanks for the info.

**Comment by blackSea4477** [comment]
Just Copy 
- libstdc++.so.6  
- ld-linux-x86-64.so.0
- libc.so.6
- libgtk-x11-2.0.so.0 
under the path .....src/node_modules/electron/dist . You can get this from Centos 7 . 
Then Download https://jlison.github.io/bin/centos6/soichih/mirror/gcc-4.7.2.tar.gz and extarct it to some folder and update LD_LIBRARY_PATH 

glibpath=/opt/glib/  (path where you have extracted glib )

export LD_LIBRARY_PATH=$glibpath/glib-2.49.4-kgesagxmtbemim2denf65on4iixy3miy/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/libffi-3.2.1-wk2luzhfdpbievnqqtu24pi774esyqye/lib64:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/pcre-8.39-itdbuzevbtzqeqrvna47wstwczud67wx/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/gettext-0.19.8.1-aoweyaoufujdlobl7dphb2gdrhuhikil/lib:$LD_LIBRARY_PATH


I am able t o run electron on my centos 6.5 and nothing breaks !
