### ISSUE TITLE
left code folding indicator

### ISSUE THREAD

**Issue by thewhitetulip** [LightTable/LightTable#1847]
the ctrl-= folds the code, but apart from the double sided arrow at the end of a function it doesn't show any indicator at the left border of the editor, it can show a small + icon, additionally the left border can hold a debugging point as a reminder not for doing program based debugging but to while checking the code manually

also a default implementation of closing all kinds of brackets like {} () [] when you type just the left bracket

**Comment by cldwalker** [comment]
LT was missing some fold css and this has been fixed on master with #1772. 

See [this FAQ](https://github.com/LightTable/LightTable/wiki/FAQ#how-do-i-add-pair-keybindings) for closing pair keybindings

**Comment by Mouvedia** [comment]
@cldwalker I added ` [:editor :lt.objs.editor/show-fold-gutter]` to my user behaviors. It doesn't show a + next to foldable code. How do you enable it?

**Comment by cldwalker** [comment]
Fixed and available with 0.8.0-alpha - https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss
