### ISSUE TITLE
Shortcut conflict

### ISSUE THREAD

**Issue by kxxoling** [LightTable/LightTable#1851]
Default shortcuts for control pane is `ctrl+space` and `cmd+space`(on Mac) which are both used for IME switch system wide. Could this be changed or at least add a menu for control pane?

**Comment by cldwalker** [comment]
If you'd like to map the command bar to a different key in your user.keymap:

```cljs
;; alt-space can be whatever keybinding
[:app "alt-space" :show-commandbar-transient]
```

The command bar is available in the menu under `View > Commands`

**Comment by kxxoling** [comment]
@cldwalker  Thanks, I got it!
