### ISSUE TITLE
Zooming in or out sometimes results in "Uncaught Error: Unable to convert 'args' passed to CallObjectMethodSync"

### ISSUE THREAD

**Issue by matthiaslange** [LightTable/LightTable#1852]
Full error:
```
Uncaught Error: Unable to convert 'args' passed to CallObjectMethodSync
    window_bindings.js [199]	anonymous
    bootstrap.js [21391]	anonymous
    bootstrap.js [6188]	b
    bootstrap.js [6234]	a
    bootstrap.js [21134]	a
    bootstrap.js [21138]	b
    bootstrap.js [23303]	lt.objs.keyboard.trigger
    bootstrap.js [23331]	lt.objs.keyboard.capture
    bootstrap.js [23403]	anonymous
    bootstrap.js [23404]	Mousetrap.handleKey
    keyevents.js [562]	_handleKeyEvent
```
This seems to happen whenever I change direction from zooming in to zooming out or vice versa.

I mean if i zoom out a couple of times, I'll get the error only for the first time, and if i then switch to zooming in and do it a couple of times, the error also only comes for the first time.

Both zooming in and zooming out work fine, though. Even when the error comes.

**Comment by cldwalker** [comment]
Thanks for the report. This is an error specific to node-webkit. We don't have this issue on the atom-shell branch. Marking as fixed since we'll be merging and using atom-shell on the next release

**Comment by rundis** [comment]
Works on master
