### ISSUE TITLE
html.erb and gemfile are not recognized

### ISSUE THREAD

**Issue by dmbennett** [LightTable/LightTable#1853]
Hello!

Just wanted to let you know that LT 0.7.2 is not recognizing html.erb files as HTML and Gemfile as Ruby.

**Comment by cldwalker** [comment]
Hi!
LightTable doesn't come with Ruby support beyond what CodeMirror does e.g. syntax highlight .rb files, etc. We leave this up to language plugins. To search for ruby plugins open up your plugin manager. I know of at least [Ruby Instarepl](https://github.com/existentialmutt/lt-ruby). If ruby plugins don't provide it, you can add a file-type [with a one-liner to your user.behaviors](https://github.com/LightTable/LightTable/wiki/FAQ#how-do-i-define-a-custom-file-type).
