### ISSUE TITLE
Line number

### ISSUE THREAD

**Issue by JasterTDC** [LightTable/LightTable#1854]
How can I see line number, in the editor. I tried all menu options, and I didn't find it. Thanks for the help, and sorry for the incovenience.

**Comment by dmbennett** [comment]
edit the default behaviors and change the line that contains "hide-line-numbers" to "line-numbers"

**Comment by ibdknox** [comment]
You don't want to modify default behaviors as that will get overwritten.
From the command pane type "user behaviors" and add this line to the file:

```clojure
 [:editor :lt.objs.editor/line-numbers]
```

**Comment by cldwalker** [comment]
Closing as this has been answered
