### ISSUE TITLE
EOL conversion CR LF CRLF

### ISSUE THREAD

**Issue by blaggacao** [LightTable/LightTable#1856]
I've searched goolge up and down, I've tried to figure out user behaviours, looked through all `Editor:` commands to no avail.

I want to transform all my files to LF line ending. I want this reasonably because I'm on windows, but rsync to a remote linux, which has a way faster internet, so playing around with large files (docker images) is not hart-attack prone due to grab-a-coffe-meanwhile-caused overconsumption of coffein.

I probably never will open a file with something like notepad again. So why actually have CRLF enabled.
BTW pushing everything trough a git repo (with .gitattributes setting to auto-conversion) isn't an option, as this terribly pollutes history during the dev-debug cycle.

Did I forget any aspects?

**Comment by blaggacao** [comment]
I've just found the line in `default.behaviours`:

    [:editor.file-backed :lt.objs.editor.file/preserve-line-endings]

to undo in `user.behaviours`

    [:editor.file-backed :-lt.objs.editor.file/preserve-line-endings]

This is kind of hacky and it's one-way: You need to open the file, and without any changes hit `CTRL + S` to remove the CR of CRLF

**Comment by sashton** [comment]
Do you have posix tools installed? If so you can use dos2unix to do a one-time line-ending swap:
```
find -name *.py -exec dos2unix {} \;
```

**Comment by kenny-evitt** [comment]
@blaggacao I'm not sure what the issue is exactly. Are you asking for a feature in Light Table to convert all of the line endings of (some) files in a directory (or workspace)?

**Comment by kenny-evitt** [comment]
Some notes:

 - LT will respect the existing line endings in files; I'm unsure how it handles files with mixed EOL characters tho
 - The LT search/find and replace can't (currently) be used to replace EOL characters but this would be ideal.

**Comment by blaggacao** [comment]
closing, because i cannot provide follow up any more.
