### ISSUE TITLE
^M - Bug

### ISSUE THREAD

**Issue by blaggacao** [LightTable/LightTable#1857]
#### On Windows:
in lighttable everything looks normal.
#### On Linux:
After a rync (trasnparent operation) to the linux server, we get:
```
$ vi file
[...]
            fontconfig^M
```
The `^M` is the pad part, causing annoying errors every so.

#### default.behaviours (for confenience):
```
 [:editor.file-backed :lt.objs.opener/save-as-rename!]
 [:editor.file-backed :lt.objs.editor.file/remove-trailing-whitespace]
 [:editor.file-backed :lt.objs.editor.file/dirty-on-change]
 [:editor.file-backed :lt.objs.editor.file/file-save]
 [:editor.file-backed :lt.objs.opener/save-as]
 [:editor.file-backed :lt.objs.editor.file/preserve-line-endings]
 [:editor.file-backed :lt.objs.editor.file/last-char-newline]
```
#### user.behaviour:
```
 [:editor.file-backed :-lt.objs.editor.file/preserve-line-endings]
```

**Comment by sueswe** [comment]
We'va got the same problems: working under windows, but scripting for UN*X. Would be nice, when there would be at least a info about file type and style.

**Comment by blaggacao** [comment]
closing, because i cannot provide follow up any more.
