### ISSUE TITLE
Ability to temporarily disable plugins

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [LightTable/LightTable#1861]
When writing #1860, I had to uninstall plugins I'd installed to ensure that the problem didn't lie within one of them. Ideally, a user would be able to *disable* a plugin, to unload it, but still have it load as normal upon the next launch.

**Comment by cldwalker** [comment]
This could be useful though if I disabled a plugin I'd find it surprising to have it re-enabled on a subsequent launch, without explicitly re-enabling it. We don't have the bandwidth to dev on this but you should be able to create this functionality as a plugin. Will leave this open for a while to see if other users would like this enhancement

**Comment by cldwalker** [comment]
Closing as it has been awhile and others haven't shown interest in this. Feel free to add to the [wishlist](https://github.com/LightTable/LightTable/wiki/Feature-wishlist). Note that plugins live in [this directory](http://docs.lighttable.com/#plugins-directory) and can be moved out between application starts to temporarily try LightTable with a different set of plugins
