### ISSUE TITLE
Allows you to open network drives under KDE, but they don't actually work.

### ISSUE THREAD

**Issue by sentientnebula** [LightTable/LightTable#1862]
I have some server folders mapped in KDE's Dolphin file manager (via sftp) to operate just like local drives.  As a backup route for non-kde aware programs, I also map these drives via gvfs.  Atom, Brackets, and Sublime Text all opt for the gvfs, and show me a gnome/gtk style file picker.

I was happy when I first saw LIghttable bring up the native (KDE Dolphin) file picker.  It allowed me to choose network drives and add them.  Unfortunately, they don't work.  When you click on them nothing happens--they don't expand or show any files.  Local drives work fine.

Idealy, it would be great to be able to select files native KDE-style, but if LightTable can't do that, it should be set not even try, and go straight to gvfs.

**Comment by sentientnebula** [comment]
Console message is:

Couldn't read dir /<DirectoryName>

**Comment by cldwalker** [comment]
When we switch to atom-shell (which Atom uses), this may be resolved. Will ping this ticket when atom-shell lands

**Comment by cldwalker** [comment]
We've release 0.8.0-alpha which is based on Electron - https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss. Closing as this should be resolved. Ping us if it is still an issue
