### ISSUE TITLE
Launching multiple processes for parallel computing from LightTable editor for Julia

### ISSUE THREAD

**Issue by Kerkil** [LightTable/LightTable#1867]
Is it possible to make an effect of "julia -p N" when executing a script from LightTable for Julia?

**Comment by rundis** [comment]
I would think this is best solved in the julia plugin. Maybe raise an issue with https://github.com/one-more-minute/Julia-LT. 

Closing as I don't think this is likely to get any attention any time soon.

**Comment by Announcement** [comment]
Tell us what processes are slow.
Be very specific on the tasks and we can see about parallelization and
optimizing the tasks at hand. Its not like we can duplicate the entire IDE
though.

**Comment by rundis** [comment]
@Announcement out of curiosity... When you say us, who are you referring to ?

**Comment by Announcement** [comment]
Me and whoever else sees this that is willing to contribute. Personally I
love the thrill of optimizing things :)

**Comment by Announcement** [comment]
Actually sorry, mg bad I replied via email and I was mistaken on what we were actually talking about. I thought op wanted LightTable to scale better across cores or something with an extension.
