### ISSUE TITLE
Command + Space doesn't work in Yosemite

### ISSUE THREAD

**Issue by salmazov** [LightTable/LightTable#1875]
Command + Space in OSX Yosemite shows this:
![screen shot 2015-03-13 at 12 06 31](https://cloud.githubusercontent.com/assets/1635615/6635655/71afc32e-c979-11e4-9a0e-bec4a7144029.png)

instead of this:
![screen shot 2015-03-13 at 12 07 13](https://cloud.githubusercontent.com/assets/1635615/6635662/83273524-c979-11e4-962a-b90e2176b1d5.png)

How can I change command map in LT to use Commands panel?

Thank you.

**Comment by rundis** [comment]
ctrl+space is your friend.

**Comment by cldwalker** [comment]
Command-space is a global OSX keybinding. Until you unbind that keybinding (if it's possible), Light Table or any other app won't be able to bind to it.

**Comment by salmazov** [comment]
And you think it's good and handy behaviour?

**Comment by rundis** [comment]
@salmazov What do you mean by that statement ? I think the closing comment was pretty explanatory.
