### ISSUE TITLE
Adding folder in Workspace can not work with forward slash path

### ISSUE THREAD

**Issue by alphaho** [LightTable/LightTable#1876]
When I use `Add folder` in Workspace, if I use a forward slash path, LightTable does not open the correct folder.
For example, it works fine with `C:\path\to\folder` but not with `C:/path/to/folder`.

I'm using LightTable 0.7.2 with binary version 0.8.6 on Windows 7 64 bit.

**Comment by cldwalker** [comment]
We rely on nodejs for file operations and [its libraries use backslashes](https://nodejs.org/api/path.html#path_path_normalize_p) so this behavior is expected
