### ISSUE TITLE
Find does not give context

### ISSUE THREAD

**Issue by tomak-git** [LightTable/LightTable#1877]
When searching for a pattern (ctrl-f), the match is always displayed either on the first or the last line of the screen (depending if it was found before or after the current screen). As a result, half of the context is not visible. Ideally, the matches could be centered in the middle of the screen, providing as much context as possible. But I guess that showing the matches at least few lines away from the screen edge would do in most cases.
Cheers,

Tom

**Comment by cldwalker** [comment]
Thanks for the idea but at this time we don't have bandwidth to modify [codemirror's search addon](https://github.com/LightTable/LightTable/blob/20681a35258a95632e4c099d003399b98f5cb4ea/deploy/core/node_modules/codemirror_addons/search.js#L147) for new behaviors like this. I'd recommend adding this to the [wishlist](https://github.com/LightTable/LightTable/wiki/Feature-wishlist)
