### ISSUE TITLE
LT starting IPython process but not running the code on it

### ISSUE THREAD

**Issue by mgab** [LightTable/LightTable#1878]
I'm running a fresh download (no extra pluggins) of LT 0.7.2 on Debian 8 Jessie. I have a python 2.7.8 interpreter in the system dir `/usr/bin/` and some extra modules including IPython 3.0.0 in `/home/username/.local/lib/python2.7/site-packages/` and the IPython executable in `/home/username/.local/bin/`.
Also, I have the `$PATH` variable updated both in the `.bashrc` and in the `.profile` files to include the directory where the IPython executable is located, so that it should be correctly defined both in the bash shell and in GUI applications. `$PYTHONPATH` is also updated. As suggested [here](https://github.com/LightTable/LightTable/issues/486), I start LT from the command line

When executing a python script from LT, I can see that an IPython process is started but the code is run in a plain python interpreter ([tested as suggested here](http://stackoverflow.com/a/23883656)). In fact, the IPython process still exists after stopping LT, which I'd say is not the expected behavior...
(also described [here](https://groups.google.com/forum/#!searchin/light-table-discussion/ipython/light-table-discussion/nRNCJ9LxxxQ/nEYLAWwSKMsJ) and [here](https://groups.google.com/forum/#!topic/light-table-discussion/xAjZpmVwPDo))

Following [these](https://groups.google.com/d/msg/light-table-discussion/s_dbPTOxxe4/eZrP1YV-Q4MJ) instructions I added the following lines to the `user.behaviors` config file **without noticing any effect**:

    [:app :lt.plugins.python/python-exe "/usr/bin/python"]
    [:app :lt.plugins.python/ipython-exe "/home/username/.local/bin/ipython"]

Interestingly, the `PYTHONPATH` seems to be correctly used, and I can import all packages in the user directory, including IPython...

I've seen some issues here and discussions in the google groups discussing similar behaviors, but could not find a solution (I'm sorry if I missed it!!). Also, none of is from recent versions (LT 0.6 with IPython 1.2 and older)...

Any idea of what to try?

**Comment by mikofski** [comment]
+1 but on windows

LT 0.7.2

can't connect to IPython kernel using any method from various docs, discussions and questions on lighttable website, google groups and so

1. changing user.behavior

 [:app :lt.plugins.python/python-exe "C:/Python27/python.exe"]
 [:app :lt.plugins.python/ipython-exe "C:/Python27/Scripts/ipython.exe"]

2. set python to ipython

 [:app :lt.plugins.python/python-exe "C:/Python27/Scripts/ipython.exe"]
 [:app :lt.plugins.python/ipython-exe "C:/Python27/Scripts/ipython.exe"]

3. with pylab

  from pylab import *
  plot([1,2,3], [1,4,9])  # [<matplotlib.lines 2D line at blah>]

4. with pyplot

  import matplotlib.pyplot as plt
  plt.plot([1,2,3], [1,4,9])  # [<matplotlib.lines 2D line at blah>]

5. with pyplot.ion()

  import matplotlib.pyplot as plt
  plt.ion()  # None
  plt.plot([1,2,3], [1,4,9])  # [<matplotlib.lines 2D line at blah>]

6. with pyplot.show()

  import matplotlib.pyplot as plt
  plt.plot([1,2,3], [1,4,9])  # [<matplotlib.lines 2D line at blah>]
  plt.show() # None

7. in a function

  import matplotlib.pyplot as plt
  def MyPlot():
    plt.plot([1,2,3], [1,4,9])  # [<matplotlib.lines 2D line at blah>]
    plt.show() # None
  if __name__ == "__main__:
    MyPlot()

various combinations, but the only thing ever embedded is the pointer to the plot.

**Comment by wjaskowski** [comment]
The same happens on my OSX 10.8

**Comment by cldwalker** [comment]
Closing as we'll be tracking iPython support in https://github.com/LightTable/Python/issues/35
