### ISSUE TITLE
I can't install all of plugins and connect to clojure is slow

### ISSUE THREAD

**Issue by 602884291** [LightTable/LightTable#1879]
I'm chinese and i'm in beijing. my company's network can't connect to pluginsServer. when i connect clojure, is slow.

**Comment by cldwalker** [comment]
It sounds like you're behind a proxy. Set your proxy information with [these variables](https://github.com/LightTable/LightTable/wiki/FAQ#how-can-i-configure-my-proxy). Closing but can reopen if you're still having trouble and provide [reproducible steps](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md#bugs)
