### ISSUE TITLE
CLJS external browser REPL issues with org.clojure/clojurescript 0.0-3126 and reagent 0.5.0

### ISSUE THREAD

**Issue by peterk87** [LightTable/LightTable#1881]
Hello,

I'm a really big fan of the REPL within LightTable. It's so powerful and easy to get up and running - an absolute pleasure to develop with!

However, when I tried to update some dependencies in a Clojurescript project of mine, I encountered some issues with trying to get the LightTable external browser REPL up and running (the REPL with the HTML script tag).

With the latest version of Clojurescript (`[org.clojure/clojurescript "0.0-3126"]`), the REPL loads, but none of the `clojure.core` functions such as `map` or `reduce` can be eval'ed as they are (`map` evals to `nil`) and must be prefixed with `clojure.core/<function_name>`. I also get the same issue with the [`[weasel "0.6.0"]`](https://github.com/tomjakubowski/weasel/) browser REPL. So this might be an issue with the latest version of Clojurescript and it's compatibility with current REPLs rather than just an LT REPL issue.

If I downgrade to `[org.clojure/clojurescript "0.0-2843"]`, then I can simply eval `map` and `reduce` as they are within LT.

For example `map` evals to:

```
#<function (f,c1,c2,c3,var_args){
var colls = var_args;
switch(arguments.length){
case 1:
return map__1.call(this,f);
case 2:
return map__2.call(this,f,c1);
case 3:
return map__3.call(this,f,c1,c2);
case 4:
return map__4.call(this,f,c1,c2,c3);
default:
var G__105736 = null;
if (arguments.length > 4) {
var G__105737__i = 0, G__105737__a = new Array(arguments.length -  4);
while (G__105737__i < G__105737__a.length) {G__105737__a[G__105737__i] = arguments[G__105737__i + 4]; ++G__105737__i;}
G__105736 = new cljs.core.IndexedSeq(G__105737__a,0);
}
return map__5.cljs$core$IFn$_invoke$arity$variadic(f,c1,c2,c3, G__105736);
}
throw(new Error('Invalid arity: ' + arguments.length));
}>
```

rather than `nil`

I also get over 2000 undeclared Var warnings in the console. I'm not sure if that is related to the REPL issue.

When I try to update to [`[reagent "0.5.0"]`](https://github.com/reagent-project/reagent), I get the following exception when I try to connect to the LT REPL:

```
clojure.lang.ExceptionInfo: No such namespace: cljsjs.react, could not locate cljsjs/react.cljs at line 2 file:/home/piotr/.m2/repository/reagent/reagent/0.5.0/reagent-0.5.0.jar!/reagent/core.cljs :: {:tag :cljs/analysis-error, :file "file:/home/piotr/.m2/repository/reagent/reagent/0.5.0/reagent-0.5.0.jar!/reagent/core.cljs", :line 2, :column 1}
                 core.clj:4403 clojure.core/ex-info
              analyzer.clj:379 cljs.analyzer/error
              analyzer.clj:376 cljs.analyzer/error
             analyzer.clj:1249 cljs.analyzer/analyze-deps
             analyzer.clj:1494 cljs.analyzer/eval4017[fn]
              MultiFn.java:249 clojure.lang.MultiFn.invoke
             analyzer.clj:1833 cljs.analyzer/analyze-seq
             analyzer.clj:1925 cljs.analyzer/analyze[fn]
             analyzer.clj:1918 cljs.analyzer/analyze
             analyzer.clj:2133 cljs.analyzer/analyze-file[fn]
             analyzer.clj:2129 cljs.analyzer/analyze-file
             analyzer.clj:1246 cljs.analyzer/analyze-deps
             analyzer.clj:1494 cljs.analyzer/eval4017[fn]
              MultiFn.java:249 clojure.lang.MultiFn.invoke
             analyzer.clj:1833 cljs.analyzer/analyze-seq
             analyzer.clj:1925 cljs.analyzer/analyze[fn]
             analyzer.clj:1918 cljs.analyzer/analyze
             analyzer.clj:2133 cljs.analyzer/analyze-file[fn]
             analyzer.clj:2129 cljs.analyzer/analyze-file
             analyzer.clj:2103 cljs.analyzer/analyze-file
```

I do not encounter this issue when I run the REPL using [weasel](https://github.com/tomjakubowski/weasel/).

If I downgrade to `[reagent "0.4.3"]`, the LT REPL works again. 

Here's my system info:

Light Table version: 0.7.2
Kernel: Linux 3.11.0-26-generic (x86_64)
OS: Linux Mint 16 Petra

Hope this is enough info to reproduce the issues!

**Comment by cldwalker** [comment]
Thanks for the detailed report. This is a duplicate issue of #1845 and there is a WIP fix being investigated to address the exception
