### ISSUE TITLE
Zoom-In out keyboard shortcuts could be more elegant

### ISSUE THREAD

**Issue by ojotoxy** [LightTable/LightTable#1882]
This is on a Mac version.

To zoom out, it's Command - Minus
To zoom in, its Command - Plus (must press the shift key)

Most other apps use command minus and command plus, too, however, they don't require using the shift key for plus, which is easier to use.

**Comment by cldwalker** [comment]
Thanks for the suggestion. Closing as this is a duplicate of #1741. Happy to take a pull request for it
