### ISSUE TITLE
HTML code formatting broken by <% .. %>

### ISSUE THREAD

**Issue by mariusa** [LightTable/LightTable#1883]
Sample code
```
<div>
<span><% print('template code') %></span>
</div>
```

Select this code in LightTable, press Shift+Tab to auto-format.
Expected
```   
    <div>
        <span><% print('template code') %></span>
    </div>
```

Result
```
    <div>
        <span><% print('template code') %></span>
        </div>
```

**Comment by dosmoc** [comment]
Reproduced in the *atom-shell* branch, which intended for the 8.0 release. This is probably a problem related specifically to CodeMirror, which LightTable uses for a lot of its editor functionality. I get similar (but not the same) results in this demo:

http://codemirror.net/2/demo/formatting.html

Are the <% %> template tags? CodeMirror does appear to support mixed mode formatting, but it probably needs a specific parser for whatever is in the tags. I'm not at all familiar with it's capabilities, however, nor it's integration with LightTable

**Comment by cldwalker** [comment]
I've verified this is a bug because we aren't providing file types for [this mode](https://codemirror.net/mode/htmlembedded/index.html). Fix coming soon

**Comment by cldwalker** [comment]
Next release will have 4 file types that handle this correctly
