### ISSUE TITLE
"cancel evaluation" isn't enough to break a python eval 

### ISSUE THREAD

**Issue by jzthree** [LightTable/LightTable#1884]
This seems to be an old issue (#532). I can reproduce this issue with most recent Lighttable (0.7.2) and python plugin (0.0.7) release on both Ubuntu 14.04 and Windows server 2012.

Below is what I pasted from the issue #532 (which was closed in a previous clean-up)
 

For example, an infinite loop like so just goes on and on without being broken:
```
import time

while True:
  print '.'
  time.sleep(5)   

```

**Comment by dosmoc** [comment]
Was able to cancel evaluation using latest build of the *atom-shell* branch on Arch Linux using both python 2.7.10 and python 3.4.3. Not sure if this is expected when canceling a python eval, but the following exception shows:

```
Traceback (most recent call last):
  File "/home/dosmo/bin/lighttable/resources/app/plugins/Python/py-src/ltmain.py", line 202, in handleEval
    exec(code, module.__dict__)
  File "test.py", line 4, in <module>
    print '.'
  File "/home/dosmo/bin/lighttable/resources/app/plugins/Python/py-src/ltmain.py", line 31, in write
    self.flush()
  File "/home/dosmo/bin/lighttable/resources/app/plugins/Python/py-src/ltmain.py", line 34, in flush
    send(currentClient, "editor.eval.python.print", {"msg": self.cur, "file": name})
  File "/home/dosmo/bin/lighttable/resources/app/plugins/Python/py-src/ltmain.py", line 136, in send
    tosend = (json.dumps([client, command, info]) + "\n").encode('utf-8')
  File "/usr/lib/python2.7/json/__init__.py", line 193, in dumps
    def dumps(obj, skipkeys=False, ensure_ascii=True, check_circular=True,
Exception
```

Testing python 3 requires a slight change to the example given, due to print being a function instead of syntax:

```
import time

while True:
  print('.')
  time.sleep(5)   
```

**Comment by kenny-evitt** [comment]
@jzthree Would you try to reproduce this on the *atom-shell* branch?

**Comment by kenny-evitt** [comment]
Add a comment if this is still unresolved for the latest version of Light Table and I'll re-open (and move the issue to [the Python plugin repo](https://github.com/LightTable/Python)).
