### ISSUE TITLE
Trying to install Plugin crashes LightTable with no information 

### ISSUE THREAD

**Issue by sarvex** [LightTable/LightTable#1886]
The issue is present with many plugin, otherwise I would have raised the issue with the plugin developer. Haskell Plugin, Typed Closure Plugin and Go Plugin; all these are causing LightTable to crash. Kindly let me know if additional information is required. 

Light Table version: 0.7.2
Binary version: 0.8.4
OS: osx 10.10.2

**Comment by kenny-evitt** [comment]
@sarvex If you can, please test the changes in [this PR](https://github.com/LightTable/LightTable/pull/1937).

**Comment by rundis** [comment]
Closing this as I'm pretty sure the PR above (which is now merged to master) handles most cases a lot more gracefully.
