### ISSUE TITLE
Portable Edition

### ISSUE THREAD

**Issue by sbrl** [LightTable/LightTable#1890]
It would be awesome if there was a (windows) portable version of Light Table. Then I could use it from my Flash Drive anywhere I like :D

**Comment by rundis** [comment]
Probably not going to happen anytime soon :-) Unless you feel inclined to whack one up I

**Comment by sbrl** [comment]
@rundis If I knew where light table stores it's data / extensions, I could probably come up with something.

**Comment by rundis** [comment]
In the file menu for LT there is a menu choice "About Light Table"
There you will see an entry with plugins directory: for my machine that's ```/Users/mrundberget/Library/Application Support/LightTable/plugins``` (I'm on a mac)
so for me my Light Table data is basically stored under ```/Users/mrundberget/Library/Application Support/LightTable```

**Comment by kenny-evitt** [comment]
@sbrl A comment I made with info about the relevant LT and Electron code.

**Comment by sbrl** [comment]
Right. I might try taking a look at bundling light table with [portable apps](http://portableapps.com/) then!
