### ISSUE TITLE
Having Issues Downloading Any Plugins 

### ISSUE THREAD

**Issue by Jaballadares** [LightTable/LightTable#1893]
Please forgive me if I post too much of the error message. I'm new the world of programming and fear omitting something useful.

Failed to load resource: the server responded with a status of 403 (Forbidden): https://api.github.com/repos/LightTable/plugin-metadata/commits
Uncaught TypeError: Cannot read property 'sha' of undefined
bootstrap.js [29185]	anonymous
bootstrap.js [23098]	anonymous
bootstrap.js [23110]	anonymous
bootstrap.js [14143]	goog.events.Listener.handleEvent
bootstrap.js [14378]	goog.events.fireListener
bootstrap.js [14368]	goog.events.fireListeners_
bootstrap.js [14421]	goog.events.dispatchEvent
bootstrap.js [14542]	goog.events.EventTarget.dispatchEvent
bootstrap.js [16377]	goog.net.XhrIo.dispatchErrors_
bootstrap.js [16408]	goog.net.XhrIo.onReadyStateChangeHelper_
bootstrap.js [16394]	goog.net.XhrIo.onReadyStateChangeEntryPoint_
bootstrap.js [16390]	goog.net.XhrIo.onReadyStateChange_

**Comment by kenny-evitt** [comment]
@Jaballadares Interestingly, your comment in GitHub only seems to show the last block of the error messages that I saw in my email notification for this issue. Did you edit your original comment?

Also, would you please post the steps you can follow to reproduce this and divulge more info about your environment, e.g. OS, LightTable version, Java JRE and JDK versions, Leiningen plugins installed, etc.

**Comment by kenny-evitt** [comment]
@Jaballadares Re-open when or if you have some more details about the problem(s) you're having.
