### ISSUE TITLE
Javascript Promises browser implementation issue

### ISSUE THREAD

**Issue by MFAshby** [LightTable/LightTable#1900]
Javascript Promises do not appear to be implemented correctly in the LightTable browser.

Replication: 
Save http://pastebin.com/SPiRiLJc as a HTML file.
Open in LightTable browser. 
You'll get the Failure alert. 

Open in other browsers (e.g. chrome(ium), firefox) and you'll get the sucess alert.
I'm using version ##0.7.2 on Ubuntu 14.04

**Comment by MFAshby** [comment]
Spotted it's using a different implementation of promises to these browsers, 
The function passed to the Promise constructor has a single argument, a PromiseResolver, instead of two arguments (resolve and reject functions)

It looks light LightTable is using an API like this: https://developer.mozilla.org/en/docs/Web/API/PromiseResolver#Browser_compatibility
Wheras Chrome et. al use a Promise API as described here: 
http://www.html5rocks.com/en/tutorials/es6/promises/

Presuming that LightTable uses a third party javascript engine, it may need updating to have this functionality behave the same as other modern browsers.  If anyone knows where to even begin doing this I'd be happy to help.

**Comment by kenny-evitt** [comment]
@MFAshby the current released version of Light Table uses [node-webkit](https://github.com/nwjs/nw.js/) (now named NW.js apparently), which uses Chromium. Several contributors are working on migrating Light Table to use [atom shell](https://github.com/atom/electron) (now named Electron!), which is also based on Chromium. I suspect tho that when the migration is complete, Light Table will be effectively using a much newer version of Chromium. Hopefully this will be fixed then.

**Comment by MFAshby** [comment]
Great, thanks for the info. I'll keep an eye on the atom-shell branch.

**Comment by rundis** [comment]
@MFAshby  Pastebin gone, so I can't be bothered to try and figure out how to trigger this. Could you try and build from master to see if this is still a problem ? 
(if indeed it is still a problem and it's due to electron, it would need to be fixed upstream)

**Comment by cldwalker** [comment]
We've release 0.8.0-alpha which is based on Electron - https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss. Closing as this should be resolved. Ping us if it is still an issue
