### ISSUE TITLE
Underscores not rendered

### ISSUE THREAD

**Issue by MartinBurian** [LightTable/LightTable#1901]
Underscores are rendered into the line below the one they actually occupy. When typing, they resemble spaces ("hello_world" looks like "hello world"). Only once the line below is redrawn (just moving the cursor to it does the job), the underscore appears. When preceded by space, they are surprisingly OK right away.

To reproduce, type (into a blank file):

    hello_world

Looks like:

    hello world

On pressing enter, the underscore appears.

Light Table version: 0.7.2
Binary version: 0.8.6
Arch Linux 64bit
(ask for any specs that may be helpful)

**Comment by kenny-evitt** [comment]
@MartinBurian what window manager are you using?

**Comment by MartinBurian** [comment]
i3wm version 4.9.1

**Comment by kenny-evitt** [comment]
@MartinBurian thanks. I don't have a Linux workstation currently but maybe someone else can reproduce this. The core contributors are working on migrating from node-webkit to atom-shell. Hopefully this will be resolved when the changes for that migration are released.

**Comment by MartinBurian** [comment]
Thank you, I'll be looking forward to the update.

**Comment by argand-lamp** [comment]
Can't reproduce on arch 64bit.
Either on DWM 6.0 or xfce 4.12 using the same version of LT (0.7.2)

**Comment by dosmoc** [comment]
Failed to reproduce using *atom-shell* branch on Arch 64bit, using i3-wm 4.10.2-1 or xmonad 01.11.1.

**Comment by sashton** [comment]
Failed to reproduce. atom-shell branch, Ubuntu 64bit

**Comment by kenny-evitt** [comment]
@argand-lamp @dosmoc @sashton – thanks!

@MartinBurian – Would you attempt to reproduce this using the *atom-shell* branch?

**Comment by MartinBurian** [comment]
I'll try to. I'm unfortunatelly leaving for two weeks, so I'll try to in
two weeks or so.

čt 25. 6. 2015 v 15:24 odesílatel kenny-evitt <notifications@github.com>
napsal:

**Comment by cldwalker** [comment]
Closing as we haven't heard back. 0.8.0-alpha release may have resolved. Feel free to ping us if it's still an issue
