### ISSUE TITLE
LT 0.7.2 - Workspace doesn't display directory if name contains the string ".git"

### ISSUE THREAD

**Issue by Dadie** [LightTable/LightTable#1903]
Example directory names: 
- foo.git
- foo.git.bar
- foo.github.io
- .git.bar
- .git

Interestingly, if you create those directories via the workspace contextmenu they actually show up but wont appear on later starts. If created externally they never show up.

reproduces on x86_64 Arch Linux.

**Comment by rundis** [comment]
LT is default setup to ignore certain file patterns. You can override this in your user behaviours if you so wish.

[:app :lt.objs.files/file.ignore-pattern "(^\\..*)|\\.class$|target/|svn|cvs|\\.git|\\.pyc|~|\\.swp|\\.jar|.DS_Store|\\.nrepl-port"]

**Comment by Dadie** [comment]
So the LT default setup is so that every file or directory that contains the substring ".git" is ignored? Is this really on purpose? I see no reason to ignore every file or directory that contains the substring ".git", so what was the reason for this decision? 

I only see two possibilities. The first is that it is on purpose, so why is it on purpose? And the second, that it isn't on purpose and was meant to just ignore the meta-file directory ".git". In that later case it is obviously a bug that any directory or file that contains the substring ".git" is also ignored.

I can change my default setting, no problem with that. But I just feel uncomfortable with this solution, as I'm not sure whether to see this as a "bug" or as "as intended".

**Comment by kenny-evitt** [comment]
@Dadie It's probably a bug. Pull requests welcome!
