### ISSUE TITLE
Feature Request: Search All Files

### ISSUE THREAD

**Issue by flyboarder** [LightTable/LightTable#1907]
It would be awesome if lighttable had an option to use the search on all the open files in a window, just saying...

**Comment by Robsteranium** [comment]
Did you know that you can search the workspace with `CTRL`+ `SHIFT`+`F`?

If you manage your workspaces properly then this should give you what you need.

**Comment by rundis** [comment]
ref suggestion from @Robsteranium. If this isn't sufficient we are open for pull requests :)
