### ISSUE TITLE
Angular2 Error: UncoatedModuleInstantiator.getUncoatedModule

### ISSUE THREAD

**Issue by MalteFabian** [LightTable/LightTable#1908]
Hi,

playing with Angular2 a bit I've (immediately) stumbled upon a weird error. The whole arrangement works perfectly in Firefox (immediately).

More details can be found here:

<a href="http://stackoverflow.com/questions/30328032/angular2-testapp-not-working-in-lighttable-error-uncoatedmoduleinstantiator-g">SO question</a>

**Comment by rundis** [comment]
I tried to replicate your example, but got the same error in firefox and chrome standalone. Could you provide an example project which works as expected regardless of Light Table ?

So far I haven't seen anything that indicates that this is a Light Table problem, but I'm not ruling out that there might be some compatibilty issues with the inbuild chromium browser that ships with the node webkit version Light Table uses. If it is, then it's not much we can do about it. (well you can always try to build the atom-shell branch of LT to see if the problem persists there).

**Comment by MalteFabian** [comment]
Thanks a lot for looking into this. I will create a small github project for this. Hopefully very soon, but I'm not sure when this will be finished.

**Comment by MalteFabian** [comment]
Alright, here is the [link to the repo](https://github.com/MalteFabian/learning-angular2). Some informations can be found in the README.md.

**Comment by rundis** [comment]
Cheers !

Indeed. It must be an issue with node-webkit/chromium shipping with Light Table. I tried running the example with the atom-shell branch of Light Table and it worked fine there.
So I guess you'll have to wait for LT 0.8 to be released, or you could try building LT from the atom-shell branch yourself

**Comment by MalteFabian** [comment]
Alright, thanks!

**Comment by rundis** [comment]
Fixed in atom-shell branch.
