### ISSUE TITLE
[Atom-Shell] Use dev tool

### ISSUE THREAD

**Issue by Armaklan** [LightTable/LightTable#1911]
After build atom-shell application, i can open dev tools but not use it.

Click on dev-tools button make no action.

**Comment by kenny-evitt** [comment]
@Armaklan please provide some more details.

I notice you figured out that Atom changed its name to Electron so I'm assuming you made the same changes as in #1899. Did you also make the same changes as in #1892 ? I'm waiting for another contributor to sign-off on both, but I merged both the last time I built from source – [unfortunately I still had issues](https://github.com/LightTable/LightTable/pull/1892#issuecomment-105305951).

What OS and version are you running on your build computer? How are you running the build, e.g. *script/light.sh* or opening one of the executables directly?

I'm guessing you're accessing DevTools from the command bar – is that correct? You wrote "i can open dev tools ..." but then you wrote "Click on dev-tools button make no action." It's not clear whether you can see the DevTools window. I'm not sure what "dev-tools button" you're referring to – is it the button in the command list in the command bar?

**Comment by Armaklan** [comment]
Sorry for the poor initial comment :/ ( bad idea to open a ticket early in the morning ).

I run in linux. I do #1899 modification. I run directly the executable.

Yes, i open dev tools from command bar. The dev tools open correctly. I view the pane in the right of editor. 

But when i want to use them (view error, use console, inspect element, ...), dev tools dont make anything. No reaction. My click on dev tools pane has no effect.

I will try with : 

- #1892 modification
- light.sh bash

And add new comment after.

**Comment by kenny-evitt** [comment]
@Armaklan – thanks for the extra info.

What Linux distro, and version, are you running?

**Comment by Armaklan** [comment]
Sorry...

I try once again and it seems to be a local problem (a corner of my desktop causes some trouble). I close the issue...
