### ISSUE TITLE
Windows: Cut not working

### ISSUE THREAD

**Issue by robjens** [LightTable/LightTable#1913]
Is any other windows user experiencing a broken cut (`ctrl-x`) key combo? I cant get it to work natively, nor with cut, _nor with menu_ or with `:editor.kill-line`.

I did swap around `CapsLock` for `Ctrl` (using `SharpKeys` tool) but in every single application, anywhere and everywhere in windows, as well as any third party software - really *all* - it works fine.

This makes me think this particular problem is specific to windows Light Table. My Linux doesn't have this problem... also I've had it since a few versions ago. I'm not sure this is a bug though, unless someone can confirm this. Didn't find any tickets/issues in the tracker.

Regards,

Rob

**Comment by robjens** [comment]
Btw, nor `ctrl-shift-0` is working (I guess I could understand that) but for example `ctrl-shift-k` is not possible to rebind I just found out. Luckily, this is and remains the `cut-line` functionality. At least I now have a way to cut ^^

**Comment by kenny-evitt** [comment]
@robjens <kbd>Ctrl</kbd>+<kbd>x</kbd> works fine for me. Would you confirm whether it works if you disable or kill SharpKeys?

Interestingly, [the SharpKeys project description on CodePlex](https://sharpkeys.codeplex.com/) states:

> Things that SharpKeys ***will not*** do:

> Allow you to swap two keys with each other - e.g. you can’t have Q and Z swap places because the remapping code would get confused

From [the Light Table User FAQ](https://github.com/LightTable/LightTable/wiki/FAQ#what-are-the-names-for-keys-in-the-keymap-files):

> Light Table uses [Mousetrap](https://craig.is/killing/mice) for key-bindings.

I'm not sure why Light Table alone wouldn't accept a key combo that works in every other app but I suspect it's some kind of incompatibility between SharpKeys and Mousetrap.

**Comment by robjens** [comment]
@kenny-evitt Hey thanks for the reply, I'll go and see. The thing is that it doesn't run constantly, it makes one-off (registry I guess) changes,... so the best I can do is uninstall it completely.

I've never heard about mousetrap before, ima check it out. Thanks for the leads anyway and I'll report back soon enough...
