### ISSUE TITLE
there is an copy/paste bug on OSX

### ISSUE THREAD

**Issue by zongwan** [LightTable/LightTable#1916]
## install light table with julia , juno ##

# cmd
```
copy : cmd + c 
paste : cmd + v
```
### four tools
1.light table 
2.sublime text
3.chrome  html page
4.terminal

# copy test result
```
copy/paste in "light table" <==> copy/paste in sublime text
copy/paste in chrome <==> copy/paste in terminal
copy/paste in light table <≠≠> copy/paste in chrome/terminal

interesting!!!
copy/paste in "light table" <==> pbcopy/pbpaste in terminal
```

I think it is a bug of OSX .
could you have any ideas ? 
bug with REPL ? remote clipboard ?

have restarted those tools many times,still with bug
how to avoid this bug ?

**Comment by kenny-evitt** [comment]
@zongwan, would you explain the info in your "copy test result" section? I don't understand your notation, e.g. what does `copy/paste in "light table" <==> copy/paste in sublime text` mean (in regular grammatical English)?

**Comment by zongwan** [comment]
@kenny-evitt 
```
copy/paste in "light table" <==> copy/paste in sublime text
```
means
copy text in "light table",then we can paste it in "sublime text", also in turn.
like
they are using same clipboard

**Comment by kenny-evitt** [comment]
@zongwan ahh; thanks for the clarification. This is indeed interesting. What version of OS X are you running?

**Comment by kenny-evitt** [comment]
@zongwan I'd be interested to know what info about this you could generate by installing an OS X 'clipboard (history)' app and checking what they show when copying and pasting between Light Table and the other apps you mention.

**Comment by zongwan** [comment]
```
$ brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 4866d56645e8e43b5356b7b7ce1a3ac9fd48d02c
Last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.10.3-x86_64
Xcode: 6.3.2
CLT: 6.3.2.0.1.1431401888
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.6.0_65
```

still bug with terminal and my QQBrower (yeah,that's a strange brower)

safari,chrome,light table,sublime text are all fine.
![img](http://i.imgur.com/CZviofY.png)

**Comment by zongwan** [comment]
...
restart OSX then everything goes fine.
copy && paste works fine now...

Maybe it is just OSX's bug, so sorry to bother
