### ISSUE TITLE
Can't type kha in Russian

### ISSUE THREAD

**Issue by coda** [LightTable/LightTable#1917]
When i am typing text in Russian layout under Gnome 3.16 and pressing "kha" button, which is assigned to the same button as "[" i am getting brackets "[]" instead of kha letter.

Light Table version
0.7.2
Binary version
0.8.6

**Comment by kolya-ay** [comment]
This is well known [issue with international layouts](https://github.com/LightTable/LightTable/issues/620#issuecomment-59621776) which was workarounded by [this commit](https://github.com/LightTable/LightTable/commit/72408f6182638ddeb2f31be29affaccef46255a1). Do you use the [pair keybindings](https://github.com/LightTable/LightTable/wiki/FAQ#how-do-i-add-pair-keybindings), right?

The issue bothered me a lot (the 'х' letter is very important for Russians, you know). I tried to fix it right way but gave up as It's related on entangled interaction of Codemirror, mousetrap and internal Chromium keyboard handling. For now I just turn off the `:pair-keybinding` behavior if I want to type the "kha" letter.

**Comment by kenny-evitt** [comment]
@kolya-ay thanks

@coda Do you have [the 'auto-pair keybindings'](https://github.com/LightTable/LightTable/wiki/FAQ#how-do-i-add-pair-keybindings) enabled in your user behaviors? If you do, try disabling that behavior and then pressing the <kbd>kha</kbd> key.

**Comment by cldwalker** [comment]
Closing as this issue has been answered. We're tracking adding support for pair keybinding in international keyboards in #2003
