### ISSUE TITLE
Haskell plugin wasn't listed in installed plugins until after Haskell was installed

### ISSUE THREAD

**Issue by eatsalog** [LightTable/LightTable#1920]
I cannot install successfully the Haskell plugin. It says it extracts the plugin, then it says that the behaviors are loaded, but I never actually see it in my installed plugins. I installed the language and 2 seconds later I saw in my installed plugins, so there is clearly some error with it.

**Comment by kenny-evitt** [comment]
This could be friendlier. Pull requests welcome!

**Comment by cldwalker** [comment]
After a plugin is installed, the Available tab is blank and a user has to navigate to the Installed tab to see that it's installed. Any suggestions on what would be friendly here? We could throw a popup when the install is complete or we could switch to the installed tab

**Comment by kenny-evitt** [comment]
I think a good – and easy – quick win would be to show a status bar message that the plugin was installed. Switching to the installed tab might be nice, but then maybe the user wants to install several plugins so staying on the available tab would be preferred – neither seems obviously better.

**Comment by cldwalker** [comment]
@kenny-evitt Good idea
