### ISSUE TITLE
atom-shell cygwin build breaks when git setting core.autocrlf = false

### ISSUE THREAD

**Issue by dosmoc** [LightTable/LightTable#1924]
Following the directions in doc/developer-install.md for build in atom-shell (assuming lein, node, and npm are working) in cygwin breaks when git config --global core.autocrlf is set to the default. Should this setting the value to true be in the build documents or is it generally understood when building with cygwin that it should be so?

Showing how the build fails:
```
$ git clone https://github.com/LightTable/LightTable.git
Cloning into 'LightTable'...
Checking out files: 100% (1527/1527), done.

$cd LightTable

$ git checkout atom-shell
Branch atom-shell set up to track remote branch atom-shell from origin.
Switched to a new branch 'atom-shell'

$ script/build.sh
: invalid option line 2: set: -
set: usage: set [--abefhkmnptuvxBCHP] [-o option-name] [arg ...]
script/build.sh: line 3: $'\r': command not found
script/build.sh: line 8: $'\r': command not found
script/build.sh: line 44: syntax error near unexpected token `$'do\r''
'cript/build.sh: line 44: `  for plugin in "${PLUGINS[@]}" ; do

```

This appears to be because the line endings are converted to Windows compatible CR LF when the cygwin shell only recognizes Unix line endings. The branch builds successfully if git config --global core.autocrlf is set to false like so:

```
git config --global core.autocrlf false
```

Additionally, it looks like it's possible to explicitly set  line ending behavior for file types using .gitattributes so repo itself can determine what files should receive what type of line ending:

http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/

**Comment by kenny-evitt** [comment]
Without changing your global `core.autocrlf` setting (or after changing it back to the original setting), would you mind testing whether the *.gitattributes* file I added in #1925 resolves this?

**Comment by dosmoc** [comment]
The addition of the .gitattributes file seems to has resolved the problem. The build completes without any intervention.

**Comment by kenny-evitt** [comment]
@dosmoc Thanks!
