### ISSUE TITLE
atom-shell Linux (Arch) build depends on libgconf-2.so.4

### ISSUE THREAD

**Issue by dosmoc** [LightTable/LightTable#1926]
After a successful build of the atom-shell branch on Arch Linux, attempting to run the LightTable binary results in an error message:

```
$ ./LightTable
./LightTable: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

According to, atom/electron/#1518, libgconf-2.so.4 is a requirement for running on Linux. Was able to run the binary successfully after installing gconf, but it might be nice to mention this somewhere in the docs for the atom-shell branch.

**Comment by kenny-evitt** [comment]
Done – thanks again!
