### ISSUE TITLE
"Invalid behavior: :lt.plugins.clojure/eval!" after initial setup (developer-install.md)

### ISSUE THREAD

**Issue by marcelocra** [LightTable/LightTable#1932]
The specific error I get is this one:

    Invalid behavior: :lt.plugins.clojure/eval!
    TypeError: Cannot call method 'call' of undefined

I already tried to run `lein uberjar` as recommended [here][1] without success. I followed precisely the instructions given in [`developer-install`][2], but maybe they are outdated?

[1]: https://github.com/LightTable/LightTable/issues/1832
[2]: https://github.com/LightTable/LightTable/blob/master/doc/developer-install.md

**Comment by kenny-evitt** [comment]
@marcelocra Please try building the *atom-shell* branch – that's the working branch for the next release.

**Comment by marcelocra** [comment]
It worked, thanks!

Note: For it to work after I had previously built using the master branch, I removed both the LightTable directory as well as the .config/LightTable directory. Otherwise I would get the same error.

**Comment by kenny-evitt** [comment]
@marcelocra Great news! And thanks for the info about needing to cleanup.
