### ISSUE TITLE
Add web page to docs with screenshots of available themes

### ISSUE THREAD

**Issue by hayd** [LightTable/LightTable#1933]
Perhaps there's already a neat way to compare available color schemes, but at the moment I'm changing the config and seeing what it looks like...

It's be really nice if there was a webpage similar to http://vimcolors.com/ or https://github.com/robbyrussell/oh-my-zsh/wiki/themes where you could quickly compare the different available schemes.

**Comment by kenny-evitt** [comment]
@hayd Why not submit a PR to [the docs repo](https://github.com/LightTable/docs.lighttable.com) for this?

**Comment by hayd** [comment]
@kenny-evitt Honestly, I'm not sure how/a good way to do this (it'd be nice not to have to update css in lots of places when a theme was updated). I guess the alternative us to enumerate and take the fifty or so screenshots of themes (if we went that route rather than using css)... ah, you changed the title to reflect going the screenshots route...

It's going to be tricky to do that neatly (so screenshots are uniform)- I'll have a think about it.

**Comment by kenny-evitt** [comment]
@hayd Feel free to change the title to reflect what you want to do (or be done).

**Comment by hayd** [comment]
There are two options:

1. show these in in html / css (this is what vimcolors does)
2. take screenshots of each theme (this is what ohmyzsh does)

The former is the "better" solution, but the latter is probably easier (and could probably still be made to look ok).

**Comment by kenny-evitt** [comment]
@hayd I have no preference. I'm fine with whatever you, or whomever submits the PR, decides.

**Comment by cldwalker** [comment]
Closing I've updated [the docs](http://docs.lighttable.com/#change-theme) to link to codemirror's theme demo. Suggested nicer comparisons are always welcome as a PR but don't require an open issue if no one is working on it
