### ISSUE TITLE
Adding a folder to workspace hangs the UI for several minutes

### ISSUE THREAD

**Issue by bitmonk** [LightTable/LightTable#1941]
I've had this problem for some time on OSX, across as many OSX versions as Light Table has ever run on - when adding a folder to the workspace, the UI hangs for several minutes and node-webkit spikes, possibly to over 100% cpu.

**Comment by rundis** [comment]
I'm pretty sure this is fixed in the master branch. Light Table has been ported from node-webkit to atom/electron.

You can try and build LT from source following https://github.com/LightTable/LightTable/blob/master/doc/developer-install.md

Let me know how that works out...

**Comment by bitmonk** [comment]
Thanks, that did work, though there's new wierdness, but I'll chock that up to life on master and try to find a way to help.
