### ISSUE TITLE
New feature:  add a menu item to open workspace files with "Open with..."

### ISSUE THREAD

**Issue by chaffra** [LightTable/LightTable#1943]
Is there a way to add a menu item to open workspace files with "Open with..." I'd like to be able to open pdf, docx, ... files externally with a different program without having to leave LT of course. I am running on ubuntu.

**Comment by kenny-evitt** [comment]
@chaffra Certainly this is *possible* tho I'm not sure if there's a way to do this easily for all three platforms. This isn't a high priority so it may be a (long) while 'til anyone looks at it. But remember – pull requests welcome! And if you want some help implementing this, just ping me in this issue or in [the Gitter (chat) room](https://gitter.im/LightTable/LightTable).

**Comment by kolya-ay** [comment]
There is [LT-Opener](https://github.com/eldargab/LT-Opener) plugin which among other things allows you to define custom commands. However I think that something like this should be gently merged to the core.

**Comment by kenny-evitt** [comment]
@kolya-ay thanks. Your suggestion about merging into core raises interesting questions about when a plugin should be included in the defaults.

**Comment by kenny-evitt** [comment]
@chaffra I'm closing because of the LT-Opener plugin.
