### ISSUE TITLE
Misleading error message when uninstalling plugin

### ISSUE THREAD

**Issue by ShayMatasaro** [LightTable/LightTable#1944]
using 0.8 from master.
when uninstalling light refactor i get the following msg:

Some plugin dependencies are missing.

We found that the following plugin dependencies are missing:
clj-light-refactor 0.1.6
Would you like us to install them?

**Comment by cldwalker** [comment]
HI @ShayMatasaro. I've verified this issue. It is misleading message caused by behaviors probably kicking off out of order. Note the uninstall still works. Regardless, it is something we'll need to fix

**Comment by cldwalker** [comment]
This is fixed on master
