### ISSUE TITLE
#enhancement. Ready for use snippet for "Inserting a comment at the end of the current line"

### ISSUE THREAD

**Issue by weaver-viii** [LightTable/LightTable#1945]
<h4> Uncomment the last line to start typing if you a vim-user </h4>
[:app "f4"
  :editor.line-end
  :editor.new-line-indent
  :comment-selection
  :editor.line-up
  :editor.sublime.joinLines
  :editor.line-end
<b>;;  [:vim.send-key "a" ]</b>
  ]

**Comment by cldwalker** [comment]
Hi @weaver-viii. Thanks for sharing your snippet. Unfortunately, it's not something that belongs in LightTable itself. If you'd like to share this with other feel free to start a Snippets [wiki page](https://github.com/LightTable/LightTable/wiki)
