### ISSUE TITLE
How to load my js after code mirror modes have been load

### ISSUE THREAD

**Issue by huaoguo** [LightTable/LightTable#1947]
How to load my js after code mirror modes have been load? I want to add my custom coffeescipt codemirror mode. 

If I config behavior like this:

[:app :lt.objs.plugins/load-js ["js/simple.js", "js/coffeescript.js"]]

This will cause codemirror default coffeescipt mode override my mode.

**Comment by cldwalker** [comment]
I'm closing as I think you've solved this with [your own plugin](https://github.com/LightTable/plugin-metadata/pull/35/files). Happy to reopen if this is still an issue
