### ISSUE TITLE
Console should be shown, if hidden and not docked to a tab, when errors are logged

### ISSUE THREAD

**Issue by kenny-evitt** [LightTable/LightTable#1948]
See [this comment](https://github.com/LightTable/LightTable/issues/607#issuecomment-131228317) for relevance.

I believe this may have been the default behavior at one time.

**Comment by Muffo** [comment]
@kenny-evitt thanks for opening this ticket :)

Just one clarification: I am not sure what you mean by *errors*, but in my [previous comment](https://github.com/LightTable/LightTable/issues/607#issuecomment-131228317) I was referring to normal output with `println` rather than Closure errors.

I think that the console should be shown in both cases.

**Comment by rundis** [comment]
I really really don't want the console to be shown by default for println and friends. (much like I don't want the console in my browser to be shown by default).

**Comment by Muffo** [comment]
Not sure that the comparison between the console of an IDE and the console of your browser makes much sense...

Here we are talking about an environment where developers want to have visibility of what's going on. 
In any other IDE I have used before when I press RUN the console is always visible or become so.

**Comment by kenny-evitt** [comment]
@Muffo You should be able to keep the console open in a tab and move the tab to a separate tab group. Then you can see the console output with other tabs open. You should be able setup this as a default by editing your *user.behaviors* file.

But, more in the LT 'spirit' would be to just eval code in your source files, or open a REPL tab and run or test code as you write it.

But I don't think opening the console if *any* output is logged to the console – or opening it if it's closed and *any* output is logged – make sense for most users. If that's what you want, you should create a plugin to implement that functionality.

And I'm sure that LT never opened the console automatically if a non-error is logged.

**Comment by Muffo** [comment]
OK I am happy to open a console in a separate tab, but my point here is that if it is the first time ever you use Clojure and LT and you simply copy and paste [this Hello World](http://java.ociweb.com/mark/clojure/article.html#Overview):

```clojure
; Clojure
(defn hello [name]
  (println "Hello," name))
```

You type this and won't see anything happening.

What about an icon somewhere in the GUI at least to highlight that there is something in the console?

**Comment by kenny-evitt** [comment]
@Muffo There *is* an icon that indicates that something's been logged to the console. In the screenshot below, the "1" highlighted in red indicates that an error has been logged:

![image](https://cloud.githubusercontent.com/assets/1461730/9357165/61c3bf86-4653-11e5-9685-6e537cbf5231.png)

In this screenshot, the "2" highlighted in lighter-gray-blue indicates that two non-errors have been logged:

![image](https://cloud.githubusercontent.com/assets/1461730/9357812/f3957528-4656-11e5-8967-91840706e038.png)

**Comment by Muffo** [comment]
Actually that's perfect!!
I did not notice this before, thanks @kenny-evitt for the clarification :)
