### ISSUE TITLE
code/license for Light Table Playground?  (for running headless/in-browser)

### ISSUE THREAD

**Issue by CrazyPyro** [LightTable/LightTable#1951]
I love the Light Table "Playground" edition at http://app.kodowa.com/playground because I can run it in a browser without installing anything.   I was wondering if the code for it is available?  The site refers to https://github.com/Kodowa/Light-Table-Playground/ but that repo redirects to here, and searching for "playground" here yields nothing.

My motivation for this strange request is that I would like to hack the server to run headless - possibly even on another machine from the browser client.  Right now the server pops up a window that says:
>  :: Light Table Playground ::
> Checking for a new version...
> Starting Server...
> Server started. Let's do this.
> (close this to kill the server)

I see no reason this part can't just be on the console, which would get rid of the GUI dependency and allow it to run headless on my DigitalOcean droplet while viewing on my Chromebook.

I realize this sounds strange, and the Electron shell is great and all, but I'm trying to make it fit the weird constraints of a system with only a browser and headless Java.

**Comment by kenny-evitt** [comment]
@CrazyPyro Your request isn't *that* strange, but you should ask it on [the Google Groups group](https://groups.google.com/forum/#!forum/light-table-discussion). There's no repo for it for the Light Table organization on GitHub, unless it's this one, so I can't answer any questions about the code or its license.

But, the core LT code is compiled to JavaScript and effectively runs in a browser – Electron. I suspect that the Java server for the playground was just running a Clojure nREPL and there are lots of other ways to do that.

@ibdknox Thoughts?

**Comment by ibdknox** [comment]
We never released that code as it required a custom-modified version of
Clojure (most of the nice tools we have now didn't exist back then). :(

That being said the instarepl is basically a port of it.
