### ISSUE TITLE
build.sh doesn't produce LightTable executable

### ISSUE THREAD

**Issue by niedzielski** [LightTable/LightTable#1960]
Towards the end of the build script output, I see the following error and LightTable isn't generated:

   mv: cannot stat ‘builds/lighttable-0.8.0-linux/atom’: No such file or directory

The electron executable built seems to work though. This might be caused by having to build with electon 0.31.1 due to issue 1958. The full build script output is below:

    $ ./script/build.sh 
    ~/opt/LightTable/shell ~/opt/LightTable
    npm WARN package.json download-electron@0.1.0 No description
    npm WARN package.json download-electron@0.1.0 No repository field.
    npm WARN package.json download-electron@0.1.0 No README data
    npm http GET https://registry.npmjs.org/grunt-cli
    npm http 304 https://registry.npmjs.org/grunt-cli
    npm http GET https://registry.npmjs.org/nopt
    npm http GET https://registry.npmjs.org/resolve
    npm http GET https://registry.npmjs.org/findup-sync
    npm http 304 https://registry.npmjs.org/nopt
    npm http 304 https://registry.npmjs.org/findup-sync
    npm http 304 https://registry.npmjs.org/resolve
    npm http GET https://registry.npmjs.org/abbrev
    npm http GET https://registry.npmjs.org/glob
    npm http GET https://registry.npmjs.org/lodash
    npm http 304 https://registry.npmjs.org/abbrev
    npm http 304 https://registry.npmjs.org/lodash
    npm http 304 https://registry.npmjs.org/glob
    npm http GET https://registry.npmjs.org/inherits
    npm http GET https://registry.npmjs.org/minimatch
    npm http 304 https://registry.npmjs.org/inherits
    npm http 304 https://registry.npmjs.org/minimatch
    npm http GET https://registry.npmjs.org/lru-cache
    npm http GET https://registry.npmjs.org/sigmund
    npm http 304 https://registry.npmjs.org/lru-cache
    npm http 304 https://registry.npmjs.org/sigmund
    grunt-cli@0.1.13 node_modules/grunt-cli
    ├── resolve@0.3.1
    ├── nopt@1.0.10 (abbrev@1.0.7)
    └── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
    npm WARN package.json download-electron@0.1.0 No description
    npm WARN package.json download-electron@0.1.0 No repository field.
    npm WARN package.json download-electron@0.1.0 No README data
    npm WARN prefer global grunt-cli@0.1.13 should be installed with -g
    Running "download-electron" task

    Done, without errors.
    ~/opt/LightTable
    Deleting files generated by lein-cljsbuild.
    Retrieving crate/crate/0.2.5/crate-0.2.5.pom from clojars
    Retrieving fetch/fetch/0.2.0/fetch-0.2.0.pom from clojars
    Retrieving org/clojure/clojurescript/0.0-2138/clojurescript-0.0-2138.pom from central
    Retrieving com/google/javascript/closure-compiler/v20131014/closure-compiler-v20131014.pom from central
    Retrieving args4j/args4j/2.0.16/args4j-2.0.16.pom from central
    Retrieving args4j/args4j-site/2.0.16/args4j-site-2.0.16.pom from central
    Retrieving com/google/guava/guava/15.0/guava-15.0.pom from central
    Retrieving com/google/guava/guava-parent/15.0/guava-parent-15.0.pom from central
    Retrieving com/google/protobuf/protobuf-java/2.4.1/protobuf-java-2.4.1.pom from central
    Retrieving com/google/google/1/google-1.pom from central
    Retrieving org/json/json/20090211/json-20090211.pom from central
    Retrieving com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.pom from central
    Retrieving org/clojure/google-closure-library/0.0-20130212-95c19e7f0f5f/google-closure-library-0.0-20130212-95c19e7f0f5f.pom from central
    Retrieving org/clojure/google-closure-library-third-party/0.0-20130212-95c19e7f0f5f/google-closure-library-third-party-0.0-20130212-95c19e7f0f5f.pom from central
    Retrieving org/clojure/data.json/0.2.3/data.json-0.2.3.pom from central
    Retrieving org/clojure/pom.contrib/0.1.2/pom.contrib-0.1.2.pom from central
    Retrieving org/clojure/clojure/1.4.0/clojure-1.4.0.pom from central
    Retrieving org/mozilla/rhino/1.7R4/rhino-1.7R4.pom from central
    Retrieving org/clojure/tools.reader/0.8.0/tools.reader-0.8.0.pom from central
    Retrieving org/clojure/tools.nrepl/0.2.10/tools.nrepl-0.2.10.pom from central
    Retrieving clojure-complete/clojure-complete/0.2.3/clojure-complete-0.2.3.pom from clojars
    Retrieving cljsbuild/cljsbuild/1.0.1/cljsbuild-1.0.1.pom from clojars
    Retrieving org/clojure/clojurescript/0.0-2014/clojurescript-0.0-2014.pom from central
    Retrieving com/google/javascript/closure-compiler/v20130603/closure-compiler-v20130603.pom from central
    Retrieving com/google/guava/guava/14.0.1/guava-14.0.1.pom from central
    Retrieving com/google/guava/guava-parent/14.0.1/guava-parent-14.0.1.pom from central
    Retrieving org/clojure/tools.reader/0.7.10/tools.reader-0.7.10.pom from central
    Retrieving clj-stacktrace/clj-stacktrace/0.2.5/clj-stacktrace-0.2.5.pom from clojars
    Retrieving args4j/args4j/2.0.16/args4j-2.0.16.jar from central
    Retrieving com/google/javascript/closure-compiler/v20131014/closure-compiler-v20131014.jar from central
    Retrieving com/google/guava/guava/15.0/guava-15.0.jar from central
    Retrieving org/clojure/clojurescript/0.0-2138/clojurescript-0.0-2138.jar from central
    Retrieving com/google/protobuf/protobuf-java/2.4.1/protobuf-java-2.4.1.jar from central
    Retrieving org/json/json/20090211/json-20090211.jar from central
    Retrieving com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar from central
    Retrieving org/clojure/google-closure-library/0.0-20130212-95c19e7f0f5f/google-closure-library-0.0-20130212-95c19e7f0f5f.jar from central
    Retrieving org/clojure/google-closure-library-third-party/0.0-20130212-95c19e7f0f5f/google-closure-library-third-party-0.0-20130212-95c19e7f0f5f.jar from central
    Retrieving org/clojure/data.json/0.2.3/data.json-0.2.3.jar from central
    Retrieving org/mozilla/rhino/1.7R4/rhino-1.7R4.jar from central
    Retrieving org/clojure/tools.reader/0.8.0/tools.reader-0.8.0.jar from central
    Retrieving org/clojure/tools.nrepl/0.2.10/tools.nrepl-0.2.10.jar from central
    Retrieving crate/crate/0.2.5/crate-0.2.5.jar from clojars
    Retrieving clojure-complete/clojure-complete/0.2.3/clojure-complete-0.2.3.jar from clojars
    Retrieving fetch/fetch/0.2.0/fetch-0.2.0.jar from clojars
    Retrieving clj-stacktrace/clj-stacktrace/0.2.5/clj-stacktrace-0.2.5.jar from clojars
    Retrieving cljsbuild/cljsbuild/1.0.1/cljsbuild-1.0.1.jar from clojars
    Compiling ClojureScript.
    Compiling "deploy/core/node_modules/lighttable/bootstrap.js" from ["src"]...
    Successfully compiled "deploy/core/node_modules/lighttable/bootstrap.js" in 30.509466942 seconds.
    ~/opt/LightTable/deploy/plugins ~/opt/LightTable
    Cloning plugin Clojure 0.1.0...
    Cloning into 'Clojure'...
    remote: Counting objects: 1100, done.
    remote: Total 1100 (delta 0), reused 0 (delta 0), pack-reused 1100
    Receiving objects: 100% (1100/1100), 40.18 MiB | 967.00 KiB/s, done.
    Resolving deltas: 100% (543/543), done.
    Checking connectivity... done.
    /home/stephen/opt/LightTable/deploy/plugins
    Cloning plugin CSS 0.0.6...
    Cloning into 'CSS'...
    remote: Counting objects: 123, done.
    remote: Total 123 (delta 0), reused 0 (delta 0), pack-reused 123
    Receiving objects: 100% (123/123), 46.29 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (48/48), done.
    Checking connectivity... done.
    /home/stephen/opt/LightTable/deploy/plugins
    Cloning plugin HTML 0.0.2...
    Cloning into 'HTML'...
    remote: Counting objects: 35, done.
    remote: Total 35 (delta 0), reused 0 (delta 0), pack-reused 35
    Unpacking objects: 100% (35/35), done.
    Checking connectivity... done.
    /home/stephen/opt/LightTable/deploy/plugins
    Cloning plugin Javascript 0.1.2...
    Cloning into 'Javascript'...
    remote: Counting objects: 264, done.
    remote: Total 264 (delta 0), reused 0 (delta 0), pack-reused 264
    Receiving objects: 100% (264/264), 673.45 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (105/105), done.
    Checking connectivity... done.
    /home/stephen/opt/LightTable/deploy/plugins
    Cloning plugin Paredit 0.0.4...
    Cloning into 'Paredit'...
    remote: Counting objects: 107, done.
    remote: Total 107 (delta 0), reused 0 (delta 0), pack-reused 107
    Receiving objects: 100% (107/107), 92.71 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (42/42), done.
    Checking connectivity... done.
    /home/stephen/opt/LightTable/deploy/plugins
    Cloning plugin Python 0.0.5...
    Cloning into 'Python'...
    remote: Counting objects: 84, done.
    remote: Total 84 (delta 0), reused 0 (delta 0), pack-reused 84
    Unpacking objects: 100% (84/84), done.
    Checking connectivity... done.
    /home/stephen/opt/LightTable/deploy/plugins
    Cloning plugin Rainbow 0.0.8...
    Cloning into 'Rainbow'...
    remote: Counting objects: 83, done.
    remote: Total 83 (delta 0), reused 0 (delta 0), pack-reused 83
    Unpacking objects: 100% (83/83), done.
    Checking connectivity... done.
    /home/stephen/opt/LightTable/deploy/plugins
    ~/opt/LightTable
    Creating builds/lighttable-0.8.0-linux ...
    mv: cannot stat ‘builds/lighttable-0.8.0-linux/atom’: No such file or directory

**Comment by cldwalker** [comment]
Thanks for the report. [We're aware](https://github.com/LightTable/LightTable/blob/master/script/build-app.sh#L17) that upgrading electron requires changes to the build. We'll be tracking a fresh install not building in #1958
