### ISSUE TITLE
Client processes not cleaned up after killing(/quitting) LT on electron

### ISSUE THREAD

**Issue by rundis** [LightTable/LightTable#1961]
If I connect to say Clojure projects in Light Table and leave them open before quitting LT, the processes (lein-light + light runner) spawned for the projects will be left running after the main LT process is gone.

Might be an issue with other clients too.

**Comment by rundis** [comment]
Seems the trigger :closing is never raised.
I also found that the prompt for closing when you have unsaved files never is invoked either.
Seems to be a close event missing somewhere to tie all this together...

**Comment by cldwalker** [comment]
Thanks for digging in. It seems I caused it with https://github.com/LightTable/LightTable/commit/9658450e3b2a9d61c706d42056656347708e9bab. I remember making this change and asking Chris if he had any objection but never heard back. When I revert this commit I do see Clojure processes killed :) Would be great if we could bring back a solution that doesn't require `windowClosing`. $IPC_DEBUG may come in handy here

**Comment by cldwalker** [comment]
Fixed with #1964
