### ISSUE TITLE
error similar to issue #927 but with pyzmq installed

### ISSUE THREAD

**Issue by use924** [LightTable/LightTable#1962]
Evaluating any python code crashes lighttable (OS X 10.9, versions 0.7.2(binary)  or  0.8 (compiled in-house) )  pyzmq installed

Message similar to #927:

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
abort() called
terminating with uncaught exception of type NSException

When python is called a white small screen appears and then lighttable crashes

If it is of any help....
No problem when using Atom editor with Hydrogen package

**Comment by kenny-evitt** [comment]
@use924 Thanks for reporting this. To make this as easy as possible for someone to troubleshoot, would you provide extremely explicit steps for *anyone* to reproduce this? I probably won't look into this anytime soon, if ever, but if I did I'd have to setup a similar environment and find or create a similar project to first reproduce this.

**Comment by kenny-evitt** [comment]
@use924 Sorry for the overly fatalistic comment! We don't currently have any active Python contributors and there are quite a few open issues pertaining to various Python tools and environments, so this seems rather daunting.

**Comment by use924** [comment]
Thanks for the reply. I am surprised nobody else has reported this problem. Perhaps there is
something wrong with my setup (no problems with julia though, only with python- )
so no worries..

**Comment by kenny-evitt** [comment]
Add a comment with steps on reproducing this problem (including how to setup the necessary environment) and I'll re-open (create a new issue in [the Python plugin repo](https://github.com/LightTable/Python)).
