### ISSUE TITLE
Can't resize workspace tree, tabsets, or console on master on Window; icon doesn't change

### ISSUE THREAD

**Issue by kenny-evitt** [LightTable/LightTable#1963]
I'm not seeing the cursor change to the resize cursor anywhere between my left-most editor tabset and the workspace tree (when the latter is visible).

**Comment by kenny-evitt** [comment]
I can't reproduce this on Ubuntu. I suspect I'm not running the latest version on the relevant Windows box.

**Comment by kenny-evitt** [comment]
I just built the latest version of *master* on the same Windows box and this behavior still afflicts me. I also can't resize any of the other elements.

**Comment by cldwalker** [comment]
It's worth seeing if this is still an issue on #1957. If it is we'll probably want to report upstream to electron

**Comment by kenny-evitt** [comment]
@cldwalker Will do. I can't repro this with #1957 on my Mac.

**Comment by kenny-evitt** [comment]
I can't reproduce this on a more recent source version on Windows
