### ISSUE TITLE
Long Base64 string hoses auto-completion and makes LightTable hang

### ISSUE THREAD

**Issue by Mosho1** [LightTable/LightTable#1974]
I have a file with a base64 string of an image, it's pretty long and when it gets triggered by auto-completion LightTable hangs and often doesn't recover at all.

**Comment by kenny-evitt** [comment]
@Mosho1 I'm not sure how to reproduce this. Would you please provide an example file and detailed steps to reproduce?

**Comment by Mosho1** [comment]
A file with just a base64 representation of an image crashes LT for me. 

For example:

> iVBORw0KGgoAAAANSUhEUgAAAGsAAAAeCAYAAAArUOB+AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyJpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoV2luZG93cykiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6MTFBNTdCOEQ1NTU5MTFFNUE2NUZBNzFBRDUxRUE3QTMiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6MTFBNTdCOEU1NTU5MTFFNUE2NUZBNzFBRDUxRUE3QTMiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDoxMUE1N0I4QjU1NTkxMUU1QTY1RkE3MUFENTFFQTdBMyIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDoxMUE1N0I4QzU1NTkxMUU1QTY1RkE3MUFENTFFQTdBMyIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Ps59GKcAAAfRSURBVHja7FprbBRVFN7dbheQYnmJaQWsFYU0KBYREQiF8gogWN5KKUKg2NSoFRKUCCj8oIo04gOthAKWNy1vChEsiBhQDFigFhCo0CIKUl5p2d1ud9fv0DPlep3ZnW3Dsks4yZeZe+c+59xz7nfujMlwXzyKu8oa63Y61rndLrPb7W7s/q+cDarJ2Dd3Mdm3dG9xTyrKUb4RynJDWe5AUJbJutj8hnVxaLSvFW0bYjvaNz6XgdvzQKp9a1yEPS9+cLAryGW91MdlKxvDyV6BNDYT8Blwxrqk/gnr0rAY67Jws6aC1rVtb8uJGcDJ3cAUIILT9YD19u39hgSlkspL+7oqLhzC7S6gcyCO0STctwXInb1ozW522ra8xQLbiojet5S0OmqkbU2bY7gljPbQXiiQa98x4JWgUNC1ky1d109P5GQi0DGQx2vSyH8ceIsshdODgPY62ySFrbB/O/jpgFVS2dHOrqu/5eO2BJgZLNZvuoPtNrXvTGgQKBN1Xvypq/PSL4uclw9HItkViAeMweSqzXe4/UmVu4ZfsfRdv1JPYcfB6aEGU0hzg9F802AMiQztOPN4rZVzfmcI2ghDWxa0uR9ZbfjR3GAlP6Y73H4IkF2ZPzrRo5IOTIlz/DwtE7cXgNeAx4AiR0F6iePIvEWOoxkP6lbSua1TnCXb83B7BZgANBQUFdRi9tOCyK7cPcZgiV9VY2GV+1I6YcVHWrot3ILkN8CjKnVbAclkDY7CTxOMxpA0WEo+6m0zt0veW/V79gu4H4S8nrCiQnP0iBSUnQWE34txn9mPFvwFsLJy74RheLlzmX2Skrb40EYsoy/wDJAOxPHz0/f6aYrJj30pm3kPVtR9CWBl3Ze6rnZbVkhjH+tU0ZYDPCDk3eT4KlSlvLv+ROd1tYbcbne4Bn12GY3GG3oGgzaMKntUBeo7VMqS2w8T54Jy5RrtymXLOX1VyDuH+lFSPYv0bgwoc00q0wQXikObESfiNktR7g9ve9ZVH5W1F1gGLBXyiHUlAC+pVcCCIOUWAKuBr6A8uzJZLTKACVlx+ZXICZCFiVRpjIfO7/KlvNnABypluwN7hLQV/XRA26d0lO3Fc/C2cLYDvYVsIlVj+XkXXObwc5NKfTpnfYfLE5slJR8GDtKe7y83SKuNzts+IWVDeXqoeAMOXonSb8ZEtMb6qkreWH5xevpY4qFtX+VNSVFEelJYEUNx+YHJkVZ/LbFwVrHnmgFE8fxIedEmXt0iZJf1l/T8b50D32yoPhQ9J+U/zwOR5SKzwxyKsaRnAw0qZ5J4AeSWhovuUzgu66JznGRBr9dVSxhLDC4fCVnkPUaSm8UzWhRZ0jZxkrwMMA/IBS5rbDnHmQEXm+GSoiSXRe7jffFFoUyBVGa8t8GjToJQPoUHpggd9E6TqpzAxMYLkycrTJPc0GqpzjAOeknI31cYbp9hJgEHdL7rdPS3zdue4UFRt85DDdVfHhRJQ3sFwoJoIjzbRlsGnrukNsZxcg27QLoeAR4hq/OLG4TiMiULawkFWrxUy5HSaq5znHD/I0ORUfwCPEkFXxuyO6ztWeFsXv01Y4ciMoV0c6n8ZVFRTEIcQBbfryFSwtfjwHfAMn9Sd6u8IL2Uf1JKF0mrmU434iXlbhLSzdh9epI5wn1PILUWVtWNSYEixXzqIopsseNRbz6z4cCKs2BFz0qBcBGszaEx+aYAubePJdq8RCqaJNB+er7TUP1BVGS3iV6Gto/3SdEdtvYx0M8W3iMRg1GwAnnfJzZ3VMqbCpSgvwwg4q4eN0FBaezDabN/WYqnFqpUiaOfGlTyKd4ahhdw3oMLzMNzOyt7q/BsCK1elZenSD3eF4mh0aeTRsBi1Omvc5rkmsU4dTn6OvQ/jcLloc3hHGK0lurT1/ZUUhpZOspW3g3LIoLwIbuERlLc8bXONtYB7TCBfMn6OkuWKu5vuZIyRng0jeqAdbKQRYqbpHN85RwP1Vg7xhar0Q/R+A7AApUtoT7wHrDWUxjhzz2LfDl9/kiCC3SqPC8Ddkihw1BmUrLIbLQ/JrmAoLJPJXn1ZUZjnuQOMzQIjSxOifZb+IWHaS0M4G0iWLzPlUlFEnjO/nWDQqfEuM5AQcVeyhdiIgOZOOznCd2ixMg7pdBg3NdTibmSPbTbg9pE/VIv/cvuMF3XpgXGxi5OseAnOExJ8lCHrHEe6hFj3CAF0v0Mt3+n8I9lQTmbGLt0KEqcSKlkObRaswUaTv+DNPWRBCTq6Fd2hzE+9JEqBbV0gjJOcNutgUYqfd5g2i9KeCC4QYMPCsvnvU2Rp4B3VYgFyUgOmEUMFE4zdLlCwR2urMV4/1Gh/V9CQcq+Sn9NHUM6mdiuoMTGKl6h+G64wbrKVLYihW3NwOT2cJ7oOnM1QoDvhTgsRmvjVxH6q6sP8LCPCstBH7mCO2zI+5dy7EVfwhcRuULen0zzW0lHUFV8EhI8lsWTv8gMSXSHy6UFtsFDE7LfH6uz3zLl8LUWIrtDYn/zVdwy7cfRKoqajP6LfLGss4bqzyAiPZXlCp9ZielCKebQI3Q8pDAntc8PmcwGIzndhoNLJfBd66FtOs0YJaQj+LxNnNs1DYVt4rink1TWKc37guwOUY8Y7ywhuxsvnOlMHujs8iEhiD7FwfznGp9qauRfAQYAnAzv2Z+kbYQAAAAASUVORK5CYII=

**Comment by kenny-evitt** [comment]
@Mosho1 I just created an empty text file in LT and copied your base64 string into the empty file in LT.  I'm guessing you're not following those same steps – what are you doing? The more detailed you are the more easily I can reproduce your issue and the faster I can determine what's causing it. See [the guidelines for submitting issues for bugs](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md#bugs):

> When filing a bug on GitHub, please help us help you by including the following:

> - *Steps to reproduce the bug.*
> - Your operating system, LT and relevant plugin versions.
> - Relevant configuration in your user.keymap and user.behaviors.

If you can share your entire project that you're working with when you can encounter that issue, that would be helpful as I suspect that's relevant to whatever is causing the auto-completion to hang.

**Comment by Mosho1** [comment]
That's just what I did. I just did the same from a different pc and LT froze. I copied the string, and started typing, so that autocompletion shows. It doesn't start until the 4th or so keystroke. Sorry if I was unclear.

**Comment by kenny-evitt** [comment]
@Mosho1 Generally, you can't be *too* specific or detailed in describing steps to reproduce.

I was able to reproduce this with both version 0.7.2 and a build of a very recent version of *master*.

In 0.7.2 the UI isn't responsive but I can open menus and various hover effects still work. In the *master* build the entire window goes white.

Steps to reproduce:

 1. Create a new text file.
 2. Paste the example Base64 into the file.
 3. Hit <kbd>Enter</kbd>.
 4. Start typing fairly quickly* – I used <kbd>a</kbd> <kbd>b</kbd> <kbd>c</kbd> <kbd>d</kbd> <kbd>e</kbd> <kbd>f</kbd> <kbd>g</kbd> – but you can probably use almost any sequence of characters.

\* I wasn't able to reproduce this if I didn't type pretty quickly.

**Comment by cldwalker** [comment]
@kenny-evitt Thanks for looking into this.
@Mosho1 Thanks for the report. We've had the same issue reported in #1635 and is being tracked there. There's a suggested fix on that issue if you're interested in contributing
