### ISSUE TITLE
Closing internal browser not cleaning up properly ? 

### ISSUE THREAD

**Issue by rundis** [LightTable/LightTable#1975]
If I;
1. Open a html file
2. Select command ```Editor: Open current file in browser```
3. Close the browser
4. Select command: ```Console: Clear console```

I get the following exception:
```WebSocket is already in CLOSING or CLOSED state.
bootstrap.js [35090]	lt.objs.clients.devtools.send_STAR_```

I tried reverting back to this [commit](https://github.com/LightTable/LightTable/commit/e97278f174e1b83fffb2f455800530f08a5cdcc1) but the error still persists.

**Comment by rundis** [comment]
Not entirely sure what's happening, but it seems that the browser (webview) client isn't removed when closed. Tried debugging a bit, and I can't seem to pick up any close events from the webview, but there is deffo a destroyed event being triggered (as per the IPC debug feature). 

Tried adding a close event handler with a println (as per https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md) in the ([t browser namespace](https://github.com/LightTable/LightTable/blob/master/src/lt/objs/browser.cljs#L231)
No output though. 

@cldwalker any pointers/ideas ?

**Comment by cldwalker** [comment]
Thanks for opening this. I've been seeing this bug for awhile at least since the atom-shell branch. Since it was so infrequent, I didn't dig into it more. With a reproducible case, I should have a fix up shortly

**Comment by rundis** [comment]
Cool. I can reproduce with the steps outlined in the initial comment.
