### ISSUE TITLE
Windows 0.7.2 Settings auto-complete not functioning properly

### ISSUE THREAD

**Issue by bmcgonag** [LightTable/LightTable#1977]
Trying to follow instructions in documentation and videos, but when I go into user behaviors to change line numbers and font size, the auto-complete typing either. 
1. does not come up,  or 
2. comes up if I backspace once, but does not provide an option for font-size. 

I copied the change for line numbers from a google forum post and got that set, but the font size does not work even when copying the editor line directly from your video example.

**Comment by kenny-evitt** [comment]
@bmcgonag What version of Windows are you running? Would you post the exact line you're trying to add to your *user.behaviors* file to change the font size?

**Comment by kenny-evitt** [comment]
@bmcgonag Let me know if this should be re-opened.
