### ISSUE TITLE
Shortcuts missing from the dropdown menu

### ISSUE THREAD

**Issue by anshbansal** [LightTable/LightTable#1978]
Environment - Ubuntu 14.04 64-bit
Light Table version - 0.7.2
Binary version - 0.8.6

The "Getting started" for files and workspaces shows that the shortcuts are available on the dropdown. e.g. Ctrl + Shift + O is shown for Open file in the video. But in my Light table these shortcuts are not being shown.

**Comment by anshbansal** [comment]
The folder | file | recent at the top of workspace are also not available

**Comment by anshbansal** [comment]
I think this is related to https://github.com/LightTable/LightTable/issues/1338

**Comment by kenny-evitt** [comment]
@anshbansal Please try building the latest source of the *master* branch and confirming whether you can reproduce this with that version. If indeed this is a limitation of NW.js, like #1338, then this may be resolved by the migration to Atom Electron.

**Comment by anshbansal** [comment]
I will build the master. By sunday. 

I am not sure whether it is related as per the technology point of view. I was talking as per functionality. The screenshots are similar to what I see myself.

**Comment by cldwalker** [comment]
We've release 0.8.0-alpha which is based on Electron - https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss. Closing as this should be resolved. Ping us if it is still an issue
