### ISSUE TITLE
Can't run simple code.

### ISSUE THREAD

**Issue by salmazov** [LightTable/LightTable#1981]
![lightttable 2](https://cloud.githubusercontent.com/assets/1635615/9905287/cc5504f0-5c8c-11e5-97bc-ca7cae721a87.PNG)
![lightttable](https://cloud.githubusercontent.com/assets/1635615/9905289/cc7f03c2-5c8c-11e5-9699-14ab2059328e.PNG)

When I was wrong?

**Comment by rundis** [comment]
Evaluate second.clj first and you are good to go.
