### ISSUE TITLE
LightTable not able to detect classpath of lein project

### ISSUE THREAD

**Issue by buzzshiva** [LightTable/LightTable#1997]
LightTable not able to detect classpath of lein project, Can someone let me know how to set classpath in lightTable for clojure projects using lein.

java.io.FileNotFoundException: Could not locate guestbook/models

**Comment by kenny-evitt** [comment]
Light Table is just using Leiningen. Are you able to run your project directly with Leiningen?

Also, see [the section about bugs](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md#bugs) in [the contributing guidelines](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md):

> When filing a bug on GitHub, please help us help you by including the following:

> * *Steps to reproduce the bug.*
> * Your operating system, LT and relevant plugin versions.
> * Relevant configuration in your user.keymap and user.behaviors.

Steps would be helpful.

Your OS, OS version, LT version, and plugin versions (particularly the Clojure plugin) would be helpful too.

It would *also* also be helpful to share a minimal example version of your project for which you can reproduce this.

All the above having been written, you should probably first try building the latest source version (of the *master* branch) and then upgrading the Clojure plugin. Well, first try running your project directly with Leiningen. But then try the latest source version.

**Comment by buzzshiva** [comment]
Basically I created a lein project and imported the root project folder and started liverepl where I pointed the src/guestbook/models/db.clj file using 

Also be noted that I'm able to resolve the classpath using lein repl under the same directory i.e., c:\samples\guestbook\lein repl,  

[use 'guestbook.models.db]

under lein classpath i can see the path is available, but guestbook model is not getting resolved via lighttable. 

One question are there any configuration I need to make to set the lein classpath in lighttable? What would be the default lein classpath in case of LightTable, What I noticed was wherever I run len repl it takes current working directory and adds lein classpath.

**Comment by rundis** [comment]
@buzzshiva I think there are some severe limitations with the instarepl when handling clojure projects (not sure if it has been recently introduced or not). This issue is related: https://github.com/LightTable/Clojure/issues/55

If you skip using instarepl and rather use eval form or eval editor contents expllicitly should work as you would expect.

**Comment by cldwalker** [comment]
This issue has moved to https://github.com/LightTable/ClojureInstarepl/issues/14 as the instarepl is now its own plugin
