### ISSUE TITLE
"Devtools: Verify js console and inspect element" for connected browser HTML and JS files?

### ISSUE THREAD

**Issue by kenny-evitt** [LightTable/LightTable#2001]
@cldwalker @rundis 

This pertains to QA-ing the latest source version on Linux.

I'm not sure what the [QA checklist](https://github.com/LightTable/LightTable/wiki/QA-Checklist) item quoted in the title of this issue means. The only 'devtools' I can find is the standard LT-global Chromium Developer Tools window/frame. `console.log` calls in included JS files are being included in the LT console not the dev-tools console. And I can't figure out how to inspect an element from a browser tab. The DOM shown in dev-tools only includes a `webview` element, with something that's shown only as `#shadowroot` (it doesn't look like any other HTML elements), and inside the `#shadowroot` a single 'browser plugin' `object` element.

**Comment by cldwalker** [comment]
@kenny-evitt Sorry for the vagueness and feel free to update the QA for clarity. That item is about using the `Dev: Open Developer Tools` command anywhere in LT. Once  Chromium Dev Tools is open, verify the [Elements tab](https://www.dropbox.com/s/j6m871342x3n73v/Screenshot%202015-10-04%2011.35.13.png?dl=0) and Console tab appear to be working. For Console tab verification, I'd recommend `document.querySelector(...)` to verify it is connected to LT

**Comment by kenny-evitt** [comment]
@cldwalker Ahh. I'll test the Console tab then but the Elements tab was definitely working.

**Comment by kenny-evitt** [comment]
I added some details to the item in the checklist.
