### ISSUE TITLE
Inline results not cleared when evaling same statement again

### ISSUE THREAD

**Issue by rundis** [LightTable/LightTable#2004]
Steps to reproduce

- Open a editor for clojurescript (say a plugin cljs file)
- connect to lt-ut
Enter and evaluate:
```clojure 
(defn hello []
  (println "hello"))
```
- then change change hello to hello world and voila to results, and so on.

<img width="498" alt="screen shot 2015-10-05 at 22 45 30" src="https://cloud.githubusercontent.com/assets/399197/10293075/ddf6af6c-6bb2-11e5-9d2f-91ceead83022.png">

Happens with both clojure and clojurescript

**Comment by kenny-evitt** [comment]
I was able to reproduce this on Windows just now and I'm pretty sure I saw the same on Linux, both with the latest source.

I wasn't sure this was fixed before.

**Comment by rundis** [comment]
I can also reproduce with javascript (:
![screen shot 2015-10-06 at 07 15 52](https://cloud.githubusercontent.com/assets/399197/10300686/20387fb2-6bfa-11e5-8726-0dbdd960a945.png)

**Comment by rundis** [comment]
Think this commit https://github.com/LightTable/LightTable/commit/2b0e9086927f5870966b9937efbf1c0e6ae47d95#diff-7bc0013fd8e35583a4681d44ccf83a91R313 is the culprit breaking inline results for "normal eval".

I can't see how this could possible work using ch, as soon as you change something on the line or newlines the lookup will be off ? I tried reverting the effects of this commit (or rather just removing the ch specifier for lookup and creation and it seems to work nicely.

But that I guess would mess up instarepl (:

**Comment by cldwalker** [comment]
@rundis I had [similar concerns](https://github.com/LightTable/LightTable/pull/1811#issuecomment-69330596) but never heard back. After the alpha release, it may be worth seeing if changing to `[line type ch]` and making the ordering change in Clojure is doable

**Comment by rundis** [comment]
Fixed on master
