### ISSUE TITLE
On OS X with multiple displays LT consistently comes up off screen when reopened

### ISSUE THREAD

**Issue by rekrabm** [LightTable/LightTable#2007]
### Configuration
I have  a MacBook Pro with 2 additional displays attached - 3 displays in use.  
OS X Yosemite 10.10.5 
### Setup
Open, use, then quit LT on one display.  

Open LT again.
#### Expected Results: 
- LT opens with something similar to it's previous location on the same screen.

#### Actual results:
No window displays because the window coordinates are completely off the screen.  

### Reproducibility
This happens every time I use LightTable.

### Workarounds?
I find no way to recover from this except by removing LightTable-related files from ~/Library/Application Support, ~/Library/Caches, and ~/Library/Preferences

**Comment by kenny-evitt** [comment]
@rekrabm Would you confirm whether you can reproduce this with only one additional display (two total in use)?

Also, would you try to reproduce (both with two and three total displays) with the latest source version?

**Comment by rekrabm** [comment]
Sorry for the delay.  I thought I'd responded to this already.  Must've lost the browser session with an interruption.

This happens with even a single additional display and it still happens with build below:
Light Table version
0.8.0-alpha
Binary version
0.31.1 
Please let me know what testing you would like me to do and what information you'd need collected.  I'll do so if I can.

**Comment by kenny-evitt** [comment]
@rekrabm The latest source version might resolve this. I should be able to reproduce this – potentially at least – but it sure seems like a likely problem with Electron, the app framework we're using, and thus trickier to troubleshoot.

You should be able to build the latest source – just clone the repo and run *script/build.sh* from a *Terminal* window.

**Comment by kenny-evitt** [comment]
@cldwalker @rundis Can either of you reproduce this?

**Comment by rundis** [comment]
@kenny-evitt Nope. I only have one additional display to play with at work. But it works pretty much as I'd expect as far as I can remember.

**Comment by cldwalker** [comment]
Closing as we haven't heard back. You can disable restoring position with the following in user.behaviors `[:app :lt.objs.app/restore-position-on-init]`
