### ISSUE TITLE
virus in light table?

### ISSUE THREAD

**Issue by rwobben** [LightTable/LightTable#2009]
Hello, 

I have downloaded the last version from Windows. 
I unpacked it without any problem.

But as soon as I run it and see the lightable editor AVG says there is a IDG.Ares virus in the .exe. 

Roelof

**Comment by kenny-evitt** [comment]
@rwobben The executable is actually node-webkit. For the pending release, and all future versions, the executable will be Electron. You could try running the latest source version instead.

I'll look into this today hopefully.

**Comment by kenny-evitt** [comment]
@rwobben I can't find any info about a virus named "IDG.Ares" virus. Please provide a link to more info.

**Comment by rwobben** [comment]
Sorry I made a typo , For more info : http://www.avgthreatlabs.com/ww-en/virus-and-malware-information/content/generic-virus/?name=IDP.ARES.Generic&utm_source=TDPU&utm_medium=IDP&PRTYPE=AVF

**Comment by kenny-evitt** [comment]
@rwobben Based on [my Google search results for "IDP ARES Generic"](https://www.google.com/search?q=IDP+ARES+Generic) [your results may vary], this looks like a false positive affecting several completely unrelated executable files on Windows. I think the odds that LT, Counterstrike (a game), and *memcached.exe* all being infected with the same virus is pretty low.

I just downloaded the ZIP file from Windows from the website and the executable in the ZIP matches my much older copy of the same file.

I'm confident AVG reporting the presence of a virus is a false positive.

**Comment by rwobben** [comment]
Op 7-10-2015 om 16:33 schreef
      kenny-evitt:
    
    
      @rwobben Based on my
          Google search results for "IDP ARES Generic" [your results
        may vary], this looks like a false positive affecting several
        completely unrelated executable files on Windows. I think the
        odds that LT, Counterstrike (a game), and memcached.exe
        all being infected with the same virus is pretty low.
      I just downloaded the ZIP file from Windows from the website
        and the executable in the ZIP matches my much older copy of the
        same file.
      I'm confident AVG reporting the presence of a virus is a false
        positive.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
      Geen virus
        gevonden in dit bericht.
        Gecontroleerd door AVG - www.avg.com
        Versie: 2015.0.6140 / Virusdatabase: 4435/10773 - datum van
        uitgifte: 10/07/15
    
    
    Thanks, 
    
    I also uploaded lighttable.exe to virustotal and found nothing.
    Or is there another file which runs when I see the IDE ?
    
    Roelof

**Comment by kenny-evitt** [comment]
@rwobben There's no other executable.
