### ISSUE TITLE
File encoded with win1250 opens as UTF-8 - cannot change

### ISSUE THREAD

**Issue by rafpran** [LightTable/LightTable#2013]
Minimal: Need to change encoding from given to UTF-8.
Fancy: any encoding to any encoding.

**Comment by kenny-evitt** [comment]
@rafpran [All files seem to be being read as UTF-8.](https://github.com/LightTable/LightTable/blob/master/src/lt/objs/files.cljs#L171)

I'm not sure what we'd need to do to support this but I suspect it would be significant. Pull requests are welcome for any core changes that are required, but as-of now I think this would be best implemented as a plugin. I added this to [the feature wishlist](https://github.com/LightTable/LightTable/wiki/Feature-wishlist).
