### ISSUE TITLE
'Docs' panel empty when opened in offline LT

### ISSUE THREAD

**Issue by MikeTheGreat** [LightTable/LightTable#2016]
Repro:
1. Turn off your networking (or, do like I did & ride the bus!)
2. Start LT.
3. In that nifty 'Welcome' tab there's a link with the text "If you're new, you might want to look at the Light Table's docs to get started"  Click on the link
4. The docs panel will appear but it contains nothing.  There's not even any feedback that the docs are unavailable because of network issues.

**Comment by kenny-evitt** [comment]
@MikeTheGreat Thanks for the report. Do you mind looking into this and at least the likely scope of the minimal changes that would resolve this?

**Comment by MikeTheGreat** [comment]
@kenny-evitt Thank you for the response!
Thank you also for the invitation to participate but I noticed the bug while casually trying out Light Table and don't want to dig into the source (nor do I have the time, sadly).  
Good luck with this!
