### ISSUE TITLE
Opening and closing new windows from the menu leads to exception in linux

### ISSUE THREAD

**Issue by cldwalker** [LightTable/LightTable#2017]
On Ubuntu 14.04, I did the following:
- From the menu File > New window, open a new window.
- Close that window.
- Open another new window from the menu
- Get the following error popup: `A JavaScript error occurred in the main process` with stacktrace:

```
Uncaught Exception:
Error: Calling a callback of released renderer view
    at ret (/home/lt/code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/atom.asar/browser/lib/rpc-server.js:112:21)
    at MenuItem.click (/home/lt/code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/atom.asar/browser/api/lib/menu-item.js:44:20)
    at Function.delegate.executeCommand (/home/lt/code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/atom.asar/browser/api/lib/menu.js:127:69)
```

Doing the above steps does not cause an exception in OSX 10.10

**Comment by MarcusE1W** [comment]
Hi.
I just checked this issue and I could reproduce it in Ubuntu 14.4.
However I have also checked Ubuntu 16.10 the currently latest version in the same way and the error does not come up.
I think this can be considered a Ubuntu 14.4 related issue and not a lighttable issue.
Maybe this issue can be closed?

**Comment by sbauer322** [comment]
@MarcusE1W, just to confirm, which version of Light Table were you testing this with?

**Comment by MarcusE1W** [comment]
I have used the linux 64bit package 0.8.1 from the website.
The test was for both images like this:
1. download ubuntu image (14.4 first, then 16.10)
2.  run image in virtualbox
3. download lighttable from lightttable.com
4. unpack package
5. start lighttable
6. use menu to open new window.
7. close the newly opened window
8. use menu to open new window.

for 14.4 step 8 caused the above mentioned error, for 16.10 I have not got this error and could open and close new windows as I like.
In my normal archlinux lighttable it works as well.

**Comment by sbauer322** [comment]
I'm inclined to agree with you that it is no longer happening. I was able to open and close additional Light Table windows without issue via Ubuntu 16.04 and LT 0.8.1. Based on the time stamp of when the issue was opened, this issue seems to have been occurring in either 0.8.0-alpha, or 0.7.2.

If anyone is able to reproduce this error in 0.8.1 or later then I am happy to reopen.

Thanks for testing this, @MarcusE1W - it is greatly appreciated!
