### ISSUE TITLE
LightTable fails to find iPython 4.0 on Mac

### ISSUE THREAD

**Issue by cmasseraf** [LightTable/LightTable#2018]
Hi,

I've been trying without success to get LightTable to find ipython on mac os. I'm currently running Anaconda.

Here are my observations:
- I've set [:app :lt.plugins.python/ipython-exe "/path/to/ipython"]
- I've set "export LT_IPYTHON_PATH=/path/to/ipython
- The python environment can find the IPython module

I've also tried debugging the Python plugin bug my lack of knowledge of Clojure didn't help me get any further than some debugging on ltmain.py which make it seem that startiPy is not being called but I cannot state it for sure.

**Comment by kenny-evitt** [comment]
@cmasseraf I'll try to reproduce this soonish. Thanks for reporting it!

**Comment by cldwalker** [comment]
Thanks for the report. This has been an ongoing issue for sometime and will be tracked in https://github.com/LightTable/Python/issues/35
