### ISSUE TITLE
Saving unsaved content

### ISSUE THREAD

**Issue by akshays04** [LightTable/LightTable#2020]
If the Machine turns off due to certain reasons, and the code inside light table is not saved, then that content is completely lost when we open the light table next time.

**Comment by kolya-ay** [comment]
This is duplicate feature request. Join the discussion on #1700 or #1222. Could be implemented as plugin though

**Comment by kenny-evitt** [comment]
@akshays04 What @kolya-ay wrote :smiley: 

But thanks for the report!
