### ISSUE TITLE
(Windows, 0.8-alpha) Console show error message that can't connect to figwheel

### ISSUE THREAD

**Issue by jbeja** [LightTable/LightTable#2023]
Starting a new Figwheel project and then pressing ``Ctr+Alt+Enter`` the console keep giving me this error, the editor seems to be connected but the messages keep appearing in a loop

```Figwheel: trying to open cljs reload socket
WebSocket connection to 'ws://localhost:3449/figwheel-ws/dev' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED: file:///C:/Users/Jesus/clojure/ree/resources/public/js/compiled/out/figwheel/client/socket.js
utils.js[94]:	
Figwheel: trying to open cljs reload socket```

**Comment by kenny-evitt** [comment]
@jbeja Would you share an example project for which I could try to reproduce this?

**Comment by jbeja** [comment]
I am test it with a very new figwheel project, this is the output of the console:

```
bootstrap.js[17085]: hello world
bootstrap.js[17085]: :TEST

Failed to load resource: net::ERR_FILE_NOT_FOUND: file:///C:/Users/Jesus/clojure/cado/resources/public/js/compiled/cado.js

Uncaught ReferenceError: cljs is not defined
browserInjection.js [48]	anonymous
events.js [77]	emitOne
events.js [169]	emit
```

Lightable is installed on my $Home folder

**Comment by cldwalker** [comment]
> I test it with a new figwheel project

Is this `lein new figwheel PROJ`?

@jbeja Have you compiled your project's clojurescript? If not I'd recommend reading the Clojure plugin README, especially the [workflow section](https://github.com/LightTable/Clojure#clojurescript-workflows). As for the figwheel errors you're seeing, that's what I would expect if you just did an eval. LT's repl has no knowledge of figwheel and figwheel [instructs you to start their repl from the commandline](https://github.com/bhauman/lein-figwheel#try-figwheel). I haven't tried using figwheel's repl with LT. You may want to ask in their mailing list

**Comment by jbeja** [comment]
I test it with a minimal clojurescript project ````lein new mies <project>```, I got the same errors.

**Comment by cldwalker** [comment]
Please read my last comment and the suggested readme

**Comment by cldwalker** [comment]
Without any explanation of what was done from the readme this isn't reproducible. Closing if we don't hear back in a few days

**Comment by jbeja** [comment]
I try to connect using the add connection command and it worked, for some reason in the last version I just have  press ```alt+enter``` worked like charm. Anyways, I'm closing this.
