### ISSUE TITLE
NOTHING whatsoever working in 0.8.0-alpha-windows release on 64-bit Windows-10

### ISSUE THREAD

**Issue by crunch3** [LightTable/LightTable#2024]
I have no prior experience with LightTable, so maybe this is the worst case of pilot error ever, but when I run the executable (on 64-bit Windows-10) in either user or administrator mode, I get a window with Light Table in large white letters on a gray background, but not even the window close box works.

**Comment by cldwalker** [comment]
That sounds like the correct startup screen. What specifically went wrong? Did you try opening a file? Does the menu work? If so, go to View > Commands and then  execute the `Console: Toggle console` command. This should open your console. Please copy the error output and paste it here

**Comment by crunch3** [comment]
if it's a startup screen, that's all I'm getting - no menus, so no mechanism with which to open a file.  Also no menu means no View Commands to get a console up, so no output to share.

**Comment by kenny-evitt** [comment]
@crunch3 Can you try opening the command pane via <kbd>Ctrl</kbd>+<kbd>Space</kbd>?

**Comment by cldwalker** [comment]
Closing as we have not heard back on this. Happy to reopen if you respond or we get more details
