### ISSUE TITLE
Using LightTable as a headless browser

### ISSUE THREAD

**Issue by divs1210** [LightTable/LightTable#2033]
Hey guys.

I was wondering if there is a plugin that would allow me to place my cursor over some symbol and press `Ctrl+E` to fetch and display all examples from [clojuredocs](https://clojuredocs.org/clojure.core/conj) inline.

ClojureDocs works on react so in order to parse it I need to run js and load the html using selenium or something. But LightTable is already a JS engine so is there any way to dynamically load html using LightTable?

**Comment by cldwalker** [comment]
> I was wondering if there is a plugin that would allow me to place my cursor over some symbol and press Ctrl+E to fetch and display all examples from clojuredocs inline.

Hey. I maintain [Sancho](https://github.com/cldwalker/Sancho), which provides commands to access [grimoire docs (clojuredocs examples)](https://github.com/clojure-grimoire/grimoire) and crossclj usages for symbol under cursor. My plugin was actually out of date and just fixed it. Cheers
