### ISSUE TITLE
Latest version is full of bugs and I was unable to find a compiled old version

### ISSUE THREAD

**Issue by flavio20002** [LightTable/LightTable#2034]
The title of the issue speaks for itself. If you release an alpha version, you must allow the user to download an old stable version.

**Comment by cldwalker** [comment]
Here are the [old versions](https://github.com/LightTable/lighttable.com/commit/cf390b35631ed3346e766032054061f61ffad668). I don't recommend using it as it probably has more bugs. When encountering bugs, we need [reproducible bug reports](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md#bugs)

**Comment by flavio20002** [comment]
I'm preparing bug reports...on my computer the last version crashes very often and lag a lot when typing. I had to call a friend to make him send me the old version, because i had to work on a project. So I opened the issue.
