### ISSUE TITLE
(Windows, 0.8-alpha, Spanish LatinAmerica keyboard layout) pressing quote (') write square brackets

### ISSUE THREAD

**Issue by jbeja** [LightTable/LightTable#2039]
It only happen when I have ``` [:app :lt.objs.settings/pair-keymap-diffs]``` added on the user behaviors.

**Comment by kolya-ay** [comment]
This is well known [issue with international keyboard layouts](https://github.com/LightTable/LightTable/issues/620#issuecomment-59621776). At the time being you could ether have enabled parenthesis autocompletion or type `'` on Spanish keyboards. Support for the both is tracked in #1807.

**Comment by cldwalker** [comment]
We were tracking it in #1807 but it's now tracked in #2003. Current status in [this comment](https://github.com/LightTable/LightTable/issues/2003#issuecomment-154335278)
