### ISSUE TITLE
linux 32-bit download link contains 64-bit electron binary

### ISSUE THREAD

**Issue by ajhutton** [LightTable/LightTable#2040]
./LightTable
-bash: ./LightTable: cannot execute binary file: Exec format error
./light: line 37: /home/alex/Downloads/lighttable-0.8.0-alpha-linux/LightTable: cannot execute binary file: Exec format error

$ ld LightTable
ld: i386:x86-64 architecture of input file `LightTable' is incompatible with i386 output

File downloaded from 32-bit link: 05498a0a3ef67a2f83a3c7fde1a978ba6c559bc7fdebc183475ad99bf919cd75  lighttable-0.8.0-alpha-linux.tar.gz

File downloaded from 64-bit link:
05498a0a3ef67a2f83a3c7fde1a978ba6c559bc7fdebc183475ad99bf919cd75  lighttable-0.8.0-alpha-linux (1).tar.gz

(identical)

**Comment by cldwalker** [comment]
Hi. This came up [recently on the mailing list](https://groups.google.com/forum/#!topic/light-table-discussion/8UmuwwZ-YlM). We didn't have a 32-bit machine so we mistakenly built it on a 64-bit. If we need to build on a 32bit machine to support 32bit linux the core team will have to decide if we want to support it going forward. Our [QA Checklist](https://github.com/LightTable/LightTable/wiki/QA-Checklist) is already fairly long to do for 3 platforms. Since none of us use this platform or have a machine for it, for every release we would need you or another 32bit linux user to QA if we are to support it.  In the meantime, [here are instructions](https://github.com/LightTable/LightTable/blob/master/doc/developer-install.md) to build LightTable from source. I'll leave this open until the core team decides what to do about this. Cheers

**Comment by Tanami** [comment]
Well, looks like I'm going back to Geany! :(

**Comment by kenny-evitt** [comment]
@ajhutton @Tanami Building from source is pretty easy. If one – or both – of you would be willing to QA release builds we could 'officially' support the 32-bit version too. As-is, I could QA the 32-bit builds but I wouldn't be really using it so 'officially' supporting it would be a little more than I feel comfortable promising.

**Comment by cldwalker** [comment]
@ajhutton We decided to not support 32-bit as a download as we don't actively develop on it and don't have the bandwidth to support it. Fwiw, Atom has a much larger core team and [they don't provide an official download for this platform](https://github.com/atom/atom/releases). In the meantime, we're happy to ensure the build script still works for 32-bit. We'll be taking down the download link soon and we'll close this issue when we announce this for the next release.

**Comment by edison23** [comment]
So why do you have 32bit linux build download link on the webpage when you know it doesnt work? (and yes, it doesnt)

**Comment by kenny-evitt** [comment]
@edison23 Because we haven't removed the link yet. Feel free to create a pull request; the website repo is also on GitHub.

**Comment by edison23** [comment]
yea, i dont even know exactly how to do that, TBH :) so i'll leave that to you guys

**Comment by kenny-evitt** [comment]
@edison23 Please be more careful in the future making pointed comments. Everyone involved in this project is a volunteer and we've all had to figure out how to contribute. If you're not willing to help yourself, the least you can do is comment politely.

As to how to contribute changes to any of the Light Table projects, the README for each project repo usually indicates what you need to do. [For the website, you basically just need to have Ruby installed and install two Ruby gems (packages)](https://github.com/LightTable/lighttable.com/blob/gh-pages/README.md) [[and possibly two others](https://github.com/LightTable/lighttable.com/issues/8)]. Information about HTML and CSS is extremely widespread. And if you're having trouble, you can ask on [the Gitter channel](https://gitter.im/LightTable/LightTable) or on [the Google Groups group](groups.google.com/forum/#!forum/light-table-discussion).

**Comment by edison23** [comment]
@kenny-evitt ok, I'm sorry, it wasnt meant to be pointed (I fail to see it that way even now, but that doesnt matter). As for the contributing, I'll think about it after I tried the software ;)

**Comment by kenny-evitt** [comment]
@edison23 Thanks

**Comment by kenny-evitt** [comment]
The 32-bit download for Linux has been removed from the LT home page. We can add it back when someone commits to providing minimal support (e.g. QA-ing release builds) for that platform.
