### ISSUE TITLE
Plugin Manager - False "Last version"

### ISSUE THREAD

**Issue by Armaklan** [LightTable/LightTable#2043]
There is a sort of problem in the version numbers. Sometimes the proposed version is not the latest version.

Exemple with TernJs.

Last version in LightTable : 0.1.9
Real last version : 0.1.10

Metadata repository is correct.

**Comment by kenny-evitt** [comment]
@Armaklan Thanks for the report. This should be fixed by my PR. Hopefully it will be included in the next release.

**Comment by kenny-evitt** [comment]
@Armaklan This should be fixed on *master*.
