### ISSUE TITLE
How do I reference a file in a file so it uses autocomplete?

### ISSUE THREAD

**Issue by codeliger** [LightTable/LightTable#2045]
I am trying to evaluate a basic javascript file but I use jquery inside of the file so it results in an error.

For example Microsoft VS Code uses this `/// <reference path="../folder/filename.js"/>`

**Comment by kenny-evitt** [comment]
There's nothing in the core Light Table app to do this. You'll need to find a plugin that does this. [The TernJS plugin](https://github.com/mortalapeman/LT-TernJS) is the best candidate of which I'm aware.
