### ISSUE TITLE
Cannot start LightTable due to an invalid identifier

### ISSUE THREAD

**Issue by johanhaleby** [LightTable/LightTable#2047]
When I try to start LightTable immediately run into this error:

```java
Error: Error: Command failed: /usr/local/etc/bash_completion.d/docker-compose: line 32: `__docker-compose_compose_file': not a valid identifier
is not ISeqable
    at Error (<anonymous>)
    at cljs.core.seq (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2833:11)
    at cljs.core.empty_QMARK_ (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:3693:62)
    at eval (file:///Applications/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:31483:32)
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.eval (child_process.js:950:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.eval [as close] (net.js:466:12)
```

And I cannot seem to do anything in the IDE (for example opening an instarepl etc).

**Comment by cldwalker** [comment]
Seeing node-webkit paths in your stacktrace, you're running an older version of LightTable. Please download the latest 0.8.0-alpha and see if there are any issues. If so, please provide [reproducible steps](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md#bugs) e.g. a Dockerfile

**Comment by johanhaleby** [comment]
I've upgraded to 0.8.0-alpha but it has the same problem.

**Steps to reproduce the bug**:

> Your operating system, LT and relevant plugin versions.
Mac OSX El Capitan (10.11.1), Light Table 0.8.0-alpha, no plugins

> Relevant configuration in your user.keymap and user.behaviors.

user.keymap:
```clojure
[
 [:editor "alt-w" :editor.watch.watch-selection]
 [:editor "alt-shift-w" :editor.watch.unwatch]

 ;; To subtract a binding, prefix the key with '-'  e.g.
 ;;  [:app "-ctrl-shift-d" :docs.search.show]
]
```

user.behavior:

```clojure
[
 ;; The app tag is kind of like global scope. You assign behaviors that affect
 ;; all of Light Table to it.
 [:app :lt.objs.style/set-skin "dark"]
 [:app :lt.objs.plugins/load-js "user_compiled.js"]

 ;; The editor tag is applied to all editors
 [:editor :lt.objs.editor/no-wrap]
 [:editor :lt.objs.style/set-theme "default"]

 ;; Here we can add behaviors to just clojure editors
 [:editor.clojure :lt.plugins.clojure/print-length 1000]

 ;; Behaviors specific to a user-defined object
 [:user.hello :lt.plugins.user/on-close-destroy]

 ;; To subtract a behavior, prefix the name with '-' e.g.
 ;;  [:app :-lt.objs.intro/show-intro]
]
```
> Error messages you see in your console. 

```clojure
Error: Error: Command failed: /bin/sh -c PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH && source /Users/johan/.profile && source /Users/johan/.bash_profile && echo $PATH
/usr/local/etc/bash_completion.d/docker-machine-prompt.bash: line 47: `__docker-machine-ps1': not a valid identifier
is not ISeqable
    at Error (native)
    at cljs.core.seq (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:2833:70)
    at cljs.core.empty_QMARK_ (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:3693:62)
    at file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:31720:32
    at ChildProcess.exithandler (child_process.js:216:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:764:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
```

Note that this error is a bit different from the one I presented earlier. The reason is that I upgraded `docker-compose` to 1.5.1 and it seems that it has a newer bash completion file that didn't cause the error in LT. The error now shows up for `docker-machine` instead (v 0.5.0 (latest version)). 

I hope you should be able to reproduce it if you have `brew` installed and just install `docker-compose` and then try to start LT.

**Comment by kenny-evitt** [comment]
@johanhaleby I think this going to be tricky to resolve because I suspect the problem is that Node is a lot more strict about shell commands – commands with dashes in their name are considered invalid by Node, because (maybe?) they are invalid (technically?), but most actual shells accept them anyways. Others have had problems with 'bash-it' before for the same reason.

**Comment by johanhaleby** [comment]
Ok that's really unfortunate :/ But I find it really strange that it doesn't complain for `docker-compose` anymore. There still many functions using underscore in `/usr/local/etc/bash_completion.d/docker-compose`. For example:

```bash
__docker_compose_compose_file() {
	local file
	for file in docker-compose.y{,a}ml fig.y{,a}ml ; do
		[ -e $file ] && {
			echo $file
			return
		}
	done
	echo docker-compose.yml
}
```

**Comment by kenny-evitt** [comment]
@johanhaleby I think the problem isn't dashes anywhere but in names specifically. I think underscores are fine generally, hence why the version of the function you reference in the newer *docker-compose* doesn't also cause an error – it was renamed to use underscores instead. The most recent error was complaining about the identifier `__docker-machine-ps1`.

**Comment by johanhaleby** [comment]
Thanks. Why is node taking this approach when it is indeed a valid identifier in bash? Is light table still using node webkit it version 0.8.0? (I'm thinking of filing a bug at docker-machine).

**Comment by johanhaleby** [comment]
It actually seems like `docker-machine` has already <a href="https://github.com/docker/machine/commit/5707b38a9ef35a21f55b1390f4ac476c3d4b84e1">fixed</a> this (but it's not yet released). If I manually changed from `-` to `_` in the `docker-machine` bash completion files I can start light table without any problems. So I'm going to close this issue. Thanks for your support.

**Comment by kenny-evitt** [comment]
@johanhaleby The latest LT release is running Electron not node-webkit but I'm not really sure why Node is more strict about identifiers than actual shells. I'm glad you found a workaround, and an upstream fix; thanks!
