### ISSUE TITLE
Create parinfer plugin for Clojure and ClojureScript

### ISSUE THREAD

**Issue by yogthos** [LightTable/LightTable#2049]
https://github.com/shaunlebron/parinfer#using-as-a-library

**Comment by kenny-evitt** [comment]
[Oh yeah!](https://github.com/shaunlebron/parinfer/issues/35)

**Comment by rundis** [comment]
I almost jumped on this just a day or two after it was announced. However I managed to hold back. It would be great if someone else from the community stepped up. I'd be happy to help out anyone willing to give it a go :-)

**Comment by cldwalker** [comment]
Bad news is a LightTable plugin can't rely on the published library because it uses .cljc and we are running such an old version of Clojurescript - #1973. Good news is that 0.1.0 doesn't use any reader conditionals so we could just use a forked version that renames .cljc to .clj/cljs. We could suggest upstream that they use .clj but I'm assuming they will eventually want to take advantage of .cljc and don't want to be held back by catering to ancient versions of Clojurescript

**Comment by shaunlebron** [comment]
Let me know if I can help out with this.  I've written more step-by-step docs on how to get this working:
https://github.com/shaunlebron/parinfer/tree/master/lib

**Comment by kenny-evitt** [comment]
@shaunlebron I think any help would be greatly appreciated. But I think we're going to need to fork your code because we're still stuck on a (very) old version of ClojureScript.

**Comment by mauricioszabo** [comment]
I've started a simple plugin in LightTable, based on https://github.com/LightTable/Declassifier.

It's hosted on https://github.com/mauricioszabo/lt_parinfer. The plugin is usable right now, it uses the node.js' version of parinfer. Some simple problems that propably will appear:

1. The plugin re-evaluates the whole text, so it might be slow with huge files
1. I didn't find any good documentation on how to work with plugins, so for now we're not able to deactivate the plugin
1. It just works in "indent-mode", there's no "paren-mode" yet
1. When installing it, it gives the message "Some plugin dependencies are missing". I wasn't able to discover what's wrong, or even if it's a bug in my plugin or in LightTable

The good news is that it works, so maybe some pull requests will be able to remove these problems above.

A little demo of me using it: 
![lt](https://cloud.githubusercontent.com/assets/138037/13033544/8c75d31e-d301-11e5-9f72-4def5e1ff12e.gif)

**Comment by shaunlebron** [comment]
Great work @mauricioszabo!

For some background, parinfer was rewritten in JS, so this makes the cljs-compatibility blocker go away.

To address the points made:

1. You may notice slowness (50ms delay) at around 5k-6k lines.  Anything lower than 3k will be fine.
2. (idk)
3. Cool, this is fine early on, but it's critical to run Paren Mode on a file before it's opened.  This prevents Indent Mode from corrupting your file.
4. (idk)

**Comment by ohAitch** [comment]
I'm guessing caching per-line paren state the way codemirror does for
syntax highlighting is also a non-beta function? :P

**Comment by rundis** [comment]
I'm closing this as there now is a plugin.

**Comment by yogthos** [comment]
👍
