### ISSUE TITLE
Release 0.8.0

### ISSUE THREAD

**Issue by kenny-evitt** [LightTable/LightTable#2064]
- [x] Version updates
    - [x] Update deploy/core/package.json, deploy/core/version.json and project.clj to 0.X.X
    - [x] Make sure electron version is up to date in version.json
    - [x] Make sure plugin versions in script/build-app.sh are latest versions
 - [x] Add changelog for release to CHANGELOG.md
 - [x] Each core developer should QA at least one OS using the [QA checklist](https://github.com/LightTable/LightTable/wiki/QA-Checklist)
    - [x] @cldwalker on Mac OS
    - [x] @rundis on Linux
    - [x] @kenny-evitt on Windows
 - [x] When QA passes freeze master
 - [x] Add changelog to [GH release draft](https://github.com/LightTable/LightTable/releases/new)
 - [x] Upload binaries from `script/build.sh --release` to draft. Don't forget to click *Save draft*!
 - [x] Publish GH release which creates git tag and notifies users about new release
 - [x] Merge README PR #2070
 - [x] Merge blog post - https://github.com/LightTable/lighttable.com/pull/10
 - [x] Merge download links and instructions - https://github.com/LightTable/lighttable.com/pull/12
      - [x] Update lighttable.com to have install instructions for osx (the osx app isn't official for now)
 - [x] Mailing list announcement - [example email](https://gist.github.com/cldwalker/3d67153fe1eade2ae3cf) @rundis
 - [x] Build latest api documentation with `script/build-api-docs.sh`

**Comment by kenny-evitt** [comment]
Besides the Emacs plugin, the latest source version looks good on Windows 7.

**Comment by cldwalker** [comment]
@kenny-evitt Could you elaborate what's wrong with Emacs on Windows? Anything that's blocking?

**Comment by kenny-evitt** [comment]
@cldwalker Sorry for not being clear. Nothing's wrong with Emacs on Windows, AFAIK – I just didn't test it.

**Comment by kenny-evitt** [comment]
@cldwalker @rundis #2067 is the only issue I ran into QA-ing on Windows. I don't think it should hold up the release.

**Comment by cldwalker** [comment]
QA passed fine for osx. Unlike the last release, we will need to add a changelog to this release before the freeze on master as the user can see the changelog from `Light Table version` command. Adding a PR for it soon

**Comment by cldwalker** [comment]
I've created a new draft with the changelog filled in. Once the changelog #2068 PR is in, we can each upload our OS build to it.

Do we want to plan on meeting up wednesday or thursday evening EST? I can get off work 5pm EST which would be 11pm @rundis time. Should take 30m. @rundis if it's too late for you I'm open to other times but it may be hard to coordinate with 9am-5pm EST filled up with work

**Comment by kenny-evitt** [comment]
Either Wednesday or Thursday is fine. But if 5p EDT is too late for you @rundis, maybe @cldwalker can take some time during lunch, say 1p EDT – so 7p your time.

**Comment by rundis** [comment]
@cldwalker @kenny-evitt  5pm EST wednesday or thursday is fine by me.

**Comment by cldwalker** [comment]
I'm leaning toward 5pm EST Thursday. @kenny-evitt Work for you?

**Comment by kenny-evitt** [comment]
5p EST on Thursday works for me.

**Comment by salmazov** [comment]
Why have you choose Electron instead of NW.js?

**Comment by kenny-evitt** [comment]
@salmazov [I answered your question the first time you asked it.](https://github.com/LightTable/LightTable/pull/2068#issuecomment-162858250)

**Comment by cldwalker** [comment]
Creating a github version of this screenshot so we don't have to rely on dropbox: <img width="413" alt="screenshot 2015-10-10 11 23 21" src="https://cloud.githubusercontent.com/assets/11994/11731454/85181e90-9f69-11e5-9c65-f6aa4228005c.png">

**Comment by cldwalker** [comment]
Done! :tada:

**Comment by rundis** [comment]
:+1:

**Comment by kenny-evitt** [comment]
Yay :fireworks:
