### ISSUE TITLE
Recal plugin does not work with lt 0.8 worked wiht 0.7

### ISSUE THREAD

**Issue by NoWayHoze** [LightTable/LightTable#2074]
not happy here.

**Comment by cldwalker** [comment]
This plugin isn't a part of LT. Please open your issue with the [Recall plugin](https://github.com/joshuafcole/recall/issues). Giving specifics to the author would be helpful. I use [Reminisce](https://github.com/JuliaIDE/Reminisce) which is known to work with 0.8.0
