### ISSUE TITLE
Running Node.js app ES6

### ISSUE THREAD

**Issue by robjens** [LightTable/LightTable#2077]
Using local node `4.2.2`, file over sshfs (mounted directory).
At behaviors, mostly, I've tried combinations of:

```clojure
 [:nodejs.client :lt.plugins.js.node/node-start-options "--harmony --use_strict --harmony_rest_parameters --harmony_destructuring"]
```

Without it, it complains about a `let foo = 1, bar = 2` Block declaration not being allowed outside `strict mode`, however, I have it defined at top of the file, and also tried wrapping it in a IIFE (`(() => { ...} ())`) with its own `use strict` but won't work either. When I use the behavioral flag, the javascript plugin starts complaining and the connection is immediately disconnected:

```
schema.js[stderr]:
/home/susy/.config/LightTable/plugins/Javascript/node/ltnodeclient.js:97
      prevModule = currentModule;
                 ^

ReferenceError: prevModule is not defined
    at sbRequire (/home/susy/.config/LightTable/plugins/Javascript/node/ltnodeclient.js:97:18)
    at init (/home/susy/.config/LightTable/plugins/Javascript/node/ltnodeclient.js:121:3)
    at Socket.<anonymous> (/home/susy/.config/LightTable/plugins/Javascript/node/ltnodeclient.js:20:5)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1048:10)
```

It seems to me, the ltnodeclient itself is being interpreted under strict mode, however, on those locations it uses undeclared variables it seems.

Anything I'm doing wrong? How well is this supported even? I'd be curious to learn from anyone else (having) use(d|ing) ES6 in InstaREPL?

**Comment by kenny-evitt** [comment]
@robjens Nothing seems obviously wrong but I don't use Node.js for any projects currently anyways.

What version of LT are you running? What OS and version is your computer running? What steps can I take to reproduce? Would you share code I can use to reproduce this?

**Comment by robjens** [comment]
@kenny-evitt 

Should be quite simple to reproduce. I'm using ArchLinux (stock kernel 4.2.5-1), LT is latest 0.8. I cleared the Javascript plugin in `~/.config/Lighttable/plugins/Javascript` and git cloned the latest of that too. LT is pretty much pristine, as last time update didn't really work for me, I did a manual download from the website. I cleared my `~/.config/LightTable/Cache` to be sure it wasn't running any interference. 

Now I'm simply doing the following:
1. open lighttable
2. open a connection panel
3. select a node.js connection (dialog opens)
4. select a file from a otherwise empty folder (I'm ensuring it has a `node_modules/` folder and `package.json` file)

File content is merely `var x = 1;` (I tried with `'use strict';` first but that didn't work). This has the same effect as strict or not. Error message is the same:

```
The node process exited.

The node process you were connected to suddenly quit. Check the console for more information.
```
In the LT dialog window, the console shows:

```
foo.js[stderr]:
/home/susy/.config/LightTable/plugins/Javascript/node/ltnodeclient.js:97
      prevModule = currentModule;
                 ^

ReferenceError: prevModule is not defined
    at sbRequire (/home/susy/.config/LightTable/plugins/Javascript/node/ltnodeclient.js:97:18)
    at init (/home/susy/.config/LightTable/plugins/Javascript/node/ltnodeclient.js:121:3)
    at Socket.<anonymous> (/home/susy/.config/LightTable/plugins/Javascript/node/ltnodeclient.js:20:5)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1048:10)
```

This, like I said, a master clone from the Lighttable/Javascript plugin. I have no problem running Node.js programs otherwise. But I am using `node 4.2.3 LTS`, could that be the cause?

**Comment by robjens** [comment]
Oh now that's odd. I completely removed LT to try a development build, everything is fine but running lighttable (either command line executable or as desktop app) fails to get beyond the splash screen. None of the keys work nor do I see the top menu bar so I can't open a dev-tools window (F12 doesn't work anymore). I have to use a SIGINT to kill the process. I need to correct one thing, not `4.2.3` but `4.2.2` is the node version, which I doubt matters.

Anyway this is very likely some deficiency on my side here, since it won't run anymore, I'm going to try some variations of the prerequisites. For one, the node 4.2.2 are precompiled binaries I think, so ima build 4.2.3 from source. Also download prebuilt LT to see if that makes a difference.

Process of elimination as always =/ Thanks anyway but I begin to suspect some other cause other than LT. I see there isn't any `--debug` switch to the `light` executable... alas. Any secrets or tricks to debugging any of these things prior/during launch might be something I could use.

**Comment by robjens** [comment]
ok so the prebuilt download at least surpasses the splash window, running that as normal user I get 
`ln: failed to create symbolic link ‘/opt/LightTable/libudev.so.0’: Permission denied` which is ok, so I escalated  `sudo /opt/LightTable/light` and no warning. Now I close it, and then try to run it again as normal user `ln: cannot remove ‘/opt/LightTable/libudev.so.0’: Permission denied`

This is a bit odd. Does it really need to remove, then re-add the symbolic link? I guess I can chown the entire folder, it's not that .. just something I don't see often. Often enough I have root own the files and folders, and can have users execute the program without a fuss. If stuff needs to be written to location, use `/tmp` or `~/.config/LightTable/sumthin` right? Or do we expect people to have `/opt` folders (or `/usr` for that matter) owned by normal user, this is not FSH common practice I think.

**Comment by robjens** [comment]
I see the 'stuck on logo' has a ticket already. Using the newly downloaded, prebuilt LT I can at least run Javascript files again. Node itself is borked though (first hit)

![image](https://cloud.githubusercontent.com/assets/11848802/11920648/5032b878-a76d-11e5-8540-775d8e2c6418.png)

The second one, I actually evalled earlier, which tells me although node 4.2.3 accepts `let` the way it is, the scoping/vm or whatever LT uses that's different (probably the Javascript plugin) doesn't aka "it's not supported yet" is my conclusion and some stuff is buggy. Since this remains a tad vague, I'll close this, sit on it and wait...

**Comment by bugs181** [comment]
I'd kindly like you to reopen this issue as I'm having it with ECMAScript 2015 code here as well.

Very simply, I can't use the `let` keyword at all, even in a new file with `use strict` at the beginning.

**Comment by deinspanjer** [comment]
Same here.  I was really hoping to be able to use instarepl to evaluate the result of some es6 javascript, but can't get LightTable going with it. :/

**Comment by sbauer322** [comment]
This seems likely to be an issue with the Javascript plugin... Unfortunately, the plugin itself is currently in need of a maintainer, thus the backlog of JS issues... but pull requests are welcomed for it.

There is also issue https://github.com/LightTable/LightTable/issues/2134 which seems to relate to the topic at hand of running ES6.
