### ISSUE TITLE
Light table stuck on logo 

### ISSUE THREAD

**Issue by justintaft** [LightTable/LightTable#2079]
When booting up, "Light Table" was displayed,  and then got stuck. 

After opening the developer tools, an error saying bootstrap.js was not found. I had to run "lein clsjbuild" to get this file to build manually.

Running script/build.sh did not fix this...

**Comment by kenny-evitt** [comment]
Were you running a source build? If so, I think there was a recent change that made the `lein cljsbuild` necessary.

**Comment by justintaft** [comment]
Ah, this still occurs.

https://github.com/LightTable/LightTable/blob/master/script/build.sh#L34

If file doesn't exist, rm error code is ```1``` so lein cljsbuild will never run

**Comment by cldwalker** [comment]
This has been fixed with https://github.com/LightTable/LightTable/commit/b3b7797c1a4c000993574b577c76361092f6f549
