### ISSUE TITLE
XFCE TopMenu doesn't work with LightTable

### ISSUE THREAD

**Issue by strangeattr** [LightTable/LightTable#2084]
TopMenu is an XFCE extension that offers functionality equivalent to Ubuntu Unity and Mac OS X displaying the active application menu bar at the top (or any else actually, this is configurable) edge of the screen rather than at the top edge of the application window. All (all I have seen) modern applications built with up-to-date versions of the GTK+ toolkit seem to be compatible with it OOTB, some (like Mozilla Firefox) require extensions of their own to support this. LightTable works just fine with the same functionality in Mac OS X (and, perhaps, in the original Ubuntu, but I had no opportunity to check) - this suggests that the modification required to introduce XFCE support is going to be rather humble. As far as I understand the technology [meant to be] behind this feature is what is called the dbusmenu protocol.

**Comment by cldwalker** [comment]
Hi. LightTable doesn't have any opinions baked into supporting programs like XCFE or TopMenu. For any menu functionality we rely on [electron](https://github.com/atom/electron). I'd recommend learning about electron and investigating if they support XCFE TopMenu. If they don't, this is isn't something we provide by default
