### ISSUE TITLE
Cannot toggle commands panel with 'Ctrl+space' in linux

### ISSUE THREAD

**Issue by ludbek** [LightTable/LightTable#2088]
I cannot toggle commands panel with 'Ctrl+space' in linux. I am using Mint.

**Comment by rundis** [comment]
Not working as in nothing happening I suppose ?

Have you checked that it is Light Table who's to blame ? Perhaps this shortcut is already bound at "os" level (like in this case http://stackoverflow.com/questions/32393497/how-to-fix-ctrl-space-shortcut-for-my-ide-using-linux-mint).

**Comment by cldwalker** [comment]
Closing as this appears to be an OS issue. If not, I can reopen once you've verified you can trigger ctrl-space for another application
