### ISSUE TITLE
Allow changing character encoding

### ISSUE THREAD

**Issue by 39bit** [LightTable/LightTable#2089]
Similar to how other editors such as Notepad++, Light Table should allow changing the encoding of the file open at the moment, and conversion between them. If possible, the default encoding could also be set for all files or per-extension (or even per-language).

Some good encodings to support would be at least UTF-8 (this is probably the current global encoding), UTF-8 + BOM, ASCII, WIndows-1252, ISO 8859-1/15, UTF-16LE/BE, and possibly some local encodings as well.

**Comment by kenny-evitt** [comment]
We're open to accepting pull requests with any core changes required, but this would be best implemented as a plugin.

This is already on [the feature wishlist](https://github.com/LightTable/LightTable/wiki/Feature-wishlist). See #2013 for an earlier issue for the same request too.
