### ISSUE TITLE
Instant evaluation is confused about execution context and breaks save option

### ISSUE THREAD

**Issue by robjens** [LightTable/LightTable#2095]
I've had this problem a few times before, I thought I might had opened a ticket for it earlier but seems like I haven't, nor has someone else, that I can see at least.

The problem is that at instant evaluation of a file, light table seems to think the file below needs to run as CLJS. I have no idea how but this should be reproducible as I have a pristine stock LT (precompiled binary) and pristine `~/.config/LightTable`.

![image](https://cloud.githubusercontent.com/assets/11848802/12104039/8923d35a-b33f-11e5-9192-73d5bf6dd371.png)

Notice the file even has a `.clj` extension but somehow it worked it out to be a CLJS file. This, I would assume as a result, also breaks the option to *save a file*.

**Comment by robjens** [comment]
Note that this may be a result from the fact that there isn't a project.clj file present with this file. At least I recall instances where this was the case in the past, I'm not really sure how this currently stands but I'm correct to presume a `.clj` file would make any assumption the editor had about the type of file, exclude it from being run in the first place. E.g. a file with `.py` extension should never be able to run under a Clojure InstaREPL (even not possible) so same case here. I would assume file type to be a major indicator here, also coming from the fact that I cannot do a "Make this current editor a InstaREPL" without first setting the correct file type *first* and then execute that command. So it seems there is a check on that, but missing here in the context of trying to evaluate the content of a single file.

**Comment by robjens** [comment]
And now I'm getting confused. Is this the Clojure plugin 0.3.0 release at work here? Since InstaREPL is completely gone now, all that is left is "Evaluate editor contents". 

![image](https://cloud.githubusercontent.com/assets/11848802/12104446/5a56cf38-b343-11e5-95b3-7a6e867836fb.png)

![image](https://cloud.githubusercontent.com/assets/11848802/12104453/6e0e0d52-b343-11e5-9596-050353f44ed4.png)

I don't think I have any way to execute that file with instant evaluation anymore? Or none I can think of anyway.

**Comment by cldwalker** [comment]
Hi. In case you haven't [seen the announcement](https://groups.google.com/forum/#!topic/light-table-discussion/jN40ZB0g3tc), the instarepl is its own plugin and is seeking a maintainer as none of the core team uses it for work. As explained in the plugin's [readme](https://github.com/LightTable/ClojureInstarepl#description), it's not recommended to use the instarepl except for trivial cases. If your project is using a project.clj, I'd highly recommend using the inline repl e.g. `Ctrl-Enter`. If you're still interested in using the instarepl, make sure to upgrade the Clojure plugin, install the ClojureInstarepl plugin and [open an issue there](https://github.com/LightTable/ClojureInstarepl/issues). 

> I have no idea how but this should be reproducible

For starters, make a bulleted list explaining everything you did to get to a failure point. For it to be reproducible you need to provide your project.clj

**Comment by robjens** [comment]
Ah, sorry for the trouble. Would have guessed it would boil down to this at some point. Thanks.
