### ISSUE TITLE
`span.cm-variable` not setting color on OSX

### ISSUE THREAD

**Issue by zachstone** [LightTable/LightTable#2100]
This line in particular `.cm-s-kudamono span.cm-variable {color: #6796DB;}` from the Kudamono Theme doesn't change the color in my Light Table on OSX. I have tried other themes, but they seem to suffer the same issue. Wondering if others are experiencing this.

I am running Light Table 0.8.0 on both machines.

Kudamono Theme on Windows 10
![colored](https://cloud.githubusercontent.com/assets/5137257/12186953/7e056ab4-b575-11e5-8d69-f37d0cbb1c75.png)

Kudamono Theme on OSX Yosemite (bigger because of retina display)
![uncolored](https://cloud.githubusercontent.com/assets/5137257/12186955/7f9e49ea-b575-11e5-8c12-2b01a54765ac.png)

**Comment by kenny-evitt** [comment]
@zachstone Would you check the CSS in the Dev Inspector in Light Table? Maybe there's a default CSS rule that overrides that for Mac.

**Comment by zachstone** [comment]
Well it could be that there's no span around what should be the `cm-variable`.

Windows
![css-win](https://cloud.githubusercontent.com/assets/5137257/12217908/1a08b854-b6dd-11e5-8aef-59aa7e75610e.png)

OSX
![css-mac](https://cloud.githubusercontent.com/assets/5137257/12217913/3bee4308-b6dd-11e5-91bc-fb4d71bda264.png)

**Comment by kenny-evitt** [comment]
@zachstone Indeed – good find!

**Comment by cldwalker** [comment]
@zachstone Nice find! This seems to be a bug from our [forked clojure mode](https://github.com/LightTable/Clojure/blob/master/codemirror/clojure-mode.js). On [this Clojure plugin branch I've switched to CodeMirror's clojure mode](https://github.com/LightTable/Clojure/tree/mode-working-with-cm-variable) and see the correct cm-variable span on osx. Until we fix this in the plugin you can run that branch for your Clojure plugin. https://github.com/LightTable/Clojure/issues/26 will be need to be done in order this to be fixed. It may be sometime before I get to that issue. If you're interested in doing the work, I'm happy to guide you

**Comment by cldwalker** [comment]
Just released 0.3.1 Clojure which has fixed this
