### ISSUE TITLE
Path + symlink issues on Linux

### ISSUE THREAD

**Issue by robjens** [LightTable/LightTable#2111]
Did a fresh download. Using ArchLinux, no `~/.config/LightTable` config so absolutely 100% pristine.

Starting using normal user in `/opt/LightTable` using `light`:

```
/opt/LightTable % ./light
ln: failed to create symbolic link ‘/opt/LightTable/libudev.so.0’: Permission denied
```

Ok, so I try to open using root: ` % sudo ./light`

![image](https://cloud.githubusercontent.com/assets/11848802/12324063/17ac9cc2-bab8-11e5-8c0f-c797f14684a7.png)

When trying to add a folder to the workspace, trying to open it will make it disappear.

This is a bit of a catch22, so I just assigned the entire LightTable folder to my own user instead. But this is a anti-pattern on Linux where it is common to have folders be owned by `root` and still remain operable.

**Comment by cldwalker** [comment]
Hi. I'm not sure what the actionable request is here. If you're having permissions with using the light script then it's reasonable for you to fix your permissions issues. Most of linux users are not experiencing permissions issues with symlinking. If you have specific advice on install documentation you think would help than I'm happy to consider it

**Comment by cldwalker** [comment]
Closing as I haven't heard back on documentation. I can reopen if you'd like to address the above

**Comment by robjens** [comment]
@cldwalker  Good call I guess, as there isn't really a proper solution as long as there is a symlink being created on executing the binary (in this case made for command line usage, may I add - light), you must run it as root when there are root permissions applied on the file. Simple as that. Normally, one has this process, if needed, take place during a formal installation procedure where rights are elevated during installation/config once, and then can be used by others as the symlink persists through reboots of the system etc. I guess since lighttable is pretty much standalone / drag-drop in folder and works, this would be the only thing that you'd be able to figure out soon enough when noticing it. No way around it really unless you'd run a setup script.
