### ISSUE TITLE
Cannot load any Clojure projects anymore

### ISSUE THREAD

**Issue by robjens** [LightTable/LightTable#2112]
Sorry to open up another ticket but in all fairness, it is not very clear at the moment what the status is concerning evaluation of projects. I understood from cldwalker that InstaREPL was taken out of the project but what I meant was not insta-instaEvaluation as in as-typed but only on evaluation of forms using `[Enter]`. Yet (pristine LT) even trying to normally connect to a Clojure project does not work anymore (for me) and I doubt this has anything to do with InstaREPL and if it *isn't* supported anymore, why am I still able to 'Connect to a Clojure project'- I mean what use is it? So I have to assume it is still intended to work... but it doesn't

![image](https://cloud.githubusercontent.com/assets/11848802/12324652/1be28ce4-babc-11e5-92c1-f7ab76cead95.png)

So really all I'm looking for is a straightforward answer: is it still possible to evaluate a project (Clojure) in LightTable or not? I've been unable to get stuff working as before and I really, really need to be able to evaluate certain expressions which otherwise would fail (obscure asynchronous Google Java API behavior where functions won't trigger when I run the project normally, but do when I manually evaluate them).

**Comment by robjens** [comment]
Well.... lein run is giving it too which makes it a total mystery but not the problem of LT so it seems.

**Comment by rundis** [comment]
Feel the pain. I'm not sure if it's related but heard clojars has had some downtime today.
Anyhow to be clear on clojure support:
Connectiong and evaling clojure (and ClojureScript), jump to def etc etc should all work as before. 

It's only the live continuous instarepl eval that has been separeted out to it's own project.

**Comment by robjens** [comment]
Yes indeed I've found what was the culprit although I do not remember what it was and should had closed this ticket. Thanks
