### ISSUE TITLE
editing dot file (hidden files)

### ISSUE THREAD

**Issue by stevebeisner** [LightTable/LightTable#2113]
There seems to be no way (through the GUI) to open dotfiles like "~/.bashrc".
They can be opened by starting lighttable through via the CLI/terminal, but
then they can't be added to the workspace, even after setting the file.ignore-pattern
appropriately in the user.behaviors file.

A better default would be "all files visible" in BOTH the workspace and in file
open dialogs... then allow options to suppress visibility selectively in both
places.

**Comment by cldwalker** [comment]
Hi. We don't have enough information to reproduce this. Could you specify what GUI you're using to open files? Is it through the navigator (cmd-o) or a file dialog (cmd-shift-o)? If the latter, on osx this is limited by osx, not by LT. What OS and LT version are you using? What file.ignore-pattern's did you try?

**Comment by stevebeisner** [comment]
OK... yes this is on OS-X. And yes, the OS-X file dialog does not normally show hidden (dot) files. However, for the benefit of other OS-X users: I've discovered that if you type SHFT-CMD-period (".") in the OS-X file dialog, it WILL show hidden files!

**Comment by cldwalker** [comment]
Glad you found a solution and thanks for sharing!
