### ISSUE TITLE
How to connect lighttable to Haskell

### ISSUE THREAD

**Issue by Jan129** [LightTable/LightTable#2120]
Hi,  

I would like to ry out the Haskell plugin of lighttable. However I can not connect to Haskell. Could someone give me the details how to do it?

Thx
Jan

**Comment by rundis** [comment]
Hi !

This is an external plugin, which I believe no one in the Light Table core team is using. Neither to we provide support for it.

You might want to try the [discussion forum](https://groups.google.com/forum/#!forum/light-table-discussion)  or maybe get in touch with the [plugin author](https://github.com/jetaggart/light-haskell). 

Having said that I'm seriously considering either taking over the plugin or write my own haskell plugin in the not to distant future. I'm keeping an eye out on the development of [haskell-ide-engine](https://github.com/haskell/haskell-ide-engine) project. Once that matures a little bit I'm probably going to give it a go. I'll post news in the discussion forum should I decide to take on the challenge !
