### ISSUE TITLE
Release 0.8.1

### ISSUE THREAD

**Issue by kenny-evitt** [LightTable/LightTable#2126]
- [x] Version updates
   - [x] Update *deploy/core/package.json*, *deploy/core/version.json* and *project.clj* (including the Codox `:source-uri` value) to 0.8.1
   - [x] Make sure electron version is up to date in *version.json*
   - [x] Make sure plugin versions in *script/build.sh* are latest versions
- [x] Add changelog for release to CHANGELOG.md
- [x] Each core developer should QA at least one OS using the [QA checklist](https://github.com/LightTable/LightTable/wiki/QA-Checklist)
   - [X] Kenny on Windows
   - [x] Magnus on Linux
   - [x] Gabriel on Mac OS
- [x] When QA passes freeze master
- [x] Add changelog to [GH release draft](https://github.com/LightTable/LightTable/releases/new)
- [x] Upload binaries from `script/build.sh --release` to draft. Don't forget to click *Save draft*!
   - [x] Generate an MD5 checksum for the binary package:
      - [x] Run `certUtil -hashfile lighttable-x.y.z-windows.zip MD5` on Windows.
      - [x] Run `openssl md5 lighttable-x.y.z-mac.tar.gz` on Mac OS X or Linux.
- [x] Publish GH release which creates git tag and notifies users about new release
- [x] Update download links on lighttable.com
- [x] Mailing list announcement - [example email](https://gist.github.com/cldwalker/3d67153fe1eade2ae3cf)
- [ ] Optional blog post if a major release
- [x] After release, [build api documentation](#build-api-documentation)

**Comment by cldwalker** [comment]
Done!
