### ISSUE TITLE
Writing ES2015+ JavaScript with a transpiler

### ISSUE THREAD

**Issue by mheiber** [LightTable/LightTable#2134]
Does LightTable support using ES2015+ and transpiling for the browser?

For example, if I'm using Webpack or Browserify with BabelJS for compiling ES2015+ to ES5, is there a way to get LightTable to understand the modern JavaScript and/or read the sourcemaps? I'd want to use features not yet available in Chrome, but still work with the live Browser view. JSX support would also be great.

**Comment by cldwalker** [comment]
Hi. LightTable's [JavaScript plugin](https://github.com/LightTable/Javascript) doesn't support transpiling but we are happy to take PRs for it. If you're interested [js eval starts here](https://github.com/LightTable/Javascript/blob/f9bec2496573ef66e396b1d3d6a48ccea57d0f08/src/lt/plugins/js.cljs#L139-L158). You can require in most npm packages e.g. [acorn required here](https://github.com/LightTable/Javascript/blob/f9bec2496573ef66e396b1d3d6a48ccea57d0f08/src/lt/plugins/js.cljs#L20). JSX support is something I've been meaning to look into and I'll leave this open to at least look into that. I know that CodeMirror has recently added a [jsx mode](http://codemirror.net/mode/jsx/index.html) but I don't know if that mode will be compatiable with our CM version (4.7)

**Comment by mheiber** [comment]
Is there a way to integrate with Babel and just use their source maps? That would provide a lot of flexibility and wouldn't require mucking around with acorn. I'm not sure if that makes sense or how source maps would fit in with the LightTable architecture.

**Comment by mheiber** [comment]
I'd really like to take a crack at this but have no idea where to start. It would be great to get some advice from package authors. Is this a good place to ask or is SO the right forum?

**Comment by rundis** [comment]
Maybe the [Discussion forum](https://groups.google.com/forum/#!forum/light-table-discussion)
or [gitter](https://gitter.im/LightTable/LightTable) would be better for getting assistance with plugin authoring etc.

**Comment by mheiber** [comment]
Thanks!

**Comment by sbauer322** [comment]
There is some relevant information and suggestions posted in this [discussion topic](https://groups.google.com/forum/#!topic/light-table-discussion/aickVtKDHcc).

**Comment by mheiber** [comment]
Thank you
