### ISSUE TITLE
Button - Exit Fullscreen is floated to left side

### ISSUE THREAD

**Issue by Trapets** [LightTable/LightTable#2135]
Hei!

In LT v0.8.1 and Win7, button with _class="button fullscreen"_ is floated to left side of first tabset.

![lt_bug_exitfulls](https://cloud.githubusercontent.com/assets/5584236/12643517/3ebaead6-c5c5-11e5-9b65-b50195eb40f1.png)

Trapets

**Comment by cldwalker** [comment]
Hi! That button class was removed before the 0.8.1 release in https://github.com/LightTable/LightTable/commit/0af45fa998824318945372bad3cca6c9aec71e35. I think this may be an issue where LT's auto-update didn't pull in the latest changes. Could you download 0.8.1 from the website?

**Comment by Trapets** [comment]
I downloaded and extracted LT, the button is gone. Thanks.

**Comment by cldwalker** [comment]
Great!
