### ISSUE TITLE
autoclose-brackets doesn't work in v0.8.1

### ISSUE THREAD

**Issue by jimypbr** [LightTable/LightTable#2137]
I just updated to 0.8.1. In the release log it says:
* CHANGED: [:app :lt.objs.settings/pair-keymap-diffs] behavior is being deprecated. Use [:editor :lt.objs.editor/autoclose-brackets] in your user.behaviors instead. 

So I replaced the first one with the second in user.behaviors. However the brackets now no longer autoclose when I do (, [, {, etc.

My user.behaviors:

 [:app :lt.objs.style/set-skin "dark"]
 [:app :lt.objs.plugins/load-js "user_compiled.js"]

 ;; The editor tag is applied to all editors
 [:editor :lt.objs.editor/no-wrap]
 [:editor :lt.objs.style/set-theme "default"]
 [:editor :lt.plugins.vim/activate-vim]
 [:editor :lt.objs.editor/autoclose-brackets]

 ;; Here we can add behaviors to just clojure editors
 [:editor.clojure :lt.plugins.clojure/print-length 1000]

 ;; Behaviors specific to a user-defined object
 [:user.hello :lt.plugins.user/on-close-destroy]

My user.keymap:
 [:editor "alt-w" :editor.watch.watch-selection]
 [:editor "alt-shift-w" :editor.watch.unwatch]

System: Mac OSX Yosemite. US Keyboard layout.

**Comment by cldwalker** [comment]
Hi. Thanks for the bug report. What file type are you on when you tried closing? Perhaps try other file types. autoclose-brackets has different default characters it closes depending on the file type. If that doesn't work I'd recommend downloading 0.8.1 from our website. We've had a recent auto-update issue in #2036 and want to make sure you're not getting bitten by that

**Comment by jimypbr** [comment]
Hi. I am trying on a clojure (.clj) file. Tried others and got the same.
Downloading version 0.8.1 from the website and using that fixed the problem. Thanks!!

**Comment by kenny-evitt** [comment]
@cldwalker @rundis I think this is more evidence that something is wrong with upgrading.
