### ISSUE TITLE
Wrong version of Go plugin, cannot install, 404

### ISSUE THREAD

**Issue by Erdk** [LightTable/LightTable#2142]
I've tried to install Go plugin but I've got 404 error:
`Error: Error downloading: https://api.github.com/repos/toqueteos/LightTable-Go/tarball/0.0.3 status code: 404...`
From what I found the only versions (branches) of Go plugin are 0.1.0 and 0.1.3.

OS: Fedora 23
Version: 0.8.1

**Comment by rundis** [comment]
There really isn't anything we can do about this. You need to contact the plugin author and ask him/her to make a proper release following the instructions for submitting plugins in https://github.com/LightTable/plugin-metadata

btw seems pretty stale, so there's a good chance it needs some fixing to be compatible with LT 0.8.*
