### ISSUE TITLE
LightTable 0.8.1, Windows 10, No Instarepl

### ISSUE THREAD

**Issue by RobertWalter83** [LightTable/LightTable#2145]
I installed LightTable 0.8.1 under Windows 10. I'm able to evaluate lines by pressing Ctrl+ENTER.

I wanted to try out Instarepl, but it cannot be found. I tried searching for it in the commands view with "repl" and other search strings, but it doesn't show up. Am I missing something?

**Comment by rundis** [comment]
@RobertWalter83 The instarepl has been factored out to a separate plugin that no longer ships with LT by default. Ref https://groups.google.com/forum/#!topic/light-table-discussion/VLOYWhCtCQg

You can find the instarepl plugin in the Light Table plugin manager.

**Comment by RobertWalter83** [comment]
Thanks, I was only browsing the ChangeLog for a change like that but didn't see it.
