### ISSUE TITLE
Metrics should be disabled by default or at least inform the user

### ISSUE THREAD

**Issue by echox** [LightTable/LightTable#2148]
Hi,

LT keeps constantly polling app.kodowa.com/_fetch.
At the moment it fails with:

`Failed to load resource: the server responded with a status of 500 (Server Error): http://app.kodowa.com/_fetch`

The Feature is mentioned at the FAQ as "autopolling" (https://github.com/LightTable/LightTable/wiki/FAQ#how-do-i-turn-off-lts-autopolling).

As a user I have no idea that there is such a feature and no idea what it does.
Checking for a new version? Updating the plugins list? Submitting user metrics?

Other tools inform the user before connecting to domains on the internet, this looks intransparent and a little bit rude.

**Comment by muhuk** [comment]
Still 500'ing.

**Comment by ibdknox** [comment]
The symptom should be fixed now after some surgery on the server. Though as far as I know, that server is completely unnecessary now, so probably best to just completely move off of it.

**Comment by cldwalker** [comment]
@ibdknox Thanks for the fix
@echox Agree there should be some mention of tracking in the About and or Welcome screen. We'll be tracking this work in #2080
