### ISSUE TITLE
Always save buffers behind the scenes, reopen on program launch

### ISSUE THREAD

**Issue by vizanto** [LightTable/LightTable#215]
Explicitly saving files to not lose work feels like going back to the dark ages now that I'm used to Sublime Text 2. :-)

**Comment by Mouvedia** [comment]
I vote for this to be integrated in core. One thing to have in mind is that there are intricacies related to non file tabs. For example reopening the plugin list tab if it was opened.

Concerning (his comment)[https://github.com/LightTable/LightTable/issues/215#issuecomment-20048012] up there, you should edit the ticket's title to reflect that decision.

**Comment by rickedanielson** [comment]
Some of the issues that link to this one are addressed by https://github.com/one-more-minute/Reminisce

**Comment by rickedanielson** [comment]
Some of the issues that link here certainly seem to be addressed (in part) by https://github.com/joshuafcole/recall and https://github.com/one-more-minute/Reminisce ... (just to emphasize comments above)

**Comment by cldwalker** [comment]
We're tracking auto-saving in https://github.com/LightTable/LightTable/issues/1700. As others have mentioned, Reminisce offers relaunch LT in a saved state including modified files
