### ISSUE TITLE
Trouble with git branching

### ISSUE THREAD

**Issue by henrywright** [LightTable/LightTable#2152]
I have 2 branches `foo` and `bar`, both with a clean working directory.

In branch `foo` I make some changes and then run `git status` to find I have some changes ready to be staged.

Now if I switch to branch `bar` and run `git status` I expect the working directory to be clean. However, I see the changes ready to be staged which I made on branch `foo`.

**Comment by kenny-evitt** [comment]
Changing branches in a Git repo doesn't 'clean' your index (what tracks your uncommitted changes).

And this is not (obviously) related to LightTable.

**Comment by kenny-evitt** [comment]
If you want to 'save' your changes without committing them, run `git stash` or `git stash -u` (to include new files in the stashed changes) before switching branches.

**Comment by henrywright** [comment]
@kenny-evitt of course. I do apologise :+1:

**Comment by kenny-evitt** [comment]
@henrywright No worries!
