### ISSUE TITLE
lighttable We couldn't find java. Clojure evaluation requires the JDK to be installed.

### ISSUE THREAD

**Issue by rushabhdotshah** [LightTable/LightTable#2153]
Light Table version
0.8.1

 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

How to resolve "We couldn't find java. Clojure evaluation requires the JDK to be installed."

I do have java installed:
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by kenny-evitt** [comment]
@rushabhdotshah Can you run your Clojure project with Leiningen from the command line via `lein run`?

**Comment by kenny-evitt** [comment]
@rushabhdotshah You can explicitly specify the path to your Java executable in your *user.behaviors* file by adding a behavior item like this:

```
    [:editor.clojure :lt.plugins.clojure/java-exe "path"]
```

where `"path"` is of course the relevant executable path.

[This is the relevant code](https://github.com/LightTable/Clojure/blob/2aeab5ca0831b6755b81f408758b8fea850f601d/src/lt/plugins/clojure.cljs#L816-L820) in the Clojure plugin that determines the Java executable path:

```
(defn check-java [obj]
  ;(println (.sync which "java"))
  (assoc obj :java (or (:java-exe @clj-lang)
                       (aget js/process.env "JAVA_HOME")
                       (.which shell "java"))))
```

Given the code, the two things to check are whether `JAVA_HOME` is set and what the output of `which java` is in your shell.

**Comment by cldwalker** [comment]
Closing as we haven't heard back and the above answer should be enough to resolve this. Feel free to ping us if you have more questions
