### ISSUE TITLE
"Cannot find command: julia"

### ISSUE THREAD

**Issue by jrlawson** [LightTable/LightTable#2154]
Have Julia 0.4.3 installed. Have LightTable 0.8.1 installed. added a launcher (Ubuntu). Ran

Pkg.update()
Pkg.add("Atom")

from julia. All is well. When I launch LightTable from the launcher I get "Cannot find command: julia" When I launch LightTable from the command line. it finds Julia just fine. Restarting doesn't help. Blowing LightTable away and reinstalling doesn't help. Any hints?

**Comment by cldwalker** [comment]
Hi. LightTable doesn't interface with julia out the box. Since this is an issue with Julia, you should report this to the [Julia plugin](https://github.com/JuliaIDE/Julia-LT/issues)
