### ISSUE TITLE
font-family: '.AppleSystemUIFont' on buttons

### ISSUE THREAD

**Issue by jeffbonhag** [LightTable/LightTable#2156]
Hi,

First off, I apologize if this isn't really an issue, but it always pops out at me so I thought I'd report it.  The buttons on the Welcome page look like they're using a generic serif font:

<img width="519" alt="screen shot 2016-03-11 at 7 46 45 pm" src="https://cloud.githubusercontent.com/assets/6937257/13719336/0e46bcc6-e7c2-11e5-8df7-4e00d278dfb8.png">

Is this the way it's intended to look?  The Electron developer tools report that the button has a CSS rule of `font-family: '.AppleSystemUIFont'` which is set by "user agent stylesheet".

I'm using Light Table version 0.8.1 on OS X 10.11.3.

**Comment by kenny-evitt** [comment]
@jeffbonhag This is a real issue; it was previously reported as #2078.

**Comment by jeffbonhag** [comment]
Oops, sorry!  I looked around but didn't see it.  Thanks.

**Comment by kenny-evitt** [comment]
@jeffbonhag No worries
