### ISSUE TITLE
online docs open in unreadable window on OS X 

### ISSUE THREAD

**Issue by paultopia** [LightTable/LightTable#2157]
attempting to read the online docs from the welcome screen in 0.8.1. default config (as I recall) on OS X el capitan, the docs appear in a tiny window with like 2 lines visible at a time, and no obvious way to resize that window.  See screenshot below: 

<img width="1280" alt="screenshot 2016-03-14 11 57 22" src="https://cloud.githubusercontent.com/assets/11756255/13752304/18e9528a-e9dc-11e5-94c5-c55fd2523a75.png">

**Comment by kenny-evitt** [comment]
@paultopia This was previously reported as #2131 and I'm pretty sure that the underlying problem is that the upgrade is broken – see #2138. I hope to actually get to work on that sometime tonight.

So, for now, to fix this issue, just download the latest version.

**Comment by paultopia** [comment]
thanks.  confirming clean download resolves.

**Comment by kenny-evitt** [comment]
@paultopia Thanks
