### ISSUE TITLE
Javascript/JSON rainbow bracket matching not working?

### ISSUE THREAD

**Issue by ciaranj** [LightTable/LightTable#2158]
Simple question, should it ?  looking at the DOM these files don't seem to have the cm-bracket classes applied to their markup.  How would I go about making this happen, or is this a fundamental restriction of the CodeMirror javascript mode ?

**Comment by cldwalker** [comment]
Hi. Your first sentence is a little hard to understand. Could you provide a specific example of what doesn't have cm-bracket classes and give us [more info](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md#bugs) about your environment?

**Comment by ciaranj** [comment]
Sorry about that. using version 0.8.1 of lighttable for windows, with Rainbow 0.0.8 (default theme).   If I'm editing a javascript file or a json file (.js/.json) I expected the rainbow brackets plugin to 'work', that is to display the variously nested depth brackets in matching colours.

It does not appear to do this.  Looking at the DOM for the code-mirror editor instance it looks to me as though the code-mirror mode does not tokenise/expose the brackets to allow the highlighter to function.  Is this correct/expected behaviour?

**Comment by sbauer322** [comment]
When testing against a .js or .json file, there is indeed no delightful rainbow of syntax occurring. 

A quick look at the README.md for https://github.com/LightTable/Rainbow suggests the plugin's current functionality is limited to CLJS.

As this issue pertains to the plugin, I am closing this issue and opening https://github.com/LightTable/Rainbow/issues/4
