### ISSUE TITLE
Can't find instarepl command

### ISSUE THREAD

**Issue by amadeuspagel** [LightTable/LightTable#2163]

**Comment by cldwalker** [comment]
Hi. Instarepl commands have been moved out to [a plugin](https://github.com/LightTable/ClojureInstarepl) and are no longer included with LightTable. See [the announcement](https://groups.google.com/forum/#!msg/light-table-discussion/VLOYWhCtCQg/EZWJpEGrFgAJ) about it. You can install from your plugin manager by searching for instarepl

**Comment by amadeuspagel** [comment]
Thanks
