### ISSUE TITLE
Scroll wheel button: closing tab and copying text

### ISSUE THREAD

**Issue by uy-rrodriguez** [LightTable/LightTable#2166]
Hello, I've found a strange behaviour while clicking with the wheel button over a tab. If some text has been copied, the clicked tab is closed and the text is pasted inside the content of the next tab. It's really nice to can paste with the wheel button, but I think that it shouldn't do it when clicking over a tab.

P/S: Thank you for this great tool !

**Comment by kenny-evitt** [comment]
@uy-rrodriguez What's your OS, OS version, and LT version?

**Comment by uy-rrodriguez** [comment]
Sorry, I forgot to tell you that.

LT:
version
0.8.1
Binary version
0.34.5

OS (obtained with uname -a):
Linux 3.16.0-67-generic #87~14.04.1-Ubuntu

**Comment by cldwalker** [comment]
Hi. This sounds like #1816. Since we're having issues with upgrading, it's possible your install hasn't gotten that bug fix. Could you download a fresh 0.8.1 and see if it's still reproducible?

**Comment by uy-rrodriguez** [comment]
Sorry, I didn't see the other message, I searched for "wheel button" not "middle button".
I tested it several times on 0.8.1 and there's no problem, closing a tab doesn't pastes the content in the clipboard.

Thank you very much!

**Comment by cldwalker** [comment]
Good to hear :)
