### ISSUE TITLE
Trailing whitespace removed from end of line

### ISSUE THREAD

**Issue by henrywright** [LightTable/LightTable#2171]
I'm writing a README.md file and need to have two spaces at the end of a line. When I save the document, the spaces are removed.

Is this a feature? If so, is it possible to disable it?

**Comment by henrywright** [comment]
I noticed this: https://github.com/LightTable/LightTable/blob/master/deploy/settings/default/default.behaviors#L223

Is that something that can be disabled?

**Comment by rundis** [comment]
Yeah it's the default behavior.

To disable just add the following to your user behaviors:
```[:editor.file-backed :-lt.objs.editor.file/remove-trailing-whitespace]```

or if you like you can target different editor types like
```[:editor.markdown :-lt.objs.editor.file/remove-trailing-whitespace]```

**Comment by henrywright** [comment]
@rundis but will that _remove_ the trailing whitespace? I actually want the trailing whitespace to _remain_ when I save the document.
