### ISSUE TITLE
LightTable does not work with xtightvncserver

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [LightTable/LightTable#2175]
This issue was encountered on a 64-bit Debian Jessie system using the pre-built binary package at the following URL:

https://github.com/LightTable/LightTable/releases/download/0.8.1/lighttable-0.8.1-linux.tar.gz

`vncserver -version` gives:

    Xvnc version TightVNC-1.3.9

The first attempt to run LightTable crashed the VNC server. 

After restarting VNC, LightTable prints a few warnings from Xlib and then
exits without further explanation:

    Xlib:  extension "RANDR" missing on display ":1.0".
    Xlib:  extension "XInputExtension" missing on display ":1.0".
    Xlib:  extension "RANDR" missing on display ":1.0".
    Xlib:  extension "XInputExtension" missing on display ":1.0".
    Xlib:  extension "XInputExtension" missing on display ":1.0".
    Xlib:  extension "XInputExtension" missing on display ":1.0".

It's very disappointing that I won't be able to use LightTable while working remotely.

**Comment by rundis** [comment]
Can you run atom or any electron app on that setup ? LightTable is based on electron. 
Also a quick google suggest you might need to try a different vnc server (that supports the required extensions that's needed given the output above).

Sorry for the dissapointment but I'm not very familiar with vnc servers and I'm not so sure LightTable is to blame (maybe Electron, but I'm not really prepared to spend a huge amount of time researching this).

**Comment by rundis** [comment]
@heegaiximephoomeeghahyaiseekh Haven't heard back on this so I'm closing
