### ISSUE TITLE
Weird empty package

### ISSUE THREAD

**Issue by 1j01** [LightTable/LightTable#2177]
I found a weird broken package under available packages. It has no name, version, author, description, or source URL. (The source button has the cursor `default` and it gets `TypeError: Error processing argument -1.` via `open_url` when clicked.)

![weird empty package](https://cloud.githubusercontent.com/assets/3630663/14287779/26d85b32-fb22-11e5-8018-ec7e4a3e827e.png)

**Comment by kenny-evitt** [comment]
@1j01 Thanks for the report.

The problem is that the code that builds the list ('cache') of plugin metadata is treating the *script* sub-directory as a plugin.

**Comment by rundis** [comment]
👍
