### ISSUE TITLE
Select text in Plugins

### ISSUE THREAD

**Issue by 1j01** [LightTable/LightTable#2178]
You should be able to select text in the Plugins view.
The text "by" shouldn't be a psuedo element, and there should probably be an actual space between the package name and version, but other than that it just needs `-webkit-user-select: text`.

**Comment by kenny-evitt** [comment]
Interesting. This seems to be explicit; [the relevant CSS](https://github.com/LightTable/LightTable/blob/53a90bee4c2c6758e4b5dffdffbc32256a05e00d/deploy/core/css/structure.css#L14):

```
body { -webkit-user-select: none; }
```

@cldwalker @rundis Any ideas about whether removing this CSS rule is a bad idea?

I commented the line out via Developer Tools and I'll update this issue if I run into anything that seems related to that change.

**Comment by kenny-evitt** [comment]
@1j01 Why should "by" text not be a pseudo-element?

**Comment by 1j01** [comment]
We should keep the global `-webkit-user-select: none;` and add` -webkit-user-select: text;` to `.plugin-manager li`, and we should avoid textual pseudo elements so that when you copy and paste, the text is present. It wouldn't be the biggest issue because it's still fairly clear the second line is the author:
```
Paredit0.0.4
Kodowa
Paredit integration for Light Table
```
But it would be better if it copied it as it appeared.

**Comment by kenny-evitt** [comment]
@1j01 How is keeping the global select-none helpful? And how is it helpful to be able to copy "by"? I'm not against making the changes, but I don't know why they were implemented or implemented that way nor what consequences changing them would have other than being able to copy the plugin text. And I'm not sure of the utility of being able to copy the plugin text either.

**Comment by 1j01** [comment]
@kenny-evitt I'm was just guessing it would break stuff to remove it. Trying it out, it's not too bad (and it's good to be able to select as much as possible), but it would probably be better to enable it specifically for each UI element (like the line / column view, the individual file/folder list items (although it would need to ignore clicks when there's selected text to be able to select the name of a file or folder easily))

Like I was trying to say, "by" wouldn't matter too much, but there's not really any point in having it be a psuedo element, so it might as well be copyable with the rest of the text

**Comment by kenny-evitt** [comment]
@1j01 I have no strong feelings about this so if you'd like the changes to be made, please submit a pull request and we'll review and test your proposed changes.

**Comment by sbauer322** [comment]
For anyone curious, below is part of the Plugin Manager where text cannot be selected;

![plugin-manager-cropped](https://cloud.githubusercontent.com/assets/2945386/18258679/731ec694-73a8-11e6-918e-5ed77df3e635.png)

The goal would be to allow the selection of the text for a given plugin such that it could be copied and pasted.

**Comment by Mouvedia** [comment]
He's right overwriting is the way to go. For example it prevents text from being selected during drag and drop.

**Comment by sbauer322** [comment]
Closing as PR #2322 has been merged to address this.
