### ISSUE TITLE
Devtools shortcut: Ctrl+Shift+I

### ISSUE THREAD

**Issue by 1j01** [LightTable/LightTable#2179]
The "[standard](https://developers.google.com/web/tools/chrome-devtools/iterate/inspect-styles/shortcuts?hl=en#accessing-devtools)" keybindings are <kbd>F12</kbd> and <kbd>Ctrl + Shift + I</kbd> on Windows, and <kbd>Cmd + Opt + I</kbd> on Mac.

We should probably use <kbd>Ctrl + Shift + I</kbd> for consistency if we can't do multiple keybindings.

**Comment by kenny-evitt** [comment]
@1j01 What's the issue? That this isn't in the default key bindings (key map)?

**Comment by 1j01** [comment]
@kenny-evitt Yeah, I mean, I guess there are two ways to open the devtools from the keyboard, from the View menu or with the command palette, but it's good when applications share shortcuts.

**Comment by kenny-evitt** [comment]
@1j01 I don't think we can do platform-specific behaviors so we'd have to pick one for all platforms. Light Table is also not a browser so consistency seems pretty minor.

I'm going to close this as I don't think we're interested in doing this. If you feel strongly about it, create a pull request and the other team members can review your proposed change or changes.

**Comment by 1j01** [comment]
Wouldn't it just be `pmeta-alt-i`? From the LT FAQ, "You can substitute option for alt", and [from here](https://groups.google.com/forum/#!topic/light-table-discussion/hJ1RRHQuAOU), "pmeta is [command on Mac, ctrl on Linux/Windows]"

**Comment by kenny-evitt** [comment]
@cldwalker @rundis Are we open to a default key binding for opening dev tools?
