### ISSUE TITLE
"Toggle connect bar" shortcut "esc"

### ISSUE THREAD

**Issue by 1j01** [LightTable/LightTable#2182]
The shortcut for "Toggle connect bar" is listed as "esc" even though <kbd>Esc</kbd> only closes it.

**Comment by kenny-evitt** [comment]
@1j01 Thanks for the report.

I'm not sure what we can feasibly do about this for the time being. The key bindings are shown for the commands automatically and <kdb>Esc</kbd> *is* bound to the toggle connect bar command, if only for when the connect bar already has focus and receives those key events.

**Comment by 1j01** [comment]
Yeah, I figured about as much. <kbd>Esc</kbd> should close the commands palette too, so maybe <kbd>Esc</kbd> should be mapped to *Close sidebar* (even outside of any sidebars). Are there any sidebars where this would be undesirable? And if we can't do it globally, we should be able to do it like *Editor: Set current editor syntax* which doesn't have a command *Toggle editor syntax switching bar* but still lets you close it with <kbd>Esc</kbd>.

**Comment by carocad** [comment]
Should this still be open? Is there any feasible solution for this?

**Comment by 1j01** [comment]
I described two possible solutions in my previous comment. Either one should be pretty easy to do.

**Comment by carocad** [comment]
@1j01 would you be willing to tackle this issue?

**Comment by 1j01** [comment]
@carocad I would, but I don't use LT. (I tried it out, but wasn't able to get live editing working.)

**Comment by kenny-evitt** [comment]
I'm closing as this doesn't seem to significantly affect anyone any more.
