### ISSUE TITLE
"Path too long" when unzipping install package in Windows 10

### ISSUE THREAD

**Issue by lacroixca** [LightTable/LightTable#2184]
When unzipping the file, I got 3 errors for 3 different files saying that the path was too long.

Anyone else?

**Comment by kenny-evitt** [comment]
@lacroixca There are issues when installing Light Table in a directory with spaces too – see #2029 – so I'd advise installing it in a directory close to the root of a drive, e.g. *C:\LightTable*.

Unfortunately, there isn't really much we can do about this.
