### ISSUE TITLE
Plugin development: cljs dependency load failure

### ISSUE THREAD

**Issue by bbbates** [LightTable/LightTable#2194]
I'm having an issue with loading an external cljs dependency (in this case "core.logic") in a simple plugin I'm building. Using Lighttable version 0.8.1 (binary version 0.34.5), with Clojure plugin version 0.3.2 if that helps. Using OSX 10.11.4. 

I've created a quick little plugin project to demonstrate the issue. See here: https://github.com/bbbates/logic-test-plugin

Steps to reproduce:

1. Import project above into LT
2. Open lt/plugins/logic_test_plugin.cljs
3. Save/touch file to start the automated build
4. Eval (cmd-shift-enter) and select the Light Table UI client
5. Execute command "logic-test-plugin: Say Hello"
6. Note the error in the console.

```
Invalid behavior: :lt.objs.sidebar.command/exec-command
TypeError: Cannot read property 'prep' of undefined
    at Function.eval (/Users/brendan/dev/logic-test-plugin/src/lt/plugins/logic_test_plugin.cljs[eval1121]:29:419)
    at b (file:///Applications/Lighttable/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6188:14)
    ...
```

The version of core.logic I've selected has a target cljs version that is the same as LT, so shouldn't be any issue with cljs incompatibilities I would imagine.

Any ideas?

**Comment by rundis** [comment]
Try restarting LT. I don't think LT is capable of loading the cljs from the dependency/ies. However when you start next it will load the compiled js for your plugin which now should include the resulting js from core.logic too. I had the same issue with core.async. Let me know if that helps.

**Comment by bbbates** [comment]
Yep, that worked! Should've known the answer would be a restart. The answer is always a restart!

Should probably update the plugin developer FAQ - I will do that shortly.
