### ISSUE TITLE
Missing GLIBC packages on RHEL5

### ISSUE THREAD

**Issue by didibus** [LightTable/LightTable#2199]
I'm trying to run 0.8.1 of LightTable on RHEL5 and I get the following error:

```
lighttable: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by lighttable)
lighttable: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by lighttable)
lighttable: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /opt/LightTable/libnode.so)
lighttable: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/LightTable/libnode.so)
lighttable: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/LightTable/libgcrypt.so.11)
lighttable: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /opt/LightTable/libgcrypt.so.11)
```

I'm guessing it's because RHEL5 is too old, and contains older versions of GLIBC. Is there any possibility to package those binaries in with the release or to default to compiling with an older gcc?

**Comment by kenny-evitt** [comment]
[I found similar issues to this one](https://github.com/LightTable/LightTable/issues?utf8=%E2%9C%93&q=is%3Aissue+libstdc):

* [Can't run on CentOS 6.5 · Issue #1842 · LightTable/LightTable](https://github.com/LightTable/LightTable/issues/1842)
* [Running on CentOS · Issue #1418 · LightTable/LightTable](https://github.com/LightTable/LightTable/issues/1418)
* [GLIBC error on Debian · Issue #164 · LightTable/LightTable](https://github.com/LightTable/LightTable/issues/164)

[My last comment](https://github.com/LightTable/LightTable/issues/1842#issuecomment-112488695) on #1842:

> Atom/Electron requires the specific version of libc. And it just doesn't seem to work on CentOS versions prior to 7; one issue among several:
> 
>  - [atom-shell not available on CentOS? · Issue #1172 · atom/electron](https://github.com/atom/electron/issues/1172)
> 
> There seem to be lots of people struggling to build it on CentOS 6.*x*, to no obvious avail.
> 
> I don't think I, or anyone else, will be able to help you. Light Table is nearly moribund as-is. Migrating from node-webkit to Atom was a significant project aimed to address major issues for a large number of users. Migrating to another alternative is just not realistic anytime soon – unless you are willing to spearhead that effort yourself.
