### ISSUE TITLE
client area is always on top (Ubuntu)

### ISSUE THREAD

**Issue by cskujbus** [LightTable/LightTable#2201]
I wanted to use LT on Ubuntu 16.04 (VirtualBox vm installation), but can't switch to other windows as LT hides everything beneath its client area.

**Comment by carocad** [comment]
@cskujbus could you please provide a screenshot of this issue? A description of what you expected vs what happened would also be nice.  Also, about which LT version are we talking?

**Comment by cskujbus** [comment]
Hi,
here they are:

1. LightTable on top
![lt-top](https://cloud.githubusercontent.com/assets/3771374/15270530/47713fce-1a23-11e6-92e9-7035c7e692af.png)

2. LightTable at bottom
![lt-bottom](https://cloud.githubusercontent.com/assets/3771374/15270535/5722990e-1a23-11e6-8787-27b7691b6e22.png)

**Comment by cskujbus** [comment]
Ok, I tried in VMWare the same Ubuntu 16.04 + LightTable 0.8.1 and there is no such problem. Maybe it's some kind of Virtualbox video driver issue.

**Comment by kenny-evitt** [comment]
@cskujbus Glad it's fixed.
