### ISSUE TITLE
runmode.node.js peek: function()  this.string = null

### ISSUE THREAD

**Issue by cneira** [LightTable/LightTable#2204]
I have tried to update lightable to use latest clojurescript 1.8.51, I have a couple of issues :

- Threadworker.js

 when registering a function it gets a bad formed one resulting in a reference error arguments$ not defined.
for example it will try to register this function 
registering function theadfunc51==>function () {
  var a = argsArray(**arguments$** ), b = a.shift(), c = a.map(cljs.reader.read_string), d = function(a, b, c) {
    return function(a, b, c) {
      return _send(a, b, cljs.core.pr_str.call(null, c), "clj");
    };
  }(a, b, c); 

I have bypassed this by stripping the $ from the arguments string.
but the actual issue is that  trying to erase text from a file threadworker.js tries to call this registered  function(the fixed one without the $) that invokes peek from runmode.node.js and this.string in that function is always null, but using the current lightable it receives the actual string being erased. 

to recreate just change in project.clj the dependencies from clojure to 1.8.0 and clojurescript to 1.8.51 and lein-cljsbuild to 1.1.3.
Is there is something that needs to be changed in threadworker.js or cljs.cljs because of the new cljs and clj versions?

**Comment by carocad** [comment]
I have no experience on this subject but I know that there is already an issue with detailed information about the steps required to accomplish that. It seems to be non-trivial though. Here is the issue #1973. 
I hope it helps

**Comment by cneira** [comment]
Thank you very much, this is really helpful!
