### ISSUE TITLE
optional docstring for lt macros

### ISSUE THREAD

**Issue by carocad** [LightTable/LightTable#2206]
hey guys,
to be honest I have never written a macro so I don't know if this is actually possible or not, but anyway here it goes. I was having troubles understanding some of the uses of some UIs and also some behaviors, the problem being that they don't have any documentation which is not a surprise.

The real problem though is that (from my limited understanding of macros) it is also not possible to (currently) add docstrings to them since the macro was never intended for it. This is true for both `defui` and `behavior` although I am not sure how plausible it would be with `behavior` since the name gets munged.

```
;; currently
(defui hello-panel []
  [:h1 "Hello from the playground"])

;; expectation
(defui hello-panel
"creates a hello panel as an h1 tag"
 []
  [:h1 "Hello from the playground"])
```

I think that adding the option of docstring for the BOT elements would make understanding a plugin code much easier as currently we have to go with the best guess based on name, triggers and similars.

**Comment by kenny-evitt** [comment]
@carocad What about just doing what `defn` does itself? Doc-strings are just added to the var's metadata – to the `:doc` key specifically. So, to add a doc-string to the `hello-panel` var, you could just do:

```
(with-meta 
  (defui hello-panel []
    [:h1 "Hello from the playground"])
  {:doc "This is the doc-string for `hello-panel`."})
```

We could of course also add support for optional doc-strings to the `behavior` and `defui` macros, but that's a low priority for us (including reviewing submitted PRs for those changes).

Given that neither `behavior` or `defui` add metadata to its symbol arguments, it should be safe to add doc-strings directly as above.

**Comment by carocad** [comment]
@kenny-evitt that's not a very sustainable solution. For what is worth I would rather put comment lines above or below the definition and just read them when I need to.

Of course I understand and agree that this is not a priority right now and I also didn't intend it to be, but I wanted to make clear that this should be addressed at some point; hopefully sooner than later (more behaviors and ui-widgets without any kind of docs will only make things more complicated for everyone in the future, especially taking into account that the LT code is not sequential)

On another note, I saw that behaviors name are being munged, so I don't know if adding the metadata works as expected (from the retrieving part). I also saw some behaviors with a :desc keyword. I guess that for understanding the code, it would be enough to have those, although it leaves the same retrieving docstring problem open.

**Comment by sbauer322** [comment]
PR #2276 addresses this request with the `:doc` key for objects, behaviors, and defui. Do note that due to https://github.com/LightTable/LightTable/issues/2203 it will likely not be possible to get this optional docstring for defui when developing plugins. In other words, this functionality currently limited to developing on the core of Light Table until that issue is addressed.
