### ISSUE TITLE
autocomplete freezes very very briefly

### ISSUE THREAD

**Issue by mkno** [LightTable/LightTable#2207]
when I type anything in win 7 installation of Lighttable, the autocomplete popups up but it seems to freeze maybe 400~600ms. I have the REPL running. Of course I don't know the exact milliseconds but it's enough for me to notice and it's not smooth at all and feels 'jerky'. Wondering if anyone is running into the same issue and was able to resolve it. 

Looks like https://github.com/LightTable/LightTable/issues/2035 covers it. I guess I am fine for the time being but it does get noticeably annoying but I'm just so glad how beautifully the ctrl+enter thingy works for clojure after struggling to get up and running with Atom plugin proto-repl

**Comment by carocad** [comment]
@mkno would you consider closing this issue since #2035 already convers it and there is quite a discussion there?
