### ISSUE TITLE
Creating multiple connections on the same clojure project

### ISSUE THREAD

**Issue by cprabhu** [LightTable/LightTable#2210]
I am using LightTable version 0.8.1 on Ubuntu 14.04 LTS. In the clojure project that I am working on, I have already evaluated and made the connection using ctrl-o. I can see the active connection as well in the connection space. Now, I want to watch over a div/link in a clj file, and hence invoked watch-selection using the key that I have loaded in the keymap for the same. But this is resulting in starting another new connection altogether to the same project and when I run the project on the browser, I do not see the result as well in LightTable. Is this a problem only on Linux? Because I can see the same works on my friend's mac. Anyway to work around this issue?

**Comment by bbbates** [comment]
What version of the Clojure plugin do you have installed?

**Comment by cprabhu** [comment]
I think it was 0.3.1. I just updated it to 0.3.3 and restarted the LightTable to see it work! :)
