### ISSUE TITLE
Light Table appimage

### ISSUE THREAD

**Issue by kskarthik** [LightTable/LightTable#2211]
I made [appimage](http://appimage.org) for light table 0.8.1 

### Advantages of appimage

* *one app = one file*
* can run on any linux distro without installation, just chmod +x to give executable permission 
* no root privilages required
* App always stays in compressed state on the disk. So, saves memory ( not a big prob for new systems) 

Download here[53.5 MB]: https://www.dropbox.com/s/3fbofqvkn8ex55q/LightTable-0.8.1_x64.AppImage.tar.gz?dl=0

**Comment by cldwalker** [comment]
Nice! We don't plan on changing how we distribute to linux distros. If you'd like to maintain an appimage for the latest LightTable release, feel free to add your package to this [wiki page](https://github.com/LightTable/LightTable/wiki#os-distributions-package)

**Comment by kskarthik** [comment]
Done ! added :smiley:

**Comment by tolyod** [comment]
@kskarthik can u share appimage again? seems previous dropbox link is broken
