### ISSUE TITLE
Add behavior to allow disabling SSL certificate checking when using NPM's request package

### ISSUE THREAD

**Issue by mluisbrown** [LightTable/LightTable#2212]
### Background

Anyone who works in a corporate environment likely has to access the internet via an HTTP/HTTPS proxy. LightTable already supports this via the `http_proxy` and `https_proxy` environment variables (see #1984 for more details).

The use of a corporate proxy allows the company to control what sites employees have access to and also potentially monitor all access to the internet. In a significant number of companies there is also the requirement to be able to monitor SSL traffic (eg banks, where all communication with the external internet by employees using corporate infrastructure has to be monitored and recorded as a measure to prevent money laundering and insider trading). I don't want to dwell on whether this is a good thing or correct, you just need to be aware that it's a thing. I work in such a company :cry:  

In order to achieve this SSL monitoring, the company inserts its own SSL certificate in the chain (man in the middle) so they can decrypt SSL traffic between the user and the proxy, which is then re-encrypted before going to the external HTTPS host. The browser(s) used by employees are suitably configured to trust this internal SSL cert, so everything works.
### The problem

The problem arises with software like `npm`, `git`, `curl` and basically anything else that accesses the internet (eg **LightTable** :wink: ) which doesn't know or trust the special corporate cert. and will error out with something like `Error: self signed certificate in certificate chain` or worse.

Most of these tools have an option to disable strict SSL certificate checking, which let you get around the problem:
- `npm config strict-ssl false` 
- `git config --global http.sslverify false`
- `curl --insecure <url>` 
### In relation to LightTable

LightTable uses the [request](https://www.npmjs.com/package/request) npm package to [download files](https://github.com/LightTable/LightTable/blob/master/src/lt/objs/deploy.cljs#L74-86) for getting plugin metadata, downloading plugins and auto updating itself.

If you are behind a proxy such as I described above, these requests silently fail (also an issue) and you get some apparently unrelated error in the console. For example, when trying to download plugin metadata you'll get something like: `Error: ENOENT: no such file or directory, scandir 'C:\Users\myid\AppData\Roaming\LightTable\metadata-temp'` because the `metadata-temp.tar.gz` (plugin metadata) file that is created is 0 bytes and so doesn't extract to anything. This problem has been mentioned #1984 and #2010.

Fortunately, the **request** npm package has the [option](https://github.com/request/request#requestoptions-callback) `strictSSL` which if set to `false` will ignore certificate errors. I work in an environment with a corporate man-in-the-middle SSL proxy and as a test I hacked my local copy of `request` in the LT installation directory to always use `strictSSL: false` and that fixed downloading plugin metadata and downloading plugins.
### What I'm suggesting / requesting

Add a behavior to Light Table that allows people to configure a `strictSSL` option to `false`, such that that option is then passed on to `request` in [`deploy/download-file`](https://github.com/LightTable/LightTable/blob/master/src/lt/objs/deploy.cljs#L74-86).

**Comment by kenny-evitt** [comment]
@mluisbrown I'm not entirely against this but what about allowing users to add your internal certificates instead? [The *request* package also seems to support this](https://github.com/request/request#using-optionsagentoptions):

> It is possible to accept other certificates than those signed by generally allowed Certificate Authorities (CAs). This can be useful, for example,  when using self-signed certificates. To require a different root certificate, you can specify the signing CA by adding the contents of the CA's certificate file to the `agentOptions`. The certificate the domain presents must be signed by the root certificate specified:

> ```js
> request.get({
>     url: 'https://api.some-server.com/',
>     agentOptions: {
>         ca: fs.readFileSync('ca.cert.pem')
>     }
> });
> ```

One (major) advantage is that you wouldn't need to completely disable SSL.

**Comment by mluisbrown** [comment]
@kenny-evitt that's a good suggestion. However, it turns out that it's extremely tricky to obtain a `.pem` file to use with an `agentOptions` config that works. I haven't been able to do it. It must be possible, but very tricky (at least at my workplace), and requires a lot of futzing around with `openssl` to get the file in the right format etc.

> One (major) advantage is that you wouldn't need to completely disable SSL.

With the `strictSSL: false` option you are not completely disabling SSL. You're just saying you don't mind self signed certificates and other weirdness that might indicate the connection has been tampered with. People in the scenario where this option is useful are fully aware of what's going on, and the connection is still SSL, and still encrypted between the corporate proxy and the remote host.

Adding a `strictSSL: false` option would be in line with other software that offers the same option.

If you accept this issue then I wouldn't mind having a shot at making the change myself :smile:

**Comment by mluisbrown** [comment]
Sorry, hit the "Close and comment" button by mistake :stuck_out_tongue_closed_eyes:
