### ISSUE TITLE
browser rendering glitches

### ISSUE THREAD

**Issue by cjdg** [LightTable/LightTable#2220]
Ubuntu 16.04 x64

Everytime i use the browser i get the same glitch in many sites, from local projects to websites, i have to close and create a new browser window to get it work
![light table_001](https://cloud.githubusercontent.com/assets/5726836/16030983/f93f697e-31bb-11e6-9726-82a201025947.png)

**Comment by kenny-evitt** [comment]
Please review [the default text when submitting a new issue](https://github.com/LightTable/LightTable/issues/new) and include the info we need to help you. I'll re-open this when you've done that.

**Comment by kenny-evitt** [comment]
@cjdg You seem to have ignored both the "Please review the guidelines for contributing to this repository." note as well as the issue template text. Did you submit this and the other issue on a mobile device? I updated the issue template text to (hopefully) be clearer about how the template text should be used. Any feedback on the text, or the changes I made just now, would be appreciated.
