### ISSUE TITLE
Browser doesnt work well

### ISSUE THREAD

**Issue by cjdg** [LightTable/LightTable#2221]
No websites work with browser
![light table_002](https://cloud.githubusercontent.com/assets/5726836/16031361/e3647dac-31bf-11e6-9e32-26f643581d4c.png)

**Comment by kenny-evitt** [comment]
Please review [the default text when submitting a new issue](https://github.com/LightTable/LightTable/issues/new) and include the info we need to help you. I'll re-open this when you've done that.
