### ISSUE TITLE
Windows 10, double click .exe, nothing happens

### ISSUE THREAD

**Issue by edwardhew** [LightTable/LightTable#2223]
Windows 10, Intel HD 4600 Graphics, 8Gig RAM.

Unzipped the 0.8.1 zip, placed in D drive (not C), tried to launch LightTable.exe, nothing, no errors, just nothing happens. Is there some requirements not met? I don't have Python for example.

**Comment by kenny-evitt** [comment]
@edwardhew Do you see "LightTable" or "Electron" in Task Manager? You're going to need to grant permission for LT (or "Electron") to use your network at some point. I vaguely recall that taking a while the first time I ran LT on my Windows 10 computer.

**Comment by edwardhew** [comment]
Hello, thanks for response, I didn't see Electron, so I unzipped from the 0.8.1 again, this time LightTable launched! I must have somehow botched the copy last time, maybe some files weren't copied correctly. Sorry about the false alarm.

**Comment by kenny-evitt** [comment]
@edwardhew No worries – glad it's working!
