### ISSUE TITLE
Provide LightTable default theme color scheme

### ISSUE THREAD

**Issue by azbshiri** [LightTable/LightTable#2226]
Hey guys, I'm new to LightTable and I really like the speed and its default theme's harmony. I often switch between a terminal and an editor and I want to my terminal color scheme to match the editor. I couldn't find the LightTable default color scheme name, nor any source with a color palette to apply to my terminal. I'd appreciate it if you could provide a color palette (solarized, gruvbox, etc) to use in different apps, terminals, editors, and so forth.

**Comment by kenny-evitt** [comment]
@azbshiri The default theme is just named *default*. Here's the CSS for it:

 - [LightTable/default.css at master · LightTable/LightTable](https://github.com/LightTable/LightTable/blob/master/deploy/core/css/themes/default.css)

**Comment by azbshiri** [comment]
I meant, a color color palette not specific css selectors which LightTable uses.

**Comment by azbshiri** [comment]
I meant, a color color palette not specific css selectors which LightTable uses.

**Comment by kenny-evitt** [comment]
@azbshiri I'm not sure what you're looking for but I'm guessing we don't have it. An example of what you're looking for would be helpful.

**Comment by azbshiri** [comment]
l;;;https://raw.githubusercontent.com/altercation/solarized/master/img/solarized-palette.png something like th picture. Provide background colors (bases) and also different colors for red, green, yellow, cyan, etc.

**Comment by kenny-evitt** [comment]
@azbshiri I'm pretty sure we don't have an image describing the palettes of our default or other themes.
