### ISSUE TITLE
Renaming a folder prevents saving already opened files

### ISSUE THREAD

**Issue by tomtau** [LightTable/LightTable#2232]
One small issue: after renaming a folder, its contained files opened before the renaming cannot be saved. One way around it is to copy the file content somewhere, close the file and "discard changes", and re-open that file and paste the changed content back.

### Steps to Reproduce

 1. Have some files opened in the editor.
 2. In the workspace browser, right-click on the folder these files are contained it, and choose to rename it.
 3. After renaming the folder, make changes in the opened files and try to save them.

### Environment

| Info                             | Details |
| -------------------------------- | ------- |
| Light Table version              |    0.8.1 (binary version: (0.34.5)     |
| Operating system                 |   Ubuntu 16.04      |

### Error Messages

```
Invalid behavior: :lt.objs.editor.file/file-save
```

**Comment by kenny-evitt** [comment]
@tomtau Thanks for the report. Unfortunately, this is not likely to be fixed anytime soon, if ever; at least not given current and recent levels of activity. That said, this may not be hard to 'fix' so if anyone's interested in working on it just ping me here or on Gitter and I'll be glad to help however I can.

I'm going to close this for now. When or if someone wants to work on it, I'll re-open.

**Comment by tomtau** [comment]
@kenny-evitt It shouldn't be too difficult to fix, I can give it a go.

**Comment by kenny-evitt** [comment]
@tomtau Great! Ping me here or in the Gitter room if you have any questions or need any other help.

**Comment by tomtau** [comment]
@kenny-evitt https://github.com/LightTable/LightTable/pull/2233
