### ISSUE TITLE
Make dependency on libcups optional

### ISSUE THREAD

**Issue by kxepal** [LightTable/LightTable#2235]
## Report Bug

It's not clear why LightTable need in cups, but it would be nice it this dependency will be optional.

### Steps to Reproduce

1. Have a system with no cups installed
2. Install any icedtea or oracle jdk
3. Download latest LightTable release
4. Run it

### Environment

| Info                             | Details |
| -------------------------------- | ------- |
| Light Table version              | 0.8.1        |
| Operating system                 | Linux        |

### Error Messages

```
$ lighttable 
lighttable: error while loading shared libraries: libcups.so.2: cannot open shared object file: No such file or directory
```

**Comment by rundis** [comment]
Light Table is build on electron. This is apparently a requirement / (or won't fix) upstream afaik. So I'm going to close this issue. 
ref : https://github.com/electron/libchromiumcontent/issues/134

**Comment by kxepal** [comment]
Thanks for the reference! That makes sense now.
