### ISSUE TITLE
Update deprecated functions in files namespace

### ISSUE THREAD

**Issue by sbauer322** [LightTable/LightTable#2248]
Current function:

```
(defn exists? 
  [path]
  (.existsSync fs path))
```

However, [existsSync](https://nodejs.org/api/fs.html#fs_fs_existssync_path) is deprecated. `exists?` should be updated to use `fs.statSync()`, `fs.accessSync()` or something else.

There may be other deprecations too, so it is worth checking out what else is labelled as deprecated and update accordingly.

**Comment by BloodShura** [comment]
Actually, `existsSync` is not deprecated at all.

From the same link you referenced: 

> Note that fs.exists() is deprecated, but fs.existsSync() is not. (The callback parameter to fs.exists() accepts parameters that are inconsistent with other Node.js callbacks. fs.existsSync() does not use a callback.)

**Comment by sbauer322** [comment]
Hmm, yep, that is certainly what the docs say... I wonder function I actually meant. I'll poke around and either update or close this soon.
