### ISSUE TITLE
Light table just displays error prompt

### ISSUE THREAD

**Issue by Gozala** [LightTable/LightTable#2249]
### Steps to Reproduce

 1. Start a light table without pre-existing (`~/.LightTable` directory).

### Environment

| Info                             | Details |
| -------------------------------- | ------- |
| Light Table version              |     lighttable-0.8.1    |
| Operating system                 |    osx   10.12 Beta  |

<img width="532" alt="screen shot 2016-08-31 at 10 07 42 am" src="https://cloud.githubusercontent.com/assets/21236/18138752/1bf693e0-6f63-11e6-9df8-2838b44c3b37.png">

**Comment by rundis** [comment]
Maybe you have some cruft left from an old LT in your ~/Library/Application Support/LightTable ?
if you do it might be worth nuking/moving that.

I'm clutching at straws here though.

It might be some flavour of this problem with Electron resurfacing:
https://github.com/ethereum/mist/issues/142

**Comment by Gozala** [comment]
> Maybe you have some cruft left from an old LT in your ~/Library/Application Support/LightTable ?
> if you do it might be worth nuking/moving that.

Thanks that helped!

**Comment by rundis** [comment]
Excellent !
