### ISSUE TITLE
Update label scheme

### ISSUE THREAD

**Issue by sbauer322** [LightTable/LightTable#2255]
@kenny-evitt, as requested, here is summary of the initial desired label changes. There is nothing too crazy... probably the most significant is appending types to various labels. For instance `status: ` to statuslabels such as `status: blocked`. Since there are multiple changes, I want to get at least one other LT member's okay as a sanity check.

To better aid contributors, users, and visitors, I am suggesting we modify our labeling scheme. We are currently at 30 unique labels and it can be burdensome to sift through. Additionally, even with this number of labels we still have vague areas that don't have labels to adequately categorize some issues.

In keeping with Github label best practices the following changes are proposed:

#### General

- Revise label definitions found in [For Contributors](https://github.com/LightTable/LightTable/wiki/For-Contributors) wiki page. A label's name should be meaningful and clear enough that there is minimal need for elaboration.
- Group types of labels by color. For instance, labels relating to bugs should all be the same or similar colors. Each group of labels should have a distinct color from other groups.

#### New Labels

- `parity` labels for a select number of IDEs we feel we should attempt to stay up to speed with feature-wise. (e.g., sublime, atom)

#### Rename

- Rename `task` label to `maintenance`. This label should cover all behind-the-scene issues including upgrades.
- Rename `feature` label to make it more significant and distinct from `enhancement`. Current working name `status: accepted`.

By prepending the following, related labels will be grouped for easier selection, visibility, and meaning.

- Prepend `platform: ` to all current platform label names. (Current labels: windows, linux, mac)
- Prepend `status: ` to all current status label names. (Current labels: blocked, in progress)
- Prepend `resolution: ` to all current resolution label names (Current labels: cannot reproduce, duplicate, triaged)

#### Remove

- Remove `experience` label and relabel its 2 issues.
- Remove `fixed-on-master` and `fixed-upstream` - they have 0 issues and have not been used since Nov 2015. 
- Remove `python` label as we have a python plugin where the issues should be sent.

As it always comes down to a question of who or time, I am happy to volunteer to implement the label changes.

Relevant links:

- https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/
- https://docs.saltstack.com/en/latest/topics/development/labels.html
- https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63#.rr8537ijk

**Comment by Mouvedia** [comment]
> Rename feature label to make it more significant and distinct from enhancement.

We need proposals for that.

> Prepend status: to all current status label names. (Current labels: cannot reproduce, blocked, crash, duplicate, triaged, in progress)

This should be divided between `status:` ones (blocked, in progress) and `resolution:` ones (cannot reproduce, duplicate, triaged). `crash` doesn't belong in either.

> Alternatively, rename to user experience.

I disagree: UX has a specific meaning. `experience` should be deleted.

**Apart from these, I agree on everything else.**

**Comment by sbauer322** [comment]
I agree can agree with all this. I was torn with appending `bug: ` to the bug labels as the label be meaningful for non-bug issues too (e.g., using the electron label to identify an enhancement that involves electron.

I have updated the original post to reflect these changes.

**Comment by rundis** [comment]
go for it.

**Comment by sbauer322** [comment]
The requested changes have been applied with the following exceptions:

- `feature` was not renamed as it does not quite fit in with the other `status: ` labels
- `fixed-on-master` and `fixed-upstream` were not removed but prepended with `resolution: `
