### ISSUE TITLE
Doc search still has focus when toggled off

### ISSUE THREAD

**Issue by esdoppio** [LightTable/LightTable#2258]
## Report a Bug

Doc search still has the focus when toggled off. I think a more desirable behavior is to transfer the focus back to the editor after toggle off the doc search.

### Steps to Reproduce

 1. Open LT and open any file.
 2. Use <kbd>ctrl-shift-d</kbd> to call out the doc search.
 3. Do <kbd>ctrl-shift-d</kbd> again to toggle off the doc search.
 4. Type something.
 5. Do <kbd>ctrl-shift-d</kbd> again to call out the doc search.

You'll find the things you just typed appear in the search box.

### Environment

| Info                             | Details |
| -------------------------------- | ------- |
| Light Table version              | 0.8.1 |
| Operating system                 | OS X 10.11.6 |

**Comment by sbauer322** [comment]
I am able to reproduce this in Ubuntu 16.04 as well. 

As @esdoppio thinks, the correct behavior should be to return focus back to the editor after the doc search is closed.

Pressing esc to close the doc search should also return focus back to the editor, but it currently does not.

**Comment by sbauer322** [comment]
PR #2275 resolves this issue and has been merged. Thank you for pointing out the bug!

**Comment by Mouvedia** [comment]
@sbauer322 gotta remove the in progress label.
