### ISSUE TITLE
[minor] Highlighting of open/closing brackets  is not visible

### ISSUE THREAD

**Issue by RetainCountZero** [LightTable/LightTable#226]
On some themes, like `lesser-dark`, the highlighting of matching open/closing brackets seems not to be shown. Switching to a theme like `monokai`, which uses underlines to indicate matching brackets, shows that the highlighting mechanism is not broken.

From this I guess that this is some effect from the bugfix to get working background colors of the themes (version 0.2.2 onward). It looks like the background color conflicts with the highlight color … or the highlight color and background color are the same, thus showing no visible effect.

**Comment by smotti** [comment]
Issue still exists with 0.8.0 for solarized-light.
