### ISSUE TITLE
Migrate user docs to GitBooks

### ISSUE THREAD

**Issue by sbauer322** [LightTable/LightTable#2261]
This issue is being opened here rather than LightTable/docs.lighttable.com as that repo can continue to exist for the time being independent of this migration. Also, there may need to be updates made in Light Table as described below.

Stemming from discussion [here](https://github.com/LightTable/docs.lighttable.com/issues/10) we wish to try out GitBooks as an alternative to the current way user level docs are hosted and presented.

User level documentation at docs.lighttable.com (and the wiki, if applicable) is to be migrated to GitBooks. We will want to keep the docs.lighttable.com repo around in the event GitBooks does not work out.

#### Updates to Light Table

According to @kenny-evitt, if we shutdown the subdomain, we need to first change [the 'intro' page](https://github.com/LightTable/LightTable/blob/53a90bee4c2c6758e4b5dffdffbc32256a05e00d/src/lt/objs/intro.cljs) in LT to not point to this [URL](https://github.com/LightTable/LightTable/blob/53a90bee4c2c6758e4b5dffdffbc32256a05e00d/src/lt/objs/docs.cljs).

#### Examples

Some examples provided by @rundis of quality Gitbook examples:

-    http://redux.js.org/
-    https://guide.elm-lang.org/
-    https://rundis.gitbooks.io/elm-light-guide/content/

**Comment by Mouvedia** [comment]
> According to @kenny-evitt, if we shutdown the subdomain, we need to first change the 'intro' page in LT to not point to this URL.

Or you could just set up a 301 redirect on all requests on that subdomain.

**Comment by sbauer322** [comment]
All known user docs have been migrated to the [Light Table User Guide](). Their original form has more or less been preserved. A new task will be opened to start making our docs great again.

docs.lighttable.com and user docs on the wiki will remain where they are until the book is in a solid state.

**Comment by Mouvedia** [comment]
> …making our docs great again.

Iv heard this somewhere.
