### ISSUE TITLE
Create Light Table organization for GitBooks

### ISSUE THREAD

**Issue by sbauer322** [LightTable/LightTable#2262]
As the title suggests, we will want an open source organization account on GitBooks. They have already been contacted about establishing one.

**Comment by sbauer322** [comment]
The open source Light Table organization was approved on GitBooks. Initially, myself and @rundis are owners and can add contributors and collaborators as needed.

Feel free to ask us!

**Comment by Mouvedia** [comment]
https://www.gitbook.com/@lighttable
