### ISSUE TITLE
Rename link to go to a plugin's page to something more obvious

### ISSUE THREAD

**Issue by sbauer322** [LightTable/LightTable#2268]
`source` does not seem like suitable text for a link that navigates to a plugin's webpage / github page. It should either be renamed to something more salient, or actually link to the source code. 

![731ec694-73a8-11e6-918e-5ed77df3e635](https://cloud.githubusercontent.com/assets/2945386/18618379/b34d032e-7db3-11e6-9933-95e42242afee.png)

I suggest changing `Source` to `view`... or any other word that better describes the purpose of the button. Maybe `open`? I'm open to alternatives.

**Comment by chris-etheridge** [comment]
Maybe just `website` is a good enough name?

**Comment by sbauer322** [comment]
Ah, yes, that might be the clearest choice!

**Comment by Mouvedia** [comment]
What about repository instead? Most, if not all, link to a repository.

**Comment by sbauer322** [comment]
Certainly a good option too.

**Comment by chris-etheridge** [comment]
If you're happy with `website`, I don't mind adding it! I think `website` works, because the website for the plugin may not always be a repository, or on source control.

**Comment by sbauer322** [comment]
Thanks for opening PR #2289 which addresses this!

**Comment by sbauer322** [comment]
Closing as #2289 has been merged.
