### ISSUE TITLE
Plugin's name should be a link to the plugin's project page

### ISSUE THREAD

**Issue by sbauer322** [LightTable/LightTable#2269]
It would be nice to have the actual name of the plugin link to the plugin's project's page. This could make the `source` button redundant, thus making issue https://github.com/LightTable/LightTable/issues/2268 obsolete.

Personally, I keep expecting the project name to be a link.

**Comment by chris-etheridge** [comment]
Happy to do this!

**Comment by sbauer322** [comment]
Thanks for opening PR #2289 which addresses this!

**Comment by sbauer322** [comment]
This has been taken care of for a while now with #2289 being merged.
