### ISSUE TITLE
Unable to start lein-light due to spaces in path.

### ISSUE THREAD

**Issue by egonelbre** [LightTable/LightTable#227]
When starting instarepl it offers to "start a local client" this fails because the lein-light path isn't formatted properly for Windows.

Message is : "Error: unable to access jarfile c:\Users\Egon\"

It seems it tries to run this:

```
java -jar C:\Users\Egon\ Elbre\.lighttable/clients/lein-light-standalone.jar "C:\Users\Egon Elbre\.lighttable/"
```

Manually running from command-line, this works:

```
java -jar "C:\Users\Egon Elbre\.lighttable/clients/lein-light-standalone.jar" "C:\Users\Egon Elbre\.lighttable/"
```

I'm running Windows 7 64bit, Light Table 0.2.4, Binary 0.3.6-pre

**Comment by sebigavril** [comment]
@ibdknox The issue is present in 0.7.2
