### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by abhi18av** [LightTable/LightTable#2277]
I've recently discovered LightTable and I am really awed by the the consistent architecture it provides, I have *some* experience with ClojureScript. The architecture of LT and ClojureScript make me want to explore and hack on this editor all the more - after all who doesn't love Electron?

## Request for guidance

But I feel, the momentum is way less than what it's supposed to be. Look at the internals of Atom or even Emacs - it's all a bit chaotic to understand the flow of the program but with LT the core is just so beautiful!

So, I wish to contribute as much as I can to LT though I'd be asking a lot many questions regarding the 
- Build cycles
- Packaging of Linux builds using [AppImage](http://appimage.org/)
- Upgrading to Electron 1.x
- Upgrading the ClojureScript to ^1.9.x
- Documentation of APIs

In addition to this I've certain queries about the possibility of adding other text editors (such as QuillJS) as editors - is it possible in LT?

* How is the UI rendered?

* Would a move to React make the UI like a test arena for ClojureScript based WebDevelopment?
*  How about a plugin for making ClojurScript - NodeJS repl more approachable.

* How about an approachable test suite for increasing the iteration cycle?

## Request for a discussion website

Another thing I'd really like to stress upon is actually having a proper discussion forum like that of Rust_Lang/Sublime/Atom... ! Trust me for beginners this is much more approachable as compared to the current Google+ based forum.

#### I'm sorry is some of the questions are obvious, but I'd really like to help so please let me know how :)

**Comment by rundis** [comment]
Awesome !

We most definitely need people contributing. We are currently doing a push to document things a whole lot better to try to make it easier for people to contribute. Hopefully we are not to far off this being good enough to make an announcement and invite more people to contribute.
However don't let our pending work stop you from start contributing now :-)

Some ideas for things that might be helpful in the short term:
- If you haven't already, try to make something in Light Table. Try to make a simple plugin. You'll find some info on the wiki, or you might find some relevant info in the WIP developers guide. 
- See if there are any PR's you are able to test/verify (fork LT and try to test the PR locally). Comment on the PR with your results
- See if there are any issues that might be possible for you to give a go. We have started to try and highlight easier once by labelling them `beginner`

I think that playing with creating a plugin just to familiarize yourself with coding in LT is sort of a good first step and enabler to progress to contribute further.

For your other questions, I'd suggest talking to us on Gitter (see below). 

- **discussion** : Hit us up on Gitter. We have gitter room at: https://gitter.im/LightTable/LightTable  It may not be fantastic, but right now it's sufficient imho. We can always re-evaluate this later

**Comment by sbauer322** [comment]
I would likely just echo what @rundis has already written so I will simply go with some advice instead:

Don't feel discouraged if you have trouble developing or learning about Light Table! Chances are someone has already encountered the same problem... or you have simply found an area where we need to improve documentation. Please, let us know! We are happy to help and chances are can get you back on track. [Gitter](https://gitter.im/LightTable/LightTable) is currently the best place for that.

Welcome, and best of luck!

**Comment by Mouvedia** [comment]
@abhi18av

1. if you don't have an idea of what's missing just pick something out of the [wish list](https://github.com/LightTable/LightTable/projects/2) that you fancy
2. if you like challenges fix one of the two most requested features: #662 or #533
3. take care of several beginner issues
4. review some pending PRs

**Comment by abhi18av** [comment]
Okay, so I've gone through the mentioned links and the issue lists and I feel I have a better Idea of how to approach this so I'd start by adding a few bits and pieces on the ongoing LightTable guide all the while working through the codebase.

As mentioned in https://github.com/LightTable/LightTable/issues/2278 where should I put up my questions :)

Thanks for the guidance and quick response @rundis @sbauer322 @Mouvedia

**Comment by sbauer322** [comment]
For questions, I would still recommend our [Gitter](https://gitter.im/LightTable/LightTable) for the time being. We are anything but fast to adopt new platforms of communications! 😄 

For the ongoing [Light Table guides](https://www.gitbook.com/@lighttable), once you sign into Gitbook, you should be able to hover over a paragraph and a button will appear on the right that lets you start discussions / make comments / suggest improvements. Those guides are still being actively created, so they are not going to be complete references. 

If you were looking to contribute content to the guides, I believe you can fork the appropriate repository for the [user-guide](https://github.com/LightTable/user-guide) or [dev guide](https://github.com/LightTable/developer-guide), make changes, push to your fork, then open a pull request as you would normally with standard repositories.

**Comment by rundis** [comment]
Ok. I'm going to close this issue now. As it doesn't contain any further work items as far as I can tell. Let's keep future discussions in gitter or the mailing list.
cheers !
