### ISSUE TITLE
Vision of LightTable?

### ISSUE THREAD

**Issue by abhi18av** [LightTable/LightTable#2279]
Hi again)

Actually, I created this issue since I believe that having this well documented in the issue list would be an asset for the newcomers. 

So, as the title says - "What's the current vision of LightTable? " 

* Is it merely to sustain the wonderful work done previously?
* Or do we still aim for having LightTable a proper editor to be reckoned with - at par with Atom/Brackets/Sublime etc?
* If not, then what direction should LT ( being an artwork of ClojureScript and Electron ) should take to rejuvenate the contribution streaks?

I really wish to know what the current maintainers of LT feel about the issue?

**Comment by Mouvedia** [comment]
This doesn't really belong here. You should repost that on the mailing list and this issue should be closed.

Id say that the current contributors are maintaining LT. The new collaborators are not bound to work on anything specific; we don't have milestones on Github. At first, it could be frightening to not have a clear vision but it's also liberating in a strange way.

**Comment by rundis** [comment]
Agreed. And it's not meant to be unfriendly in any way shape or form. Just as I mentioned in another issue, we'd like the issue tracker to focus on things we can work on.

**Comment by abhi18av** [comment]
Okay, I'll keep this in mind :)
