### ISSUE TITLE
Connection Pane's arrow is the same in both states

### ISSUE THREAD

**Issue by sbauer322** [LightTable/LightTable#2286]
As the title says, the Connection Pane's arrow is always in the same direction.

Here is the initial state, where current connections are displayed:

![connection-pane-arrow-incorrect](https://cloud.githubusercontent.com/assets/2945386/19414704/b4feee3c-9323-11e6-9f2a-738c88fd9a57.png)

This arrow likely should be pointing downward.

For comparison, when you click on the 'Add Connection' button, the arrow is in the correct position indicating that it can be collapsed:

![connection-pane-arrow-correct](https://cloud.githubusercontent.com/assets/2945386/19414720/01f210d4-9324-11e6-9f4e-754ef35bdee1.png)

Alternatively, the arrow could simply be removed.

**Comment by pndpo** [comment]
I've got a real simple fix for this locally. I read through the docs and didn't find anything on github PR request flow. Is it fine to just PR from my fork and reference this bug?

**Comment by sbauer322** [comment]
Yes, that flow sounds perfect!
