### ISSUE TITLE
Make plugin manager title links more obvious

### ISSUE THREAD

**Issue by sbauer322** [LightTable/LightTable#2294]
Thanks to the work performed in this [pull request](https://github.com/LightTable/LightTable/pull/2289), the title of a plugin in the plugin manager is now a link.

One improvement would be to make it more obvious the title is actually a link. Currently, there is no indication the title is actually a link until you click it and a page is opened.

My initial thoughts were to simply mimic how links normally work. In other words, the title could become underlined and the mouse cursor change when hovering.

**Comment by chris-etheridge** [comment]
I was thinking about doing the same when implementing that pull request. Would be a simple change, and then the links would behave like they usually do in web browsers.

**Comment by sbauer322** [comment]
Closing issue as PR #2294 addresses it.
