### ISSUE TITLE
Upload not working after fresh install with PPA

### ISSUE THREAD

**Issue by knzudgt** [LightTable/LightTable#2328]
## Report a Bug

Upload not working

### Steps to Reproduce

I installed as common user Light Table using the following steps, as described at [itsfoss](https://itsfoss.com/install-lighttable-ubuntu/):

```
$ sudo add-apt-repository ppa:dr-akulavich/lighttable
$ sudo apt-get update
$ sudo apt-get install lighttable-installer
```

I launch as common user Light Table from Application/Programming/Light Table

Once launched, Light Table informs that there is an update availble for version 0.8.1
Version installed is in fact 0.8.0
Accept the update

The console shows the following errors:

```
Error: EACCES: permission denied, open '/opt/LightTable/resources/app/tmp.tar.gz'
    at Error (native)

Error: ENOENT: no such file or directory, open '/opt/LightTable/resources/app/tmp.tar.gz'
    at Error (native)

Error: EACCES: permission denied, mkdir '/opt/LightTable/resources/app/tmp'
    at Error (native)
```

### Environment

| Info                             | Details |
| -------------------------------- | ------- |
| Light Table version              |  0.8.0       |
| Operating system                 |  Linux Ubuntu 14.04 LTS       |

#### Relevant Plugins

Default plugins

#### Relevant Settings in your *user.keymap* and *user.behaviors* Files

Default setting

### Error Messages

```
Error: EACCES: permission denied, open '/opt/LightTable/resources/app/tmp.tar.gz'
    at Error (native)

Error: ENOENT: no such file or directory, open '/opt/LightTable/resources/app/tmp.tar.gz'
    at Error (native)

Error: EACCES: permission denied, mkdir '/opt/LightTable/resources/app/tmp'
    at Error (native)
```

**Comment by sbauer322** [comment]
@knzudgt, unfortunately 0.8.0 has an issue with its updating system where it does not update. In order to update, it is necessary to manually retrieve 0.8.1 from Light Table's [website](http://lighttable.com/) or the from downloads under the 0.8.1 [release tag](https://github.com/LightTable/LightTable/releases/tag/0.8.1).

Restoring the automatic updating is high on our priorities.

**Comment by sbauer322** [comment]
Closing this issue as a workaround has been provided.
