### ISSUE TITLE
LT Freezes When Opening - Ubuntu 15.04 64bit

### ISSUE THREAD

**Issue by PearJam** [LightTable/LightTable#2333]
I installed LT and it appeared to operate normally. I was able to open files etc..

I wanted to disable the intro window so I looked it up, found - https://github.com/LightTable/LightTable/issues/1258 - and put the following in the 'users.behaviors' file:

:- {
     :app [:lt.objs.intro/show-intro]

     :editor []}

Now LT only shows the intro window lol. It won't open past that, including any version I try.

I've tried a variety of things:
- Installed older versions and tested, same issue.
- Chown -R to my user. Chmod -R all to 777.
- Tried opening as super user.
- Tried installing in opt/.
- Tried just downloading and running start script.
- Tried opening as bash, sh and ./LightTable.
- Some post described an issue with the bash script not getting the right uname so I replaced the script with the suggested one, no change.
- Tried using installer from http://ppa.launchpad.net/dr-akulavich/lighttable/ubuntu/pool/main/l/lighttable-installer/

I didn't see anything that stood out to me looking in var/logs.

I can get some errors from starting up via command line:

(note in below I was using an older version, it's the same for all versions)

 ~/Downloads/lighttable-0.8.0-alpha-linux ./LightTable
[1631:0418/163158:ERROR:browser_main_loop.cc(185)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[1631:0418/163158:ERROR:socket_libevent.cc(122)] bind() returned an error, errno=98: Address already in use
[1631:0418/163158:ERROR:devtools_http_handler.cc(224)] Cannot start http server for devtools. Stop devtools.
[1656:0418/163158:INFO:renderer_main.cc(200)] Renderer process started
^C
 ~/Downloads/lighttable-0.8.0-alpha-linux killall LightTable
 ~/Downloads/lighttable-0.8.0-alpha-linux killall LightTable
LightTable: no process found
 ~/Downloads/lighttable-0.8.0-alpha-linux ./LightTable
[1765:0418/163249:ERROR:browser_main_loop.cc(185)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[1790:0418/163249:INFO:renderer_main.cc(200)] Renderer process started

 ~/lighttable sudo bash LightTable
LightTable: LightTable: cannot execute binary file
 ~/lighttable bash LightTable
LightTable: LightTable: cannot execute binary file

I'm so fed up with the Sublime's pop-ups and 'spinning wheel', other alternatives don't suite me, so when I found LT, I thought I found "the one"... I really think I'll like using LT and can't wait to get started - I hope someone can help!!

Thank you!

**Comment by sbauer322** [comment]
Sorry to hear you are having some troubles!

Could you share the contents of your `user.behaviors` file via something like [Gist](https://gist.github.com/)?

Also, and I don't think this will necessarily help your issue, but there is an 0.8.1 release available via the [Light Table website](http://lighttable.com/). Release 0.8.0 managed to break the upgrading process.

**Comment by sbauer322** [comment]
If it helps, here is default initial `user.behaviors` file is [here](https://github.com/LightTable/LightTable/blob/master/deploy/core/User/user.behaviors). Using the above file, you should simply be able to add the following to disable the welcome screen:

```
[:app :-lt.objs.intro/show-intro]
```

The formatting from the issue you linked might not be compatible with recent versions of LT. I did notice the  issue has a timestamp of 2014... so it may be the case things have changed. 

If the above works then I will update that issue accordingly.

**Comment by PearJam** [comment]
Thank you so much for responding!!

Version 0.8.1 is the one I'm trying. The paste in the OP is when I was trying older versions to see if it corrected the issue. *All* versions hang the same way (stops at opening screen).

The users.behaviors file is 'stock'.
- I download 0.8.1 (or any version).
- Extract.
- Run "light" or "LightTable".
- Hangs on opening screen.

I agree that the formatting is different on the snip I pasted into user.behaviors file. I noticed (after messing it up) that the version was different for the code I pasted into the file, and found the current one (which is different from what I pasted in - the same as the snip you provided).

The history looks like this:
- I downloaded the latest LT.
- Everything worked.
- I accidentally pasted old code in the current user.behaviors file.
- Nothing works - not even a fresh install of the current version, or any older version.

As a side note:
I did a strace on it and I can't get anything from it.
The parent thread waits, the last thread loops indefinitely.

Is it possible there's some dependency that was messed up? Like cojure (sp) or electron?

Is it possible there was an environmental variable that was changed?


Thank you for your help - and please keep helping (anyone). I can't stand ST3, and up until I some how broke it, LT looked like the answer to all my ST3 woes.

**Comment by sbauer322** [comment]
Just to confirm, LT was working until you started making changes to the `user.behaviors` file?

**Comment by PearJam** [comment]
Yes.

I downloaded it - it worked - I pasted old code - nothing works, not even a fresh install or older versions.

**Comment by sbauer322** [comment]
Hmm, very odd. Assuming there are no significant changes to you wanted to keep, would you mind trying to delete the contents of `~/,config/LightTable` (or wherever your LT config folder is located) and then opening Light Table?

**Comment by PearJam** [comment]
IT WORKS!!!!!

You sir, are a coding-life saver!!

Wow.. I even know about the .config file and didn't think to check it. I thought I was loosing my mind lol.

Seriously, thank you so much..

Are you LT's author?

**Comment by sbauer322** [comment]
Glad to hear it works!

I am not LT's original author, that was @ibdknox. As he is now focusing on [Eve](http://witheve.com/), Light Table has been transitioned to the open source community since release 0.7.0 in late 2014. I am one of the current maintainers.

**Comment by PearJam** [comment]
Ahh, ok. Either way I plan on blogging about LT as an alternative to ST3 to help get the word out. I'll try to find a way to let you know when I do (it'll be a wile, I'm working on a new design).

Thank you again! I'll close this issue!
