### ISSUE TITLE
Is php twig template is supported by light table editor?

### ISSUE THREAD

**Issue by shahzadthathal** [LightTable/LightTable#2340]
Hi,

Is PHP twig template is supported by light table editor?

Thanks

**Comment by rundis** [comment]
I don´t think so. Should be quite easy to create a simple plugin to add the codemirror mode that exists to give some support though

**Comment by kolya-ay** [comment]
@rudis, @shahzadthathal, actually Codemirror already has support for twig templates [since 5.4](https://github.com/codemirror/CodeMirror/releases/tag/5.4.0). However LT still uses obsolete 4.7.0 version. It should definitely be updated to keep LT alive.
