### ISSUE TITLE
How do I build this from source?

### ISSUE THREAD

**Issue by yamboy1** [LightTable/LightTable#2344]
I would like to install this on a Raspberry Pi. It uses an ARM processor, so the x64 binary won't work and I would like to install this from source. However I have no experience using clojure. How do I do this?

**Comment by rundis** [comment]
Check out this page (and note the prerequisites!)

**Comment by rundis** [comment]
No idea whether it will work though...

**Comment by sbauer322** [comment]
I am not aware of ARM support either and am dubious that the current build will work without additional tweaking.

If you had and luck or find out additional information then please feel free to update us on your findings.

Closing this issue @rundis provided the current build instructions.
