### ISSUE TITLE
FileChooser Character Encoding

### ISSUE THREAD

**Issue by sirolf2009** [LightTable/LightTable#2349]
I've just downloaded light table from the official repo, version 0.8.1 for linux and my filechooser doesn't display any text. I'm running Parrot OS.
```bash
$ uname -a
Linux parrot 4.9.0-parrot13-amd64 #1 SMP Parrot 4.9.13-1parrot1 (2017-03-02) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Parrot
Description:	Parrot 3.7 - JollyRoger
Release:	3.7
Codename:	JollyRoger
```
![screenshot at 2017-07-29 15-00-53](https://user-images.githubusercontent.com/3534736/28745026-401a4764-746f-11e7-92f1-f4cc0c1ee878.png)

**Comment by sbauer322** [comment]
We seem to be having the same problem with [ArchLinux](https://github.com/LightTable/LightTable/issues/2343) as well.

Would you know what version of python you have installed on your system?

**Comment by sirolf2009** [comment]
Yeah
```bash
$python --version
Python 2.7.13
$python3 --version
Python 3.5.3+
```

**Comment by sbauer322** [comment]
Thanks!

Since this is occurring on at least three linux OSes at this point, I am going to close this issue in favor of https://github.com/LightTable/LightTable/issues/2343.
