### ISSUE TITLE
Eval clojure in Readme.md And Block Selected Eval

### ISSUE THREAD

**Issue by azizzaeny** [LightTable/LightTable#2350]
How do you eval if specified fileTypes not in context...
and expected result of select text then eval... is recursively send individualy block of code and get inline result rather than  single result in the end of selected text 

example: 
i want to eval just inside markdown code 

nb: see comment below
readme.md 
```txt
## About
content

```clj
(ns boot.user) ; => 1

(def deps '[[org.clojure/clojure "1.8.0" :scope "provided"]
            [adzerk/boot-cljs "2.0.0-SNAPSHOT" :scope "test"]  
            [org.clojure/clojurescript "1.9.293"  :scope "test"]
            [metosin/boot-alt-http "0.1.2" :scope "test"]]) ; => 2

;; need to set default dependencies
(set-env! :dependencies deps
            :resource-paths #{"resources" "src"}) ; => 3

;; start building clojurescript

(require '[adzerk.boot-cljs :as js]
         '[metosin.boot-alt-http :as alt-http]) ; => 4

(boot (watch) (alt-http/serve) (js/cljs :ids #{"public/main"})) ;; => not ended result here but at 1, 2, 3, 4

```
```

**Comment by sbauer322** [comment]
If I understand correctly, as far as I know, clojure eval can only occur in clojure files. Attempting to eval code in a markdown file will not work.

Hope that helps! :grinning:
