### ISSUE TITLE
I received error "the system cannot find the specified file" in clojure scripts

### ISSUE THREAD

**Issue by yilmazedis** [LightTable/LightTable#2352]
![capture](https://user-images.githubusercontent.com/15719990/31057573-a5659690-a6ed-11e7-9c1f-4ac5d02320dc.PNG)
Altought I have working same directory my clojure file and examp.txt . i received "the system cannot find the specified file" always. What should i do. please help.

**Comment by MarcusE1W** [comment]
Could you check the file name? Your directory is called 'example'. And you check for 'exampl.txt'. Is the missing e in the filename intentional?

**Comment by sbauer322** [comment]
Closing this issue as user has not followed on questions. Happy to help if it is still a problem.
