### ISSUE TITLE
tofu in file dialog, 0.8.1

### ISSUE THREAD

**Issue by davidwords** [LightTable/LightTable#2360]
### Steps to Reproduce

 1. Open file, or open folder
 2. Tofu! (See screenshot.)

### Environment

| Info                             | Details |
| -------------------------------- | ------- |
| Light Table version              |   0.8.1      |
| Operating system                 |  Ubuntu Linux 17.10       |

#### Relevant Plugins

This is a new, plain-vanilla installation, from tarball.

![lighttable0 8 1](https://user-images.githubusercontent.com/1211551/33923100-296fdd78-df9d-11e7-97e4-6264eaeca8e7.png)

**Comment by maddin79** [comment]
Same here ...

**Comment by tbalashov** [comment]
any ideas?

**Comment by MarcusE1W** [comment]
A known problem, unfortunately not solved. Please see Issue #2343 and PR #2359

**Comment by sbauer322** [comment]
Closing this issue in favor of #2343.
