### ISSUE TITLE
File missing in lighttable's workspace view

### ISSUE THREAD

**Issue by Miku25** [LightTable/LightTable#2361]
I have a folder with 4 files of which only 3 show up in Lighttable's workspace view. All the files have the exact same access rights etc.

Steps to reproduce
1. Clone the certain repo from git
2. Add the folder as a workspace through Lighttable
3. Navigate to the certain folder

Very strange bug and might be hard to pin down but took me some time before I realized this was the case and can be very troublesome overall.

**Comment by rundis** [comment]
Could it it be that your missing file matches the following regex : `"^\\.|\\.class$|^target/|svn|cvs|\\.pyc$|~$|\\.swp$|\\.jar$"`

Files matching this regex is by default filtered from the workspace/file tree.

**Comment by Miku25** [comment]
So it would seem. Still annoying, even if intended, that naming a file "cvsubview" makes it dissapear entirely from the view.

**Comment by sbauer322** [comment]
I can duplicate the problem with the filename `cvsubview`, `dcsvsubview`, and `cvssubview.css`. I believe it is indeed a problem with the file match regex.

We'll need to either improve the file matching or make it more obvious what is going on to the user.

The simplest approach might be to provide an option in the right click context menu for a project to toggle hidden file visibility.

**Comment by Mouvedia** [comment]
Until someone fixes the regex you will have to overwrite `:lt.objs.files/file.ignore-pattern`.

related issues: #818, #1153

**Comment by denis631** [comment]
Can not we just add change it to ``` ... | ^svn$ | ^cvs$ | ... ``` ?

**Comment by sbauer322** [comment]
With #2371 merged, this should no longer be an issue.
