### ISSUE TITLE
create a .yml for up-for-grabs (as a PR)

### ISSUE THREAD

**Issue by Mouvedia** [LightTable/LightTable#2366]
http://up-for-grabs.net/
https://github.com/up-for-grabs/up-for-grabs.net#add-a-project

The `link` value would currently be `https://github.com/LightTable/LightTable/labels/beginner`.

BTW Id recommend to rename the _beginner_ to _good first issue_.
cf https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/

**Comment by Mouvedia** [comment]
@sbauer322 could you add the beginner label?

**Comment by sbauer322** [comment]
The label has been added to this issue, and the `beginner` label has been renamed `good first issue` to better align with Github's recommendations.

**Comment by Mouvedia** [comment]
#2369
