### ISSUE TITLE
Add Code Of Conduct

### ISSUE THREAD

**Issue by sbauer322** [LightTable/LightTable#2375]
See https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

**Comment by Mouvedia** [comment]
> [Be respectful toward other members of the community. Don't initiate or engage in discussions that are designed to insult, inflame, attack, or incite hate/discrimination/bullying against others. Don't feed the trolls. If we detect any kind of behaviour we consider unacceptable, we reserve the right to ban, block, or remove the involved members from any or all of our communities.](https://github.com/reactos/reactos/blob/master/CODE_OF_CONDUCT.md)

How's that?
