### ISSUE TITLE
Add LT to codeshelter

### ISSUE THREAD

**Issue by Mouvedia** [LightTable/LightTable#2383]
> [Code Shelter is a collective of volunteer software developers that aims to help with maintaining popular open source projects whose authors no longer have time to.](https://www.codeshelter.co)

**Comment by Mouvedia** [comment]
@kenny-evitt @rundis @sbauer322 @cldwalker @ibdknox

**Comment by Mouvedia** [comment]
@jamii @MikeInnes

**Comment by sbauer322** [comment]
All LT repos have been addeed to Code Shelter. This can be reversed should an issue arise or someone disagrees with the decision

**Comment by skorokithakis** [comment]
I just saw the addition, thank you for adding the project to the Code Shelter! I'd be happy to add any maintainer of LightTable who wanted to as a maintainer to Code Shelter, as having commit privileges to LightTable is credential enough.

**Comment by sbauer322** [comment]
@skorokithakis I'd be happy to be added to Code Shelter.

The LT projects are largely undocumented and in dire need or help so if anyone has questions I am happy to assist

**Comment by skorokithakis** [comment]
@sbauer322 if you visit and follow https://www.codeshelter.co/maintainer-application/, I'd be happy to approve you ASAP.

**Comment by MikeInnes** [comment]
Is there a particular reason for the interest in this project now? My guess is that most users and developers have moved on to newer projects like Atom and VS Code, and aside from being much more polished editors, there are plenty of ways to get LT-like features (and then some) on top of them.

Can't stop anyone from spending their time as they please, I just suspect that at this point code shelter's maintenance effort can be better used elsewhere.

**Comment by skorokithakis** [comment]
Code Shelter is mostly project-specific, since it doesn't tell the maintainers what to work on, so there's no harm in leaving LightTable in. If a CS maintainer wants to work on LT and LT isn't available, they might just not work on anything, it doesn't necessarily mean they'll work on something else, so there's no effort being wasted by LT being in CS.
