### ISSUE TITLE
Plugin refresh: Extract -> extract

### ISSUE THREAD

**Issue by prertik** [LightTable/LightTable#2411]
Obtained from Dublo/LightTable-forked#6 reported by @MarcusE1W

**Comment by Mouvedia** [comment]
dupe of #2138
cf https://github.com/LightTable/LightTable/pull/2176/files/8f2dfbac0efa01a0d12d776b7027431f7161dc22..7867d36060fb7e7ee2fa3c4c34d056aa5c39a918#diff-a27d831e5730304bc2b99611ccb6b7bbR137
