### ISSUE TITLE
Problem saving file to Debian 10 stable

### ISSUE THREAD

**Issue by ghost** [LightTable/LightTable#2453]
When I am going to save a file from the editor and it asks for the path, I get a window with quite a few small boxes.

[<a href="https://i.imgur.com/y6cU0oo.png">
  <img src="https://imgur.com/y6cU0ool.png" />
</a>](url)

**Comment by mariopr25** [comment]
I have the same issue, but not only saving, also opening files

Im using Kubuntu 19.10.

**Comment by prertik** [comment]
Hi, this is an issue, I'm tackling currently. This needs other linking updates.
