### ISSUE TITLE
qualified keywords don't show up as such in the instarepl

### ISSUE THREAD

**Issue by strangemonad** [LightTable/LightTable#246]
e.g. of what get's printed in the instarepl
(ns user) => nil
::blah
(= ::blah :user/blah) => true

I would expect ::blah to show up as :user/blah as it does in a regular clojure repl

**Comment by BenjaminVanRyseghem** [comment]
Still not showing in Light Table version: 0.7.2, Binary version: 0.22.1

**Comment by cldwalker** [comment]
This issue has moved to https://github.com/LightTable/ClojureInstarepl/issues/11 as the instarepl is now its own plugin
