### ISSUE TITLE
Installing Light Table

### ISSUE THREAD

**Issue by ghost** [LightTable/LightTable#2486]
I have OS Ubuntu 20.04 (Focal Fossa). I tried to install IDE Light Table (for Clojure).
shem@lenovoip:~$ umake ide lighttable
/usr/lib/python3/dist-packages/umake/tools.py:92: YAMLLoadWarning: calling yaml.load() without Loader=… is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
self._config = yaml.load(f)
Choose installation path: /home/shem/.local/share/umake/ide/lighttable
Downloading and installing requirements |
100% |#########################################################################|
Installing LightTable
/home/shem/.local/share/umake/ide/lighttable/LightTable |
|##############################################################################|
Installation done
shem@lenovoip:~$ lighttable
lighttable: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
I see the installed program icon In the Application Center but it does not start. Something went wrong? Thanks.

**Comment by didier-deschamps-magnetiques** [comment]
As Lighttable is an Electron package, you’ll need to install gconf libraries to run it.

You can find informations about that in the README.md file.

**Comment by ghost** [comment]
Already 100 years have passed before you bothered  to answer me. Only VIM!!! Goodbye.Отправлено со смартфона Samsung Galaxy.
-------- Исходное сообщение --------От: Didier Deschamps Magnétiques <notifications@github.com> Дата: 24.05.20  14:53  (GMT+03:00) Кому: LightTable/LightTable <LightTable@noreply.github.com> Копия: incomer17 <incomer17@gmail.com>, Author <author@noreply.github.com> Тема: Re: [LightTable/LightTable] Installing Light Table (#2486) 

As Lighttable is an Electron package, you’ll need to install gconf libraries to run it.

You can find informations about that in the README.md file.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/LightTable/LightTable/issues/2486#issuecomment-633219721",

"url": "https://github.com/LightTable/LightTable/issues/2486#issuecomment-633219721",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
