### ISSUE TITLE
Harfbuzz version too old (1.0.0)

### ISSUE THREAD

**Issue by spyro-98** [LightTable/LightTable#2488]
The editor crash during the opening.
After run the bash script named "light" the terminal show this error:
**(LightTable:47234): Pango-ERROR **: 00:21:09.661: Harfbuzz version too old (1.0.0)**

**Branch**
I downloaded the editor from the website, extract all and execute the "light" script. 
LightTable script also make an error:
**(LightTable:47641): Pango-ERROR **: 00:26:28.772: Harfbuzz version too old (1.0.0)
Rilevato trace/breakpoint (core dump creato)**

**To Reproduce**
1. Go to the folder of the software
2. Execute ./light or ./LightTable

**Expected behavior**
The editor opens

**Screenshots**
![Schermata del 2020-05-11 00-30-54](https://user-images.githubusercontent.com/31597742/81512170-cb758500-931e-11ea-8f50-813edcb6b1bf.png)

**Desktop (please complete the following information):**
![Schermata del 2020-05-11 00-30-00](https://user-images.githubusercontent.com/31597742/81512147-936e4200-931e-11ea-8cee-7e2819e20ed3.png)

**Comment by ell1e** [comment]
Same problem here on Fedora 32

**Comment by TheArturZh** [comment]
Same problem, Kubuntu 20.04 LTS. I have a 2.6.4 version of HarfBuzz installed.

**Comment by esemds** [comment]
Same problem, Arch linux 5.6.11-arch1-1 :(

**Comment by skamansam** [comment]
Of which issue is this a duplicate? I can only find this one when I do a search for `Harfbuzz`.

**Comment by Hayao0819** [comment]
I have encountered the same situation on Arch linux.
This issue is not duplicate with any of the issues I have seen.

**Comment by prertik** [comment]
This is not directly a duplicate issue of harfbuzz but, it is an issue related to the version of electron. updating electron makes this issue go away and we are already tracking electron update issues so, it is a duplicate or sub-issue for that.

**Comment by softerdk** [comment]
> Same problem here on Fedora 32
Also a problem on Fedora 34 :-)
(LightTable:32488): Pango-ERROR **: 23:23:12.371: Harfbuzz version too old (1.0.0)

**Comment by Hayao0819** [comment]
I have updated electon and it has been latest. But it has still not been fixed.

**Comment by glyh** [comment]
Crash into the same problem on Wayland(Sway), Arch Linux. 

@prertik If this is duplicate, is there a solution, or other issue that we can refer to?

**Comment by prertik** [comment]
@glyh Sadly no. There's not one immediate fix. As I mentioned in the discussion: https://github.com/LightTable/LightTable/discussions/2506 work is going on a new version and that can only fix these electron/packages issue.
