### ISSUE TITLE
All characters appear as rectangles in the open folder/file dialog

### ISSUE THREAD

**Issue by francois90** [LightTable/LightTable#2493]
**Describe the bug**
All is in the title, see screenshots below.

**Branch**
Production build downloaded from http://lighttable.com/

**To Reproduce**
1. Download LT for Linux from http://lighttable.com/
2. Extract files
3. Run LightTable
4. Click File -> Open file or Open folder

**Expected behavior**
Letters should appear instead of rectangles

**Screenshots**
![image](https://user-images.githubusercontent.com/2145890/85508321-58c91c00-b5e3-11ea-89a0-ace56abf74db.png)

**Desktop (please complete the following information):**
 - OS: Debian 10
 - LT Version 0.8.1

**Comment by Mouvedia** [comment]
dupe of #2343
