### ISSUE TITLE
On trying to connect to a project, I get the error 'We couldn't find java'

### ISSUE THREAD

**Issue by murtaza52** [LightTable/LightTable#263]
Hi,

I have my lein working correctly, and the java options appear on typing 'java' in the command line. 

However when I open lighttable and try to connect to a project, I get the error 'We couldn't find java' ?

I also have JAVA_HOME set. How do I debug this error ?

Thanks,
Murtaza

**Comment by kenny-evitt** [comment]
Re-open if you're still having this issue on the latest version.
