### ISSUE TITLE
Light table has no way of showing recursive proceses.

### ISSUE THREAD

**Issue by 11Kilobytes** [LightTable/LightTable#31]
One of the most important things such an interactive IDE such as light table can have, especially when dealing with functional programming languages such as clojure is a way of showing recursive processes (yes I read SICP and it's awsome)

A way I suggest showing recursive processes is demonstrated on this website (roll over the text):
http://community.schemewiki.org/?sicp-ex-1.10

The only problem is that it won't work for functions that output complex data such as HTML or nested record structures.

**Comment by kenny-evitt** [comment]
Relevant paper describing "RainbowScheme":

 - [Visualizing Evaluation in Scheme](http://www.mis.yuntech.edu.tw/~tungsh/lasc.pdf)

**Comment by kenny-evitt** [comment]
I added this to the [Feature wishlist](https://github.com/LightTable/LightTable/wiki/Feature-wishlist) wiki page.
