### ISSUE TITLE
"Don't Show Welcome Screen Again" option

### ISSUE THREAD

**Issue by dubiousdavid** [LightTable/LightTable#358]
It would be nice to have a "Don't Show Welcome Screen Again" option on the welcome screen.  Maybe it would only be overridden if there is new information that needs to be communicated due to an important update.

**Comment by thSoft** [comment]
I'd vote for reopening. I'd propose that welcome screen should only appear on first startup before installing/updating LT.

**Comment by abhi18av** [comment]
+1, it does get annoying after a while.

**Comment by rundis** [comment]
Just add `[:app :-lt.objs.intro/show-intro]` to your user.behaviors file.

**Comment by rundis** [comment]
If someone think the above solution is insufficient, feel free to submit a PR that updates the user.behaviors file for you from the welcome screen or something to that effect. 
Locking this issue down
