### ISSUE TITLE
Non-ASCII character syntax highlighting

### ISSUE THREAD

**Issue by thoradam** [LightTable/LightTable#426]
It looks like the syntax highlighting has some trouble with non-ASCII characters:

![Screen Shot](https://f.cloud.github.com/assets/519188/354607/21893ef0-a0a6-11e2-90fa-5bdb9884b528.png)

**Comment by gjvnq** [comment]
It is still a problem on 0.8.0 with Clojure, LaTeX and probably other language's syntax highlighting.

**Comment by cldwalker** [comment]
@gjvnq Can you give a specific example? Syntax highlighting is working for me with `:ãvião_Ícone` and the Clojure mode [we're about to release](https://github.com/LightTable/Clojure/pull/70)
