### ISSUE TITLE
Unable to run Light Table 0.4 (Linux64) on Ubuntu 13.04 (more libudev issues)

### ISSUE THREAD

**Issue by sherbondy** [LightTable/LightTable#453]
Hey Chris,
Just downloaded the latest and greatest, did:

```
tar -xzvf /LightTableLinux64.tar.gz
mv LightTable/ /usr/local
cd /usr/local/LightTable
./LightTable
```

to test things out, but the process exited with the following output:

```
[11471:0430/122322:ERROR:zygote_host_impl_linux.cc(146)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.

(LightTable:11471): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",
[11471:0430/122322:INFO:gpu_info_collector_linux.cc(78)] NVCtrl extension does not exist.
```

As stated in the title, this is the 0.4.0 Linux64 binary running on Ubuntu 13.04.
For what it's worth, I've currently got my version of libudev, located in:
`/usr/lib/x86_64-linux-gnu/libudev.so` symlinked to `/usr/lib/libudev.so.0`

I'm guessing this all stems from: https://code.google.com/p/chromium/issues/detail?id=226002

The version of libudev that ships with Ubuntu 13.04 is 1.2.2, so it's understandable if there are incompatibilities.

I tried installing the [libudev0 deb package](https://launchpad.net/ubuntu/+source/udev/175-0ubuntu19/+build/4325788/+files/libudev0_175-0ubuntu19_amd64.deb) linked to in the chromium issue thread and removing my old symlink, but the issue persists.

I'm sure this will be resolved further upstream soon enough, just a heads up.

**Comment by jagledy** [comment]
I am having this same problem. Light Table worked fine for me the first time I downloaded it. I enabled vim key bindings and it crashed on me. I have tried everything suggested in this thread, as well as building the latest git build. Still not working for me.

**Comment by learner010** [comment]
>>libudev.so.0 or libudev.so.1 not found in any of /lib64 /lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu /usr/lib64 /usr/lib /lib.

I have installed libudev1, even tried linking at x86_64-linux-gnu but still not working

**Comment by kenny-evitt** [comment]
@jagledy @learner010 Are you seeing the exact same error message as the creator of this issue? Would you both trying building and running the *atom-shell* branch and confirming whether this is still an issue for that version?

**Comment by learner010** [comment]
i downloaded the latest code 2 days ago and tried it. it threw the error above.

**Comment by kenny-evitt** [comment]
@learner010 You downloaded the latest code from the *atom-shell* branch? Can you confirm that the libudev files *do* in fact exist in one of the locations mentioned in the error?
