### ISSUE TITLE
Add Previous Tab Command (in the sense of last seen)

### ISSUE THREAD

**Issue by tp** [LightTable/LightTable#460]
I added myself a key binding for "previous tab", just to find out that it rather means "tab to the left".

Is a command planned to get to the previously seen tab?

Sublime has a rather nice implementation that is now ingrained into my workflow, where you can switch multiple tabs back via the "previous tab" command if you hit it repeatedly, and then you cycle between the current and the last (form where you started to go back) again.

I hope I explained my wish for this well, but totally understand if LT has different concepts in mind and doesn't take specific features from other tools.

**Comment by BenjaminVanRyseghem** [comment]
any news here?

**Comment by cldwalker** [comment]
Closing as this functionality can be implemented as a plugin as demonstrated in @joshuafcole links above. If anyone is interested in making it a plugin, happy to help them with it. Added to [the wishlist](https://github.com/LightTable/LightTable/wiki/Feature-wishlist#general) in the meantime

**Comment by Mouvedia** [comment]
Anyone managed to do it? If so how?
`[:tabs-extended :lt.plugins.user/last-tab]` doesn't seem to be enough.

Apart from adding/editing the user.cljs, is there anything else that needs to be done?

**Comment by Mouvedia** [comment]
Here are the steps to enable the `:tabs.last` behaviour:

1. add user plugin to workspace
2. replace user.cljs with https://github.com/joshuafcole/lt-user-plugin/blob/master/src/lt/plugins/user.cljs
3. add these behaviours:
```
 [:tabset.tab :lt.plugins.user/push-active-tab]
 [:tabs-extended :lt.plugins.user/last-tab]
```
4. eval everything once in the user.cljs or restart LT

**Comment by kenny-evitt** [comment]
@Mouvedia Thanks

**Comment by Mouvedia** [comment]
@kenny-evitt np.

disclaimer: moving tabs will now have a minor bug (if you are switching a tab with the juxtaposed last tab.

**Comment by kenny-evitt** [comment]
@Mouvedia What's the bug?

**Comment by Mouvedia** [comment]
@kenny-evitt Ill give you one way to reproduce it:

1. 4 tabs open A, B, C and D
2. B is the last and D is active
3. move C so that you end up with this order: A C B D
4. B title tab has the hover styling
