### ISSUE TITLE
Adding folder to the wrokspace that resides on a samba network share freezes LightTable

### ISSUE THREAD

**Issue by MrException** [LightTable/LightTable#462]
On my Windows machine I use Vagrant while developing a small AngularJS project.

I share the project code folder on the Vagrant VM using Samba, and then connect to it from Windows. I can't just share a folder from Windows to the vagrant server. Unfortunately, it has to be this way for livereload type functionality to work properly.

Opening this folder in LightTable totally freezes up the editor for a pretty good amount of time. It eventually comes back and is useable.

**Comment by uripatish** [comment]
Still happening in lighttable 0.8.0

**Comment by kenny-evitt** [comment]
@uripatish Any chance you could create something like a (small) vagrant VM that we could use to reproduce this? Otherwise, I can probably setup a Samba share eventually.
