### ISSUE TITLE
CSS and JS Preprocessor support

### ISSUE THREAD

**Issue by techwraith** [LightTable/LightTable#493]
The app that I'm working on uses Browserify and Rework. This means that my source files do not directly map to the files in the browser. This produces unexpected results when evaling code.

Any chance we could get support for things like LESS, SASS, Stylus, Rework, Browserify, and (ew) CoffeeScript?

**Comment by xuv** [comment]
@jaredly Sorry for bumping up a closed issue. But did you have some time to work on that lesscss preprocessor: I'm guessing it should be pretty easy to cook it from the Sass one. But before digging in that, I'd like to know if you did anything already.

**Comment by jaredly** [comment]
Nope, I never did end up working on it
