### ISSUE TITLE
node JS parameters

### ISSUE THREAD

**Issue by zachaller** [LightTable/LightTable#494]
is there a way to pass params to a node js connections such as harmony for your project we need harmony support so we normally start node with 

node --harmony app.js

**Comment by frankcash** [comment]
If this issue is still open I'd be happy to attempt to solve it

**Comment by gavocanov** [comment]
+1, it's a must have IMHO
BTW, the alias workaround does not work here on OSX 10.10.3

**Comment by kenny-evitt** [comment]
[I think I've got this working.](https://github.com/kenny-evitt/Javascript/tree/add-node-js-parameters)

I've only been running it against a local build of the latest *atom-shell* branch (on a Mac).

To use, add an entry like this to your *user.behaviors* file:

```
[:app :lt.plugins.js.node/node-js.start-options "--harmony"]
```

I used the *hello-world* example from the Koa example apps:

 - [koajs/examples](https://github.com/koajs/examples)

and connected Node.js to the *app.js* file for that example. I can then access the example at *http://localhost:3000* tho I do see the following logged to the console:

```
app.js[stderr]:
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at Application.app.listen (/Users/kenny/@code/examples/node_modules/koa/lib/application.js:69:24)
    at /Users/kenny/@code/examples/hello-world/app.js:9:25
    at Object.exports.runInContext (vm.js:64:17)
    at sbRequire (/Users/kenny/@code/LightTable/builds/lighttable-0.8.0-mac/LightTable.app/Contents/Resources/app/plugins/Javascript/node/ltnodeclient.js:99:10)
    at init (/Users/kenny/@code/LightTable/builds/lighttable-0.8.0-mac/LightTable.app/Contents/Resources/app/plugins/Javascript/node/ltnodeclient.js:121:3)
    at Socket.<anonymous> (/Users/kenny/@code/LightTable/builds/lighttable-0.8.0-mac/LightTable.app/Contents/Resources/app/plugins/Javascript/node/ltnodeclient.js:20:5)
```

The example continues to work even after the above error is logged.

**Comment by kenny-evitt** [comment]
@zachaller @skeet70 @fbender @eafzali @gavocanov Anyone interested or willing to test my initial attempt? You should be able to clone my fork into the plugin directory and then refresh the plugin list in LT.

@frankcash If you're still available and willing to help, I'd appreciate a review of my changes.

**Comment by gavocanov** [comment]
@kenny-evitt I built the latest atom-shell branch, cloned your fork in the plugins directory and it works like a charm, all "harmony" features seems working (let, const, arrow functions etc.).

Thanks a lot!

**Comment by cldwalker** [comment]
@kenny-evitt I've verified this works with a few harmony features:

```js
"foo".contains("f")
"f".startsWith("f")
var a = [
  "Hydrogen",
  "Helium",
  "Lithium",
  "Beryl­lium"
];
a.map( s => s.length );
```

Nice work!
Code feedback:
* Most of LT's behaviors don't log to console and if they do it's because the user isn't sure what/when something has been set. This behavior seems straightforward (if behavior present -> enabled) and so we probably don't need it. Your call
* Given the behavior is already in a  `lt.plugins.js.node` namespace, adding a `node-js` subnamespace seems redundant. Perhaps `node-start-options`?
* Could you remove [client-command](https://github.com/kenny-evitt/Javascript/commit/3240e22af0b90afb463eb01fd1d4d5d9643d2ade#diff-7a6e9b44ddbea584080591acea450cefR89) in your PR? It's not being used and if it were it would've been in the `:args` you changed?

**Comment by cldwalker** [comment]
@kenny-evitt Your branch is close to knocking this out. Want to open a PR for it and address the minor feedback?

**Comment by kenny-evitt** [comment]
@cldwalker Thanks for the eyes. I created [a PR for my changes](https://github.com/LightTable/Javascript/pull/17/files) and I just pushed a rebase of my changes and your suggestions.

The console logging was just a quick aid for debugging.

I don't remember why I named the behavior the original name. I changed it to your suggestion.

I removed `client-command`.

**Comment by kenny-evitt** [comment]
This is in the latest version of the JavaScript plugin. You should be able to update to that version from within LT.
