### ISSUE TITLE
Errors sometimes incorrectly persist in python editor

### ISSUE THREAD

**Issue by simonhughes22** [LightTable/LightTable#521]
![light_table_persistent_errors](https://f.cloud.github.com/assets/2167017/462078/20b85d2e-b471-11e2-81c5-29601bfbf375.png)
Writing some code in python, run an eval to get an error. Then if you correct the error but skip ahead of the error message and then eval the whole form, the errors persist. I have seen other situations where the only way to clear the errors is to delete empty space after the last valid input, or use the clear eval command.

This is on windows 7, running iPython with a Python version of 2.7.

**Comment by kenny-evitt** [comment]
I'm closing this just 'cause it's old. And it may have been fixed by #2008 – I noticed that the 'checkmark' result is duplicated too in the screenshot included in the original comment. I'll re-open if anyone confirms that this is still an open issue.
