### ISSUE TITLE
ipython

### ISSUE THREAD

**Issue by jasonmader** [LightTable/LightTable#524]
lttools.py:

    >>> import sys
    >>> ipy = sys.modules['__main__'].__dict__['get_ipython']()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    KeyError: 'get_ipython'
    >>> print sys.modules['__main__'].__dict__
    {'__builtins__': <module '__builtin__' (built-in)>, '__name__': '__main__', 'sys': <module 'sys' (built-in)>, '__doc__': None, '__package__': None}

Also, on my OS X 10.8.3, even though ipython works on the command line, LightTable doesn’t use ipython as a connection.

% ipython
Python 2.7.2 (default, Oct 11 2012, 20:14:37) 
Type "copyright", "credits" or "license" for more information.

IPython 1.0.dev -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:

**Comment by kenny-evitt** [comment]
Anyone – add a comment if this is still an un-resolved issue.
