### ISSUE TITLE
Delete whitespaces intelligently

### ISSUE THREAD

**Issue by derekchiang** [LightTable/LightTable#548]
So currently, if I configure LT to insert spaces rather than tabs, what happens when I try to delete the spaces is that I have to delete the spaces one by one, rather than deleting them as tabs (delete 4 spaces at once in my case).  Could LT intelligently detect when I want to delete a tab width of spaces?

**Comment by kenny-evitt** [comment]
I created LightTable/Python#36 to track this in the repo for the Python plugin.

Please note that none of the current members of the core team, nor any frequent contributors, are using Python and we *really* need someone to step up and support Python features for them to remain (or become) viable for lots of users.
