### ISSUE TITLE
Command integration with Ubuntu's unity menu

### ISSUE THREAD

**Issue by ryanprior** [LightTable/LightTable#558]
Running commands with ctrl+space in lighttable is nice. In Ubuntu we've already been moving to that model, but we use the Alt key. It brings up a command-filter menu [1] which is constructed from the app's menu entry.

It would be better for ubuntu users if, rather than duplicating that functionality, lighttable used the DBus API [2] to utilize it. In my web browser I hit Alt, type 'tab', hit enter, and this opens a new tab. To open a browser tab in lighttable would ideally be the same.

[1] http://www.linuxuser.co.uk/wp-content/uploads/2012/04/hudpageweb.jpg for example
[2] http://askubuntu.com/questions/98692/how-to-add-support-for-the-global-menu-to-a-python-non-gtk-non-qt-app

**Comment by kenny-evitt** [comment]
I added this to the [feature wishlist](https://github.com/LightTable/LightTable/wiki/Feature-wishlist).
