### ISSUE TITLE
Search bar keybinding improvements

### ISSUE THREAD

**Issue by dubiousdavid** [LightTable/LightTable#581]
1. Cmd-G should work when focus is within search bar
2. Cmd-G should work after switching from one file to another without having to first bring focus to the search bar.
3. Cmd-F for search selection really should be changed to the default (at least for OSX), which is Cmd-E.  The problem is that you wipe out a search term unintentionally, when all you really wanted to do was open the search bar and see what's in there.

**Comment by kenny-evitt** [comment]
We can re-open this if anyone is willing to submit a PR.
