### ISSUE TITLE
socket.io not working

### ISSUE THREAD

**Issue by dctr** [LightTable/LightTable#586]
Hi, 

i am running LightTable 0.4.9 and have a node.js app, that runs fine when started from terminal and used with my default browsers (Firefox, Chromium).

If i open LightTable and add a node.js connection for the app.js, i get the following output when accessing the site (no matter if accessed from LightTable's own browser or my external one):

    app.js[stdout]:
    info: socket.io started

    app.js[stdout]:
    Express server listening on port 11907

    app.js[stdout]:
    debug: served static content /socket.io.js

    app.js[stdout]:
    info: client protocol version unsupported

The output in the internal browser is:

    Failed to load resource: the server responded with a status of 500 (Internal Server Error): http://localhost:11907/socket.io/1/?t=1368688328748

In Firefox with Firebug i get:

    socket.io.js (line 1659): Server Response: Protocol version not supported.

If you need further information, please tell me.

I really like LightTable and would like to use it over my current solution, but this, as you might assume, is a blocker for me.

Greetings, 
David

**Comment by kenny-evitt** [comment]
@zencodism I don't know of any reason why this would be fixed, but would you mind confirming whether you can reproduce this with a build of the latest source version of the *master* branch?

**Comment by kenny-evitt** [comment]
I was just able to reproduce this using the latest source version of *master* (the same version as the latest alpha release).

**Comment by kenny-evitt** [comment]
I *wasn't* able to reproduce this just now. [I wasn't connecting to the right *app.js* file!]

In the console I have a new error logged:

```
Uncaught Error: prompt() is and will not be supported.
override.js [161]	window.prompt
index.html [9]	anonymous
socket.io.js [1335]	Emitter.emit
socket.io.js [754]	Socket.emit
socket.io.js [933]	Socket.onconnect
socket.io.js [833]	Socket.onpacket
socket.io.js [1197]	anonymous
socket.io.js [1335]	Emitter.emit
socket.io.js [395]	Manager.ondecoded
socket.io.js [1197]	anonymous
socket.io.js [1335]	Emitter.emit
socket.io.js [5934]	Decoder.add
socket.io.js [385]	Manager.ondata
socket.io.js [1197]	anonymous
socket.io.js [1335]	Emitter.emit
socket.io.js [1953]	Socket.onPacket
socket.io.js [1771]	anonymous
socket.io.js [1335]	Emitter.emit
socket.io.js [2378]	Transport.onPacket
socket.io.js [3218]	callback
socket.io.js [4661]	anonymous
socket.io.js [4660]	exports.decodePayloadAsBinary
socket.io.js [4428]	exports.decodePayload
socket.io.js [3222]	Polling.onData
socket.io.js [2806]	anonymous
socket.io.js [1335]	Emitter.emit
socket.io.js [2954]	Request.onData
socket.io.js [3025]	Request.onLoad
socket.io.js [2907]	xhr.onreadystatechange
```

**Comment by kenny-evitt** [comment]
The new error seems like good news. [Apparently Electron just doesn't support `prompt`](https://github.com/atom/electron/blob/master/atom/renderer/lib/override.coffee#L91-L93).

**Comment by kenny-evitt** [comment]
If I replace `'prompt` with `alert` then it works – I can't however enter a name with the `alert` dialog box – but I can send messages and see them on the page in LT.

@dctr @zencodism If you would, please install the latest alpha 0.8.0 release and confirm whether this has been resolved.

**Comment by kenny-evitt** [comment]
Anyone – comment if this is still a problem.

**Comment by kenny-evitt** [comment]
A permalink for the "Apparently Electron just doesn't support `prompt` link above":

 - [electron/override.coffee at 30ec7fdeed715f4a8e234bb2557497081f8d1171 · electron/electron](https://github.com/electron/electron/blob/30ec7fdeed715f4a8e234bb2557497081f8d1171/atom/renderer/lib/override.coffee)
