### ISSUE TITLE
(name nil) throws an NPE but LightTable does not print anything

### ISSUE THREAD

**Issue by spoon16** [LightTable/LightTable#597]

**Comment by kenny-evitt** [comment]
@pawrsccouk I'm not sure if I can reproduce this with your code. When I run your code I see the `"Exception on canvas paint."` exception logged to the console.

@pawrsccouk @spoon16 I'm going to tentatively consider this to have been resolved. If I'm wrong, add a comment to that effect and I'll re-open this. Build the latest source version of the *master* branch if you can to test reproducing this.
