### ISSUE TITLE
Add .desktop file in distribution for Linux desktop launchers

### ISSUE THREAD

**Issue by mariusa** [LightTable/LightTable#616]
Having this would allow one to add it to Desktop Environment's menu/launchers

e.g. http://davidetaviani.com/2012/03/07/creating-launchers-for-gnome-3-shell/

**Comment by develop7** [comment]
@cldwalker the issue is still relevant.

**Comment by kenny-evitt** [comment]
@develop7 We're sharing stuff like this in [the wiki](https://github.com/LightTable/LightTable/wiki).
