### ISSUE TITLE
On a german keyboard the 'ü' key is interpreted wrong.

### ISSUE THREAD

**Issue by heyLu** [LightTable/LightTable#620]
With a german keyboard layout (`setxkbmap de` on Linux) LightTable ignores the `ü` key and inserts `[` instead. Both are on the same key, but differ depending on the layout.

I don't think this is intentional, but I'm not sure. The key on the right of  the `ü` or `[` results in the correct character (`+` and `]` respectively).

I'm using 0.4.11, but I'm not sure whether this is a new problem or I noticed it only now.

**Comment by ottonascarella** [comment]
on japanese keyboard on mac book pro
all the keys are swapped. caps key is interpreted as control and so forth.
this way I would have to have different shortcuts for different layouts, even though I wanna keep same layout.
