### ISSUE TITLE
Code folding

### ISSUE THREAD

**Issue by kirillsalykin** [LightTable/LightTable#621]
Code folding should be implemented

**Comment by babinc** [comment]
I really like Light Table. Every code editor i have ever used for the past 10 years has had Code Folding. I have become accustomed to using it day to day as I write code. I really need code folding in Light Table in order for it to be complete.

**Comment by babinc** [comment]
IT WORKS

I see that it is being implemented. IF my cursor is on a line of code that ends in a curly brace (javascript) and I hit "ctrl-+" it will fold the code. That is good enough to hold me over :+1:
