### ISSUE TITLE
LT AutoComplete. Uncaught Error: No protocol method IDeref.-deref defined for type null

### ISSUE THREAD

**Issue by clojens** [LightTable/LightTable#655]
I suddenly have the following error message popping up. I wasn't using the autocomplete function to the best of my knowledge.

![selection_006](https://f.cloud.github.com/assets/3727933/734732/3371d3ba-e2d8-11e2-9a34-0226a8378185.png)

**Comment by yin** [comment]
Same error happens to me, when trying to fire up instarepl. Absolutelly unusable, until fixed. Please fix it finally!

**Comment by kpfell** [comment]
FWIW, I'm building a language plugin in my spare time, and I'm getting this error when I fire up the instarepl _I_ implemented.

It's a pretty obtuse error message, and there don't seem to be any obvious explanations posted anywhere, so it'd be really useful if you wrote about the approach you took! \o/

**Comment by rundis** [comment]
Well something somewhere is trying to deref an atom which is nil. It's not completely unlikely that your error isn't the same as the op reported, or is your stactktrace exactly the same ? A gist with the complete stacktrace might be be helpful 

would be sweet if LT had a ClojureScript version upgrade and made proper use of the now fairly advanced sourcemapping support. 

Well in the meantime we'll have to try and decrypt cryptic javascript stacktraces

**Comment by clojens** [comment]
Right. Doesn't hurt to check `~/.config/LightTable/log/window0.log` every now and then either. 1/2 of the times I'm able to track (my own) mistakes somewhere down the line (cat) - or perhaps up the line (tac). I haven't been seeing this particular kind of errors around too much. Although every now and then, a few key(bindings) break and drop a trace, usually its solved easily enough by a save and close/re-open editor.
