### ISSUE TITLE
eval in repl hangs LT

### ISSUE THREAD

**Issue by gzmask** [LightTable/LightTable#667]
OS: osx 10.8.4
lein 2.2.0
LT 0.4.11
java 1.6.0_51
node v0.10.13
npm 1.3.2

When openning LT, connecting to a clojure project, or opening a repl then eval something, all leads to LT dies silently

Tried remove .lighttable and ~/Lib.../App...Support/Lighttable couple times, still having the problem.  

Amazingly, on my Macbook air which having basically same environment, LT works perfectly. 

Only different I can think of the two system is that I changed my HOME path to secondary harddrive with the one LT dies silently.

**Comment by cldwalker** [comment]
Closing as I never heard back on this
