### ISSUE TITLE
Better file navigation

### ISSUE THREAD

**Issue by Gozala** [LightTable/LightTable#687]
With a switch to LT I observe that I spend a lot more time finding a right buffer to work with. That's because I have to options to do it:

A. Find a tab I'm looking for.
B. Use navigate feature.

Option A is quite time consuming if you have many buffers open (which tends to be my case). What makes it even worth is that code base I deal with has lot of files with a same name like `core.js`, looking at the tab it's hard to know which on I need to jump to, there's no place I can take a look at file path either so I end up looking at source to detect whether it's `core.js` or not.

Option B is also not ideal since I need to type file names over and over & the matching file names again don't help here either.

Before switching to light table I used [peep open](https://peepcode.com/products/peepopen) that had plugins to all of the major editors. I would not dive into details
how it works as you can take a look at their page and this post:
https://peepcode.com/blog/2010/file-navigation-in-text-editors

But the main difference from current LT's navigate feature is that next time you open it it does not shows same results as before, instead it shows stack of most frequent files you navigated with more contextual info. As a matter of fact I never even looked at tabs when using it since it was faster and with more info.

So this is a suggestion to borrow some of the ideas to make navigation feature in LT better ;)

**Comment by kenny-evitt** [comment]
If anyone is still interested in this, add it to [the feature wishlist](https://github.com/LightTable/LightTable/wiki/Feature-wishlist). Also, provide some details – doing so as a comment on this issue is fine – as PeepCode seems to have been acquired and neither of the links in the original comment work now.

**Comment by christopherbalz** [comment]
Doesn't narrowing to the desired workspace (cntrol-o, open recent workspace), and then cntrol-o with the completion (type file name, work well for this already?  

Improvements here could be arrow-key nav in the workspace pane, but one typically doesn't switch workspaces constantly.
