### ISSUE TITLE
Enable Ctrl+C copy selection while in vim-mode

### ISSUE THREAD

**Issue by clojens** [LightTable/LightTable#688]
I don't know about you guys, but old habits die slow and one keystroke combination in particular I've found myself returning to is, while typing text in LightTable with vim on, is to `Shift+Home` or `Home, Shift+End` and then close up with a `Ctrl+C` to copy the whole thing.

It seems that at the moment, it doesn't do anything, I was wondering if it were possible to, while maintaining also of course the yank `y` in normal-mode of vim, to enable the `Ctrl+C` copy behaviour also when in vim insert-mode `i`. Not sure if it's possible though... or even desirable?

Thanks for your work,
Rob

**Comment by crantok** [comment]
Got directed here from codemirror/CodeMirror/#3075 and was grateful for the tip. I don't know whether the original config structure still works but I did the following successfully and am have pasted it in here case any noobs find it useful.

```clojure
;; User keymap
[
 [:editor.keys.vim "ctrl-c" :editor.copy]
 [:editor.keys.vim "ctrl-x" :editor.cut]
 [:editor.keys.vim "ctrl-v" :editor.paste]
 [:editor.keys.vim "ctrl-z" :editor.undo]
 [:editor.keys.vim "ctrl-y" :editor.redo]
 ;; ...
```
