### ISSUE TITLE
Linux ARM build

### ISSUE THREAD

**Issue by jvdneste** [LightTable/LightTable#703]
It would be awesome if I could run LightTable on my Samsung Chromebook. Perhaps it's easy to do? If not, I understand it's not exactly a priority.

If applicable, I'm willing to invest time in this to get it working.

**Comment by jalbam** [comment]
Maybe this is useful: https://github.com/jalbam/nwjs_rpi

**Comment by kenny-evitt** [comment]
@jalbam Light Table switched from node-webkit (NW.js) to Electron a while ago, tho someone could use the old code if they really wanted.
