### ISSUE TITLE
Vim movement keys do not auto-repeat

### ISSUE THREAD

**Issue by mmower** [LightTable/LightTable#711]
I enabled Vim mode in 0.5 (OSX10.8.4) by following instructions I found here:

https://groups.google.com/d/msg/light-table-discussion/TuJmH5Bpo2c/_BPvc5H4lT8J

And it seems to work except that the Vim movement keys hjkl do not auto-repeat and have to be pressed repeatedly. The cursor keys auto-repeat as normal.

**Comment by jdivock** [comment]
The solution listed didn't work for me, even with 

```
defaults write com.kodowa.LightTable ApplePressAndHoldEnabled -bool false
``` 

Keys do not repeat for me.
