### ISSUE TITLE
Python default logging isn't being output to the console

### ISSUE THREAD

**Issue by icorderi** [LightTable/LightTable#712]
Couple things on python's console output:

* I get a lot of "execing" "execed" and "evaling" when running python scripts that belong to LT and not my script (I assume they were part of your debugging output).

* The second point is logging. The logging output is not being shown on the LT console (unless I write to the logger on the same file).

Essentially, the output from evaling the code inside LT compared to doing "python foo.py" is very different and most importantly, it's missing all the debugging output from my own code.

**Comment by kenny-evitt** [comment]
I created LightTable/Python#37 for this in the repo for the Python plugin.

Note that we *really* need someone to commit to maintaining the Python plugin as none of the current members of the core team, nor any frequent contributors, are using Python.
