### ISSUE TITLE
Light Table 0.5.0: Line numbers disappear when you open the right-hand side menu

### ISSUE THREAD

**Issue by michael-okeefe** [LightTable/LightTable#737]
Setup: Light Table 0.5.0 on Mac OS 10.8.4 editing a Clojure file

Precondition: Select "Editor: Toggle line numbers" and line numbers appear as expected.

Bug causing condition: open the menu on the right hand side.

Expected outcome: I expect line numbers to stay visible once toggled on, regardless of which menu I open.

Actual outcome: The line numbers appear to be "pushed off screen to the left" and are no longer visible. Playing with the "Editor:Toggle line numbers" shows that line numbers are apparently still "toggled on" (i.e., it takes two executions of "Editor: Toggle line numbers" before we see the line numbers again).

**Comment by just3ws** [comment]
Just stumbled on this issue after trying to setup line numbers in LT. FWIW, the first thing I tried was to change the word `hide` to `show`. Not sure if that helps with what a new LT user might reasonably expect the API to respond to.
