### ISSUE TITLE
select word under cursor

### ISSUE THREAD

**Issue by chrisfjones** [LightTable/LightTable#744]
Idea has this great feature where you can hit a hotkey and select the word underneath the cursor. If you have a selection, then the same hotkey will 'grow' the selection to be the parent word or form of the current selection. In this way, you can very quickly select and manipulate code in terms of forms rather than by line. This works really well when combined with the eval hotkey (cmd-enter in LT) and would be a great fit in LT IMHO.
The following video shows how this works in Idea: 
http://www.youtube.com/watch?v=VE6go04EZbw

A deeper textual example:
Given the following clojure code with my cursor is where the | is:

``` clojure
(defn- param? [params k]
  (and
    (contains? params k)
    (not (blank-o|r-nil? (get params k)))))
```

Pressing the hotkey in this state, selects the entire symbol

``` clojure
blank-or-nil? 
```

Pressing the same hotkey again, selects the entire enclosing form for that symbol

``` clojure
(blank-or-nil? (get params k))
```

..and again, the next enclosing form...

``` clojure
(not (blank-or-nil? (get params k)))
```

...and so on, until the entire outer form is selected

``` clojure
(defn- param? [params k]
  (and
    (contains? params k)
    (not (blank-or-nil? (get params k)))))
```

**Comment by kenny-evitt** [comment]
@cldwalker Should this be moved to the Clojure plugin or the Paredit plugin? Or somewhere else? The feature wishlist?

**Comment by cldwalker** [comment]
@kenny-evitt Clojure plugin would be good. Thanks!

**Comment by kenny-evitt** [comment]
I created LightTable/Clojure#60 for this in the Clojure plugin repo.

**Comment by kenny-evitt** [comment]
@chrisfjones [Magnus's plugin Parembrace](https://github.com/rundis/parembrace) does this; see [*Misc commands* in the plugin's README](https://github.com/rundis/parembrace#56-misc-commands).

**Comment by Mouvedia** [comment]
This needs to be reopened.

**Comment by rundis** [comment]
Why ?

**Comment by rundis** [comment]
I'm guessing this isn't necessarily something you'd easily implement generically if the behaviour is to work as OP describes. The parembrace plugin does/did implement it specifically for Clojure/ClojureScript. Just selecting a word however is already there no  (well one could provide a default mapping for the command like `[:editor "ctrl-g" :editor.sublime.selectNextOccurrence]`) ?

**Comment by Mouvedia** [comment]
@rundis
Would you prefer to close this one and reopen #2215?
Would you consider adding the _good first issue_ to this issue?

**Comment by rundis** [comment]
I think the original feature request is really useful. However I think it probably needs to be specific to each language, so I'm closing this issue for now and if it resurfaces it would be great to have separate issues for each language (that LT aims to provide out of the box support for). 

For solving the the simple select word under cursor feature see reopened: #2215
