### ISSUE TITLE
Evaluating code inline with Python

### ISSUE THREAD

**Issue by juanpr2** [LightTable/LightTable#760]
When using Python to evaluate code inline, Light Table seams to evaluate the whole file upon connect. This causes the evaluator to spend a lot of time if there are time consuming functions or if there are errors in the file. (with a spinning working indicator that doesn't stop).
As a workaround, I have to cut everything but the first 10 lines of code, save the file, evaluate the file, paste the cut part again, save the file again; and then I can evaluate the code inline normally.
Is there a better way for this?

I have tested it with OSX Lion and Mountain Lion,
Versions 0.4 and 0.5 of Light Table (0.5.2)
Python 2.7.1
pyzmq==13.1.0
ipython==1.0.0

**Comment by kenny-evitt** [comment]
I created LightTable/Python#38 for this in the Python plugin repo.

Note that we really need someone to step up and handle Python support as neither none of the members of the core team or any frequent contributors use Python.
