### ISSUE TITLE
[Windows7] Middle-click in Docs window breaks the UI

### ISSUE THREAD

**Issue by doxxx** [LightTable/LightTable#764]
Clicking the middle mouse button in the Docs window causes it to go into a "hands-free" scrolling mode but it's impossible to get out of this mode. As a result, left-clicking anywhere else in the UI has no effect. I can right-click on some UI elements and get a context menu which will work but even if I close the Docs window, the rest of the UI is still busted.

**Comment by kenny-evitt** [comment]
I wasn't able to reproduce this just now on a Windows 7 computer running a earlier-today source version.

**Comment by cldwalker** [comment]
I can't reproduce this on osx. It's possible this will be resolved once we switch docs to a browser tab #2101. I'll leave this open for a bit longer to see if we get more any more information to reproduce this. If we can't reproduce we can't fix it

**Comment by cldwalker** [comment]
Closing as we haven't heard back and I also can't reproduce on ubuntu 14
