### ISSUE TITLE
Adding shell

### ISSUE THREAD

**Issue by kirillsalykin** [LightTable/LightTable#765]
It would be to have shell inside LT. For git add or whatever.
Thanks.

**Comment by kristofer** [comment]
#533 has been closed
#765 has been closed
#1687 has been closed

and still no shell tab?

**Comment by joshuafcole** [comment]
Hey Kristofer, adding a shell is a plugin request, which doesn't belong in the issue tracker for the core editor itself. We provide all necessary hooks to make the plugin. We do have a plugin request wiki page, which I believe @cldwalker has already linked to. As time permits, someone with the know-how will give it a go. If it's very important to you, you might consider trying to implement it yourself. If you want to try and need advice or assistance, just let us know in IRC or the mailing list.

Cheers,
Josh
