### ISSUE TITLE
Consider built-in support for editorconfig

### ISSUE THREAD

**Issue by Mpdreamz** [LightTable/LightTable#813]
I've seen some mention of an `Editor: indentation settings` command but I can not seem to get to it (using the latest alpha 0.5.4). 

It would be nice if LightTable would have builtin support for editorconfig:

http://www.editorconfig.org

which is a great way to create shareable editor settings across many editors and allows a project maintainer to dictate indentation settings for a repository.

**Comment by blaggacao** [comment]
:+1: it's kind of a good thing to enforce code style across the team.. So it's not so much about supporting editorconfig, but about supporting teams. That's the really important aspect of it. However editorconfig might be best of breed.

**Comment by kenny-evitt** [comment]
This is already in [the Feature wishlist wiki page](https://github.com/LightTable/LightTable/wiki/Feature-wishlist). If someone is interested in working on this, create a separate repo for the code – which should be an LT plugin.
