### ISSUE TITLE
A way to hide the menubar

### ISSUE THREAD

**Issue by algernon** [LightTable/LightTable#831]
Since LightTable 0.5, the menubar is always visible, which can be distracting when one's entering Deep Hack Mode. Would it be possible to make it togglable, so I can hide it with a keypress?

**Comment by penntaylor** [comment]
For future searchers who come across this issue, here's how to do it with the new user behaviors format. You still have to restart LT for this to take effect.

    [:app :-lt.objs.menu/create-menu]
    [:app :-lt.objs.menu/set-menu]
    [:window :-lt.objs.menu/set-menu]
