### ISSUE TITLE
Python watcher is apparently broken

### ISSUE THREAD

**Issue by sterfield** [LightTable/LightTable#856]
Hi,

Currently on my system, the watch feature is not working.

OS : Debian testing
Lighttable build x86_64
Version : 0.5.12
type connection : python
Commands : editor.eval.python
Python version : Python 2.7.5+

What : Create a simple python file; with this code "x = 5", then select the "x" variable, open the "command" tab, and select "Editor: watch selection".
Actual results : The python intepretation crashes with this stacktrace :

Traceback (most recent call last):
  File "/opt/Lighttable/plugins/python/ltmain.py", line 155, in handleEval
    toExec.append(handlePos(code, data[2]["pos"]))
  File "/opt/Lighttable/plugins/python/ltmain.py", line 118, in handlePos
    a = ast.parse(string)
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 3
SyntaxError: can't assign to function call

Expected result : the interpretation doesn't crash and the watch is set up correctly.

I've checked that the feature is supposed to work, and search for similar issues without any success.

Thanks for your help, and all the hard work done on Lighttable !

Sterfield

**Comment by joonro** [comment]
I'm getting this error as well - as @foobarbecue asked, could you please clarify this?

**Comment by foobarbecue** [comment]
@joonro I think it's pretty clear he just got his right and left mixed up.

**Comment by ibdknox** [comment]
Yeah, my apologies for the confusion, you can't assign to a function so you can't watch something on the left-hand side of an assignment. The right is fair game.
