### ISSUE TITLE
CSS is not being eval'ed relative to the file's path

### ISSUE THREAD

**Issue by jeremypenner** [LightTable/LightTable#872]
I have a directory layout something like this:

    src/web/css/page.css
    src/web/images/
    src/web/index.html

page.css refers to images in the "images" directory with relative URLs, ie ../images/icon.png

When I eval something in page.css, all of the images disappear, with error messages like:

    Failed to load resource: file:///Users/jpenner/src/images/icon.png

Which suggests that it is evaluating the CSS file with the current directory set to src/web/, where index.html is, rather than src/web/css/, where the CSS file I'm working on is.

It would be nice if this didn't happen.

**Comment by cldwalker** [comment]
Closing as the discussion for this has moved to https://github.com/LightTable/CSS/issues/1 and https://github.com/LightTable/CSS/issues/3
