### ISSUE TITLE
Option to display print margin

### ISSUE THREAD

**Issue by Gozala** [LightTable/LightTable#892]
I would really like to have an option for displaying print margin, it's kind of feature that
is very hard in vim & emacs but easy everywhere else :) I hope it's can be easy in LT too.

**Comment by Jinyi77** [comment]
+1

**Comment by apriendeau** [comment]
@cldwalker how come lighttable cant use the codemirror's addon? http://codemirror.net/doc/manual.html#addon_rulers

**Comment by cldwalker** [comment]
@apriendeau Good idea. Addressed with #1831
