### ISSUE TITLE
console font settings?

### ISSUE THREAD

**Issue by zeyangl** [LightTable/LightTable#915]
how do I change font settings for the console. I tried

```
 :console [((:lt.objs.style/font-settings "Monaco" 8 1))]
```

but it does nothing like it did to editor.

**Comment by stemd** [comment]
Put following line in ```user.behaviors```:

    [:app :lt.objs.plugins/load-css "/home/<your_username>/.config/LightTable/console.css"]

In ```console.css``` put something like this:

    ul.console, em.file, em.line {
        font-family:"DejaVu Sans"
        font-size:12px;
    }
    
    ul.console > li > table > tr > td > pre {
        font-family:"Ubuntu Mono";
        font-size:12px;
    }

Of course, you need not have two different font families as filename and output are already printed in different colors, but there it is.

CSS styling is not dynamically reloaded as user keybindings and behaviors, if you change your CSS, you need to close & reopen LightTable. That should be fixed, hopefully someone will open an issue at github issue tracker. ;)
