### ISSUE TITLE
tab size incorrect.

### ISSUE THREAD

**Issue by zeyangl** [LightTable/LightTable#916]
I tried setting tab size to 4
:editor [(:lt.objs.editor/tab-settings 1 4 4)]
and
:editor [(:lt.objs.editor/tab-settings 0 4 4)]

but the tab size appears to remain 2 spaces.

**Comment by bassmake** [comment]
I have this problem with html in 7.2.
setting [:editor :lt.objs.editor/tab-settings false 2 2] in User behaviors didn't help. I had to change {LightTable}/plugins/html/html.behaviours.

Seems like html.behaviors override User and Default behaviors.

**Comment by kmsquire** [comment]
Just ran into this as well.  I found that just using
```clojure
[:editor :lt.objs.editor/tab-settings false 4 4]
```
did not override anything, but if I specify 
```clojure
[:editor.python :lt.objs.editor/tab-settings false 4 4]
```
it works fine.
