### ISSUE TITLE
Python connection crashes when using pylab.show()

### ISSUE THREAD

**Issue by remysaissy** [LightTable/LightTable#927]
The following code (taken from the scikit learn tutorial: http://scikit-learn.org/stable/tutorial/statistical_inference/settings.html):
from sklearn import datasets
digits = datasets.load_digits()
digits.images.shape
import pylab as pl
pl.imshow(digits.images[-1], cmap=pl.cm.gray_r)
pl.show()

Crashes the python connection after a quick blank window.
 Process:         Python [57533]
Path:            /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:      org.python.python
Version:         2.7.5 (2.7.5)
Build Info:      python-76000000000000~157
Code Type:       X86-64 (Native)
Parent Process:  node-webkit Helper [57493]
Responsible:     node-webkit [57491]
User ID:         501

Date/Time:       2013-11-26 18:23:12.155 +0100
OS Version:      Mac OS X 10.9 (13A603)
Report Version:  11
Anonymous UUID:  E911B7BF-B1C7-0A89-C8E8-55284CEF6B9F

Sleep/Wake UUID: ABF8F0AA-ACC7-4767-87A4-E5D158C3BDCC

Crashed Thread:  7

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
abort() called
terminating with uncaught exception of type NSException

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff971a241c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x00007fff9640ce75 objc_exception_throw + 43
2   CoreFoundation                      0x00007fff971a21f8 +[NSException raise:format:arguments:] + 104
3   Foundation                          0x00007fff9539dc61 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 189
4   Foundation                          0x00007fff9530822c +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 156
5   AppKit                              0x00007fff97298afd -[NSApplication run] + 858
6   _macosx.so                          0x000000010b1a910e init_macosx + 1995
7   Python                              0x00000001085621ef PyEval_EvalFrameEx + 12338
8   Python                              0x000000010855f093 PyEval_EvalCodeEx + 1641
9   Python                              0x00000001085658c8 _PyEval_SliceIndex + 929
10  Python                              0x00000001085624d4 PyEval_EvalFrameEx + 13079
11  Python                              0x000000010855f093 PyEval_EvalCodeEx + 1641
12  Python                              0x0000000108506796 PyFunction_SetClosure + 809
13  Python                              0x00000001084e8f72 PyObject_Call + 101
14  Python                              0x00000001084f39a7 PyMethod_New + 1200
15  Python                              0x00000001084e8f72 PyObject_Call + 101
16  Python                              0x000000010852dcad _PyObject_SlotCompare + 2972
17  Python                              0x00000001084e8f72 PyObject_Call + 101
18  Python                              0x0000000108563395 PyEval_EvalFrameEx + 16856
19  Python                              0x000000010855f093 PyEval_EvalCodeEx + 1641
20  Python                              0x00000001085658c8 _PyEval_SliceIndex + 929
21  Python                              0x00000001085624d4 PyEval_EvalFrameEx + 13079
22  Python                              0x000000010855f093 PyEval_EvalCodeEx + 1641
23  Python                              0x000000010855ea24 PyEval_EvalCode + 54
24  Python                              0x000000010855b1f2 _PyBuiltin_Init + 3972
25  Python                              0x000000010856114d PyEval_EvalFrameEx + 8080
26  Python                              0x000000010855f093 PyEval_EvalCodeEx + 1641
27  Python                              0x0000000108506796 PyFunction_SetClosure + 809
28  Python                              0x00000001084e8f72 PyObject_Call + 101
29  Python                              0x0000000108563395 PyEval_EvalFrameEx + 16856
30  Python                              0x0000000108565864 _PyEval_SliceIndex + 829
31  Python                              0x00000001085624d4 PyEval_EvalFrameEx + 13079
32  Python                              0x0000000108565864 _PyEval_SliceIndex + 829
33  Python                              0x00000001085624d4 PyEval_EvalFrameEx + 13079
34  Python                              0x000000010855f093 PyEval_EvalCodeEx + 1641
35  Python                              0x0000000108506796 PyFunction_SetClosure + 809
36  Python                              0x00000001084e8f72 PyObject_Call + 101
37  Python                              0x00000001084f39a7 PyMethod_New + 1200
38  Python                              0x00000001084e8f72 PyObject_Call + 101
39  Python                              0x000000010856501f PyEval_CallObjectWithKeywords + 93

**Comment by vvansice** [comment]
also have similar error, pyzmq is installed.

**Comment by kenny-evitt** [comment]
@vvansice Please open an issue in [the Python plugin repo](https://github.com/LightTable/Python). Keep in mind tho that the core team doesn't support the Python plugin; thus we don't support Python either (because none of us use Python [much]). Someone stepped forward to maintain the plugin (and thus Light Table Python support) but they haven't been active much since.
