### ISSUE TITLE
defrecord in instarepl produces warnings

### ISSUE THREAD

**Issue by ikarth** [LightTable/LightTable#934]
When I eval or Instarepl a defrecord in a .clj:

```clojure  
  (defrecord Test [])
```

I get a bunch of warnings in the console:

```
  WARNING: Symbol IHash is not a protocol at line 4 
  WARNING: Symbol ILookup is not a protocol at line 4 
  WARNING: Symbol IAssociative is not a protocol at line 4 
  WARNING: Symbol IPrintWithWriter is not a protocol at line 4 
  WARNING: Symbol IRecord is not a protocol at line 4 
  WARNING: Symbol ICollection is not a protocol at line 4 
  WARNING: Symbol ISeqable is not a protocol at line 4 
  WARNING: Symbol ICounted is not a protocol at line 4 
  WARNING: Symbol IEquiv is not a protocol at line 4 
  WARNING: Symbol IWithMeta is not a protocol at line 4 
  WARNING: Symbol IMeta is not a protocol at line 4 
  WARNING: Symbol IMap is not a protocol at line 4 
```

This isn't a critical issue, but since it fills the console every time I reevaluate the file it's a bit annoying.

This may be down to my limited understanding of records, protocols, and the warning system. I have not seen this behavior with other REPLs, though I suppose they may be suppressing the warning. I've looked for any information on this and no one else seems to have mentioned this exact issue.

**Comment by cldwalker** [comment]
This issue has moved to https://github.com/LightTable/ClojureInstarepl/issues/10 as the instarepl is now its own plugin
