### ISSUE TITLE
Light table is not git friendly

### ISSUE THREAD

**Issue by Gozala** [LightTable/LightTable#942]
Switching between branches is really a painful when working with light table. If LT spots
any missing files it's very sad (see #941), then I switch back to a make LT happy again,
but it still thinks files are diff and won't let me do anything unless I close all buffers.

LT should recognize that files are back to normal and they are no longer missing nor changed.

**Comment by cldwalker** [comment]
On master invasive and buggy popups for modified and deleted files have been removed. This should resolve most git issues. Will go out on next release. If u have other git workflow issues let us know
