### ISSUE TITLE
Debian 7 GLIBC

### ISSUE THREAD

**Issue by siscia** [LightTable/LightTable#972]
After all the installation process on a debian 7 64bit I get
```shell
simo@simo:~/sandBox/light-table-core-2/deploy$ ./ltbin 
./ltbin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./ltbin)
./ltbin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by ./ltbin)
```
it is a know problem #164 back in the day was fixed compiling with gcc 4.4, now I don't know how to manage it...

**Comment by kenny-evitt** [comment]
This is *probably* irrelevant now that we've (a while ago now) merged the changes to migrate from node-webkit to { Atom Shell / Electron }.
