### ISSUE TITLE
Error: incorrect header check    at Zlib._binding.onerror (zlib.js:295:17)

### ISSUE THREAD

**Issue by darthdeus** [LightTable/LightTable#974]
When I click on any plugin to install it, Lighttable shows the following error

```
Error: incorrect header check    at Zlib._binding.onerror (zlib.js:295:17)
```

**Comment by mbernat** [comment]
I'm still hitting this on 0.7.2. Can't install a single plugin.

**Comment by Sisyphuss** [comment]
I'm hitting this from an upgrade from 0.7.2 to 0.8.0.

**Comment by kenny-evitt** [comment]
@Sisyphuss I think the problem is that *0.8.0-alpha* is considered a newer version than *0.8.0* – see #2081.

I suspect both issues will be resolved, even if the underlying issues aren't fixed, by upgrading to the even newer version *0.8.1*.

**Comment by Sisyphuss** [comment]
@kenny-evitt thanks! After upgrading to 0.8.1, the problem disappears.

**Comment by kenny-evitt** [comment]
@Sisyphuss Excellent :tada:
