### ISSUE TITLE
Better build / hack workflow

### ISSUE THREAD

**Issue by Gozala** [LightTable/LightTable#977]
Current [build / test process](https://github.com/LightTable/LightTable#building) is pretty complicated. In addition changes made in repo won't automatically be reflected unless changes are copied manually.

It would be a lot nicer if there was some make file in the repo that would download and patch latest LT build into `deploy` folder to simplify build and testing changes process.

**Comment by cldwalker** [comment]
0.8.0-alpha is out and has scripts and [instructions on building](https://github.com/LightTable/LightTable/blob/master/doc/developer-install.md) - https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss
